Repository vlggms/lobotomy-corp13, pull requests merged in 2022-11, with the labels that each got.

#403 Pizza Time
  code/controllers/subsystem/lobotomy_corp.dm
Labels: Feature

#402 Express Train to Hell
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/64x96.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/effects/abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/waw/express_train.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  lobotomy-corp13.dme
  sound/abnormalities/expresstrain/express_horn.ogg
  sound/abnormalities/expresstrain/express_move_loop.ogg
  sound/abnormalities/expresstrain/express_summoned.ogg
  sound/abnormalities/expresstrain/express_whistle.ogg
Labels: Feature

#366 adds porccubus
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/teguitems.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/surgery/bodyparts/head.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/porccubus/head_explode.ogg
  sound/abnormalities/porccubus/head_explode_laugh.ogg
  sound/abnormalities/porccubus/porccu_attack.ogg
  sound/abnormalities/porccubus/porccu_death.ogg
  sound/abnormalities/porccubus/porccu_giggle.ogg
Labels: Feature

#387 Adds Child of the Galaxy
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/tegu_effects32x48.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/galaxy_child.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/projectiles/ammunition/ego_ammunition/he.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#405 Worktick procs!
  code/game/machinery/computer/abnormality_work.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Tweak

#392 EGO Dump 5 - October 2022
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/projectiles/ammunition/ego_ammunition/he.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
Labels: Feature

#394 Bottle changes and Censored bug fix
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  icons/hud/screen_alert.dmi
  sound/abnormalities/bottle/bottledrown.ogg
Labels: Tweak, Fix

#397 Minor insanity buffs
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/ai/sanity/sanityloss_behaviors.dm
Labels: Balance, Tweak

#412 Edits EGO sounds and updates crimson claw
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/special.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  sound/abnormalities/redhood/attack_1.ogg
  sound/abnormalities/redhood/attack_2.ogg
  sound/abnormalities/redhood/attack_3.ogg
  sound/abnormalities/redhood/fire.ogg
  sound/abnormalities/redhood/throw.ogg
  sound/weapons/ego/ecstasy.ogg
  sound/weapons/gun/pistol/deagle.ogg
  sound/weapons/gun/pistol/tp17.ogg
  sound/weapons/gun/revolver/shot_light.ogg
  sound/weapons/gun/rifle/leveraction.ogg
  sound/weapons/gun/rifle/shot_alt.ogg
  sound/weapons/gun/smg/vp70.ogg
Labels: Tweak

#399 Red fixer and some tweaks
  ModularTegustation/Teguicons/tegumobs.dmi
  code/controllers/subsystem/lobotomy_corp.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
  code/modules/ordeals/white_ordeals.dm
  sound/effects/ordeals/white/Liq_White_Cast.ogg
  sound/effects/ordeals/white/Liq_White_Cast2.ogg
  sound/effects/ordeals/white/Liq_White_CircleAtk.ogg
  sound/effects/ordeals/white/Liq_White_CircleCastEnd.ogg
  sound/effects/ordeals/white/Liq_White_Dead.ogg
  sound/effects/ordeals/white/red_attack.ogg
  sound/effects/ordeals/white/red_beam.ogg
  sound/effects/ordeals/white/red_beam_fire.ogg
  sound/effects/ordeals/white/red_dead.ogg
Labels: Feature, Tweak

#414 Fixes crimson claw sound
  code/game/objects/items/ego_weapons/waw.dm
Labels: Fix

#406 Ppodae Buff
  code/modules/mob/living/simple_animal/abnormality/teth/ppodae.dm
  icons/mob/ppodae.dmi
Labels: Balance

#398 reworks shepherd and buddy's fight
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
Labels: Tweak

#413 Porccubus nerf & dash fix
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/paperwork/records/info/he.dm
Labels: Balance, Fix

#416 Galaxy Wand Fix
  code/modules/projectiles/ammunition/ego_ammunition/he.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  icons/obj/projectiles.dmi
Labels: Fix

#409 Express Train adjustments
  code/game/objects/effects/abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/waw/express_train.dm
  sound/abnormalities/expresstrain/express_move_loop.ogg
Labels: Balance, Tweak

#420 Scaredy Cat loses its target when teleporting
  code/modules/mob/living/simple_animal/abnormality/he/scaredy_cat.dm
Labels: Fix

#421 Blood Bath no longer requires 2 stats
  code/modules/mob/living/simple_animal/abnormality/teth/blood_bath.dm
  code/modules/paperwork/records/info/teth.dm
Labels: Tweak

#408 fix porccubus head explosion not accounting for directions
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/surgery/bodyparts/head.dm
Labels: Fix

#425 Remove recursion on Magic Bullet movement
  code/game/objects/effects/abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
Labels: Fix

#369 Managers console and bullets + Gadgets
  ModularTegustation/Teguicons/lc13icons.dmi
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/Tegusounds/weapons/guns/manager_bullet_fire.ogg
  ModularTegustation/Tegusounds/weapons/guns/manager_shock.ogg
  ModularTegustation/Tegusounds/weapons/guns/manager_wind.ogg
  ModularTegustation/tegu_items/lc13unique_items.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/machinery/computer/manager_camera.dm
  code/game/objects/items/wayfinding.dm
  lobotomy-corp13.dme
Labels: Feature

#429 Fixes black fixer
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
Labels: Fix

#410 Alriune
  ModularTegustation/Teguicons/48x64.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/alriune.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/effects/effects.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
  sound/abnormalities/alriune/curtain_in.ogg
  sound/abnormalities/alriune/curtain_out.ogg
  sound/abnormalities/alriune/damage.ogg
  sound/abnormalities/alriune/kill.ogg
  sound/abnormalities/alriune/timer.ogg
  sound/weapons/ego/crossbow.ogg
Labels: Feature

#423 Abnormality queue, qliphoth and ordeal timing changes
  code/controllers/subsystem/abnormality_queue.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/datums/abnormality/datum/abnormality.dm
Labels: Code improvement, Tweak, Test Merge Candidate

#401 Adds Yang, the Escort mission
  ModularTegustation/Teguicons/64x64.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/yang.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/obj/projectiles_impact.dmi
  icons/obj/projectiles_muzzle.dmi
  icons/obj/projectiles_tracer.dmi
  lobotomy-corp13.dme
Labels: Feature

#426 Shrimp tweak
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
Labels: Tweak

#433 More plushes
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
  sound/effects/radio_clear.ogg
Labels: Tweak

#404 Paradise Lost and It's Consequences Have Been Disastrous for Lobotomy Corp 13 endgame.
  code/datums/abnormality/_ego_datum/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/realized.dm
Labels: Balance

#436 Status Sprites
  ModularTegustation/Teguicons/status_sprites.dmi
  code/modules/mob/living/simple_animal/abnormality/aleph/staining_rose.dm
  code/modules/mob/living/simple_animal/abnormality/he/galaxy_child.dm
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cherry_blossoms.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
  icons/hud/screen_alert.dmi
Labels: Code improvement, Tweak

#431 WCCA Damage refactor
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
  code/modules/paperwork/records/info/zayin.dm
Labels: Tweak

#435 Singing Machine PR 2 Electric Boogaloo
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/Teguicons/tegu_effects32x48.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/looping_sounds/abnormalities.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/projectiles/ammunition/ego_ammunition/he.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
  sound/abnormalities/singingmachine/addiction.ogg
  sound/abnormalities/singingmachine/chew.ogg
  sound/abnormalities/singingmachine/creak.ogg
  sound/abnormalities/singingmachine/crunch.ogg
  sound/abnormalities/singingmachine/grind.ogg
  sound/abnormalities/singingmachine/motor.ogg
  sound/abnormalities/singingmachine/music.ogg
  sound/abnormalities/singingmachine/open.ogg
  sound/abnormalities/singingmachine/swallow.ogg
  sound/weapons/ego/harmony1.ogg
Labels: Feature

#407 adds piscine mermaid
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/48x32.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/datum/abnormality.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  icons/mob/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/head.dmi
  lobotomy-corp13.dme
  sound/abnormalities/piscinemermaid/bigsplash.ogg
  sound/abnormalities/piscinemermaid/splashattack.ogg
  sound/abnormalities/piscinemermaid/waterjump.ogg
Labels: Feature

#439 Record Fix
  code/modules/paperwork/records/info/aleph.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Fix

#438 B and C plushes
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Tweak

#428 E.G.O. Gift selling
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
Labels: Feature

#430 Some Claw buffs
  ModularTegustation/tegu_mobs/the_claw.dm
Labels: Balance, Code improvement

#418 Indigo Midnight Buff
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Balance

#445 Allows the manager camera to examine things
  code/game/machinery/computer/manager_camera.dm
Labels: Tweak

#434 Warden gets her melee back
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
Labels: Balance

#419 Ego gear nerf
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/clothing/suits/ego_gear/special.dm
Labels: Tweak

#444 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Github

#447 Intern no longer overrides announcement message
  code/datums/announcers/intern_announcer.dm
Labels: Fix

#450 fix mermaid's gift keeping buff after destruction
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
Labels: Fix

#443 Rabbit IFF
  code/modules/clothing/outfits/ert.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Tweak

#411 Walls and Floors PR 4
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/templates/abnormality_containment.dmm
  code/game/turfs/closed/_closed.dm
  code/game/turfs/open/floor/fancy_floor.dm
  code/game/turfs/open/lobotomy.dm
  code/modules/vending/cola.dm
  icons/obj/doors/airlocks/vault/overlays.dmi
  icons/obj/doors/airlocks/vault/vault.dmi
  icons/obj/smooth_structures/reinforced_window.dmi
  icons/obj/smooth_structures/window.dmi
  icons/obj/vending.dmi
  icons/turf/floors.dmi
  icons/turf/floors/facility.dmi
  icons/turf/walls/facility.dmi
  lobotomy-corp13.dme
Labels: Tweak, Mapping

#391 E corp city Zone
  _maps/map_files/Epsilon/epsiloncommand.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  code/game/area/areas/lobotomy_corp.dm
  code/game/turfs/open/floor/plating/misc_plating.dm
Labels: Mapping

#454 Judgement Bird range increase
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
Labels: Balance

#453 Big Bird tweaks
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
Labels: Balance, Tweak

#455 This fixes paper
  tgui/packages/tgui/interfaces/PaperSheet.js
Labels: javascript, Fix

#449 Snow White deletes vines on death
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
Labels: Tweak

#427 Panic Edits
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/ai/sanity/sanityloss_behaviors.dm
Labels: Tweak, Fix

#459 Frequency and Telecomms tweaks
  code/game/machinery/telecomms/machines/server.dm
  code/game/machinery/telecomms/telecomunications.dm
  tgui/packages/tgui/constants.js
Labels: Code improvement, Fix

#458 Buffs clerk pistol
  code/modules/projectiles/guns/ego_gun/zayin.dm
Labels: Tweak

#461 Mermaid spellcheck
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
Labels: Fix

#463 Wander and Justice Panic update
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/ai/sanity/sanityloss_behaviors.dm
Labels: Code improvement, Fix

#466 Alriune and KoD kill effects
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/alriune.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
Labels: Tweak

#467 Death & Insanity tweaks and fixes
  code/datums/status_effects/panic.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/effects/effects.dmi
Labels: Tweak, Fix

#470 Download Tablet apps for FREE
  code/modules/modular_computers/file_system/programs/airestorer.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
  code/modules/modular_computers/file_system/programs/card.dm
  code/modules/modular_computers/file_system/programs/crewmanifest.dm
  code/modules/modular_computers/file_system/programs/jobmanagement.dm
  code/modules/modular_computers/file_system/programs/powermonitor.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
Labels: Tweak

#464 Minor Singing Machine buff
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
Labels: Balance, Tweak

#476 TGS chat commands updated
  code/modules/admin/chat_commands.dm
  code/modules/ordeals/_ordeal.dm
Labels: Tweak

#472 Nothing There visuals & sounds
  code/datums/looping_sounds/abnormalities.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  sound/abnormalities/nothingthere/ambience.ogg
  sound/abnormalities/nothingthere/breach.ogg
  sound/abnormalities/nothingthere/growl.ogg
  sound/abnormalities/nothingthere/heartbeat.ogg
  sound/abnormalities/nothingthere/heartbeat2.ogg
Labels: Tweak

#469 Sal acid & mental stabilizator tweaks; Changes examine message for damage.
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Tweak

#432 Daredevil Parry Update
  code/game/objects/items/ego_weapons/he.dm
Labels: Balance, Fix

#471 Remove() > Cut()
  code/datums/ai/sanity/sanityloss_behaviors.dm
Labels: Fix

#465 Deltacorp Overhauled
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/FacilityTest/facility_test.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/structures/displaycase.dm
  icons/turf/decals.dmi
Labels: Mapping

#460 Betacorp Update
  _maps/map_files/Beta/betacorp.dmm
Labels: Mapping

#477 "Don't Touch Me" improvements
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/touch.dm
  sound/abnormalities/donttouch/breach.ogg
  sound/abnormalities/donttouch/end.ogg
  sound/abnormalities/donttouch/kill.ogg
  sound/abnormalities/donttouch/kill2.ogg
  sound/abnormalities/donttouch/panic.ogg
Labels: Code improvement, Tweak

#462 MoSB Upgrade
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
Labels: Balance, Code improvement, Tweak

#475 Helper Work Made Accurate
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
Labels: Balance

#483 Pscine Tweak
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
Labels: Code improvement, Tweak

#487 Punishing bird attack fix
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
Labels: Fix

#488 Alriune kill effect curtains
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/abnormality/waw/alriune.dm
Labels: Tweak

#478 fix buddy no longer dying with shepherd
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
Labels: Fix

#417 Cameras are indestructible
  code/game/machinery/camera/camera.dm
Labels: Fix

#457 Admin Quick Leveler and Easy Gift Extractor
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_items/lc13unique_items.dm
Labels: Tweak, Fix

#474 Apocalypse Bird Enchant Changes
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Code improvement, Tweak

#468 Silent Girl Refactor
  code/datums/status_effects/panic.dm
  code/modules/mob/living/simple_animal/abnormality/he/silent_girl.dm
  code/modules/paperwork/records/info/he.dm
Labels: Code improvement, Tweak, Fix
