Repository vlggms/lobotomy-corp13, pull requests merged in 2022-07, with the labels that each got.

#7 Adds in the map for the first facility
  _maps/alphacorp.json
  _maps/map_files/Alpha/alphacorp.dmm
  code/game/area/areas/lobotomy_corp.dm
  config/maps.txt
Labels: Feature

#12 Clerk Buff And ID Update
  code/game/objects/items/storage/firstaid.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/jobs.dm
  icons/mob/hud.dmi
  icons/obj/card.dmi
  icons/obj/storage.dmi
Labels: Feature

#14 Alpha Corp P2
  _maps/map_files/Alpha/alphacorp.dmm
Labels: Feature

#17 Agent Captain
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/manager.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  icons/mob/hud.dmi
  icons/obj/card.dmi
Labels: Feature

#18 Clerks now get better medical gear
  ModularTegustation/altjobtitles/LC13.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/clothing/under/clerksuits.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/projectiles/ammunition/ego_ammunition/zayin.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  code/modules/projectiles/projectile/ego_bullets/zayin.dm
  icons/mob/clothing/ego_gear/under.dmi
  icons/obj/clothing/under/suits.dmi
  icons/obj/ego_weapons.dmi
Labels: Balance

#19 Removes Unused map shit
  _maps/map_files/Alpha/alphacorp.dmm
Labels: Tweak

#29 Sleeper buffs
  code/game/machinery/Sleeper.dm
Labels: Tweak

#27 Nerfs metal
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Tweak

#31 EGO Weapon disappearing no more !
  code/modules/mob/living/carbon/death.dm
Labels: Balance

#33 Obliterates miasma
  code/__DEFINES/atmospherics.dm
Labels: Tweak

#32 Claw update(buff) + minor tweaks
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/tegu_mobs/the_claw.dm
  icons/hud/screen_gen.dmi
Labels: Tweak

#25 Rabbit Team Eye Color
  icons/mob/clothing/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Tweak

#30 Adds beauty and the beast
  ModularTegustation/Teguicons/48x32.dmi
  code/modules/mob/living/simple_animal/abnormality/teth/beauty_beast.dm
  lobotomy-corp13.dme
Labels: Feature

#24 Map Updates
  _maps/alphacorp.json
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/shuttles/emergency_alpha.dmm
  code/datums/shuttles.dm
Labels: Tweak

#36 Clerk/Agent improvement
  code/game/objects/items/storage/boxes.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/manager.dm
  code/modules/modular_computers/computers/item/tablet_presets.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
Labels: Tweak

#22 Adds Warden Abnormality
  ModularTegustation/Teguicons/48x64.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#39 Adds Extraction Officer
  code/game/objects/items/devices/radio/headset.dm
  code/modules/clothing/suits/armor.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/manager.dm
  code/modules/jobs/jobs.dm
  icons/mob/clothing/suit.dmi
  icons/mob/hud.dmi
  icons/obj/card.dmi
  icons/obj/clothing/suits.dmi
  lobotomy-corp13.dme
Labels: Tweak

#40 AlphaCorp+
  _maps/map_files/Alpha/alphacorp.dmm
Labels: Tweak

#26 Betacorp
  ModularTegustation/Teguicons/lcsigns.dmi
  _maps/betacorp.json
  _maps/map_files/Beta/betacorp.dmm
  code/game/area/areas/lobotomy_corp.dm
  code/game/objects/structures/signs/lobotomy/departments.dm
  lobotomy-corp13.dme
Labels: Feature

#38 Update of the workchance of the Abnormalities
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fragment.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
  code/modules/mob/living/simple_animal/abnormality/teth/scorched_girl.dm
  code/modules/mob/living/simple_animal/abnormality/teth/training_rabbit.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/queen_bee.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
Labels: Tweak

#37 Sprite Improvements (Blue Star and Reddit)
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  code/modules/mob/living/simple_animal/abnormality/aleph/blue_star.dm
Labels: Tweak

#43 Update betacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
Labels: Tweak

#41 Update CentCom.dmm
  _maps/map_files/generic/CentCom.dmm
Labels: Feature

#42 Rhinoceros Unit !
  code/__DEFINES/colors.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/vehicles/mecha/combat/durand.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
  icons/mecha/durand_shield.dmi
  icons/mecha/mecha.dmi
  icons/mecha/mecha_equipment.dmi
  icons/obj/projectiles.dmi
Labels: Feature

#46 Nerfs ego
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
Labels: Balance

#50 Update warden.dm
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
Labels: Tweak

#51 Rabbit hud + Mindshield
  code/modules/clothing/outfits/ert.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
Labels: Tweak

#47 Updated Betacorp (Extraction in Disciplinary)
  _maps/map_files/Beta/betacorp.dmm
Labels: Tweak

#53 Armband update!
  .vscode/settings.json
  ModularTegustation/altjobtitles/outfits.dm
  ModularTegustation/tegu_terragov_code/clothing.dm
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PackedStation/PackedStation.dmm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/outfits/terragov.dm
  code/modules/clothing/under/accessories.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/vending/wardrobes.dm
Labels: Tweak

#57 Warden Nerf
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
Labels: Tweak

#56 Remastered Judgement Bird
  ModularTegustation/Teguicons/48x64.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
Labels: Tweak

#54 Makes ugly sprite invisible
  icons/mob/clothing/belt.dmi
Labels: Tweak

#61 [READY] Extraction Officer Hud+Tablet, Agent Captain Tablete removal, Suit sensors to maximum by default.
  code/modules/clothing/under/_under.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/command.dm
Labels: Tweak

#60 Description Update + Cryopod Storage
  ModularTegustation/altjobtitles/outfits.dm
  ModularTegustation/tegu_terragov_code/clothing.dm
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  code/game/machinery/cryopod.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/watercloset.dm
  code/modules/clothing/under/accessories.dm
  code/modules/clothing/under/clerksuits.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/instruments/items.dm
  code/modules/instruments/stationary.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/vending/cigarette.dm
  code/modules/vending/coffee.dm
  code/modules/vending/snack.dm
Labels: Tweak

#59 [READY] Rhino Balance
  code/datums/ert.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/vehicles/mecha/combat/durand.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Balance

#62 Manager Monocle
  code/modules/clothing/glasses/_glasses.dm
  code/modules/jobs/job_types/manager.dm
Labels: Tweak

#55 Adding EGO
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/simple_animal/abnormality/teth/beauty_beast.dm
  code/modules/mob/living/simple_animal/abnormality/waw/queen_bee.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
Labels: Tweak

#64 Better Blue Star sprite
  ModularTegustation/Teguicons/96x96.dmi
  code/modules/mob/living/simple_animal/abnormality/aleph/blue_star.dm
Labels: Tweak

#66 Cams updated
  _maps/map_files/Beta/betacorp.dmm
Labels: Tweak

#67 Fix blue star sprite not showing
  code/modules/mob/living/simple_animal/abnormality/aleph/blue_star.dm
Labels: Fix

#69 Sleepers now get pentic acid
  code/game/machinery/Sleeper.dm
Labels: Tweak

#63 [HE] Adds Red Queen
  ModularTegustation/Teguicons/48x64.dmi
  code/modules/mob/living/simple_animal/abnormality/he/red_queen.dm
  lobotomy-corp13.dme
Labels: Tweak

#73 Rabbit inhand / Agent belt
  code/game/objects/items/ego_weapons/special.dm
  icons/mob/clothing/belt.dmi
  icons/mob/clothing/belt_mirror.dmi
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
Labels: Tweak

#76 small kitchen update
  ModularTegustation/tegu_drinks/drinks.dm
  _maps/RandomRuins/SpaceRuins/smallsphere.dmm
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/game/machinery/computer/arcade.dm
  code/game/objects/effects/contraband.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/toys.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/vending/cola.dm
  strings/tcg/set_one.json
Labels: Tweak

#75 adds Happy Teddy Bear to the game
  ModularTegustation/Teguicons/32x48.dmi
  code/modules/mob/living/simple_animal/abnormality/he/happy_teddy_bear.dm
  lobotomy-corp13.dme
Labels: Feature

#78 Red Queen hurts if you mess her up
  code/modules/mob/living/simple_animal/abnormality/he/red_queen.dm
Labels: Tweak

#80 Indigo Midnight buff
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Balance

#82 Betacorp Manager elevator added
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/manager_elevator.dmm
  code/datums/shuttles.dm
Labels: Tweak

#72 Survival box tweak
  code/game/objects/items/storage/boxes.dm
  code/modules/clothing/masks/gasmask.dm
Labels: Tweak

#79 [READY] No more ugly purple sprite
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/storage/bags.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  icons/mob/clothing/back.dmi
  icons/mob/clothing/belt.dmi
  icons/mob/clothing/belt_mirror.dmi
Labels: Tweak

#88 Record and Extraction Clerks
  ModularTegustation/altjobtitles/LC13.dm
  code/modules/clothing/under/clerksuits.dm
  icons/mob/clothing/ego_gear/under.dmi
  icons/obj/clothing/under/suits.dmi
Labels: Tweak

#89 Correctional Shotgun is now slightly less comically powerful
  code/modules/projectiles/projectile/ego_bullets/waw.dm
Labels: Balance

#91 New Sleeper Sprite
  icons/obj/machines/sleeper.dmi
Labels: Tweak

#83 Adds Dingle Dangle, Spider Bud [And fills out Ego]
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/64x96.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/simple_animal/abnormality/he/happy_teddy_bear.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_queen.dm
  code/modules/mob/living/simple_animal/abnormality/teth/dingle_dangle.dm
  code/modules/mob/living/simple_animal/abnormality/teth/spider_bud.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature
