Repository vlggms/lobotomy-corp13, pull requests merged in 2022-10, with the labels that each got.

#340 Fumo
  code/game/objects/items/plushes.dm
  icons/obj/toy.dmi
Labels: Feature

#317 Ego dump 3
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/clothing/old_ego.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
Labels: Balance, Feature

#330 Fragment + Grant Us Love Nerf
  code/modules/mob/living/simple_animal/abnormality/teth/fragment.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
Labels: Balance

#321 Surplus Sprites
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/224x128.dmi
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Teguicons/64x48.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/64x96.dmi
  ModularTegustation/Teguicons/96x48.dmi
  ModularTegustation/Teguicons/96x96.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
Labels: Tweak

#341 Late Spawn Fix
  code/modules/jobs/job_types/agent.dm
Labels: Fix

#322 QoH Arcana Beats + Death Counters
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/paperwork/records/info/waw.dm
  sound/abnormalities/hatredqueen/gun.ogg
  strings/tips.txt
Labels: Feature

#338 Officer Buff
  code/modules/jobs/job_types/command.dm
Labels: Tweak

#332 Adds Tutorial Zone and Intern Role
  ModularTegustation/Teguicons/!training.dmi
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/lcsigns.dmi
  _maps/map_files/generic/CentCom.dmm
  code/game/area/areas/lobotomy_corp.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/game/objects/structures/signs/lobotomy/departments.dm
  code/modules/client/client_procs.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/ego_gear/special.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/simple_animal/abnormality/!tutorial/bill.dm
  code/modules/mob/living/simple_animal/abnormality/!tutorial/cube.dm
  code/modules/mob/living/simple_animal/abnormality/!tutorial/fairies.dm
  code/modules/mob/living/simple_animal/abnormality/!tutorial/shadow.dm
  code/modules/paperwork/records/tutorial/abnormalities.dm
  code/modules/paperwork/records/tutorial/levelling.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/hud.dmi
  icons/obj/card.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#345 Bodybag Nerfed
  code/game/objects/structures/crates_lockers/closets/bodybag.dm
Labels: Balance

#336 Red Queen now does less damage
  code/modules/mob/living/simple_animal/abnormality/he/red_queen.dm
Labels: Balance

#334 Forsaken Murderer
  ModularTegustation/Teguicons/tegumobs.dmi
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/simple_animal/abnormality/teth/forsaken_murderer.dm
  code/modules/paperwork/records/info/teth.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#320 Nothing there speaks
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
Labels: Feature

#344 Realization Set 2
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  icons/mob/clothing/ego_gear/realized.dmi
  icons/obj/clothing/ego_gear/realization.dmi
Labels: Balance, Feature

#313 Scaredy Cat
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/64x32.dmi
  ModularTegustation/Teguicons/64x64.dmi
  code/__DEFINES/dcs/signals.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/effects/abnormality.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/he/scarecrow.dm
  code/modules/mob/living/simple_animal/abnormality/he/scaredy_cat.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/scaredycat/catattack.ogg
  sound/abnormalities/scaredycat/catchange.ogg
  sound/abnormalities/scaredycat/cateleport.ogg
  sound/abnormalities/scaredycat/catgrunt.ogg
Labels: Feature

#289 Adds Price of Silence
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x64.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/silence.dm
  code/modules/paperwork/records/info/waw.dm
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/realization.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/silence/bong.ogg
Labels: Feature

#331 Der Frei Admin-Only Upgrade
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
Labels: Feature

#347 Blue Star & Queen Bee buff
  code/datums/diseases/bee_spawn.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/blue_star.dm
Labels: Balance

#353 working on a meltdown now gives pity attributes
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/abnormality_work.dm
Labels: Tweak

#329 Abnorm Patrolling + Changes
  code/controllers/subsystem/lobotomy_corp.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/blue_star.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/silent_orchestra.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/he/scarecrow.dm
  code/modules/mob/living/simple_animal/abnormality/he/scaredy_cat.dm
  code/modules/mob/living/simple_animal/abnormality/teth/blood_bath.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
  code/modules/mob/living/simple_animal/abnormality/teth/scorched_girl.dm
  code/modules/mob/living/simple_animal/abnormality/teth/training_rabbit.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dreaming_current.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/queen_bee.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bald.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
Labels: Feature

#342 Realized EGO active abilities
  code/datums/action.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/spells/ability_types/_ability.dm
  code/modules/spells/ability_types/realized_ego.dm
  icons/effects/32x64.dmi
  icons/mob/actions/actions_ability.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  lobotomy-corp13.dme
  sound/effects/impact_thunder.ogg
  sound/effects/impact_thunder_far.ogg
Labels: Feature

#358 scaredy cat loses courage when his friend is deleted instead of dying
  code/modules/mob/living/simple_animal/abnormality/he/scaredy_cat.dm
Labels: Fix

#348 Adds Reddened Buddy
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  lobotomy-corp13.dme
  sound/abnormalities/redbuddy/redbuddy_howl.ogg
Labels: Feature

#362 Forsaken Murderer Buff
  code/modules/mob/living/simple_animal/abnormality/teth/forsaken_murderer.dm
Labels: Balance

#363 We Can Change Anything is more forgiving
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
Labels: Balance

#360 Warden rework
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
Labels: Balance

#364 Dangle work chance increase
  code/modules/mob/living/simple_animal/abnormality/teth/dingle_dangle.dm
Labels: Balance

#352 Staining Rose Refactor
  code/modules/mob/living/simple_animal/abnormality/aleph/staining_rose.dm
  code/modules/paperwork/records/info/aleph.dm
  sound/abnormalities/rose/meltdown.ogg
Labels: Balance, Tweak, Fix

#375 nerfs red buddy's rapid melee
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
Labels: Balance

#378 Realizer Fix
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
Labels: Fix

#380 Dreaming Current Paperwork Fix
  code/modules/paperwork/records/info/waw.dm
Labels: Tweak

#370 Ppodae
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/ppodae.dm
  code/modules/paperwork/records/info/teth.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/mob/ppodae.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/ppodae/attack.wav
  sound/abnormalities/ppodae/bark.wav
Labels: Feature

#377 Adds Today's Shy Look
  code/datums/abnormality/_ego_datum/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/shy_look.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/projectiles/ammunition/ego_ammunition/teth.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/mob/shy_look.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#365 Adds Grave of Cherry Blossoms
  ModularTegustation/Teguicons/128x128.dmi
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cherry_blossoms.dm
  code/modules/paperwork/records/info/teth.dm
  icons/effects/effects.dmi
  lobotomy-corp13.dme
Labels: Feature

#373 [DNM] Less Mirror Jank
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/mirror.dm
Labels: Code improvement, Fix

#386 LC13-specific area icons
  code/game/area/areas/lobotomy_corp.dm
  icons/turf/areas.dmi
Labels: Feature, Mapping

#385 Fixed Some Runtimes
  code/datums/quirks/neutral.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Code improvement, Fix

#367 Bug Fixes
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
Labels: Code improvement, Tweak, Fix

#388 Removes all +5% defenses on all Ego gear
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/waw.dm
Labels: Balance, Tweak

#384 adds Gone with a simple smile
  ModularTegustation/Teguicons/32x32.dmi
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/simple_animal/abnormality/teth/simple_smile.dm
  code/modules/paperwork/records/info/teth.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#389 Cherry Blossom Nerf
  code/modules/mob/living/simple_animal/abnormality/teth/cherry_blossoms.dm
Labels: Balance

#381 fix even more shepherd dragging jank
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
Labels: Fix

#379 Abnormality balance and tweaks
  code/__DEFINES/dcs/signals.dm
  code/datums/looping_sounds/abnormalities.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/blue_star.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/silent_orchestra.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/he/scarecrow.dm
  code/modules/mob/living/simple_animal/abnormality/he/scaredy_cat.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
  code/modules/mob/living/simple_animal/abnormality/teth/spider_bud.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dreaming_current.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/silence.dm
  sound/abnormalities/silence/ambience.ogg
  sound/abnormalities/silence/bong.ogg
  sound/abnormalities/silence/price.ogg
  sound/weapons/ego/price_of_silence.ogg
Labels: Balance, Code improvement, Tweak, Fix

#361 Green Noon now has some spread on their gun
  code/modules/projectiles/projectile/bullets/smg.dm
Labels: Balance

#396 allow admins to give every abnormality a radio implant
  code/datums/abnormality/datum/abnormality.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Feature
