Repository vlggms/lobotomy-corp13, pull requests merged in 2022-09, with the labels that each got.

#250 Amber Dawn Resistance Change
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
Labels: Balance

#244 Work logs
  code/controllers/subsystem/lobotomy_corp.dm
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/abnormality_ego.dm
  code/game/machinery/computer/abnormality_logs.dm
  lobotomy-corp13.dme
Labels: Feature

#245 Adds remaining Asiyah core suppressions
  code/_globalvars/lists/objects.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/machinery/computer/camera_advanced.dm
  code/game/machinery/computer/crew.dm
  code/game/machinery/regenerator.dm
  code/game/objects/items/clerks/hypo/hypo.dm
  code/modules/ordeals/white_ordeals.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/suppressions/_core_suppression.dm
  code/modules/suppressions/control.dm
  code/modules/suppressions/information.dm
  code/modules/suppressions/safety.dm
  code/modules/suppressions/training.dm
  lobotomy-corp13.dme
Labels: Balance, Feature

#248 Adds General Bee
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Teguicons/48x96.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/living/simple_animal/abnormality/waw/queen_bee.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/effects/effects.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
Labels: Feature

#258 Agents can now select their departments
  code/_globalvars/lists/flavor_misc.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/language/bong.dm
  icons/mob/clothing/ears.dmi
  icons/obj/radio.dmi
Labels: Feature

#260 Work Logging Console Map Addition + Map Fixes (Alpha, Beta, and CentComm)
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/generic/CentCom.dmm
Labels: Mapping

#262 Update suits.dmi
  icons/obj/clothing/ego_gear/suits.dmi
Labels: Fix

#261 Round end report tweak + round time fix
  ModularTegustation/tegu_procs.dm
  code/__HELPERS/roundend.dm
  code/_globalvars/game_modes.dm
  code/controllers/subsystem/statpanel.dm
  code/controllers/subsystem/ticker.dm
Labels: Tweak, Fix

#267 Bloodbath fix
  ModularTegustation/Teguicons/48x64.dmi
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/mob/living/simple_animal/abnormality/teth/blood_bath.dm
  lobotomy-corp13.dme
Labels: Fix

#255 CENSORED
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/64x64.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/paperwork/records/info/aleph.dm
  icons/effects/beam.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/censored/attack.ogg
  sound/abnormalities/censored/convert.ogg
  sound/abnormalities/censored/heal.ogg
  sound/abnormalities/censored/mini_attack.ogg
  sound/abnormalities/censored/mini_born.ogg
  sound/abnormalities/censored/sacrifice.ogg
  sound/weapons/ego/censored1.ogg
  sound/weapons/ego/censored2.ogg
  sound/weapons/ego/censored3.ogg
Labels: Feature

#249 Indigo dusk
  ModularTegustation/Teguicons/tegumobs.dmi
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/ordeals/indigo_ordeals.dm
Labels: Feature

#254 The Shrimp Association Executive
  ModularTegustation/Teguicons/32x32.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/ammunition/ego_ammunition/special.dm
  code/modules/projectiles/guns/ego_gun/special.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/special.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/grenade.dmi
  lobotomy-corp13.dme
Labels: Feature

#229 Apoca bird
  ModularTegustation/Teguicons/224x128.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
  _maps/map_files/FacilityTest/facility_test.dmm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/he/scarecrow.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  sound/abnormalities/apocalypse/beak.ogg
  sound/abnormalities/apocalypse/enchant.ogg
Labels: Tweak

#252 Deltacorp - Branch D-317
  _maps/deltacorp.json
  _maps/map_files/Delta/deltacorp.dmm
Labels: Feature, Mapping

#276 Silent Jank
  code/modules/mob/living/simple_animal/abnormality/he/silent_girl.dm
Labels: Fix

#266 Ego Weapon Redux 2
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/effects/misc.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullet.dm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/effects/effects.dmi
  icons/obj/projectiles.dmi
Labels: Balance, Fix

#277 Only first names that show up in Lobotomy Corp will show up here.
  strings/names/first.txt
  strings/names/first_female.txt
  strings/names/first_male.txt
Labels: Tweak

#273 Indigo dawn
  ModularTegustation/Teguicons/32x48.dmi
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/ordeals/indigo_ordeals.dm
Labels: Feature

#288 NERFS CENSORED NOISE
  code/game/objects/items/ego_weapons/aleph.dm
Labels: Tweak

#290 Rudolta Buff
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
Labels: Balance

#279 Rhino Enfuckening
  _maps/map_files/generic/CentCom.dmm
  code/modules/vehicles/mecha/combat/durand.dm
  code/modules/vehicles/mecha/combat/rhino.dm
  lobotomy-corp13.dme
Labels: Balance, Code improvement

#280 ゴゴゴ Shrimp Buff ゴゴゴ
  ModularTegustation/Teguicons/32x32.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Balance

#285 Nerfs Daredevil, Buffs Lutemis
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
Labels: Balance

#284 Clothing and comms vendors.
  code/__DEFINES/economy.dm
  code/modules/vending/lobotomyarmband.dm
  code/modules/vending/lobotomyheadset.dm
  code/modules/vending/lobotomyuniform.dm
  lobotomy-corp13.dme
Labels: Tweak

#294 Fixes WCCA EGO cost
  code/datums/abnormality/_ego_datum/zayin.dm
Labels: Fix

#287 Aleph Tweaks, Revised
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/silent_orchestra.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
Labels: Balance, Tweak

#274 The Great Workening
  code/datums/abnormality/datum/abnormality.dm
  code/datums/attributes/_attribute.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#297 Apoca Tweaks
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
Labels: Balance

#295 Agents become BatB upon killing her
  code/datums/abnormality/datum/abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/teth/beauty_beast.dm
Labels: Tweak

#303 Jokes Over
  code/modules/projectiles/guns/ego_gun/he.dm
Labels: Fix

#306 White Fix
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix

#283 Censor EGO nerf
  code/game/objects/items/ego_weapons/aleph.dm
Labels: Balance

#302 Silent Girl Null Removal
  code/modules/mob/living/simple_animal/abnormality/he/silent_girl.dm
Labels: Tweak, Fix

#304 Betacorp Changes
  ModularTegustation/Teguicons/tegucontraband.dmi
  _maps/map_files/Beta/betacorp.dmm
  code/game/objects/effects/contraband.dm
  code/game/objects/structures/memorial.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  icons/obj/tomb.dmi
Labels: Mapping

#275 White Lake Rework
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
  code/modules/paperwork/records/info/he.dm
  icons/effects/effects.dmi
Labels: Balance

#293 No More Carts!
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Tweak

#310 Changes Hub message and Death Message
  ModularTegustation/tegu_world.dm
  code/modules/mob/living/carbon/human/death.dm
Labels: Tweak

#301 Calming Cup of Tea Reagent update
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Feature, Tweak, Fix

#299 Shepherd can now lie (again)
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
Labels: Feature

#309 Rabbit team moment
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/suits/ego_gear/special.dm
  code/modules/clothing/under/clerksuits.dm
  icons/mob/clothing/big_hat.dmi
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/clothing/ego_gear/under.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/clothing/under/suits.dmi
  lobotomy-corp13.dme
Labels: Tweak

#305 E.G.O. Gift Menu
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bald.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
Labels: Feature, Fix

#271 Epsiloncorp
  _maps/epsiloncorp.json
  _maps/map_files/Epsilon/epsiloncommand.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/epsilon_elevator.dmm
  code/datums/shuttles.dm
  code/modules/shuttle/on_move.dm
  code/modules/shuttle/shuttle.dm
  config/maps.txt
Labels: Feature, Mapping

#307 CENSORED tweaks
  code/datums/abnormality/_ego_datum/aleph.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
Labels: Balance, Tweak

#292 Aleph and Gun Rebalance
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncommand.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/datums/abnormality/_ego_datum/zayin.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/game/objects/items/storage/belt.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  code/modules/projectiles/ammunition/ego_ammunition/aleph.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/special.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  code/modules/projectiles/projectile/ego_bullets/aleph.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
Labels: Balance

#312 Extraction-themed morgues!
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  code/game/objects/structures/morgue.dm
  icons/obj/stationobjs.dmi
Labels: Feature, Mapping

#278 Woodsman And Funeral Update
  code/game/objects/items/ego_weapons/he.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
Labels: Tweak

#318 Set the default Icon states for crushed can to cola instead of Melty bucket
  icons/obj/janitor.dmi
Labels: Fix

#296 Abno Working Rework
  code/controllers/subsystem/lobotomy_corp.dm
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/staining_rose.dm
  code/modules/mob/living/simple_animal/abnormality/teth/old_lady.dm
Labels: Tweak

#327 Der Freischutz Records fix and Magic Bullet Fix
  code/modules/paperwork/records/info/he.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
Labels: Fix

#323 Big bird nerf
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
Labels: Balance

#326 Blue Shep Teleports Properly
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
Labels: Fix

#325 Pink Midnight no longer calls hostile abnormalities to her
  code/modules/mob/living/simple_animal/hostile/ordeal/misc.dm
Labels: Fix

#333 Artillery Nerf
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
Labels: Balance

#315 Adds Tool Abnormalities
  ModularTegustation/Teguicons/toolabnormalities.dmi
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  code/datums/attributes/_attribute.dm
  code/game/machinery/fat_sucker.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/skin.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/theresia.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/mirror.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/touch.dm
  code/modules/paperwork/records/info/tools.dm
  code/modules/paperwork/records/lore/zayin.dm
  code/modules/paperwork/records/recordsfiling.dm
  icons/mob/clothing/ego_gear/realized.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/realization.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  lobotomy-corp13.dme
Labels: Feature

#311 Amber midnight
  ModularTegustation/Teguicons/224x128.dmi
  code/controllers/subsystem/lobotomy_corp.dm
  code/datums/looping_sounds/abnormalities.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/ordeals/amber_ordeals.dm
  code/modules/ordeals/white_ordeals.dm
  sound/effects/ordeals/amber/midnight_ambience.ogg
  sound/effects/ordeals/amber/midnight_create.ogg
  sound/effects/ordeals/amber/midnight_dead.ogg
  sound/effects/ordeals/amber/midnight_in.ogg
  sound/effects/ordeals/amber/midnight_out.ogg
  sound/effects/ordeals/amber/midnight_out_far.ogg
Labels: Feature, Tweak

#308 Dreaming Current
  ModularTegustation/Teguicons/64x48.dmi
  code/datums/looping_sounds/abnormalities.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dreaming_current.dm
  lobotomy-corp13.dme
  sound/abnormalities/dreamingcurrent/ambience.ogg
  sound/abnormalities/dreamingcurrent/bite.ogg
  sound/abnormalities/dreamingcurrent/dead.ogg
  sound/abnormalities/dreamingcurrent/move.ogg
Labels: Feature

#335 Vanilla ss13 items tweaks
  ModularTegustation/tegu_terragov_code/clothing.dm
  ModularTegustation/tegu_terragov_code/ert.dm
  ModularTegustation/tegu_terragov_code/misc.dm
  ModularTegustation/tegu_weaponry/guns/terra_pistols.dm
  ModularTegustation/tegu_weaponry/melee/nano_blade.dm
  code/datums/status_effects/buffs.dm
  code/modules/antagonists/changeling/powers/fleshmend.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/clothing/outfits/terragov.dm
  code/modules/clothing/spacesuits/chronosuit.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/spacesuits/terragov.dm
Labels: Tweak
