Repository vlggms/lobotomy-corp13, pull requests merged in 2022-12, with the labels that each got.

#484 Manager camera examination overhaul
  code/__DEFINES/dcs/signals.dm
  code/_onclick/click.dm
  code/game/machinery/computer/manager_camera.dm
Labels: Tweak

#382 Laetitia Rework
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Tweak

#501 Reworks Abnormality Queue into TGUI
  code/__DEFINES/abnormalities.dm
  code/game/machinery/computer/abnormality_queue.dm
  tgui/packages/tgui/interfaces/AbnormalityQueue.js
Labels: Feature, javascript

#493 Pale Fixer + Some changes to white ordeals
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  ModularTegustation/tegu_mobs/the_claw.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/game/objects/effects/abnormality.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
  code/modules/ordeals/white_ordeals.dm
  icons/effects/effects.dmi
  icons/obj/projectiles.dmi
  sound/effects/ordeals/white/pale_knife.ogg
  sound/effects/ordeals/white/pale_knife_end.ogg
  sound/effects/ordeals/white/pale_pistol.ogg
  sound/effects/ordeals/white/pale_suitcase.ogg
  sound/effects/ordeals/white/pale_teleport_in.ogg
  sound/effects/ordeals/white/pale_teleport_out.ogg
Labels: Feature, Tweak

#505 Moves HandleStartingAbnormalities call to post_setup(), ...
  code/controllers/subsystem/abnormality_queue.dm
  code/game/gamemodes/game_mode.dm
Labels: Fix

#506 Contract alteration to be lore friendly
  code/modules/paperwork/contract.dm
Labels: Tweak

#494 Wounds Removed Hotfix, HUDs delete on removal.
  code/datums/wounds/_wounds.dm
  code/modules/surgery/organs/augments_eyes.dm
Labels: Do Not Merge, Tweak

#490 New Regenerator Visuals
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x64.dmi
  code/game/machinery/regenerator.dm
Labels: Tweak

#473 Prevent Attack from Judgement, scorched, current, helper, and warden
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Fix

#509 Visual fixes
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/teth/ppodae.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yang.dm
Labels: Fix

#498 bun bun!
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/64x96.dmi
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/training_rabbit.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
Labels: Feature, Tweak

#497 Clerks start with -50 stats
  code/modules/jobs/job_types/assistant.dm
Labels: Balance, Tweak

#479 Simple Smile always makes you drop your weapon
  code/modules/mob/living/simple_animal/abnormality/teth/simple_smile.dm
Labels: Balance

#492 Increase items that LC vending machines start with
  code/modules/vending/lobotomyarmband.dm
  code/modules/vending/lobotomyheadset.dm
  code/modules/vending/lobotomyuniform.dm
Labels: Tweak

#424 Gunblade ego dump
  code/game/objects/items/ego_weapons/aleph.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
Labels: Tweak

#515 Slight pale fixer nerf
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
Labels: Balance

#510 Agent spawn updates
  code/modules/jobs/job_types/agent.dm
Labels: Tweak

#500 Wishing Well part 1
  ModularTegustation/Teguicons/toolabnormalities.dmi
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  code/modules/paperwork/records/info/tools.dm
  lobotomy-corp13.dme
  sound/abnormalities/bloodbath/Bloodbath_EyeOn.ogg
Labels: Feature

#491 Tool Abnormalities Part 2
  ModularTegustation/Teguicons/tegu_effects32x48.dmi
  ModularTegustation/Teguicons/toolabnormalities.dmi
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/behavior.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/skin.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/theresia.dm
  code/modules/paperwork/records/info/tools.dm
  lobotomy-corp13.dme
Labels: Balance, Feature

#441 Naked Nest: You will become the Serpents Nest
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/surgery/bodyparts/helpers.dm
  code/modules/vending/medical.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#524 Magic Bullet Minor Fix
  code/game/objects/effects/abnormality.dm
Labels: Fix

#528 Christmas Break Abno dump Baseline
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/32x64.dmi
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/96x64.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/projectiles/ammunition/ego_ammunition/he.dm
  code/modules/projectiles/ammunition/ego_ammunition/teth.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/clothing/old_ego.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  sound/abnormalities/khz/Clip1.ogg
  sound/abnormalities/khz/Clip2.ogg
  sound/abnormalities/khz/Clip3.ogg
  sound/abnormalities/khz/Clip4.ogg
  sound/abnormalities/khz/Clip5.ogg
  sound/abnormalities/khz/Clip6.ogg
  sound/abnormalities/khz/Clip7.ogg
Labels: Feature

#534 Redo of #530
  code/modules/mob/living/simple_animal/abnormality/he/KHz.dm
  code/modules/mob/living/simple_animal/abnormality/he/fan.dm
  code/modules/mob/living/simple_animal/abnormality/he/schadenfreude.dm
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
  code/modules/mob/living/simple_animal/abnormality/he/watchman.dm
  lobotomy-corp13.dme
Labels: Feature

#529 Teth Dump, 4 new Teths!
  code/modules/mob/living/simple_animal/abnormality/teth/MHz.dm
  code/modules/mob/living/simple_animal/abnormality/teth/drowned_sisters.dm
  code/modules/mob/living/simple_animal/abnormality/teth/penitent_girl.dm
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
  lobotomy-corp13.dme
Labels: Feature

#535 King of Greed Deshittified 5; The Empire Strikes Back
  ModularTegustation/Teguicons/64x48.dmi
  ModularTegustation/Teguicons/64x64.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/paperwork/records/info/waw.dm
  lobotomy-corp13.dme
Labels: Feature

#532 Regular Update To Alphacorp and Betacorp
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
Labels: Fix, Mapping

#520 Adds Random Roll buttons for Queue Console
  code/controllers/subsystem/abnormality_queue.dm
  code/game/machinery/computer/abnormality_queue.dm
  tgui/packages/tgui/interfaces/AbnormalityQueue.js
Labels: Code improvement, Feature, javascript

#537 Map vote fix
  code/controllers/subsystem/vote.dm
Labels: Fix

#536 EGO console tweak
  code/datums/abnormality/_ego_datum/_ego_datum.dm
  code/game/machinery/computer/abnormality_ego.dm
Labels: Tweak

#538 Updates stats on an aleph weapon
  code/game/objects/items/ego_weapons/aleph.dm
Labels: Fix

#539 Actual map vote fix
  code/controllers/subsystem/vote.dm
Labels: Fix

#542 KHz Healing nerf
  code/modules/mob/living/simple_animal/abnormality/he/KHz.dm
Labels: Balance

#541 sCHADenfreude HP nerf
  code/modules/mob/living/simple_animal/abnormality/he/schadenfreude.dm
Labels: Balance

#540 Void Dream nerf
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
Labels: Balance

#522 Realization tweaks
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/spells/ability_types/_ability.dm
  code/modules/spells/ability_types/realized.dm
  code/modules/spells/ability_types/realized_aimed.dm
  icons/mob/actions/actions_ability.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  lobotomy-corp13.dme
Labels: Balance, Code improvement, Tweak

#531 Adds alephs from the christmas Dump
  code/modules/mob/living/simple_animal/abnormality/aleph/space_lady.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  lobotomy-corp13.dme
Labels: Feature

#544 Removes A plush from the map
  _maps/map_files/generic/CentCom.dmm
Labels: Mapping
