Repository vlggms/lobotomy-corp13, pull requests merged in 2022-08, with the labels that each got.

#92 Correctional Armor is no longer Worse Lamp
  code/modules/clothing/suits/ego_gear/waw.dm
Labels: Balance

#97 Fixes Sweepers
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Fix

#95 Adds Bottle Of Tears and White Lake as abnormalities.
  ModularTegustation/Teguicons/tegumobs.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/ordeals/indigo_ordeals.dm
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#98 Matriarch Rework (10% less bullshit)
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Balance

#99 Eyeball Scooper & White Lake hotfix
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
Labels: Fix

#94 wellcheers soda updoot
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  code/modules/paperwork/paper_premade.dm
Labels: Tweak

#85 Sleeper tweak, pistol buff [BETACORP HOTFIXES]
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/machinery/Sleeper.dm
  code/modules/projectiles/projectile/ego_bullets/zayin.dm
Labels: Tweak

#101 Fix rhinos sprites
  icons/mecha/mecha.dmi
Labels: Fix

#100 No more Negative cake
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
Labels: Fix

#96 Nothing There
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/64x96.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/turf/floors.dmi
  lobotomy-corp13.dme
  sound/abnormalities/nothingthere/attack.ogg
  sound/abnormalities/nothingthere/disguise.ogg
  sound/abnormalities/nothingthere/goodbye_attack.ogg
  sound/abnormalities/nothingthere/goodbye_cast.ogg
  sound/abnormalities/nothingthere/hello_bam.ogg
  sound/abnormalities/nothingthere/hello_cast.ogg
  sound/abnormalities/nothingthere/hello_clash.ogg
  sound/abnormalities/nothingthere/walk.ogg
Labels: Feature

#90 The Armband PR
  ModularTegustation/altjobtitles/outfits.dm
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/accessory/armband.dm
  code/modules/clothing/under/accessories.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/ego_gear/armband.dmi
  icons/obj/clothing/ego_gear/armband.dmi
  lobotomy-corp13.dme
Labels: Tweak

#84 Refactors Ego Examine Text [And Ego Diversifacation]
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
Labels: Tweak

#104 Sprite and WL hotfix
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
Labels: Tweak, Fix

#105 Fairy Festival
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  code/__DEFINES/abnormalities.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  lobotomy-corp13.dme
  sound/abnormalities/fairyfestival/fairylaugh.ogg
Labels: Feature

#106 Hokma Balls
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  code/__DEFINES/access.dm
  code/game/machinery/accounting.dm
  code/game/machinery/computer/aifixer.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/crew.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/defibrillator_mount.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/noticeboard.dm
  code/game/objects/structures/signs/lobotomy/departments.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/manager.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/jobs.dm
  code/modules/mining/aux_base.dm
  code/modules/mob/living/simple_animal/abnormality/teth/dingle_dangle.dm
  code/modules/modular_computers/file_system/programs/airestorer.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
  code/modules/modular_computers/file_system/programs/card.dm
  code/modules/modular_computers/file_system/programs/crewmanifest.dm
  code/modules/modular_computers/file_system/programs/jobmanagement.dm
  code/modules/paperwork/records/info/_info.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/paperwork/records/info/zayin.dm
  code/modules/paperwork/records/lore/zayin.dm
  code/modules/paperwork/records/recordsfiling.dm
  code/modules/projectiles/guns/energy/dueling.dm
  code/modules/shuttle/emergency.dm
  icons/mob/clothing/suit.dmi
  icons/mob/hud.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/card.dmi
  icons/obj/clothing/suits.dmi
  lobotomy-corp13.dme
Labels: Feature

#112 HIGH PRIORITY WL FIX
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
Labels: Fix

#113 Extraction office fixed
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
Labels: Fix

#114 Return of betacorp tcomms
  _maps/map_files/Beta/betacorp.dmm
Labels: Fix

#107 Adds Butcherable Ordeals
  code/game/objects/items/food/meat.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
  icons/obj/food/food.dmi
Labels: Tweak

#122 Railing Nerf
  code/game/objects/structures/railings.dm
Labels: Tweak

#126 Nerfs indigo midnight
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Balance

#123 Alpha, Beta, and CentComm Map Updates
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/generic/CentCom.dmm
Labels: Tweak

#119 Fixes armbands
  code/modules/clothing/accessory/armband.dm
  icons/mob/clothing/accessories.dmi
  icons/mob/clothing/ego_gear/armband.dmi
Labels: Fix

#117 Ordeal Despawns
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/food/meat.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/paperwork/paper_premade.dm
  code/modules/paperwork/records/lore/zayin.dm
  icons/obj/food/food.dmi
Labels: Tweak

#109 The Mountain Of Smiling Bodies
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/96x96.dmi
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  lobotomy-corp13.dme
Labels: Feature

#118 Morgue Nerf
  code/game/objects/structures/morgue.dm
Labels: Tweak

#129 Updates and improves MoSB
  ModularTegustation/Teguicons/64x64.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/obj/projectiles.dmi
  sound/abnormalities/mountain/bite.ogg
  sound/abnormalities/mountain/breach.ogg
  sound/abnormalities/mountain/level_down.ogg
  sound/abnormalities/mountain/level_up.ogg
  sound/abnormalities/mountain/scream.ogg
  sound/abnormalities/mountain/slam.ogg
  sound/abnormalities/mountain/spit.ogg
Labels: Code improvement, Tweak

#130 Round health and sanity
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#133 Entirety of Silent Girl, her EGO, Work Complete Signals, and Universal Work Mod
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/__DEFINES/abnormalities.dm
  code/__DEFINES/dcs/signals.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/carbon/human/physiology.dm
  code/modules/mob/living/simple_animal/abnormality/he/silent_girl.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/silentgirl/Guilt_Apply.ogg
  sound/abnormalities/silentgirl/Guilt_Remove.ogg
  sound/weapons/ego/remorse.ogg
Labels: Feature

#86 [Ready] Melting Love
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/96x96.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/projectiles/ammunition/ego_ammunition/aleph.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/projectile/ego_bullets/aleph.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/effects/32x64.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/janitor.dmi
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
Labels: Feature

#135 Oppression fix
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
Labels: Balance, Fix

#139 Small Bird Bye Bye
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
Labels: Tweak

#141 Records update
  code/modules/paperwork/records/info/aleph.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/paperwork/records/info/teth.dm
Labels: Tweak

#136 Adds Smile armor
  code/datums/abnormality/_ego_datum/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
Labels: Tweak

#144 No More Champion Stacking
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
Labels: Fix

#145 Adoration PE box cost
  ModularTegustation/Teguicons/96x96.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
Labels: Tweak, Fix

#115 Der Freischütz
  ModularTegustation/Teguicons/32x64.dmi
  ModularTegustation/Teguicons/64x64.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/effects/abnormality.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  icons/obj/projectiles_tracer.dmi
  lobotomy-corp13.dme
  sound/abnormalities/freischutz/portal.ogg
  sound/abnormalities/freischutz/prepare.ogg
  sound/abnormalities/freischutz/shoot.ogg
Labels: Feature

#132 Fixes & Tweaks PR
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  icons/mob/clothing/ears.dmi
Labels: Balance, Code improvement, Tweak, Fix

#146 Add a clerk only hypo spray
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  code/game/objects/items/clerks/hypo/hypo.dm
  code/game/objects/items/clerks/hypo/hypo_upgrades.dm
  lobotomy-corp13.dme
Labels: Feature

#142 Crumbling Armor addition and Silent Girl Tweak
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/simple_animal/abnormality/he/silent_girl.dm
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/paperwork/records/info/teth.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature, Tweak

#149 Attribute level fix, update; Freischutz bullet tweaks & fixes
  code/datums/abnormality/datum/abnormality.dm
  code/datums/attributes/_attribute.dm
  code/game/objects/effects/abnormality.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/mob/clothing/ego_gear/suit.dmi
Labels: Balance, Tweak, Fix

#138 Magical Girl PR
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  sound/abnormalities/hatredqueen/dead.ogg
Labels: Balance, Tweak

#143 Blue Smocked Shepherd (and 1.76 MHz sprites and EGO)
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/96x96.dmi
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/projectiles/ammunition/ego_ammunition/teth.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
  icons/effects/weather_effects.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#127 Adds Rudolta of the Sleigh
  ModularTegustation/Teguicons/64x48.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/rudolta/throw.ogg
Labels: Feature

#121 Adds Staining Rose
  ModularTegustation/Teguicons/64x64.dmi
  _maps/map_files/generic/CentCom.dmm
  code/game/area/areas/lobotomy_corp.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/staining_rose.dm
  icons/effects/weather_effects.dmi
  lobotomy-corp13.dme
Labels: Feature

#152 Fixes rudolta object path
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
Labels: Fix

#153 Melting love tweaks or balance
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/paperwork/records/info/aleph.dm
Labels: Tweak

#155 Why did this have a flat 30% resistance to all
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
Labels: Fix

#157 Fixes mimicry lifesteal
  code/game/objects/items/ego_weapons/aleph.dm
Labels: Balance, Fix

#154 Silent Girl and White Lake Fix
  code/modules/mob/living/simple_animal/abnormality/he/silent_girl.dm
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
  code/modules/paperwork/records/info/he.dm
Labels: Fix

#158 Made Crew sensors show everyone regardless of the z-level
  code/game/machinery/computer/crew.dm
Labels: Tweak

#161 Add new rabbit gun sprite / Modify Queen bee sprite
  ModularTegustation/Teguicons/48x64.dmi
  code/modules/projectiles/guns/energy/energy_gun.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/energy.dmi
Labels: Tweak

#160 Training dummy and QoH Rebalance
  _maps/map_files/Beta/betacorp.dmm
  code/controllers/subsystem/lobotomy_corp.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
  code/modules/mob/living/simple_animal/abnormality/teth/training_rabbit.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
Labels: Balance, Tweak

#164 Alphacorp 2
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
Labels: Tweak

#165 Rose V2, Oppression Rework, Minor Ego changes,
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/staining_rose.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
Labels: Balance, Tweak

#168 Updated Temperance Placement
  code/game/machinery/computer/abnormality_work.dm
Labels: Fix

#167 Swiper no Swiping
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Fix

#169 Warm-Hearted Woodsman
  ModularTegustation/Teguicons/64x64.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/woodsman/woodsman_attack.ogg
  sound/abnormalities/woodsman/woodsman_prepare.ogg
  sound/abnormalities/woodsman/woodsman_strong.ogg
Labels: Feature

#173 MOSB buff
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
Labels: Balance

#175 Ports necromancer + some tweaks for non-abnormality megafauna
  ModularTegustation/Teguicons/96x32.dmi
  ModularTegustation/Teguicons/megafauna.dmi
  ModularTegustation/tegu_mobs/chaos_marine.dm
  ModularTegustation/tegu_mobs/necromancer.dm
  ModularTegustation/tegu_mobs/necromancer_mobs.dm
  code/datums/mind.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/pointed/necromancer_curse.dm
  code/modules/spells/spell_types/touch_attacks.dm
  icons/mob/actions/actions_spells.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/inhands/misc/touchspell_lefthand.dmi
  icons/mob/inhands/misc/touchspell_righthand.dmi
  icons/mob/simple_human.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/items_and_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#166 Melting Love tweaks/balance
  code/datums/abnormality/_ego_datum/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/projectile/ego_bullets/aleph.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
Labels: Tweak

#170 Headset Keys
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
Labels: Tweak

#180 Allow Manager to change the current alert level.
  code/game/machinery/computer/communications.dm
  config/game_options.txt
  tgui/packages/tgui/interfaces/CommunicationsConsole.js
Labels: Tweak

#186 Armbands now show above EGO suits
  code/modules/clothing/accessory/armband.dm
Labels: Tweak

#163 Update abnormality queue and meltdowns
  code/controllers/subsystem/abnormality_queue.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
Labels: Tweak

#185 ML can now fire her melting blob point blanc
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/projectiles/projectile/ego_bullets/aleph.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
Labels: Tweak

#178 Godly Gib Check
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/mob/living/simple_animal/abnormality/teth/beauty_beast.dm
  code/modules/mob/living/simple_animal/abnormality/teth/spider_bud.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
Labels: Tweak

#150 The arbiter
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/tegu_mobs/the_claw.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/antagonists/wizard/arbiter.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/clothing/under/clerksuits.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/spells/spell_types/aimed.dm
  code/modules/spells/spell_types/knock.dm
  code/modules/spells/spell_types/wizard.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/bodyparts/parts.dm
  icons/effects/beam.dmi
  icons/mob/clothing/ears.dmi
  icons/mob/clothing/neck.dmi
  icons/obj/clothing/cloaks.dmi
  icons/obj/projectiles_tracer.dmi
  lobotomy-corp13.dme
  sound/magic/arbiter/Binah_Atk4_CastCharge.ogg
  sound/magic/arbiter/Binah_Atk4_CastEnd.ogg
  sound/magic/arbiter/Binah_Atk4_CastLoop.ogg
  sound/magic/arbiter/Binah_Atk4_CastStart.ogg
  sound/magic/arbiter/Binah_Atk4_make.ogg
  sound/magic/arbiter/Binah_Clear.ogg
  sound/magic/arbiter/Binah_ClearAll.ogg
  sound/magic/arbiter/Binah_Meltdown.ogg
  sound/magic/arbiter/Binah_Pin.ogg
  sound/magic/arbiter/fairy.ogg
  sound/magic/arbiter/knock.ogg
  sound/magic/arbiter/pillar_hit.ogg
  sound/magic/arbiter/pillar_start.ogg
  sound/magic/arbiter/repulse.ogg
Labels: Feature

#190 Blue shep no longer goes down on normal work
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
Labels: Tweak

#189 Laetitia
  ModularTegustation/Teguicons/64x48.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
  code/modules/projectiles/ammunition/ego_ammunition/he.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#188 Slight meltdown adjustments
  code/controllers/subsystem/lobotomy_corp.dm
Labels: Balance

#183 Fear immunity
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/ai/sanity/sanityloss_behaviors.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/manager.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Balance, Tweak

#182 Ordeal tweaks
  code/modules/mob/living/simple_animal/hostile/ordeal/_ordeal.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
Labels: Balance

#191 EGO Gifts
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
  code/datums/abnormality/datum/abnormality.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/physiology.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/blue_star.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/silent_orchestra.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
  code/modules/mob/living/simple_animal/abnormality/he/happy_teddy_bear.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
  code/modules/mob/living/simple_animal/abnormality/he/scarecrow.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/mob/living/simple_animal/abnormality/teth/beauty_beast.dm
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fragment.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
  code/modules/mob/living/simple_animal/abnormality/teth/scorched_girl.dm
  code/modules/mob/living/simple_animal/abnormality/teth/spider_bud.dm
  code/modules/mob/living/simple_animal/abnormality/teth/training_rabbit.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/queen_bee.dm
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bald.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  lobotomy-corp13.dme
  sound/abnormalities/crumbling/megalovania.ogg
Labels: Feature

#194 Zwei Association ERT update!
  _maps/RandomRuins/SpaceRuins/prototype.dmm
  _maps/shuttles/ferry_lighthouse.dmm
  _maps/shuttles/whiteship_delta.dmm
  code/controllers/subsystem/traumas.dm
  code/datums/dog_fashion.dm
  code/datums/ert.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/food/meat.dm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/awaymissions/corpse.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories.dm
  code/modules/clothing/under/jobs/Plasmaman/centcom.dm
  code/modules/clothing/under/jobs/centcom.dm
  code/modules/clothing/under/jobs/civilian/curator.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/wardrobes.dm
  tools/UpdatePaths/clothingunderrepath.txt
Labels: Feature

#196 Make Little Witch's Friend disappear once dead.
  code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
Labels: Tweak

#198 Adoration and ML melting blob attack tweak
  code/datums/abnormality/_ego_datum/aleph.dm
  code/modules/projectiles/projectile/ego_bullets/aleph.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
Labels: Balance

#200 EGO tweaks + Laetitia update
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  sound/abnormalities/laetitia/spider_attack.ogg
  sound/abnormalities/laetitia/spider_born.ogg
  sound/abnormalities/laetitia/spider_dead.ogg
Labels: Balance, Tweak, Fix

#179 Abnorm changes
  code/datums/abnormality/datum/abnormality.dm
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/ai/sanity/sanityloss_behaviors.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/blue_star.dm
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
  code/modules/mob/living/simple_animal/abnormality/he/silent_girl.dm
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
  code/modules/mob/living/simple_animal/abnormality/teth/spider_bud.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/paperwork/records/info/teth.dm
Labels: Balance, Tweak

#202 Architecture department clerks + headset tweak for RO and EO
  ModularTegustation/altjobtitles/LC13.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/clothing/accessory/armband.dm
  code/modules/clothing/under/clerksuits.dm
  icons/mob/clothing/accessories.dmi
  icons/mob/clothing/ego_gear/under.dmi
  icons/obj/clothing/ego_gear/armband.dmi
  icons/obj/clothing/under/suits.dmi
Labels: Tweak

#201 Updates to Alpha, Beta, and CentCom.dmm
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/generic/CentCom.dmm
Labels: Mapping

#204 Bong Language
  code/modules/language/bong.dm
Labels: Feature

#203 Better Regenerators
  code/game/machinery/regenerator.dm
  code/game/objects/items/tools/safety_kit.dm
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
  icons/obj/tools.dmi
  lobotomy-corp13.dme
Labels: Balance, Tweak

#197 Changes description of default vest
  code/modules/clothing/suits/armor.dm
Labels: Tweak

#206 Bong Bong
  code/datums/quirks/neutral.dm
  code/modules/admin/smites/bonging.dm
  code/modules/language/bong.dm
  code/modules/surgery/organs/tongue.dm
  lobotomy-corp13.dme
Labels: Feature, Red Label

#195 White Night Rework
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Tegusounds/apostle/antagonist/scythe_spell.ogg
  ModularTegustation/Tegusounds/apostle/antagonist/staff_charge.ogg
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
  ModularTegustation/tegu_mobs/apostle_antag.dm
  code/datums/abnormality/datum/abnormality.dm
  code/datums/looping_sounds/abnormalities.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  icons/effects/beam.dmi
  lobotomy-corp13.dme
  sound/abnormalities/whitenight/apostle_bell.ogg
  sound/abnormalities/whitenight/apostle_death.ogg
  sound/abnormalities/whitenight/apostle_death_final.ogg
  sound/abnormalities/whitenight/apostle_heal.ogg
  sound/abnormalities/whitenight/apostle_shout.ogg
  sound/abnormalities/whitenight/apostle_spell.ogg
  sound/abnormalities/whitenight/rapture.ogg
  sound/abnormalities/whitenight/rapture2.ogg
  sound/abnormalities/whitenight/scythe.ogg
  sound/abnormalities/whitenight/scythe_spell.ogg
  sound/abnormalities/whitenight/spear.ogg
  sound/abnormalities/whitenight/spear_charge.ogg
  sound/abnormalities/whitenight/spear_dash.ogg
  sound/abnormalities/whitenight/staff_attack.ogg
  sound/abnormalities/whitenight/staff_end.ogg
  sound/abnormalities/whitenight/staff_prepare.ogg
  sound/abnormalities/whitenight/whisper.ogg
Labels: Feature

#207 Added the icon sprite for bong language
  icons/misc/language.dmi
Labels: Tweak

#209 manager and commands are now able to understand the bong bong horde
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/manager.dm
  code/modules/language/bong.dm
Labels: Tweak

#211 Alt title tweaks
  ModularTegustation/altjobtitles/LC13.dm
  code/modules/jobs/access.dm
Labels: Tweak, Fix

#208 Work chance cleanup, trait, zero qliphoth alert.
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/jobs/job_types/command.dm
  lobotomy-corp13.dme
Labels: Tweak, Fix

#193 [TM] Adds Black Fixer as a dusk
  ModularTegustation/Teguicons/32x64.dmi
  ModularTegustation/Teguicons/64x96.dmi
  code/modules/mob/living/simple_animal/hostile/ordeal/misc.dm
  code/modules/ordeals/misc_ordeals.dm
  code/modules/ordeals/white_ordeals.dm
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
Labels: Feature

#217 Regenerator Dead Body Fix
  code/game/machinery/regenerator.dm
Labels: Fix

#212 WN fix and buff
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
Labels: Balance, Fix

#214 Black fixer update
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/misc.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
  code/modules/ordeals/misc_ordeals.dm
  code/modules/ordeals/white_ordeals.dm
  lobotomy-corp13.dme
  sound/effects/ordeals/pink_end.ogg
  sound/effects/ordeals/pink_start.ogg
  sound/effects/ordeals/white/black_ability.ogg
  sound/effects/ordeals/white/black_ability_end.ogg
  sound/effects/ordeals/white/black_ability_start.ogg
  sound/effects/ordeals/white/black_dead.ogg
  sound/effects/ordeals/white/black_kunai.ogg
  sound/effects/ordeals/white/black_swing.ogg
Labels: Balance, Tweak

#222 Ordeal monitor
  code/_globalvars/lists/objects.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/game/objects/structures/ordealmonitor.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/ordeals/amber_ordeals.dm
  code/modules/ordeals/crimson_ordeals.dm
  code/modules/ordeals/green_ordeals.dm
  code/modules/ordeals/indigo_ordeals.dm
  code/modules/ordeals/misc_ordeals.dm
  icons/obj/ordeal_monitor.dmi
  lobotomy-corp13.dme
Labels: Feature

#215 The bear armor EGO resprite
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
Labels: Tweak

#223 Abnormality queue console
  code/game/machinery/computer/abnormality_queue.dm
  lobotomy-corp13.dme
Labels: Feature

#216 Observation Bonuses
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/abnormality_work.dm
Labels: Tweak

#218 Records 2, Electric Boogaloo
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
  code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/paperwork/records/info/_info.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/paperwork/records/info/zayin.dm
Labels: Tweak

#224 Oops, Woodsman Record Update!
  code/modules/paperwork/records/info/he.dm
Labels: Tweak

#225 Alpa, Beta, CentComm Updates: 2, Meltdown Screen
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/manager_elevator.dmm
Labels: Mapping

#227 Work Results
  code/game/machinery/computer/abnormality_work.dm
Labels: Tweak

#221 Adds About half of the Remaining LC Ego
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
Labels: Feature

#232 Small Fix
  code/datums/abnormality/datum/abnormality.dm
Labels: Fix

#171 Life For A Daredevil Buff and Tweak
  code/game/objects/items/ego_weapons/he.dm
  sound/weapons/ego/crumbling_parry.ogg
Labels: Tweak

#234 Ordeal tweaks
  code/modules/mob/living/simple_animal/hostile/ordeal/_ordeal.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/ordeals/violet_ordeals.dm
Labels: Tweak, Fix

#235 Resprites EO and RO jackets
  icons/mob/clothing/suit.dmi
Labels: Tweak

#220 White Fixer
  ModularTegustation/Teguicons/32x48.dmi
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
  code/modules/ordeals/white_ordeals.dm
  sound/effects/ordeals/white/Liq_White_Cast.ogg
  sound/effects/ordeals/white/Liq_White_Cast2.ogg
  sound/effects/ordeals/white/Liq_White_CircleAtk.ogg
  sound/effects/ordeals/white/Liq_White_CircleCastEnd.ogg
  sound/effects/ordeals/white/Liq_White_Dead.ogg
  sound/effects/ordeals/white/white_beam.ogg
  sound/effects/ordeals/white/white_beam_start.ogg
  sound/effects/ordeals/white/white_circle.ogg
  sound/effects/ordeals/white/white_reflect.ogg
Labels: Feature

#219 no more bong
  code/datums/quirks/neutral.dm
Labels: Tweak

#239 Adds Old Lady and Solitude (Fixed this time)
  ModularTegustation/Teguicons/32x32.dmi
  code/datums/abnormality/_ego_datum/teth.dm
  code/modules/mob/living/simple_animal/abnormality/teth/old_lady.dm
  code/modules/projectiles/ammunition/ego_ammunition/teth.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
  icons/effects/effects.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#238 We can change anything 2: electric bogaloo
  ModularTegustation/Teguicons/tegumobs.dmi
  code/datums/abnormality/_ego_datum/zayin.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
  code/modules/paperwork/records/info/zayin.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#230 EGO Gifts 2: With a VENGEANCE
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/staining_rose.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_queen.dm
  code/modules/mob/living/simple_animal/abnormality/he/silent_girl.dm
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
  code/modules/mob/living/simple_animal/abnormality/teth/dingle_dangle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
Labels: Tweak

#241 Control department core suppression
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/ordeals/white_ordeals.dm
  code/modules/suppressions/_core_suppression.dm
  code/modules/suppressions/control.dm
  lobotomy-corp13.dme
  sound/effects/suppression.ogg
Labels: Feature

#240 Upgrades abnormality queue, fixes meltdown works
  code/_globalvars/lists/objects.dm
  code/controllers/subsystem/abnormality_queue.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/abnormality_queue.dm
  code/game/machinery/computer/abnormality_work.dm
  sound/machines/dun_don_alert.ogg
Labels: Tweak, Fix

#242 Bottle Of Tears 2 Electric Boogaloo
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/paperwork/records/info/zayin.dm
Labels: Tweak

#231 Funeral Of The Dead Butterflies
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/64x96.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
  sound/abnormalities/funeral/coffin.ogg
  sound/abnormalities/funeral/spiritgun.ogg
  sound/abnormalities/funeral/spiritgunblack.ogg
  sound/abnormalities/funeral/spiritgunwhite.ogg
Labels: Feature
