Repository vlggms/lobotomy-corp13, pull requests merged in 2023-03, with the labels that each got.

#687 Treesap fix
  code/modules/mob/living/simple_animal/abnormality/_tools/he/treesap.dm
Labels: Fix

#686 WAW Dump
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/64x48.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/64x96.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/contract.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dimension_refraction.dm
  code/modules/mob/living/simple_animal/abnormality/waw/flesh_idol.dm
  code/modules/paperwork/records/info/waw.dm
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#697 Halves Chems inside pens
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Balance

#675 Punishing bird no longer flies in containment
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
Labels: Fix

#701 DRV damage increase.
  code/modules/mob/living/simple_animal/abnormality/waw/dimension_refraction.dm
Labels: Balance

#695 Nerfs clown smiling at me
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
Labels: Balance

#702 Makes Galaxy EGO fire faster without homing
  code/modules/projectiles/guns/ego_gun/he.dm
Labels: Balance

#704 Updates pharaoh in-hands
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
Labels: Fix

#683 SG Tweak
  code/modules/mob/living/simple_animal/abnormality/he/silent_girl.dm
Labels: Tweak

#699 Flesh Idol and Pink Midnight Bugfixes
  code/modules/mob/living/simple_animal/abnormality/waw/flesh_idol.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/misc.dm
Labels: Fix

#696 Cowardice Fix
  code/modules/mob/living/carbon/human/ego_gifts.dm
Labels: Balance, Fix

#714 Updates Gammacorp
  _maps/map_files/Gamma/gammacorp.dmm
Labels: Mapping

#707 Shield code cleanup
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
Labels: Code improvement

#710 Limbus sweep
  code/game/objects/items/ego_weapons/limbus.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  icons/mob/inhands/96x96_lefthand.dmi
  icons/mob/inhands/96x96_righthand.dmi
  icons/mob/inhands/weapons/limbus_lefthand.dmi
  icons/mob/inhands/weapons/limbus_righthand.dmi
  icons/obj/limbus_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#625 Violet Midnight
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/64x64.dmi
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
  code/modules/ordeals/violet_ordeals.dm
  icons/effects/beam.dmi
  icons/effects/effects.dmi
  sound/effects/ordeals/violet/midnight_black_attack1.ogg
  sound/effects/ordeals/violet/midnight_black_attack2.ogg
  sound/effects/ordeals/violet/midnight_dead.ogg
  sound/effects/ordeals/violet/midnight_pale_attack.ogg
  sound/effects/ordeals/violet/midnight_pale_move.ogg
  sound/effects/ordeals/violet/midnight_portal_off.ogg
  sound/effects/ordeals/violet/midnight_portal_on.ogg
  sound/effects/ordeals/violet/midnight_red_attack.ogg
  sound/effects/ordeals/violet/midnight_white_attack.ogg
Labels: Feature, Tweak

#713 Limbus Plushie Update
  ModularTegustation/tegu_items/lc13unique_items.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/game/objects/items/plushes.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  icons/obj/plushes.dmi
Labels: Tweak

#718 Naked Nest Text Changes
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
Labels: Tweak

#698 What is he wearing!?
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Feature

#725 Lances no longer turn you into sonic the hedgehog
  code/game/objects/items/ego_weapons/limbus.dm
Labels: Fix

#721 Quick Waw Records fix
  code/modules/paperwork/records/info/waw.dm
Labels: Fix

#711 Automates Weapon Examination and Adds in LC Armor Examination
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ego_gun.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/special.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
Labels: Code improvement, Tweak

#693 Pbird no longer can solo ordeals
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
Labels: Balance

#717 Gun Fix PR
  code/modules/projectiles/ammunition/ego_ammunition/aleph.dm
  code/modules/projectiles/guns/ego_gun.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  code/modules/projectiles/projectile/ego_bullets/aleph.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
Labels: Fix

#732 Revert "Bump webpack from 5.21.2 to 5.76.0 in /tgui"
  tgui/package.json
  tgui/yarn.lock
Labels: dependencies

#734 Apostle Buff
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
Labels: Tweak

#502 Queen of Hatred Code Improvement and Visual Changes
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  icons/effects/64x64.dmi
Labels: Fix

#735 Updates Gamma and Delta (Mostly Gamma)
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
Labels: Mapping

#736 Improves custom vendors
  code/modules/vending/_vending.dm
  tgui/packages/tgui/interfaces/Vending.js
Labels: Code improvement, Tweak, Fix

#737 Library of Ruina Fix
  code/modules/paperwork/records/info/_info.dm
Labels: Fix

#738 FIXES GAMMA SAFETY
  _maps/map_files/Gamma/gammacorp.dmm
Labels: Fix, Mapping

#741 Fix linter and CI issues
  .github/workflows/ci_suite.yml
  .vscode/launch.json
  .vscode/tasks.json
  code/datums/brain_damage/severe.dm
  code/datums/components/singularity.dm
  code/datums/diseases/dna_spread.dm
  code/datums/quirks/neutral.dm
  code/game/machinery/requests_console.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
  code/modules/client/preferences_savefile.dm
  code/modules/hydroponics/hydroponics_chemreact.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/mob_helpers.dm
  code/modules/power/singularity/singularity.dm
  code/modules/research/nanites/nanite_programs.dm
  code/modules/ruins/lavalandruin_code/elephantgraveyard.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/vehicles/mecha/equipment/tools/other_tools.dm
  code/modules/vending/_vending.dm
  config/game_options.txt
  dependencies.sh
  tgui/bin/tgui
  tools/bootstrap/node
  tools/bootstrap/node.bat
  tools/bootstrap/node_.ps1
  tools/build/build
  tools/ci/build.ps1
  tools/ci/ci_maps.txt
  tools/ci/run_server.sh
Labels: Code improvement, Github, Red Label

#742 More chat badges
  config/badges.json
  icons/badges.dmi
Labels: Tweak

#739 Delta, Gamma, CC Tweaks.
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/generic/CentCom.dmm
Labels: Mapping

#743 Removes stuns and stamina damage from unarmed attacks
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
Labels: Tweak

#744 Sorts attributes
  code/datums/attributes/_attribute.dm
Labels: Tweak

#726 Third fate's loom
  ModularTegustation/Teguicons/toolabnormalities.dmi
  code/modules/mob/living/simple_animal/abnormality/_tools/he/fateloom.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/paperwork/records/info/tools.dm
  lobotomy-corp13.dme
  sound/abnormalities/fateloom/garrote.ogg
  sound/abnormalities/fateloom/garrote_bloody.ogg
Labels: Feature

#751 Fix typos and rephrase messages
  code/datums/quirks/good.dm
  code/datums/quirks/negative.dm
  code/modules/paperwork/paper_premade.dm
Labels: Fix

#755 Punishing Bird tweaks
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
Labels: Tweak

#753 Fixes random spawn station trait
  code/controllers/subsystem/job.dm
Labels: Fix

#731 Recycler and morgue tray changes
  code/game/machinery/recycler.dm
  code/game/objects/structures/morgue.dm
Labels: Tweak

#752 Fix manager camera examination
  code/__HELPERS/abnormalities.dm
  code/game/machinery/computer/manager_camera.dm
Labels: Fix

#747 Rewrites status_type handling to be clearer
  code/datums/status_effects/status_effect.dm
Labels: Code improvement

#750 Adds a tutorial button to the lobby menu
  code/__HELPERS/tegutranslate.dm
  code/modules/awaymissions/corpse.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Tweak

#746 Update Byond and SpacemanDMM versions, remove extools
  SpacemanDMM.toml
  code/__DEFINES/_tick.dm
  code/_compile_options.dm
  code/controllers/subsystem/statpanel.dm
  code/controllers/subsystem/time_track.dm
  code/game/world.dm
  dependencies.sh
  tools/tgs4_scripts/PreCompile.sh
Labels: dependencies, Tweak

#748 Bee Target Fix
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
Labels: Tweak

#745 Adds limbus company clothes
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/suits/ego_gear/limbus.dm
  code/modules/clothing/under/accessories.dm
  code/modules/clothing/under/limbus_suits.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  icons/mob/clothing/accessories.dmi
  icons/mob/clothing/ego_gear/limbus_suit.dmi
  icons/mob/clothing/ego_gear/under.dmi
  icons/mob/clothing/neck.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/ego_gear/limbus_suits.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/clothing/under/suits.dmi
  lobotomy-corp13.dme
Labels: Tweak

#759 Abnormalities by default will not target dead bodies.
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Tweak

#754 Dreaming current fix(?) and tweak
  code/modules/mob/living/simple_animal/abnormality/waw/dreaming_current.dm
Labels: Tweak, Fix

#758 Nothing There tweaks
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
Labels: Balance, Tweak, Test Merge Candidate

#763 SpawnAbno but as a verb
  code/modules/admin/admin_verbs.dm
Labels: Feature

#733 LONG BIRD BASEBALL BAT
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
Labels: Balance

#768 Removes maintainance pills from wishing well
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
Labels: Balance, Tweak

#769 Apostle tweaks
  ModularTegustation/Teguicons/48x64.dmi
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  sound/abnormalities/whitenight/apostle_growl.ogg
  sound/abnormalities/whitenight/scythe_gib.ogg
Labels: Balance, Tweak, Fix

#772 Added qliphoth logs
  code/datums/abnormality/datum/abnormality.dm
Labels: Tweak

#775 Abnormality queue rank tweaks
  code/controllers/subsystem/abnormality_queue.dm
Labels: Tweak

#771 QoH beam anywhere
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
Labels: Tweak

#776 Lance refractor
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/limbus.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  icons/mob/inhands/96x96_lefthand.dmi
  icons/mob/inhands/96x96_righthand.dmi
  icons/obj/limbus_weapons.dmi
Labels: Code improvement, Tweak

#774 Void Dream update
  code/datums/status_effects/debuffs.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/sound.dm
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  icons/effects/effects.dmi
  sound/abnormalities/voiddream/ambient_1.ogg
  sound/abnormalities/voiddream/ambient_2.ogg
  sound/abnormalities/voiddream/change.ogg
  sound/abnormalities/voiddream/fire.ogg
  sound/abnormalities/voiddream/shout.ogg
  sound/abnormalities/voiddream/skill.ogg
  sound/weapons/ego/dreamy1.ogg
  sound/weapons/ego/dreamy2.ogg
Labels: Code improvement, Tweak

#777 Please for the love of God give player-contolled clowns a click cooldown!
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson.dm
Labels: Fix

#757 Changes green midnight's behavior
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
Labels: Balance, Fix

#709 Fairy Law
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
Labels: Feature

#716 Adds Meat Lantern
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/224x128.dmi
  ModularTegustation/Teguicons/64x32.dmi
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/meat_lantern.dm
  code/modules/paperwork/records/info/teth.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#778 Button tweaks
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/touch.dm
Labels: Code improvement, Tweak

#756 Adds Golden Apple
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/96x48.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/goldenapple/False_Attack.ogg
  sound/abnormalities/goldenapple/False_Attack2.ogg
  sound/abnormalities/goldenapple/False_Dead.ogg
  sound/abnormalities/goldenapple/Gold_Attack.ogg
  sound/abnormalities/goldenapple/Gold_Attack2.ogg
  sound/abnormalities/goldenapple/Gold_Falsify.ogg
  sound/abnormalities/goldenapple/Gold_Sparkle.ogg
  sound/abnormalities/goldenapple/Legerdemain.ogg
Labels: Feature, Test Merge Candidate

#681 White Lake tweaks
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
Labels: Balance

#788 Locks "Red Roll" behind secrets button
  code/controllers/subsystem/abnormality_queue.dm
  code/game/machinery/computer/abnormality_queue.dm
  code/modules/admin/verbs/secrets.dm
  tgui/packages/tgui/interfaces/AbnormalityQueue.js
  tgui/packages/tgui/interfaces/Secrets.js
Labels: Tweak

#790 Happy teddy bear fix
  code/modules/mob/living/simple_animal/abnormality/he/happy_teddy_bear.dm
Labels: Fix

#789 Adds LC-themed HP icons, centers sanity cracks
  code/_onclick/hud/_defines.dm
  icons/hud/screen_gen.dmi
Labels: Sprites

#648 E-Corp V4 - Wonderlabs Realized
  ModularTegustation/tegu_items/lc13unique_items.dm
  _maps/alphacorp.json
  _maps/betacorp.json
  _maps/deltacorp.json
  _maps/epsiloncorp.json
  _maps/gammacorp.json
  _maps/map_files/Epsilon/epsiloncommand.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/shuttles/secondary_epsilon.dmm
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/maptype.dm
  code/datums/map_config.dm
  code/datums/shuttles.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/clothing/head/departmentberet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/gimmick/HHPP.dm
  code/modules/jobs/job_types/gimmick/departmentcaptain.dm
  code/modules/jobs/job_types/gimmick/departmenthead.dm
  code/modules/jobs/jobs.dm
  icons/mob/hud.dmi
  icons/obj/card.dmi
  lobotomy-corp13.dme
Labels: Tweak, Mapping

#791 Fixes misplaced negative, increases bottle damage.
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
Labels: Balance, Fix

#794 Void dream targeting fix
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
  lobotomy-corp13.dme
Labels: Fix

#795 Moves records watches
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/command.dm
  icons/obj/closet.dmi
Labels: Fix, Mapping

#519 door panels
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/lc13doorpanels.dmi
  ModularTegustation/lc13_machinery.dm
  _maps/templates/abnormality_containment.dmm
  code/game/machinery/computer/abnormality_work.dm
  code/game/objects/effects/spawners/abnormality_room.dm
  lobotomy-corp13.dme
Labels: Feature, Mapping

#740 Adds nosferatu
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/64x64.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/nosferatu/attack.ogg
  sound/abnormalities/nosferatu/attack_special.ogg
  sound/abnormalities/nosferatu/bat_attack.ogg
  sound/abnormalities/nosferatu/batspawn.ogg
  sound/abnormalities/nosferatu/bloodcollect.ogg
  sound/abnormalities/nosferatu/special_start.ogg
  sound/abnormalities/nosferatu/transform.ogg
Labels: Feature, Test Merge Candidate
