Repository vlggms/lobotomy-corp13, pull requests merged in 2023-10, with the labels that each got.

#1478 Adds library maps (Except Kether)
  _maps/map_files/Library/floor_art.dmm
  _maps/map_files/Library/floor_history.dmm
  _maps/map_files/Library/floor_language.dmm
  _maps/map_files/Library/floor_literature.dmm
  _maps/map_files/Library/floor_naturalsci.dmm
  _maps/map_files/Library/floor_philosophy.dmm
  _maps/map_files/Library/floor_religion.dmm
  _maps/map_files/Library/floor_socialsci.dmm
  _maps/map_files/Library/floor_techsci.dmm
  _maps/map_files/Library/floor_template.dmm
Labels: Mapping

#1495 EGO Weapon Cleanup
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/subtype/shield.dm
Labels: Red Label, Fix

#1497 Fixes shield armor scaling
  code/game/objects/items/ego_weapons/subtype/shield.dm
Labels: Balance, Tweak

#1492 Increases both roses armors stats by 1
  code/modules/clothing/suits/ego_gear/aleph.dm
Labels: Balance

#1444 Makes Violet Midnight not Racist
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
Labels: Tweak

#1498 Grown Strong Nerf
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
Labels: Balance

#1500 AIB Sanity Fix
  code/modules/mob/living/simple_animal/abnormality/aleph/army_in_black.dm
Labels: Fix

#1501 Shield Update Fix
  code/game/objects/items/ego_weapons/subtype/shield.dm
Labels: Fix

#1505 Ledgermain and Cane Office Fix
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/non_abnormality/black_silence.dm
  code/game/objects/items/ego_weapons/non_abnormality/cane.dm
Labels: Fix

#1506 Library Map Fixes
  _maps/map_files/Library/floor_history.dmm
  _maps/map_files/Library/floor_literature.dmm
  _maps/map_files/Library/floor_naturalsci.dmm
  _maps/map_files/Library/floor_philosophy.dmm
  _maps/map_files/Library/floor_religion.dmm
  _maps/map_files/Library/floor_socialsci.dmm
Labels: Mapping

#1388 Ppodae sprite change
  ModularTegustation/Teguicons/48x48.dmi
Labels: Sprites

#1489 Blue Reverb Scythe Update
  code/game/objects/items/ego_weapons/non_abnormality/blue_sicko.dm
Labels: Balance, Tweak

#1512 Buffs Out of Space
  code/game/objects/items/ego_weapons/aleph.dm
Labels: Balance

#1515 Update Outis's Plushie Hair and Skin Color
  icons/obj/plushes.dmi
Labels: Sprites

#1508 Judgement Bird now creates a noose on kill.
  ModularTegustation/Teguicons/48x64.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  sound/abnormalities/judgementbird/hang.ogg
  sound/abnormalities/judgementbird/kill.ogg
Labels: Feature

#1513 Purple Tear Weapon
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_left_64x64.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_right_64x64.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/tegu_items/refinery/crates/workshop.dm
  code/game/objects/items/ego_weapons/non_abnormality/color_fixer.dm
  code/game/objects/items/ego_weapons/non_abnormality/purple_tear.dm
  icons/effects/beam.dmi
  icons/mob/actions/actions_ability.dmi
  lobotomy-corp13.dme
  sound/weapons/purple_tear/blunt1.ogg
  sound/weapons/purple_tear/blunt2.ogg
  sound/weapons/purple_tear/change.ogg
  sound/weapons/purple_tear/guard.ogg
  sound/weapons/purple_tear/slash1.ogg
  sound/weapons/purple_tear/slash2.ogg
  sound/weapons/purple_tear/slash3.ogg
  sound/weapons/purple_tear/stab1.ogg
  sound/weapons/purple_tear/stab2.ogg
Labels: Feature

#1483 Replaces old Sorority sprite
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
Labels: Sprites

#1519 J-Corp syndicate Refinery
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/Teguicons/refiner.dmi
  ModularTegustation/tegu_items/refinery/_spawners.dm
  ModularTegustation/tegu_items/refinery/crates/syndicate.dm
  ModularTegustation/tegu_items/refinery/sales.dm
  code/game/objects/items/ego_weapons/non_abnormality/_cityweapons.dm
  code/game/objects/items/ego_weapons/non_abnormality/jcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/mariachi.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/jcorp.dm
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  lobotomy-corp13.dme
Labels: Expansion

#1525 Revert Pillow to 9.3.0
  tools/requirements.txt
Labels: dependencies

#1524 NO MORE COCOONS
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/spells/ability_types/realized_aimed.dm
  sound/abnormalities/spider_bud/jump.ogg
  sound/abnormalities/spider_bud/land.ogg
Labels: Tweak

#1518 Removes dark color restriction for spraying but removes spraying in LoR
  code/game/objects/items/crayons.dm
Labels: Tweak

#1517 Adds pinocchio plush
  code/datums/quirks/neutral.dm
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Sprites

#1457 Puts "random" Seeds in the Concept Incinerator
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/cargo/blackmarket/blackmarket_items/misc.dm
  code/modules/cargo/packs.dm
  code/modules/hydroponics/grown/random.dm
  code/modules/hydroponics/seeds.dm
  code/modules/vending/megaseed.dm
  lobotomy-corp13.dme
Labels: Removal

#1382 Sweeper get diminishing returns from eating other sweepers
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Tweak

#1481 Adds a new distortion
  ModularTegustation/Teguicons/32x32.dmi
  code/modules/mob/living/simple_animal/distortion/star/_star.dm
  code/modules/mob/living/simple_animal/distortion/star/shrimp.dm
  lobotomy-corp13.dme
Labels: Side content

#901 Adds Red Shoes
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/datums/looping_sounds/abnormalities.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_shoes.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/feet.dmi
  lobotomy-corp13.dme
  sound/abnormalities/redshoes/RedShoes_Activate.ogg
  sound/abnormalities/redshoes/RedShoes_Attack.ogg
  sound/abnormalities/redshoes/RedShoes_Idle.ogg
  sound/abnormalities/redshoes/RedShoes_Kill.ogg
Labels: Test Merge Candidate, Abnormality

#1511 Fixes Charge Weapons
  code/game/objects/items/ego_weapons/non_abnormality/_charge.dm
  code/game/objects/items/ego_weapons/non_abnormality/cane.dm
  code/game/objects/items/ego_weapons/non_abnormality/rosespanner.dm
  code/game/objects/items/ego_weapons/non_abnormality/wcorp.dm
  code/game/objects/items/ego_weapons/subtype/charge.dm
Labels: Fix

#1532 Fixes Bleeding heart
  code/game/objects/items/ego_weapons/waw.dm
Labels: Fix

#1533 THE BIG BIRD ANIMATION BUFF (and Yin and Yang Sprite update)
  ModularTegustation/Teguicons/64x64.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
Labels: Sprites

#1535 Thumb, Kuro, and BL inhands
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  code/game/objects/items/ego_weapons/non_abnormality/syndicate.dm
Labels: Sprites

#1536 Adds Maraca audio file, J corp maracas will now
  code/game/objects/items/ego_weapons/non_abnormality/jcorp.dm
  sound/weapons/fixer/generic/maracas1.ogg
Labels: Tweak

#1400 Some experimental changes
  code/__DEFINES/abnormalities.dm
  code/__DEFINES/attributes.dm
  code/__DEFINES/mobs.dm
  code/datums/abnormality/datum/abnormality.dm
  code/datums/attributes/_attribute.dm
  code/datums/attributes/fortitude.dm
  code/datums/attributes/justice.dm
  code/datums/attributes/prudence.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/physiology.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Code improvement, Tweak, Test Merge Candidate

#1541 Shi, 7, and Hana updates/inhands
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/tegu_items/refinery/sales.dm
  code/game/objects/items/ego_weapons/non_abnormality/hana.dm
  code/game/objects/items/ego_weapons/non_abnormality/shi.dm
  sound/weapons/fixer/hana_blunt.ogg
  sound/weapons/fixer/hana_pierce.ogg
  sound/weapons/fixer/hana_slash.ogg
Labels: Tweak, Sprites

#1224 Abno Dump 2023
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/zayin.dm
  code/datums/attributes/_attribute.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  code/modules/mob/living/simple_animal/abnormality/he/eris.dm
  code/modules/mob/living/simple_animal/abnormality/he/highway_devotee.dm
  code/modules/mob/living/simple_animal/abnormality/he/will_you_play.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cleaner.dm
  code/modules/mob/living/simple_animal/abnormality/teth/skin_prophet.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/oceanwaves.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/sunset_traveller.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/paperwork/records/info/zayin.dm
  code/modules/projectiles/ammunition/ego_ammunition/zayin.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  code/modules/projectiles/projectile/ego_bullets/zayin.dm
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/mob/clothing/ego_gear/abnormality/zayin.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/clothing/ego_gear/abnormality/zayin.dmi
  icons/obj/drinks.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/structures.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#1539 Distortions update
  code/controllers/subsystem/city_events.dm
  code/modules/mob/living/simple_animal/distortion/_distortion.dm
  code/modules/mob/living/simple_animal/distortion/plague/lantern.dm
  code/modules/mob/living/simple_animal/distortion/star/shrimp.dm
  lobotomy-corp13.dme
Labels: Side content

#1540 Better living nest worms and some other realized ability changes
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/spells/ability_types/realized.dm
Labels: Feature, Tweak

#1545 Nerfs gold dusk
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold.dm
Labels: Balance

#1549 Sunset Traveller buff
  code/modules/mob/living/simple_animal/abnormality/zayin/sunset_traveller.dm
Labels: Balance

#1552 The Inhandening PR + Some organization
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
Labels: Fix, Sprites

#1556 Enforce labels
  .github/workflows/enforce-labels.yml
Labels: Github

#1551 Ego dump
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/96x96_lefthand.dmi
  icons/mob/inhands/96x96_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
Labels: Sprites, Expansion

#1558 Pygmalion prudence fix
  code/modules/mob/living/simple_animal/abnormality/waw/pygmalion.dm
Labels: Fix

#1557 The Inhandening PR act 2, *children of the city starts playing
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  code/game/objects/items/ego_weapons/non_abnormality/kcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/rosespanner.dm
  code/game/objects/items/ego_weapons/non_abnormality/shrimp.dm
  code/game/objects/items/ego_weapons/non_abnormality/streetlight.dm
  code/game/objects/items/ego_weapons/non_abnormality/weak_edits/city.dm
  code/game/objects/items/ego_weapons/non_abnormality/zwei.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
Labels: Sprites

#1565 Damage Coeff Instancing
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Red Label, Fix

#1568 Fix Aquarium Sprites
  ModularTegustation/fishing/code/fish/freshwater_fish.dm
  ModularTegustation/fishing/code/fish/saltwater_fish.dm
  code/datums/components/aquarium.dm
Labels: Fix

#1562 Removes Toggle from Blind Rage AOE
  code/game/objects/items/ego_weapons/waw.dm
Labels: Balance, Fix

#1559 Minor abnormality fixes and adjustments
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/tegu_items/rcorp/landmarks.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/wayward_passenger.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
Labels: Tweak, Fix

#1570 Adds joke E.G.O.
  ModularTegustation/Teguicons/lc13_weapons.dmi
  code/datums/abnormality/_ego_datum/joke.dm
  code/game/objects/items/ego_weapons/joke.dm
  code/modules/clothing/suits/ego_gear/joke.dm
  icons/mob/clothing/under/costume.dmi
  icons/obj/clothing/under/costume.dmi
  lobotomy-corp13.dme
Labels: Expansion

#1372 More fish modularization, adds fish debug items, the fishing hat can now vore, you can fish in bathwater
  ModularTegustation/Teguicons/head_item.dmi
  ModularTegustation/fishing/code/_debug_spawners.dm
  ModularTegustation/fishing/code/fish_market.dm
  ModularTegustation/fishing/code/fishing_items/_debug_items.dm
  ModularTegustation/fishing/code/fishing_items/fishing_cloak.dm
  ModularTegustation/fishing/code/fishing_items/fishing_hat.dm
  ModularTegustation/fishing/code/fishing_items/fishing_rod.dm
  ModularTegustation/fishing/code/fishing_skill.dm
  ModularTegustation/fishing/code/turfs.dm
  ModularTegustation/fishing/icons/clothes_items.dmi
  ModularTegustation/fishing/icons/clothes_worn.dmi
  ModularTegustation/tegu_clothes_code/head.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
  icons/obj/clothing/cloaks.dmi
  lobotomy-corp13.dme
Labels: Code improvement

#1567 Agent work statistics
  code/__HELPERS/roundend.dm
  code/_globalvars/game_modes.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/abnormality_logs.dm
Labels: Feature

#1571 Fixes Armor Update hitby Proc Runtimes
  code/game/objects/obj_defense.dm
Labels: Fix

#1574 Makes adjustments to god of the seasons
  code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
  code/modules/paperwork/records/info/aleph.dm
Labels: Balance, Tweak

#1563 Strong info update
  code/modules/paperwork/records/info/he.dm
Labels: Fix, Writing

#1530 Updates FAN
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/modules/mob/living/simple_animal/abnormality/he/fan.dm
  code/modules/paperwork/records/info/he.dm
  sound/abnormalities/FAN/turnoff.ogg
  sound/abnormalities/FAN/turnon.ogg
Labels: Tweak

#1502 Adds old faith and promise
  ModularTegustation/Teguicons/toolabnormalities.dmi
  code/_onclick/item_attack.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/promise.dm
  code/modules/paperwork/records/info/tools.dm
  code/modules/projectiles/guns/ego_gun.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/spells/ability_types/realized.dm
  lobotomy-corp13.dme
  sound/abnormalities/portrait/dead1.ogg
  sound/abnormalities/portrait/dead2.ogg
  sound/abnormalities/portrait/use.ogg
  sound/abnormalities/promise/fail.ogg
  sound/abnormalities/promise/marble.ogg
  sound/abnormalities/promise/process.ogg
  sound/abnormalities/promise/result.ogg
  sound/abnormalities/promise/success.ogg
Labels: Abnormality

#1543 Adds Visual to Immunity and Heal for Hostile Mobs
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  icons/effects/effects.dmi
Labels: Feature, Tweak

#1326 Damage Coeff Change Standardization
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_items/workshop/mods/curing.dm
  ModularTegustation/tegu_items/workshop/mods/healthup.dm
  ModularTegustation/tegu_items/workshop/mods/sapping.dm
  ModularTegustation/tegu_mobs/chaos_marine.dm
  code/controllers/subsystem/lobotomy_events.dm
  code/datums/status_effects/buffs.dm
  code/datums/status_effects/debuffs.dm
  code/game/machinery/computer/manager_camera.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_ego.dm
  code/game/objects/items/ego_weapons/non_abnormality/pierre.dm
  code/game/objects/items/ego_weapons/non_abnormality/purple_tear.dm
  code/game/objects/items/ego_weapons/non_abnormality/wcorp.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/_damage_coeff.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/silent_orchestra.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/mob/living/simple_animal/abnormality/he/norinori.dm
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_shoes.dm
  code/modules/mob/living/simple_animal/abnormality/he/scaredy_cat.dm
  code/modules/mob/living/simple_animal/abnormality/he/schadenfreude.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yang.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yin.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/damage_coeff_helper.dm
  code/modules/mob/living/simple_animal/damage_procs.dm
  code/modules/mob/living/simple_animal/dc_changes.dm
  code/modules/mob/living/simple_animal/distortion/_distortion.dm
  code/modules/mob/living/simple_animal/distortion/plague/bunnyman.dm
  code/modules/mob/living/simple_animal/guardian/types/protector.dm
  code/modules/mob/living/simple_animal/guardian/types/support.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  code/modules/spells/ability_types/realized.dm
  code/modules/suppressions/extraction.dm
  lobotomy-corp13.dme
Labels: Code improvement, Feature, Fix

#1542 Fixes Homing Instinct not correctly going back to a minimum
  code/game/objects/items/ego_weapons/he.dm
Labels: Fix

#1548 Better evil shrimp sprite
  ModularTegustation/Teguicons/32x32.dmi
Labels: Sprites

#1544 Modular Regenerator Effects for Remote Procs
  ModularTegustation/tegu_items/representative/research.dm
  code/game/machinery/regenerator.dm
Labels: Tweak

#1473 Tool E.G.O weapon rework
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/tools.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  code/modules/spells/ability_types/realized.dm
  icons/obj/projectiles.dmi
Labels: Tweak, Expansion

#1580 Fixes roundend abnormality report
  code/__HELPERS/roundend.dm
Labels: Fix

#1581 Assorted fixes (maybe)
  ModularTegustation/tegu_items/refinery/crates/association.dm
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/refinery/crates/misc.dm
  ModularTegustation/tegu_items/refinery/crates/syndicate.dm
  ModularTegustation/tegu_items/refinery/crates/workshop.dm
  _maps/templates/syndicate_office/index.dmm
  code/modules/clothing/suits/ego_gear/non_abnormality/index.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/jcorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/kcorp.dm
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
Labels: Fix

#1582 More Joke Ego
  code/datums/abnormality/_ego_datum/joke.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/joke.dm
  icons/mob/inhands/96x96_lefthand.dmi
  icons/mob/inhands/96x96_righthand.dmi
  icons/obj/ego_weapons.dmi
Labels: Feature

#1583 EGO immunity fix
  code/modules/mob/living/simple_animal/_damage_coeff.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Red Label, Fix

#1585 Fixes abno report for good
  code/__HELPERS/roundend.dm
Labels: Fix

#1586 Damage Coeff order of operations
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#1522 Reworks some TETH abnormalities
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Teguicons/96x64.dmi
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_gentleman.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_long_legs.dm
  code/modules/mob/living/simple_animal/abnormality/teth/so_that_no_cry.dm
  code/modules/paperwork/records/info/teth.dm
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  sound/abnormalities/fairygentleman/jump.ogg
  sound/abnormalities/so_that_no_cry/attack.ogg
  sound/abnormalities/so_that_no_cry/counter.ogg
  sound/abnormalities/so_that_no_cry/prepare.ogg
Labels: Tweak

#1572 The Holomap Port
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/flags.dm
  code/__DEFINES/holomap.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/subsystems.dm
  code/_globalvars/bitfields.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/subsystem/holomap.dm
  code/game/area/areas/shuttles.dm
  code/game/machinery/facility_holomap.dm
  code/modules/holomap/holomap_areas.dm
  code/modules/holomap/holomap_datum.dm
  icons/480x480.dmi
  icons/effects/64x64.dmi
  icons/misc/holomap_markers.dmi
  icons/obj/machines/facilitymap.dmi
  lobotomy-corp13.dme
Labels: Feature, Mapping

#1584 Some Zayin Buffs and Visual Glow ups.
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/blubbering_toad.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/quiet_day.dm
  code/modules/paperwork/records/info/zayin.dm
  icons/effects/effects.dmi
Labels: Balance, Sprites
