Repository vlggms/lobotomy-corp13, pull requests merged in 2023-07, with the labels that each got.

#1106 Shields had more issues
  code/game/objects/items/ego_weapons/subtype/shield.dm
Labels: Fix

#1097 [TG PORT] adjustHealth Code Cleanup
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/mob/living/simple_animal/damage_procs.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Code improvement

#986 Adds puss in boots
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  code/game/objects/items/clerks/hypo/hypo.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/ego_weapons/tutorial.dm
  code/modules/mob/living/simple_animal/abnormality/he/puss_in_boots.dm
  code/modules/paperwork/records/info/he.dm
  icons/effects/effects.dmi
  icons/mob/inhands/96x96_lefthand.dmi
  icons/mob/inhands/96x96_righthand.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/pussinboots/counterslash.ogg
  sound/abnormalities/pussinboots/gatoblessing.ogg
  sound/abnormalities/pussinboots/slash.ogg
  sound/weapons/ego/mace1.ogg
Labels: Test Merge Candidate, Abnormality

#1112 Protag Weapon Fixes (Eyeball & Daredevil)
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
Labels: Fix

#1066 Pygmalion Prudence Fix
  code/modules/mob/living/simple_animal/abnormality/waw/pygmalion.dm
Labels: Fix

#1111 Nothing There Visual Effects Update
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  icons/effects/effects.dmi
Labels: Sprites

#1107 Stops Moonlight span during work
  code/game/objects/items/ego_weapons/waw.dm
Labels: Balance

#1098 You can no longer be spaced by stepping out an elevator
  code/controllers/subsystem/shuttle.dm
Labels: Fix

#1114 Pyg Prudence fix when sanity is lost
  code/modules/mob/living/simple_animal/abnormality/waw/pygmalion.dm
Labels: Fix

#1118 Timestop Fix
  code/modules/fields/timestop.dm
Labels: Fix

#1090 EGO Resprite, Adds Syrinx.
  code/datums/abnormality/_ego_datum/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/projectiles/ammunition/ego_ammunition/he.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
Labels: Tweak, Sprites

#1037 Minor abnormality adjustments
  ModularTegustation/Teguicons/32x32.dmi
  code/modules/mob/living/simple_animal/abnormality/_tools/he/theonite_slab.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/vivavoce.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  code/modules/mob/living/simple_animal/abnormality/waw/sphinx.dm
  code/modules/paperwork/records/info/tools.dm
  code/modules/paperwork/records/info/waw.dm
  sound/abnormalities/myformempties/attack.ogg
  sound/abnormalities/seasons/fall_attack.ogg
  sound/abnormalities/seasons/summer_attack.ogg
Labels: Tweak

#1083 Black Silence Furioso and IFF Tweak
  code/game/objects/items/ego_weapons/non_abnormality/black_silence.dm
Labels: Tweak, Test Merge Candidate

#1099 Doomsday Calendar Adjustments 2: Electric Boogaloo
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/paperwork/records/info/he.dm
Labels: Tweak, Test Merge Candidate

#1117 2 new neutral quirks, minor quirk rebalance
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/quirks/negative.dm
  code/datums/quirks/neutral.dm
  code/game/objects/items/RCL.dm
  code/game/objects/items/storage/toolbox.dm
Labels: Tweak

#1133 Updates clown smiling at me
  ModularTegustation/Teguicons/tegumobs.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
Labels: Fix, Sprites

#1128 Adds 3 new backstreet rooms
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/east.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/south.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/west.dm
  _maps/RandomRooms/backstreets/medium_east/kcorp_storage.dmm
  _maps/RandomRooms/backstreets/medium_south/eyes_temple.dmm
  _maps/RandomRooms/backstreets/small_west/gcorp_swa.dmm
Labels: Tweak

#1126 LC13 Admin Tools 2
  code/modules/admin/admin_verbs.dm
Labels: Feature

#1040 Simple Fishing Version 1 because TG Fishing is too hard to port for me.
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/head_item.dmi
  ModularTegustation/Teguicons/head_worn.dmi
  ModularTegustation/tegu_clothes_code/head.dm
  code/__DEFINES/aquarium.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/dcs/signals_fish.dm
  code/datums/components/aquarium.dm
  code/datums/skills/fishing.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/modules/aquarium/aquarium_behaviour.dm
  code/modules/aquarium/fish.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/fishing/aquarium/aquarium.dm
  code/modules/fishing/aquarium/aquarium_kit.dm
  code/modules/fishing/fish/_fish.dm
  code/modules/fishing/fish/fish_types.dm
  code/modules/fishing/simple_fishing.dm
  icons/mob/clothing/neck.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/obj/aquarium.dmi
  icons/obj/clothing/cloaks.dmi
  lobotomy-corp13.dme
  sound/effects/bigsplash.ogg
  sound/effects/fish_splash.ogg
  sound/effects/splash.ogg
Labels: Feature

#1101 Dream of Black Swan
  ModularTegustation/Teguicons/64x96.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/black_swan.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  lobotomy-corp13.dme
  sound/abnormalities/blackswan/sis_bash.ogg
  sound/abnormalities/blackswan/sis_roar.ogg
  sound/abnormalities/blackswan/sis_swoop.ogg
  sound/abnormalities/blackswan/sis_transformation.ogg
Labels: Abnormality

#1075 Refinery Update - Color Fixers
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/Teguicons/refiner.dmi
  ModularTegustation/tegu_items/refinery/_spawners.dm
  ModularTegustation/tegu_items/refinery/crates.dm
  ModularTegustation/tegu_items/refinery/sales.dm
  code/game/objects/items/ego_weapons/non_abnormality/_cityweapons.dm
  code/game/objects/items/ego_weapons/non_abnormality/color_fixer.dm
  code/game/objects/items/ego_weapons/non_abnormality/fullstop.dm
  code/game/objects/items/ego_weapons/non_abnormality/gradeone.dm
  code/game/objects/items/ego_weapons/non_abnormality/index.dm
  code/game/objects/items/ego_weapons/non_abnormality/leaflet.dm
  code/game/objects/items/ego_weapons/non_abnormality/liu.dm
  code/game/objects/items/ego_weapons/non_abnormality/miscfixer.dm
  code/game/objects/items/ego_weapons/non_abnormality/rats.dm
  code/game/objects/items/ego_weapons/non_abnormality/shi.dm
  code/game/objects/items/ego_weapons/non_abnormality/yun.dm
  code/game/objects/items/ego_weapons/non_abnormality/zwei.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/color.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/liu.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/ncorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/rosespanner.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/paperwork/records/tutorial/refinery.dm
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/mob/clothing/old_ego.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  lobotomy-corp13.dme
Labels: Tweak

#1125 Fixes the harmony gift
  code/modules/mob/living/carbon/human/ego_gifts.dm
Labels: Fix, Removal

#1121 Fuck Ravens
  ModularTegustation/tegu_items/rcorp/random_maps.dm
  _maps/RandomRooms/rcorp/facility/beaches.dmm
  _maps/RandomRooms/rcorp/facility/maze.dmm
  _maps/RandomRooms/rcorp/facility/maze2.dmm
  _maps/RandomRooms/rcorp/facility/standard.dmm
  _maps/map_files/Event/rcorp.dmm
  _maps/rcorp_test.json
  code/controllers/subsystem/maptype.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/management/event/combat.dm
  code/game/objects/items/clerks/hypo/hypo.dm
  code/game/objects/items/ego_weapons/non_abnormality/rcorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/rcorp.dm
  code/modules/clothing/under/clerksuits.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/rcorp/command.dm
  code/modules/jobs/job_types/rcorp/officer.dm
  code/modules/jobs/job_types/rcorp/rabbit.dm
  code/modules/jobs/job_types/rcorp/raven.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/guns/misc/medbeam.dm
  icons/mob/clothing/ego_gear/under.dmi
  icons/mob/hud.dmi
  icons/obj/card.dmi
  icons/obj/clothing/ego_gear/lcuniform.dmi
  lobotomy-corp13.dme
Labels: Balance, Mapping

#934 Lambda Corp
  _maps/lambdacorp.json
  _maps/map_files/Lambda/lambdacorp.dmm
Labels: Mapping

#1087 Time-related and other QOL changes
  code/__DEFINES/time.dm
  code/controllers/subsystem/abnormality_queue.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/controllers/subsystem/statpanel.dm
  code/datums/abnormality/datum/abnormality.dm
  code/modules/admin/chat_commands.dm
  code/modules/ordeals/_ordeal.dm
Labels: Code improvement, Tweak, Test Merge Candidate

#1103 Welfare Core Suppression
  ModularTegustation/Teguicons/status_sprites.dmi
  code/modules/suppressions/welfare.dm
  lobotomy-corp13.dme
Labels: Feature

#1109 White ordeals tweak
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
Labels: Balance, Tweak, Fix

#1073 Turns Claw into a menace
  ModularTegustation/tegu_mobs/the_claw.dm
Labels: Balance, Tweak, Test Merge Candidate

#1122 Ice queen room + its items
  ModularTegustation/Teguicons/160x160.dmi
  _maps/custom/iceroom.dmm
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/game/objects/structures/flora.dm
  icons/obj/doors/snowqueendoor.dmi
  icons/obj/flora/icedecor.dmi
Labels: Mapping

#1116 Fixes oversight in IsContained proc
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Fix

#1148 Fuck off clerks
  _maps/map_files/generic/CentCom.dmm
Labels: Fix

#1096 Realized mimicry plus alot of other changes to realized armor
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/spells/ability_types/realized.dm
  code/modules/spells/ability_types/realized_aimed.dm
  icons/effects/effects.dmi
  icons/mob/actions/actions_ability.dmi
  icons/mob/clothing/big_hat.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/obj/clothing/ego_gear/realization.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature, Tweak

#1137 Fishhook Office Fixer
  _maps/map_files/Zeta/zetacorp.dmm
  _maps/zetacorp.json
  code/controllers/subsystem/job.dm
  code/modules/client/preferences.dm
  code/modules/clothing/under/clerksuits.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/gimmick/onemap/fishing.dm
  code/modules/jobs/jobs.dm
  icons/mob/clothing/ego_gear/under.dmi
  icons/mob/hud.dmi
  icons/obj/card.dmi
  icons/obj/clothing/ego_gear/lcuniform.dmi
  lobotomy-corp13.dme
Labels: Feature

#1139 Fixes clown smiling at me getting stuck on mob corpses
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
Labels: Fix

#1140 reworks golden apple
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/paperwork/paper_premade.dm
  code/modules/reagents/chemistry/reagents/abnormality_reagents.dm
Labels: Balance

#1150 Removes Attacking Through Walls Cheese From Some Egos
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
Labels: Balance

#1123 64by64 adjustments
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
Labels: Sprites

#1059 Forging: Ordeal Parts -> Materials
  ModularTegustation/Teguicons/workshop.dmi
  ModularTegustation/tegu_items/workshop/_materials.dm
  ModularTegustation/tegu_items/workshop/_templates.dm
  ModularTegustation/tegu_items/workshop/forging.dm
  ModularTegustation/tegu_items/workshop/ordeal extractor.dm
  lobotomy-corp13.dme
Labels: Feature

#1153 Fishing no longer puts a strain on reality
  code/modules/fishing/simple_fishing.dm
Labels: Fix

#1149 paperbins and misc lights
  _maps/RandomRooms/backstreets/medium_west/butcher_medium.dmm
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
  _maps/map_files/Xi/xicorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
Labels: Mapping

#1147 PE Has a Purpose
  ModularTegustation/tegu_items/records/ordealcheck.dm
  ModularTegustation/tegu_items/refinery/sales.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/game/machinery/computer/abnormality_queue.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/modules/ordeals/_ordeal.dm
Labels: Balance, Tweak

#1141 Shrimple Fishing Update V2
  code/__DEFINES/dcs/signals_fish.dm
  code/datums/components/aquarium.dm
  code/datums/diseases/parasitic_infection.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/game/objects/items/food/meat.dm
  code/game/objects/items/storage/bags.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/fishing/aquarium/aquarium.dm
  code/modules/fishing/aquarium/aquarium_kit.dm
  code/modules/fishing/fish/_fish.dm
  code/modules/fishing/fish/fish_types.dm
  code/modules/fishing/simple_fishing.dm
  code/modules/fishing/simple_fishing_equipment.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/jobs/job_types/gimmick/onemap/fishing.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/obj/aquarium.dmi
  icons/obj/fishing.dmi
  icons/obj/food/food.dmi
  lobotomy-corp13.dme
Labels: Feature, Expansion

#1157 More refinery weapon description updates
  code/game/objects/items/ego_weapons/non_abnormality/dawn.dm
  code/game/objects/items/ego_weapons/non_abnormality/gradeone.dm
  code/game/objects/items/ego_weapons/non_abnormality/jeong.dm
  code/game/objects/items/ego_weapons/non_abnormality/leaflet.dm
  code/game/objects/items/ego_weapons/non_abnormality/mirae.dm
  code/game/objects/items/ego_weapons/non_abnormality/miscfixer.dm
  code/game/objects/items/ego_weapons/non_abnormality/streetlight.dm
Labels: Tweak, Writing

#1062 Limbus Company E.G.O dump
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/spells/ability_types/realized.dm
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/realization.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  sound/abnormalities/fairygentleman/ego_sloshing.ogg
  sound/abnormalities/nocry/ego_redsheet.ogg
  sound/abnormalities/pinkshoes/Pinkshoes_Attack.ogg
  sound/abnormalities/pinkshoes/Pinkshoes_Binding.ogg
  sound/abnormalities/pinkshoes/Pinkshoes_Breach.ogg
  sound/weapons/ego/farmwatch.ogg
  sound/weapons/ego/farmwatch_tree.ogg
  sound/weapons/ego/spicebush.ogg
  sound/weapons/ego/spicebush_fan.ogg
  sound/weapons/ego/spicebush_openfan.ogg
  sound/weapons/ego/spicebush_special.ogg
Labels: Tweak

#1129 I am the Library of Ruina (*turns people into books*)
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/admin/smites/book.dm
  code/modules/mob/living/turn_book.dm
  icons/effects/effects.dmi
  icons/obj/bureaucracy.dmi
  lobotomy-corp13.dme
  sound/effects/book_burn.ogg
  sound/effects/book_turn.ogg
Labels: Feature

#1092 New abno: Fairy Gentleman
  ModularTegustation/Teguicons/96x64.dmi
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_gentleman.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  icons/obj/drinks.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#1164 E.G.O. : Sloshing
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_gentleman.dm
Labels: Fix

#1165 Fix Fishing Net Duping
  code/modules/fishing/simple_fishing.dm
Labels: Fix

#1159 Abnormalities roughly have their movespeeds fixed when playable.
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nihil.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/mob/living/simple_animal/abnormality/he/jangsan.dm
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
  code/modules/mob/living/simple_animal/abnormality/he/road_home.dm
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
  code/modules/mob/living/simple_animal/abnormality/teth/forsaken_murderer.dm
  code/modules/mob/living/simple_animal/abnormality/teth/scorched_girl.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clouded_monk.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dimension_refraction.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
  code/modules/mob/living/simple_animal/abnormality/waw/pygmalion.dm
  code/modules/mob/living/simple_animal/abnormality/waw/sphinx.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yang.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/blubbering_toad.dm
Labels: Fix

#1163 Psicorp update
  _maps/map_files/Psi/psicorp.dmm
Labels: Fix, Mapping

#1169 Remove Steel Ordeal Dexteriity
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
Labels: Tweak

#1172 standardize watch spawn amounts
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
Labels: Tweak

#635 [COMMISSION] Apex Predator
  ModularTegustation/Teguicons/64x64.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/apex_predator.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/paperwork/records/info/zayin.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#1178 Ego refactor (All EGO PRs will be frozen until this is merged.)
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/tools.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/datums/abnormality/_ego_datum/zayin.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/clothing/suits/ego_gear/tools.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  code/modules/mob/living/simple_animal/abnormality/teth/dingle_dangle.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/pile_of_mail.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/mob/clothing/ego_gear/abnormality/tools.dmi
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/mob/clothing/ego_gear/abnormality/zayin.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/clothing/ego_gear/abnormality/tools.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/clothing/ego_gear/abnormality/zayin.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  lobotomy-corp13.dme
Labels: Code improvement

#1182 TETH lore from vanilla LC + Penitent Girl
  code/modules/paperwork/records/lore/teth.dm
Labels: Writing

#1132 Ordealtype Tweaks 2 ATOMIZATION
  code/modules/ordeals/_ordealtypes.dm
  code/modules/ordeals/green_ordeals.dm
  code/modules/ordeals/steel_ordeals.dm
Labels: Tweak

#1175 Gadgets-V1.2
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_items/gadgets/detector.dm
  ModularTegustation/tegu_items/gadgets/powered.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/game/objects/items/tools/safety_kit.dm
  lobotomy-corp13.dme
Labels: Code improvement, Tweak, Fix

#1180 Shrimple Fishing Update V2.1
  code/datums/diseases/parasitic_infection.dm
  code/game/objects/items/food/meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
Labels: Tweak, Fix

#1120 HE lore from vanilla LC + You Must Become Strong
  code/modules/paperwork/records/lore/he.dm
  code/modules/paperwork/records/lore/zayin.dm
Labels: Writing

#1179 QoH Face Change
  ModularTegustation/Teguicons/32x48.dmi
Labels: Sprites

#1156 Adds Pinocchio
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/human_parts.dmi
  icons/mob/mutant_bodyparts.dmi
  lobotomy-corp13.dme
  sound/abnormalities/pinocchio/activate.ogg
  sound/abnormalities/pinocchio/lie.ogg
  sound/abnormalities/pinocchio/success.ogg
Labels: Test Merge Candidate, Abnormality
