Repository vlggms/lobotomy-corp13, pull requests merged in 2023-08, with the labels that each got.

#1188 Real Grilling Action
  code/game/objects/items/food/meat.dm
  code/modules/fishing/fish/fish_types.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Balance

#1171 Updates fishing map
  _maps/map_files/Zeta/zetacorp.dmm
  code/modules/fishing/simple_fishing_equipment.dm
Labels: Tweak

#1020 Ordeal Pets 1.1
  ModularTegustation/Teguicons/tegumobs.dmi
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
  code/datums/components/riding/riding_mob.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Feature

#1048 adds god of the seasons
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/64x96.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/lobotomy_events.dm
  code/controllers/subsystem/weather.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/effects/effects.dmi
  icons/effects/weather_effects.dmi
  lobotomy-corp13.dme
  sound/abnormalities/seasons/aoe_attack.ogg
  sound/abnormalities/seasons/aoe_warning.ogg
  sound/abnormalities/seasons/breath_attack.ogg
  sound/abnormalities/seasons/old_fall_attack.ogg
  sound/abnormalities/seasons/pulse.ogg
Labels: Abnormality

#1194 Adjustments to cross-server news reports
  code/__DEFINES/misc.dm
  code/controllers/subsystem/ticker.dm
  code/modules/ordeals/white_ordeals.dm
  code/modules/suppressions/_core_suppression.dm
  code/modules/suppressions/extraction.dm
Labels: Tweak

#1200 [New Abnormality] Fairy Long Legs
  ModularTegustation/Teguicons/64x96.dmi
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_long_legs.dm
  code/modules/paperwork/records/info/teth.dm
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/fairy_longlegs/attack.ogg
  sound/abnormalities/fairy_longlegs/death.ogg
  sound/abnormalities/fairy_longlegs/heal.ogg
Labels: Abnormality

#1187 Sorted Status Effects
  ModularTegustation/Teguicons/tegu_effects10x10.dmi
  ModularTegustation/Teguicons/tegu_effects32x48.dmi
  code/datums/status_effects/status_effect.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/behavior.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/bracelet.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/heart.dm
  code/modules/mob/living/simple_animal/abnormality/he/galaxy_child.dm
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
  code/modules/mob/living/simple_animal/abnormality/waw/parasite_tree.dm
Labels: Feature, Tweak, Sprites

#1199 Increases character Slots from 5 to 7
  code/modules/client/preferences.dm
Labels: Tweak

#1167 Maptypes refactor
  code/controllers/subsystem/job.dm
  code/modules/jobs/job_types/city/HHPP.dm
  code/modules/jobs/job_types/city/backstreets_butcher.dm
  code/modules/jobs/job_types/city/doctor.dm
  code/modules/jobs/job_types/city/fixer/east.dm
  code/modules/jobs/job_types/city/fixer/north.dm
  code/modules/jobs/job_types/city/scavenger.dm
  code/modules/jobs/job_types/city/workshop.dm
  code/modules/jobs/job_types/gimmick/fishing.dm
  code/modules/jobs/job_types/gimmick/wonderlabs/departmentcaptain.dm
  code/modules/jobs/job_types/gimmick/wonderlabs/departmenthead.dm
  lobotomy-corp13.dme
Labels: Code improvement

#1174 LOOS gets Directions
  ModularTegustation/Teguicons/32x48.dmi
Labels: Tweak, Sprites

#1203 Meltdown Rebalance and Autovote Removal
  code/controllers/subsystem/autotransfer.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/modules/suppressions/extraction.dm
Labels: Tweak

#1210 Yurai Spriting #1
  ModularTegustation/Teguicons/32x32.dmi
Labels: Sprites

#1212 Removes wooden doors and drugs
  code/game/objects/items/stacks/sheets/sheet_types.dm
  lobotomy-corp13.dme
Labels: Removal

#1191 Orange tree no longer spreads from corpses
  code/datums/diseases/orange_tree.dm
Labels: Fix

#1211 Adds new E.G.O.
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/mob/inhands/96x96_lefthand.dmi
  icons/mob/inhands/96x96_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/ego_weapons.dmi
Labels: Fix, Sprites

#676 Schizoid++
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/ai/sanity/sanityloss_behaviors.dm
  code/datums/quirks/negative.dm
  code/game/machinery/doors/airlock.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  sound/abnormalities/kog/GreedHit1.ogg
  sound/abnormalities/kog/GreedHit2.ogg
  strings/hallucination.json
  strings/insanity.json
Labels: Balance, Feature, Tweak

#1095 Moves tutorial to new z-level, other updates
  _maps/map_files/FacilityTest/facility_test.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/generic/Tutorial_Zone.dmm
  code/__DEFINES/maps.dm
  code/__HELPERS/level_traits.dm
  code/controllers/subsystem/mapping.dm
  code/datums/abnormality/datum/abnormality.dm
  code/datums/holocall.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/machinery/regenerator.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/game/objects/structures/tutorial.dm
  code/modules/mob/living/simple_animal/abnormality/!tutorial/cube.dm
  code/modules/paperwork/records/tutorial/abnormalities.dm
  code/modules/shuttle/navigation_computer.dm
  code/modules/suppressions/safety.dm
Labels: Tweak

#1216 Buffs Infinity
  code/game/objects/items/ego_weapons/waw.dm
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/mob/clothing/old_ego.dmi
Labels: Balance, Sprites

#1215 Parasite Tree is now from Lobotomy corp
  code/modules/mob/living/simple_animal/abnormality/waw/parasite_tree.dm
Labels: Fix

#1222 Green Ordeal part and Ordeal Extractor Fix
  ModularTegustation/tegu_items/workshop/ordeal extractor.dm
Labels: Fix

#1223 Fixes hidden Schizoid issue
  code/modules/flufftext/Hallucination.dm
Labels: Fix

#1162 Sephirah Update
  _maps/map_files/generic/CentCom.dmm
  code/game/machinery/doors/airlock.dm
  code/modules/admin/verbs/commandreport.dm
  code/modules/jobs/job_types/trusted_players/sephirah.dm
Labels: Tweak

#1218 Swaps out some Abno codes
  code/modules/paperwork/records/info/teth.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Writing

#1196 Outskirts monsters delete on death
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
Labels: Fix

#1205 [NEW ABNORMALITY] So That No One Will Cry
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/mob/living/simple_animal/abnormality/teth/so_that_no_cry.dm
  code/modules/paperwork/records/info/teth.dm
  icons/effects/effects.dmi
  lobotomy-corp13.dme
  sound/abnormalities/so_that_no_cry/curse_talisman.ogg
  sound/abnormalities/so_that_no_cry/talisman.ogg
Labels: Abnormality

#827 [COMMISSION] Adds Til the Last Shot
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/48x48.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/last_shot.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/obj/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  lobotomy-corp13.dme
Labels: Feature, Abnormality

#1166 Adds crimson midnight
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/64x96.dmi
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson.dm
  code/modules/ordeals/crimson_ordeals.dm
  sound/effects/ordeals/crimson/midnight_appear.ogg
  sound/effects/ordeals/crimson/midnight_dead.ogg
  sound/effects/ordeals/crimson/midnight_slam.ogg
  sound/effects/ordeals/crimson/midnight_spawn.ogg
Labels: Feature

#855 Green Ordeals Tweaks and Rebalancing
  ModularTegustation/Teguicons/64x48.dmi
  ModularTegustation/Teguicons/96x48.dmi
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/ordeals/_ordealtypes.dm
  code/modules/ordeals/green_ordeals.dm
  code/modules/projectiles/projectile/bullets/smg.dm
  sound/effects/ordeals/green/dawn_dead.ogg
  sound/effects/ordeals/green/dusk_dead.ogg
  sound/effects/ordeals/green_end.ogg
Labels: Balance

#1225 Fixes Pinocchio and Shield Subtypes
  ModularTegustation/Teguicons/status_sprites.dmi
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_sinner.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
Labels: Fix

#1204 adds the Tool E.G.O extractor
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_items/refinery/crates.dm
  code/datums/abnormality/_ego_datum/tools.dm
  code/datums/abnormality/_ego_datum/zayin.dm
  code/modules/clothing/suits/ego_gear/tools.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/dr_jekyll.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/fateloom.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/theonite_slab.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/vivavoce.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/heart.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/snake_oil.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  icons/obj/projectiles_tracer.dmi
Labels: Balance, Feature

#1236 EGO console now can show info on the items before purchase
  code/datums/abnormality/_ego_datum/_ego_datum.dm
  code/game/machinery/computer/abnormality_ego.dm
Labels: Feature

#1192 Adds shelter from the 27th of march and static tools
  ModularTegustation/Teguicons/toolabnormalities.dmi
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Psi/psicorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/area/areas/lobotomy_corp.dm
  code/game/objects/items/devices/traitordevices.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/shelter.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/paperwork/records/info/tools.dm
  icons/obj/crates.dmi
  icons/obj/food/food.dmi
  icons/obj/storage.dmi
  icons/turf/areas.dmi
  lobotomy-corp13.dme
  sound/abnormalities/shelter/open.ogg
Labels: Feature, Mapping

#1227 adds missed reaper
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x64.dmi
  code/modules/mob/living/simple_animal/abnormality/he/missed_reaper.dm
  code/modules/paperwork/records/info/he.dm
  lobotomy-corp13.dme
  sound/abnormalities/missed_reaper/shadowcast.ogg
  sound/abnormalities/missed_reaper/shadowhit.ogg
Labels: Abnormality

#1110 HitInTurf proc
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
  ModularTegustation/tegu_mobs/the_claw.dm
  code/__HELPERS/mobs.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/non_abnormality/black_silence.dm
  code/game/objects/items/ego_weapons/non_abnormality/dawn.dm
  code/game/objects/items/ego_weapons/non_abnormality/rcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/rosespanner.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/mob/living/simple_animal/abnormality/teth/my_sweet_home.dm
  code/modules/mob/living/simple_animal/abnormality/teth/ppodae.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dreaming_current.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/luna.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yang.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
Labels: Code improvement

#1232 Paper works correctly on LC13 airlocks now
  code/game/machinery/doors/airlock_types.dm
  icons/obj/doors/airlocks/vault/overlays.dmi
Labels: Fix

#1230 Clerks can now work training rabbit
  code/game/machinery/computer/abnormality_work.dm
Labels: Tweak

#1231 Twilight nerf
  code/modules/clothing/suits/ego_gear/aleph.dm
Labels: Balance

#1228 Realization Resprites and Rcorp armor
  code/modules/clothing/suits/ego_gear/non_abnormality/rcorp.dm
  code/modules/jobs/job_types/rcorp/raven.dm
  code/modules/jobs/job_types/rcorp/reindeer.dm
  icons/mob/clothing/ego_gear/abnormality/zayin.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/clothing/old_ego.dmi
  icons/obj/clothing/ego_gear/abnormality/zayin.dmi
  icons/obj/clothing/ego_gear/realization.dmi
  icons/obj/clothing/ego_gear/suits.dmi
Labels: Sprites

#1198 New Matriarch AI
  ModularTegustation/tegu_items/gadgets/detector.dm
  code/__HELPERS/_lists.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Code improvement, Tweak

#1251 KOG Duplicate definition fix
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
Labels: Red Label, Fix

#1237 E.G.O. Dump and adjustments
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/projectiles/ammunition/ego_ammunition/aleph.dm
  code/modules/projectiles/ammunition/ego_ammunition/teth.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/projectile/ego_bullets/aleph.dm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/mob/inhands/96x96_lefthand.dmi
  icons/mob/inhands/96x96_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  sound/abnormalities/armyinblack/black_attack.ogg
  sound/abnormalities/armyinblack/black_breach.ogg
  sound/abnormalities/armyinblack/black_cast.ogg
  sound/abnormalities/armyinblack/black_explosion.ogg
  sound/abnormalities/armyinblack/black_heartbeat.ogg
  sound/abnormalities/armyinblack/pink.ogg
  sound/abnormalities/armyinblack/pink_explosion.ogg
  sound/abnormalities/armyinblack/pink_heal.ogg
  sound/abnormalities/babayaga/attack.ogg
  sound/abnormalities/babayaga/land.ogg
  sound/abnormalities/ichthys/blast.ogg
  sound/abnormalities/ichthys/charge.ogg
  sound/abnormalities/ichthys/hammer1.ogg
  sound/abnormalities/ichthys/hammer2.ogg
  sound/abnormalities/ichthys/hammer3.ogg
  sound/abnormalities/ichthys/hardslap.ogg
  sound/abnormalities/ichthys/jump.ogg
  sound/abnormalities/ichthys/land.ogg
  sound/abnormalities/ichthys/slap.ogg
Labels: Balance, dependencies, Sprites

#1146 Refinery Update: Syndicate
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/Teguicons/refiner.dmi
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_items/associations/association_beacon.dm
  ModularTegustation/tegu_items/refinery/crates.dm
  ModularTegustation/tegu_items/refinery/sales.dm
  code/game/objects/items/clerks/hypo/hypo.dm
  code/game/objects/items/ego_weapons/non_abnormality/_cityweapons.dm
  code/game/objects/items/ego_weapons/non_abnormality/fullstop.dm
  code/game/objects/items/ego_weapons/non_abnormality/hana.dm
  code/game/objects/items/ego_weapons/non_abnormality/jeong.dm
  code/game/objects/items/ego_weapons/non_abnormality/kcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/liu.dm
  code/game/objects/items/ego_weapons/non_abnormality/mariachi.dm
  code/game/objects/items/ego_weapons/non_abnormality/miscbackstreet.dm
  code/game/objects/items/ego_weapons/non_abnormality/miscfixer.dm
  code/game/objects/items/ego_weapons/non_abnormality/shi.dm
  code/game/objects/items/ego_weapons/non_abnormality/sweeper.dm
  code/game/objects/items/ego_weapons/non_abnormality/syndicate.dm
  code/game/objects/items/ego_weapons/non_abnormality/thumb.dm
  code/game/objects/items/ego_weapons/non_abnormality/yun.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/liu.dm
  code/modules/projectiles/ammunition/ego_ammunition/special.dm
  code/modules/projectiles/projectile/ego_bullets/special.dm
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  icons/obj/syringe.dmi
  lobotomy-corp13.dme
Labels: Expansion

#1242 Removes LC armor protection Classes.
  code/modules/clothing/clothing.dm
Labels: Removal

#1244 Minor fixes across the board
  code/modules/mob/living/simple_animal/abnormality/_tools/he/shelter.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
  code/modules/mob/living/simple_animal/abnormality/he/puss_in_boots.dm
Labels: Code improvement, Fix

#1197 More cross-comms adjustments
  code/__DEFINES/misc.dm
  code/__HELPERS/priority_announce.dm
  code/_globalvars/misc.dm
  code/controllers/subsystem/ticker.dm
  code/datums/world_topic.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/computer/communications.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/suppressions/_core_suppression.dm
Labels: Tweak

#1080 Melting Love improvements
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  sound/abnormalities/meltinglove/attack.ogg
  sound/abnormalities/meltinglove/death.ogg
  sound/abnormalities/meltinglove/empower.ogg
  sound/abnormalities/meltinglove/gift.ogg
  sound/abnormalities/meltinglove/pawn_attack.ogg
  sound/abnormalities/meltinglove/pawn_big_convert.ogg
  sound/abnormalities/meltinglove/pawn_convert.ogg
  sound/abnormalities/meltinglove/pawn_death.ogg
  sound/abnormalities/meltinglove/ranged.ogg
  sound/abnormalities/meltinglove/ranged_hit.ogg
Labels: Code improvement, Tweak, Test Merge Candidate

#1229 Alriune upgrades
  code/__HELPERS/unsorted.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/alriune.dm
Labels: Balance, Tweak

#1108 Arbiter update
  code/modules/suppressions/extraction.dm
  icons/effects/effects.dmi
Labels: Tweak

#1259 HitInTurf Fix and the Discovery of Output Variables
  code/__HELPERS/mobs.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
Labels: Fix

#1258 Adds Red-Blooded American
  ModularTegustation/Teguicons/32x48.dmi
  code/modules/mob/living/simple_animal/abnormality/teth/redblooded.dm
  code/modules/paperwork/records/info/teth.dm
  lobotomy-corp13.dme
Labels: Abnormality

#1265 Fixes Apex Predator records
  code/modules/paperwork/records/info/waw.dm
Labels: Writing

#1268 Moths automatically jump at big bird
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
Labels: Tweak

#1249 WIP Rep Console
  ModularTegustation/Teguicons/lc13icons.dmi
  ModularTegustation/Teguicons/lcsigns.dmi
  ModularTegustation/representative_console.dm
  ModularTegustation/tegu_items/lc13unique_items.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/game/objects/structures/signs/lobotomy/departments.dm
  lobotomy-corp13.dme
Labels: Feature

#1272 Rep Console touchup
  ModularTegustation/Teguicons/lcsigns.dmi
  ModularTegustation/representative_console.dm
Labels: Fix

#1274 Smoking is cool
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/withdrawal/generic_addictions.dm
Labels: Removal

#1281 Microwaves are now hot enough to destroy Fish Liver Parasites
  ModularTegustation/fishing/code/fish/_fish.dm
  code/datums/components/food/edible.dm
  code/game/objects/items/food/_food.dm
Labels: Fix

#1278 Fishin Fixes 3.1 Fishin Rods Now Bonk Off of Walls.
  ModularTegustation/fishing/code/fishing_items/fishing_net.dm
  ModularTegustation/fishing/code/fishing_items/fishing_rod.dm
  ModularTegustation/fishing/code/turfs.dm
Labels: Tweak, Fix

#1294 Excludes Disposal Pipes from HurtInTurf
  code/__HELPERS/mobs.dm
Labels: Fix, Expansion

#1279 Fixes Mob Spawner Factions to allow lists & attributes
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/outfits/ert.dm
Labels: Tweak, Fix

#1247 Adds spirit of Falada
  ModularTegustation/Teguicons/tegumobs.dmi
  code/modules/mob/living/simple_animal/abnormality/teth/falada.dm
  code/modules/paperwork/records/info/teth.dm
  lobotomy-corp13.dme
Labels: Test Merge Candidate, Abnormality

#1115 Child of the Galaxy Rework
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/datums/abnormality/datum/abnormality.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/he/galaxy_child.dm
  code/modules/paperwork/records/info/he.dm
Labels: Balance, Tweak

#1261 Ports radio noises
  code/__DEFINES/preferences.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  sound/effects/radio/radio1.ogg
  sound/effects/radio/radio2.ogg
  sound/effects/radio/radio3.ogg
Labels: Feature

#1234 adds buttons to a few playable abnormalities
  code/datums/action.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fragment.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/black_swan.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
  code/modules/mob/living/simple_animal/abnormality/waw/sphinx.dm
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
  icons/mob/actions/actions_abnormality.dmi
  icons/mob/actions/backgrounds.dmi
Labels: Tweak, Test Merge Candidate

#1291 Fixes some stuff
  ModularTegustation/Teguicons/96x96.dmi
  code/modules/mob/living/simple_animal/abnormality/_tools/he/shelter.dm
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
  code/modules/mob/living/simple_animal/abnormality/waw/fire_bird.dm
Labels: Fix

#1298 Shrimps Drop From Pods
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
Labels: Tweak

#1301 Maptype Setup
  code/controllers/subsystem/maptype.dm
  code/game/gamemodes/management/event/combat.dm
Labels: W-Test PR

#1299 Kurokumo Update
  _maps/templates/syndicate_office/kurokumo.dmm
  code/__DEFINES/jobs.dm
  code/modules/jobs/job_types/city/syndicate/kurokumo/blade_ronin.dm
  code/modules/jobs/job_types/city/syndicate/kurokumo/captain.dm
  code/modules/jobs/job_types/city/syndicate/kurokumo/enforcer.dm
  lobotomy-corp13.dme
Labels: Tweak

#1297 You must become strong fix
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
Labels: Fix

#1305 Injector fix
  ModularTegustation/tegu_items/associations/items.dm
Labels: Fix

#1308 W test weapons update
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/tegu_items/wcorp/enemies.dm
  _maps/map_files/Event/wcorp.dmm
  _maps/wcorp.json
  code/game/gamemodes/management/event/combat.dm
  code/game/objects/items/ego_weapons/non_abnormality/wcorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/wcorp.dm
  code/modules/jobs/job_types/wcorp/wcorpl1.dm
  code/modules/jobs/job_types/wcorp/wcorpl2.dm
  code/modules/jobs/job_types/wcorp/wcorpl3.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  config/maps.txt
  lobotomy-corp13.dme
Labels: W-Test PR

#1310 L2A Lieutenant
  code/modules/jobs/job_types/wcorp/wcorpl2.dm
  code/modules/jobs/jobs.dm
Labels: W-Test PR
