Repository vlggms/lobotomy-corp13, pull requests merged in 2023-09, with the labels that each got.

#1312 3 New random carriages
  _maps/map_files/Event/wcorp-carriage1.dmm
  _maps/map_files/Event/wcorp-firstclass.dmm
  _maps/map_files/Event/wcorp-passenger1.dmm
Labels: W-Test PR

#1311 Slowdown Bullet Rework
  ModularTegustation/tegu_items/gadgets/powered.dm
  code/datums/status_effects/debuffs.dm
  code/game/machinery/computer/manager_camera.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/movespeed/modifiers/mobs.dm
Labels: Tweak, Fix

#1239 Adds headless ichthys
  ModularTegustation/Teguicons/64x48.dmi
  ModularTegustation/Teguicons/64x64.dmi
  code/modules/mob/living/simple_animal/abnormality/he/headless_ichthys.dm
  code/modules/paperwork/records/info/he.dm
  lobotomy-corp13.dme
Labels: Test Merge Candidate, Abnormality

#1319 Some tweaks to the necromancer
  ModularTegustation/tegu_mobs/necromancer.dm
  code/modules/spells/spell_types/pointed/necromancer_curse.dm
Labels: Tweak

#1289 Steel Manager Health and Black Defense reduction
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
Labels: Tweak

#1329 Hana Intern + Paramedic Crew tracker on spawn
  code/modules/jobs/job_types/city/doctor.dm
  code/modules/jobs/job_types/trusted_players/hana.dm
  code/modules/jobs/jobs.dm
Labels: Expansion

#1317 Save the Disposal Pipes (real)
  code/__HELPERS/mobs.dm
Labels: Fix

#1316 Unaimed shots miss cloaked Apex Predator
  code/modules/mob/living/simple_animal/abnormality/waw/apex_predator.dm
Labels: Tweak

#1318 Worse Dragon
  ModularTegustation/fishing/code/turfs.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yin.dm
Labels: Tweak, Fix

#1328 Prevents panicked employees from being grabbed
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/status_effects/panic.dm
  code/modules/mob/living/living_defense.dm
Labels: Balance

#1314 Liver Parasites get blended in Cybernetic Liver
  code/datums/diseases/parasitic_infection.dm
Labels: Tweak, Fix

#1300 Thumb Buff and Ncorp Nerf
  _maps/templates/syndicate_office/ncorp.dmm
  code/game/objects/items/ego_weapons/non_abnormality/weak_edits/city.dm
Labels: Balance

#1238 Psicorp update
  _maps/map_files/Psi/psicorp.dmm
Labels: Fix, Mapping

#1275 Drinking is Cool
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Tweak

#1330 Spray can on walls again!
  code/game/objects/items/crayons.dm
Labels: Tweak

#1280 Backstreets mob expansion: full of L O V E L O V E
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/96x96.dmi
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  icons/effects/effects.dmi
  sound/creatures/lc13/lovetown/abomination_counter_end.ogg
  sound/creatures/lc13/lovetown/abomination_counter_start.ogg
  sound/creatures/lc13/lovetown/abomination_lovewhip_hit.ogg
  sound/creatures/lc13/lovetown/abomination_lovewhip_start.ogg
  sound/creatures/lc13/lovetown/abomination_stagetransition.ogg
  sound/creatures/lc13/lovetown/scream.ogg
  sound/creatures/lc13/lovetown/slam.ogg
Labels: Expansion

#1273 Adds hammer of light
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/64x64.dmi
  code/modules/mob/living/simple_animal/abnormality/zayin/hammer_light.dm
  code/modules/paperwork/records/info/zayin.dm
  icons/effects/96x96.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/lighthammer/hammer_filter.ogg
  sound/abnormalities/lighthammer/hammer_filterOut1.ogg
  sound/abnormalities/lighthammer/hammer_filterOut2.ogg
  sound/abnormalities/lighthammer/hammer_usable1.ogg
  sound/abnormalities/lighthammer/hammer_usable2.ogg
Labels: Do Not Merge, Test Merge Candidate, Abnormality

#1331 Add COMSIG_GLOB_PATROL_START
  code/__DEFINES/dcs/signals.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Feature

#1320 Various Text Changes
  code/__HELPERS/abnormalities.dm
  code/controllers/subsystem/abnormality_queue.dm
  code/datums/holocall.dm
  code/datums/quirks/good.dm
  code/datums/quirks/negative.dm
  code/datums/quirks/neutral.dm
  code/game/machinery/computer/abnormality_archive.dm
  code/game/machinery/computer/abnormality_queue.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/structures/ordealmonitor.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/abnormality/teth/shy_look.dm
  code/modules/paperwork/records/info/_info.dm
  code/modules/paperwork/records/tutorial/levelling.dm
  strings/tips.txt
Labels: Tweak

#1338 Adding The Crying Children Episode: 2, Epilogue
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/96x96.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/crying_children.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/spells/ability_types/realized.dm
  icons/mob/actions/actions_ability.dmi
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/clothing/ego_gear/realization.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/crying_children/attack_aoe.ogg
  sound/abnormalities/crying_children/attack_child.ogg
  sound/abnormalities/crying_children/attack_salvador.ogg
  sound/abnormalities/crying_children/attack_yuna.ogg
  sound/abnormalities/crying_children/death.ogg
  sound/abnormalities/crying_children/final_phase.ogg
  sound/abnormalities/crying_children/seperate.ogg
  sound/abnormalities/crying_children/sorrow_charge.ogg
  sound/abnormalities/crying_children/sorrow_shot.ogg
  sound/weapons/ego/burn_guard.ogg
  sound/weapons/ego/burn_sword.ogg
Labels: Feature

#1337 Glossy Quirk (roundstart lipstick quirk)
  code/datums/quirks/neutral.dm
Labels: Tweak

#1248 Adds Wayward Passenger
  ModularTegustation/Teguicons/48x96.dmi
  code/game/objects/items/ego_weapons/he.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/wayward_passenger.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  lobotomy-corp13.dme
  sound/abnormalities/wayward_passenger/teleport.ogg
Labels: Test Merge Candidate, Abnormality

#1334 Reduces starter fishing gear cost and Fishing Nets cant be Harvested with your mind
  ModularTegustation/fishing/code/fish_market.dm
  ModularTegustation/fishing/code/fishing_items/fishing_net.dm
Labels: Tweak, Fix

#1195 Runaway Birds
  ModularTegustation/Teguicons/tegumobs.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
Labels: Balance

#1341 Lovetown added to Wcorp
  ModularTegustation/tegu_items/wcorp/enemies.dm
  code/game/gamemodes/management/event/combat.dm
Labels: W-Test PR

#1296 Misc City Touch-Ups
  ModularTegustation/tegu_items/associations/machines.dm
  ModularTegustation/tegu_items/workshop/_materials.dm
  ModularTegustation/tegu_items/workshop/ordeal extractor.dm
  ModularTegustation/tegu_items/workshop/templates/dice.dm
Labels: Tweak

#1342 Runtime Fixes
  code/controllers/subsystem/processing/station.dm
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
Labels: Fix

#1349 TCC Cleanup
  code/modules/mob/living/simple_animal/abnormality/aleph/crying_children.dm
Labels: Balance, Code improvement

#1354 Liver Parasites get blended in Cybernetic Liver 2.0
  code/datums/diseases/parasitic_infection.dm
Labels: Tweak, Fix

#1356 Disables Broken Light Sparks on City
  code/modules/power/lighting.dm
Labels: Fix

#1351 Displays Test Merge Comments in game
  code/datums/helper_datums/getrev.dm
Labels: Tweak

#1350 One-Line Hammer Update
  code/modules/mob/living/simple_animal/abnormality/zayin/hammer_light.dm
Labels: Fix

#1347 Ordeal Extractor Information Update
  ModularTegustation/tegu_items/workshop/ordeal extractor.dm
Labels: Expansion

#1276 3 new small backstreet spawns
  ModularTegustation/tegu_items/backstreets/random_rooms/small/east.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/north.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/south.dm
  _maps/RandomRooms/backstreets/small_east/noodlebar.dmm
  _maps/RandomRooms/backstreets/small_north/smallarmory.dmm
  _maps/RandomRooms/backstreets/small_south/open_shrine.dmm
Labels: Mapping

#1315 Adjusts some abnormalities
  code/__DEFINES/sound.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/looping_sounds/abnormalities.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/mob/living/simple_animal/abnormality/he/headless_ichthys.dm
  code/modules/mob/living/simple_animal/abnormality/he/jangsan.dm
  code/modules/mob/living/simple_animal/abnormality/he/missed_reaper.dm
  code/modules/mob/living/simple_animal/abnormality/he/siren.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/hammer_light.dm
  code/modules/paperwork/records/info/he.dm
Labels: Balance, Code improvement, Tweak, Test Merge Candidate

#1269 Adds backwards clock
  ModularTegustation/Teguicons/toolabnormalities.dmi
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Psi/psicorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
  code/modules/mob/living/simple_animal/abnormality/_tools/waw/clock.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/touch.dm
  code/modules/paperwork/records/info/tools.dm
  lobotomy-corp13.dme
  sound/abnormalities/clock/clank.ogg
  sound/abnormalities/clock/end.ogg
  sound/abnormalities/clock/finish.ogg
  sound/abnormalities/clock/start.ogg
  sound/abnormalities/clock/turn_on.ogg
  sound/abnormalities/clock/work.ogg
Labels: Do Not Merge, Test Merge Candidate, Abnormality

#1363 Noodle bar spacing fix
  _maps/RandomRooms/backstreets/small_east/noodlebar.dmm
Labels: Fix

#1293 The great attribute update-ening
  ModularTegustation/tegu_items/workshop/templates/gauntlet.dm
  code/_onclick/item_attack.dm
  code/datums/abnormality/datum/abnormality.dm
  code/datums/ai/sanity/sanityloss_behaviors.dm
  code/datums/attributes/_attribute.dm
  code/datums/attributes/fortitude.dm
  code/datums/attributes/justice.dm
  code/datums/attributes/prudence.dm
  code/datums/attributes/temperance.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/dr_jekyll.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nihil.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
  code/modules/mob/living/simple_animal/abnormality/teth/so_that_no_cry.dm
  code/modules/mob/living/simple_animal/abnormality/waw/fire_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/pygmalion.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/suppressions/training.dm
Labels: Balance, Code improvement, Test Merge Candidate, Expansion

#1277 Nerfs crimson midnight
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson.dm
  code/modules/ordeals/crimson_ordeals.dm
  sound/effects/ordeals/crimson/ball.ogg
Labels: Balance, Test Merge Candidate

#1243 Adds baba yaga
  ModularTegustation/Teguicons/96x96.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/babayaga.dm
  code/modules/paperwork/records/info/waw.dm
  icons/effects/96x96.dmi
  lobotomy-corp13.dme
  sound/abnormalities/babayaga/warning.ogg
Labels: Test Merge Candidate, Abnormality

#1340 KCorp Drone Tweaks
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
Labels: Tweak

#1355 Fixed Quirk Blacklist
  code/controllers/subsystem/processing/quirks.dm
Labels: Fix

#1271 Rep Console Update
  ModularTegustation/Teguicons/lc13icons.dmi
  ModularTegustation/representative_console.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_items/representative/console.dm
  ModularTegustation/tegu_items/representative/outfits.dm
  ModularTegustation/tegu_items/representative/research.dm
  ModularTegustation/tegu_items/representative/spawners.dm
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/clothing/under/clerksuits.dm
  code/modules/jobs/job_types/trusted_players/representative.dm
  icons/obj/clothing/ego_gear/lcuniform.dmi
  lobotomy-corp13.dme
Labels: Expansion

#1313 RCorp Updates
  ModularTegustation/tegu_items/rcorp/landmarks.dm
  ModularTegustation/tegu_items/rcorp/random_maps.dm
  _maps/RandomRooms/rcorp/facility/beaches.dmm
  _maps/RandomRooms/rcorp/facility/offices.dmm
  _maps/map_files/Event/rcorp.dmm
  code/modules/projectiles/guns/misc/medbeam.dm
  code/modules/projectiles/guns/misc/reindeer.dm
  code/modules/vehicles/mecha/combat/rhino.dm
Labels: Balance

#1333 melee_reach Variable and controlled mob attack rate fix
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Code improvement, Feature, Fix

#1343 Lets you Spray Walls
  code/modules/reagents/reagent_containers/spray.dm
Labels: Tweak

#1362 Adds shrimp carbons
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/shrimp.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  icons/mob/human_parts.dmi
  lobotomy-corp13.dme
Labels: Tweak

#1189 Big and Will be Bad Wolf
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/96x64.dmi
  ModularTegustation/Teguicons/lc13icons.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_wolf.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/big_wolf/Wolf_EatOut.ogg
  sound/abnormalities/big_wolf/Wolf_FogChange.ogg
  sound/abnormalities/big_wolf/Wolf_Hori.ogg
  sound/abnormalities/big_wolf/Wolf_Howl.ogg
  sound/abnormalities/big_wolf/Wolf_Scratch.ogg
Labels: Abnormality

#1119 Reverberation Scythe
  ModularTegustation/Teguicons/lc13_effects.dmi
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
  code/game/objects/items/ego_weapons/non_abnormality/blue_sicko.dm
  icons/effects/number_overlays.dmi
  icons/hud/screen_alert.dmi
  icons/mob/actions/actions_ability.dmi
  lobotomy-corp13.dme
  sound/weapons/fixer/reverb_far1.ogg
  sound/weapons/fixer/reverb_far2.ogg
  sound/weapons/fixer/reverb_grand_dash.ogg
  sound/weapons/fixer/reverb_grand_end.ogg
  sound/weapons/fixer/reverb_grand_start.ogg
  sound/weapons/fixer/reverb_normal.ogg
  sound/weapons/fixer/reverb_strong1.ogg
  sound/weapons/fixer/reverb_strong2.ogg
Labels: Feature

#1371 Child of the Galaxy Realization
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  icons/mob/clothing/ego_gear/realized.dmi
  icons/obj/clothing/ego_gear/realization.dmi
Labels: Expansion

#1377 Fix Grammar Issue with Piscine Mermaid
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
Labels: Writing

#1381 Fix missing bar codes on wolf and baba yaga
  code/modules/paperwork/records/info/waw.dm
Labels: Fix

#1380 Adds Wolf to RCorp, changes Wolf Dash to a Toggle
  ModularTegustation/Teguicons/lc13icons.dmi
  ModularTegustation/tegu_items/rcorp/landmarks.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_wolf.dm
  icons/mob/actions/actions_abnormality.dmi
Labels: Tweak

#1383 Buffs Swan
  code/modules/mob/living/simple_animal/abnormality/waw/black_swan.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Balance

#1379 Oz realizations (no abilities)
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/obj/clothing/ego_gear/realization.dmi
Labels: Feature

#1378 We Can Change Anything update: lets agents kill themselves!
  code/datums/abnormality/_ego_datum/aleph.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
  code/modules/paperwork/records/info/zayin.dm
  icons/obj/ego_weapons.dmi
  sound/abnormalities/we_can_change_anything/change_gas.ogg
  sound/abnormalities/we_can_change_anything/change_generate.ogg
  sound/abnormalities/we_can_change_anything/change_start.ogg
Labels: Feature

#1376 Tgstation Smartfridge Fix Port
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Labels: Fix

#1361 Add realized armor for yin and yang
  ModularTegustation/Teguicons/status_sprites.dmi
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/spells/ability_types/realized.dm
  code/modules/spells/ability_types/realized_aimed.dm
  icons/mob/actions/actions_ability.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/obj/clothing/ego_gear/realization.dmi
Labels: Balance

#1322 add new ego and lance changes
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/ego_weapons/subtype/lance.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_gentleman.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/hammer_light.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/pile_of_mail.dm
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/mob/inhands/96x96_lefthand.dmi
  icons/mob/inhands/96x96_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/limbus_weapons.dmi
Labels: Code improvement, Tweak, Expansion

#1260 Adds Norinori
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/48x48.dmi
  code/modules/mob/living/simple_animal/abnormality/he/norinori.dm
  code/modules/paperwork/records/info/he.dm
  lobotomy-corp13.dme
Labels: Test Merge Candidate, Abnormality

#1369 Removes wallshove knockdowns
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/unit_tests/combat.dm
Labels: Tweak, Removal

#1304 WARP Cleanup Gamemode
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/tegu_items/wcorp/berets.dm
  ModularTegustation/tegu_items/wcorp/enemies.dm
  ModularTegustation/tegu_items/wcorp/headsets.dm
  ModularTegustation/tegu_items/wcorp/mapping.dm
  ModularTegustation/tegu_items/wcorp/storage.dm
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
  _maps/RandomRooms/wcorp/carriage1.dmm
  _maps/RandomRooms/wcorp/carriage2.dmm
  _maps/RandomRooms/wcorp/firstclass.dmm
  _maps/RandomRooms/wcorp/open1.dmm
  _maps/RandomRooms/wcorp/open2.dmm
  _maps/RandomRooms/wcorp/passenger1.dmm
  _maps/RandomRooms/wcorp/passenger2.dmm
  _maps/map_files/Event/wcorp.dmm
  _maps/wcorp.json
  code/controllers/subsystem/maptype.dm
  code/game/gamemodes/management/event/combat.dm
  code/game/objects/items/ego_weapons/non_abnormality/wcorp.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/wcorp.dm
  code/modules/clothing/under/clerksuits.dm
  code/modules/jobs/job_types/wcorp/wcorpl1.dm
  code/modules/jobs/job_types/wcorp/wcorpl2.dm
  code/modules/jobs/job_types/wcorp/wcorpl3.dm
  code/modules/jobs/job_types/wcorp/wcorprecon.dm
  code/modules/jobs/job_types/wcorp/wcorprep.dm
  code/modules/jobs/job_types/wcorp/wcorpshield.dm
  code/modules/jobs/job_types/wcorp/wcorpspear.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  config/maps.txt
  icons/mob/clothing/ego_gear/under.dmi
  icons/obj/clothing/ego_gear/lcuniform.dmi
  icons/obj/storage.dmi
  lobotomy-corp13.dme
Labels: Feature, W-Test PR

#1257 adds looc
  ModularTegustation/looc.dm
  code/__DEFINES/chat.dm
  code/__DEFINES/keybinding.dm
  code/datums/keybinding/communication.dm
  code/modules/client/client_procs.dm
  lobotomy-corp13.dme
  tgui/packages/tgui-panel/chat/constants.js
Labels: Feature

#1391 Re-Adds icons for Desperation and Our Galaxy
  icons/mob/clothing/ego_gear/realized.dmi
Labels: Fix

#1335 Makes many Mobs Update Speed on Move_To_Delay changing
  ModularTegustation/tegu_mobs/necromancer.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Fix

#1370 Adds distortions
  ModularTegustation/Teguicons/48x96.dmi
  code/_globalvars/lists/mobs.dm
  code/modules/mob/living/simple_animal/distortion/_distortion.dm
  code/modules/mob/living/simple_animal/distortion/canard/_canard.dm
  code/modules/mob/living/simple_animal/distortion/legend/_legend.dm
  code/modules/mob/living/simple_animal/distortion/myth/another_day_work.dm
  code/modules/mob/living/simple_animal/distortion/nightmare/_nightmare.dm
  code/modules/mob/living/simple_animal/distortion/plague/_plague.dm
  code/modules/mob/living/simple_animal/distortion/star/_star.dm
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles_impact.dmi
  icons/obj/projectiles_tracer.dmi
  lobotomy-corp13.dme
Labels: Feature

#1368 Realized armor reballanced
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/spells/ability_types/realized.dm
  code/modules/spells/ability_types/realized_aimed.dm
Labels: Balance

#1394 Refinery Update
  ModularTegustation/Teguicons/refiner.dmi
  ModularTegustation/tegu_items/refinery/_spawners.dm
  ModularTegustation/tegu_items/refinery/crates.dm
  ModularTegustation/tegu_items/refinery/crates/_crate.dm
  ModularTegustation/tegu_items/refinery/crates/association.dm
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/refinery/crates/misc.dm
  ModularTegustation/tegu_items/refinery/crates/syndicate.dm
  ModularTegustation/tegu_items/refinery/crates/workshop.dm
  lobotomy-corp13.dme
Labels: Expansion

#1395 Enables nihil E.G.O. and adds a missing inhand
  code/modules/mob/living/simple_animal/abnormality/aleph/nihil.dm
  code/modules/projectiles/projectile/ego_bullets/aleph.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
Labels: Tweak

#1396 Handicap Accessible Work
  code/game/machinery/computer/abnormality_work.dm
Labels: Tweak

#1373 Fixes a runtime and gives apple reach
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Code improvement, Fix

#1348 Rat update
  ModularTegustation/Teguicons/lc13_weapons.dmi
  code/game/objects/items/ego_weapons/non_abnormality/rats.dm
  code/modules/jobs/job_types/city/scavenger.dm
Labels: Tweak

#1241 Makes Bots Go Through Crates & Doors + Adds Missing Ego To Realizer
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
Labels: Tweak

#1402 Fixes potential Claw issues
  ModularTegustation/tegu_mobs/the_claw.dm
Labels: Fix

#1404 Makes Structures ignore White Damage HurtInTurf
  code/__HELPERS/mobs.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
Labels: Tweak

#1405 PE Report Update
  code/__HELPERS/roundend.dm
Labels: Tweak

#1389 Add Overridable procs to Forging Mods.
  ModularTegustation/tegu_items/refinery/crates/association.dm
  ModularTegustation/tegu_items/workshop/_mods.dm
  ModularTegustation/tegu_items/workshop/_templates.dm
  ModularTegustation/tegu_items/workshop/mods/aoe.dm
  ModularTegustation/tegu_items/workshop/mods/curing.dm
  ModularTegustation/tegu_items/workshop/mods/healthup.dm
  ModularTegustation/tegu_items/workshop/mods/sapping.dm
  ModularTegustation/tegu_items/workshop/mods/sharp.dm
  ModularTegustation/tegu_items/workshop/mods/split.dm
  ModularTegustation/tegu_items/workshop/templates/basic.dm
  ModularTegustation/tegu_items/workshop/templates/gauntlet.dm
  ModularTegustation/tegu_items/workshop/vending.dm
Labels: Tweak

#1358 TCC 420$ EA DLC, SINS OF THE PLAYABLES
  code/modules/mob/living/simple_animal/abnormality/aleph/crying_children.dm
Labels: Tweak

#1407 Adds Persistence to Agents and PE Quota
  code/__DEFINES/abnormalities.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/controllers/subsystem/persistence.dm
  code/modules/ordeals/_ordeal.dm
Labels: Feature

#1403 Bunnyman distortion and distortion adjustments
  ModularTegustation/Teguicons/48x48.dmi
  code/modules/mob/living/simple_animal/distortion/_distortion.dm
  code/modules/mob/living/simple_animal/distortion/plague/_plague.dm
  code/modules/mob/living/simple_animal/distortion/plague/bunnyman.dm
  lobotomy-corp13.dme
Labels: Feature

#1409 Fix training core debuffs & buffs
  code/modules/suppressions/training.dm
Labels: Fix

#1401 Allows Potential Machines to function with empty hand.
  ModularTegustation/tegu_items/associations/machines.dm
Labels: Tweak

#1398 Adds in Our Galaxy Realization Ability
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/spells/ability_types/realized.dm
  icons/effects/effects.dmi
  icons/mob/actions/actions_ability.dmi
Labels: Feature, Test Merge Candidate

#1413 Updates 2 Realized Sprites
  icons/mob/clothing/ego_gear/realized.dmi
  icons/obj/clothing/ego_gear/realization.dmi
Labels: Sprites

#1421 W-Corp Inhands
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_left_64x64.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_right_64x64.dmi
  code/game/objects/items/ego_weapons/non_abnormality/wcorp.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
Labels: Sprites

#1422 STOP BREAKING MY RACKS
  code/game/objects/structures/tables_racks.dm
Labels: Code improvement

#1414 Adds: W-Corp Cryo Pod
  icons/obj/WcorpCryoPod.dmi
Labels: Sprites

#1418 Nerfs knight of despair
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Balance

#1399 adds shrimp ship
  ModularTegustation/tegu_items/gadgets/powered.dm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/area/areas/lobotomy_corp.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
  icons/turf/areas.dmi
Labels: Mapping

#1423 Implements the snow queen arena
  _maps/custom/iceroom.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/area/areas/lobotomy_corp.dm
  code/game/machinery/doors/airlock_types.dm
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
  icons/obj/structures.dmi
  icons/turf/areas.dmi
  lobotomy-corp13.dme
Labels: Code improvement, Mapping, Expansion

#1420 Work Type Sublist
  code/datums/abnormality/datum/abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Tweak

#1321 adds poor screenwriter's note
  ModularTegustation/Teguicons/32x32.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/screenwriter.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/effects/32x64.dmi
  icons/effects/effects.dmi
  lobotomy-corp13.dme
  sound/abnormalities/screenwriter/finish.ogg
  sound/abnormalities/screenwriter/start.ogg
Labels: Abnormality

#1432 fixes dimension shredder
  code/game/objects/items/ego_weapons/he.dm
Labels: Fix

#1430 Re-sprites Winter Solstice
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/clothing/ego_gear/abnormality/aleph.dmi
Labels: Sprites

#1426 Fixes BL Ronin
  code/modules/jobs/jobs.dm
Labels: Fix

#1431 New realized armor and bisect animation
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/mob/living/simple_animal/abnormality/he/puss_in_boots.dm
  code/modules/spells/ability_types/realized.dm
  icons/mob/actions/actions_ability.dmi
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/mob/mob.dmi
  icons/obj/clothing/ego_gear/realization.dmi
Labels: Feature

#1443 Fixes Little Prince fully healing you
  code/modules/mob/living/simple_animal/abnormality/waw/little_prince.dm
Labels: Fix

#1441 Fix Stacking Footprints
  code/game/objects/effects/decals/cleanable/humans.dm
Labels: Tweak

#1384 More fixes and tweaks to Indigo Midnight Matriarch AI
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Fix, Test Merge Candidate

#1353 Massive Sanity Edits
  code/__DEFINES/ai.dm
  code/datums/ai/_ai_controller.dm
  code/datums/ai/generic_actions.dm
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/ai/sanity/sanityloss_behaviors.dm
  code/datums/status_effects/panic.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Balance, Code improvement

#1437 More claw fix attempts
  ModularTegustation/tegu_mobs/the_claw.dm
Labels: Fix

#1452 cobalt claw damage buff
  code/game/objects/items/ego_weapons/waw.dm
Labels: Tweak

#1374 Ego Smartfridge : Stabilized Ego Armory
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  icons/obj/vending.dmi
Labels: Feature

#1408 Speed code unification
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Tweak, Fix

#1220 Adds you must be happy and notes of a crazed researcher
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/tegu_effects10x10.dmi
  code/modules/mob/living/simple_animal/abnormality/_tools/he/researcher.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/you_happy.dm
  code/modules/paperwork/records/info/tools.dm
  lobotomy-corp13.dme
  sound/abnormalities/you_happy/change.ogg
  sound/abnormalities/you_happy/fail.ogg
  sound/abnormalities/you_happy/success.ogg
Labels: Test Merge Candidate, Abnormality

#1001 Ordeals of gold - Dawn through Dusk
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x64.dmi
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/64x32.dmi
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold.dm
  code/modules/ordeals/gold_ordeals.dm
  code/modules/projectiles/projectile/ego_bullets/zayin.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
  sound/effects/ordeals/gold/cromer_slam.ogg
  sound/effects/ordeals/gold/cromer_stab.ogg
  sound/effects/ordeals/gold/dead_generic.ogg
  sound/effects/ordeals/gold/flea_attack.ogg
  sound/effects/ordeals/gold/flea_dead.ogg
  sound/effects/ordeals/gold/flea_kill.ogg
  sound/effects/ordeals/gold/flower_attack.ogg
  sound/effects/ordeals/gold/flower_kill.ogg
  sound/effects/ordeals/gold/pridespin.ogg
  sound/effects/ordeals/gold/rock_attack.ogg
  sound/effects/ordeals/gold/rock_dead.ogg
  sound/effects/ordeals/gold/rock_kill.ogg
  sound/effects/ordeals/gold/rock_runover.ogg
  sound/effects/ordeals/gold/tentacle_attack.ogg
  sound/effects/ordeals/gold/tentacle_before_explode.ogg
  sound/effects/ordeals/gold/tentacle_death.ogg
  sound/effects/ordeals/gold/tentacle_explode.ogg
  sound/effects/ordeals/gold_end.ogg
  sound/effects/ordeals/gold_start.ogg
Labels: Feature, Test Merge Candidate

#1463 ALEPH lore from vanilla LC + Staining Rose
  code/modules/paperwork/records/lore/aleph.dm
Labels: Writing

#1464 Chem Hallucination Removal
  code/game/objects/items/devices/portable_chem_mixer.dm
  code/modules/plumbing/plumbers/synthesizer.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Fix, Removal

#1466 Fixes Crumbling Armor meltdown
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
Labels: Fix

#1465 Null Loot fix
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#1458 K-Corp Armors/inhands
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_left_64x64.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_right_64x64.dmi
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  code/game/objects/items/ego_weapons/non_abnormality/kcorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/kcorp.dm
  code/modules/clothing/under/clerksuits.dm
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
Labels: Sprites

#1462 Prevents Multiple Actions from Justice Panic Controller
  code/datums/ai/sanity/_sanityloss_controller.dm
Labels: Fix

#1470 Fix weapon issue in weapon smartfridge
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Labels: Tweak, Fix

#1438 White Night particles
  code/game/objects/effects/particles/particles.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  lobotomy-corp13.dme
Labels: Tweak

#1424 Charge Refactor
  ModularTegustation/tegu_items/associations/fixer.dm
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/refinery/crates/workshop.dm
  ModularTegustation/tegu_items/representative/console.dm
  ModularTegustation/tegu_items/representative/outfits.dm
  ModularTegustation/tegu_items/representative/research.dm
  code/game/objects/items/ego_weapons/non_abnormality/_charge.dm
  code/game/objects/items/ego_weapons/non_abnormality/_cityweapons.dm
  code/game/objects/items/ego_weapons/non_abnormality/cane.dm
  code/game/objects/items/ego_weapons/non_abnormality/molar.dm
  code/game/objects/items/ego_weapons/non_abnormality/rosespanner.dm
  code/game/objects/items/ego_weapons/non_abnormality/wcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/weak_edits/ecorp.dm
  code/game/objects/items/storage/belt.dm
  code/modules/jobs/job_types/wcorp/wcorpl1.dm
  code/modules/jobs/job_types/wcorp/wcorpl2.dm
  code/modules/jobs/job_types/wcorp/wcorpl3.dm
  code/modules/jobs/job_types/wcorp/wcorprecon.dm
  code/modules/jobs/job_types/wcorp/wcorpshield.dm
  code/modules/jobs/job_types/wcorp/wcorpspear.dm
  lobotomy-corp13.dme
Labels: Code improvement, Fix

#1456 W-Test Update
  ModularTegustation/tegu_items/wcorp/enemies.dm
  code/modules/jobs/job_types/wcorp/wcorprecon.dm
Labels: Fix, Side content

#1419 Fix Some Golden Apple Runtimes
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
Labels: Tweak, Fix

#1479 Fixes some bugs and updates desc
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
Labels: Fix

#1467 Playable wayward passenger & KQE improvements
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/wayward_passenger.dm
Labels: Tweak

#1440 Fixes Sparks staying forever
  code/controllers/subsystem/atoms.dm
Labels: Fix, Test Merge Candidate

#867 Adds Army In Black
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/96x96.dmi
  ModularTegustation/Teguicons/tegu_effects10x10.dmi
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/army_in_black.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/projectile/ego_bullets/aleph.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#1477 Lobotomizing The Brain Tumor Quirk
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/datums/quirks/negative.dm
  code/modules/mob/living/brain/brain_item.dm
Labels: Tweak

#1475 Manager Camera now has Following!
  code/game/machinery/computer/manager_camera.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/teth/meat_lantern.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dimension_refraction.dm
Labels: Feature

#1472 QBee EGO Tweaks and Additions
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/queen_bee.dm
  code/modules/spells/ability_types/realized.dm
  icons/mob/inhands/96x96_lefthand.dmi
  icons/mob/inhands/96x96_righthand.dmi
  icons/obj/ego_weapons.dmi
Labels: Tweak

#1412 City updates
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/tegu_items/associations/cityspawners.dm
  ModularTegustation/tegu_items/associations/machines.dm
  _maps/map_files/Event/city.dmm
  code/controllers/subsystem/city_events.dm
  code/modules/mob/living/simple_animal/distortion/nightmare/black_hole_sun.dm
  code/modules/mob/living/simple_animal/distortion/plague/lantern.dm
Labels: Tweak, Side content
