Repository vlggms/lobotomy-corp13, pull requests merged in 2023-01, with the labels that each got.

#550 Adds beanstalk without Jack abnormality and shield EGO subtype
  ModularTegustation/Teguicons/64x98.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/beanstalk.dm
  code/modules/paperwork/records/info/teth.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/weapons/ego/shield1.ogg
Labels: Feature

#552 Adds message when working no longer gives you stats
  code/datums/abnormality/datum/abnormality.dm
Labels: Tweak

#549 Minor Ego Resprite
  ModularTegustation/Teguicons/64x64.dmi
  code/modules/mob/living/simple_animal/abnormality/he/schadenfreude.dm
  icons/hud/screen_gen.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/clothing/old_ego.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
Labels: Tweak

#546 Gift Hider
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Tweak

#514 Corruption Balance Element
  ModularTegustation/Teguicons/lc13icons.dmi
  code/_onclick/hud/screen_objects.dm
  code/datums/components/corruption_balance.dm
  code/modules/spells/ability_types/component_ability.dm
  lobotomy-corp13.dme
Labels: Feature

#557 Adds parry to lutemia
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/teth.dm
Labels: Tweak

#559 Fix KoG behavior when playable
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
Labels: Fix

#567 Fixes beanstalk without jack's special EGO gift
  code/modules/mob/living/simple_animal/abnormality/teth/beanstalk.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
Labels: Balance, Fix

#563 Adds a new shield EGO to scaredy cat
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/scaredy_cat.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
Labels: Tweak

#558 Blue Shep sound is no longer insanely loud
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
Labels: Fix

#545 Remove random reagent mutation from plants
  code/modules/hydroponics/seeds.dm
Labels: Tweak

#569 Updates CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Github

#565 ZAYIN Buffs
  code/modules/clothing/suits/ego_gear/zayin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bald.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
  code/modules/projectiles/guns/ego_gun.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  code/modules/projectiles/projectile/ego_bullets/zayin.dm
  lobotomy-corp13.dme
Labels: Balance, Code improvement, Tweak

#570 Improves/Reworks most tool abnormalities
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/behavior.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/skin.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/theresia.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/mirror.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  sound/abnormalities/behavior/eyes_out.ogg
Labels: Code improvement, Tweak, Fix

#452 "Tegu Translate"
  code/__DEFINES/preferences.dm
  code/__HELPERS/tegutranslate.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/admin/admin.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/new_player.dm
  lobotomy-corp13.dme
Labels: Feature

#573 Ports vote panel fix
  code/controllers/subsystem/vote.dm
  tgui/packages/tgui/interfaces/Vote.js
Labels: Fix

#533 Epsilon Corp V3
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_items/lc13unique_items.dm
  _maps/map_files/Epsilon/epsiloncommand.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  code/game/area/areas/lobotomy_corp.dm
Labels: Fix, Mapping

#575 Fixes jukebox and lowers volume
  code/game/machinery/jukebox.dm
  lobotomy-corp13.dme
Labels: Code improvement, Fix

#499 Abnormality Archive
  code/game/machinery/computer/abnormality_archive.dm
  code/modules/paperwork/records/info/_info.dm
  lobotomy-corp13.dme
  tgui/packages/tgui/interfaces/LC13AbnormalityArchive.js
Labels: Feature, javascript

#576 Head of God realization ability
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/spells/ability_types/_ability.dm
  code/modules/spells/ability_types/realized.dm
  icons/effects/effects.dmi
  icons/mob/actions/actions_ability.dmi
Labels: Tweak

#578 Fix worn icon of Head of God
  icons/mob/clothing/ego_gear/realized.dmi
Labels: Fix

#556 Refactors daredevil into a shield
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
Labels: Tweak

#543 Record and abnorm names changed for consistency
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/behavior.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/silent_orchestra.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/staining_rose.dm
  code/modules/mob/living/simple_animal/abnormality/waw/express_train.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bald.dm
  code/modules/paperwork/records/info/_info.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/paperwork/records/info/tools.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/paperwork/records/info/zayin.dm
  strings/sillytips.txt
  strings/tips.txt
Labels: Tweak

#579 Removes questionable text
  code/modules/mob/living/carbon/human/examine.dm
Labels: Tweak

#581 Fix woodsman
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
Labels: Code improvement, Fix

#582 Fixes on_mob_death procs
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
Labels: Code improvement, Fix

#583 EGO gift descriptions
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Tweak

#585 Fix murder insanity moving while dead
  code/datums/ai/sanity/_sanityloss_controller.dm
Labels: Fix
