Repository vlggms/lobotomy-corp13, pull requests merged in 2023-02, with the labels that each got.

#584 Manager can now trigger core suppression
  _maps/map_files/generic/CentCom.dmm
  code/_globalvars/lists/objects.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/game/machinery/computer/abnormality_auxilary.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/ordeals/white_ordeals.dm
  code/modules/suppressions/_core_suppression.dm
  code/modules/suppressions/control.dm
  code/modules/suppressions/information.dm
  code/modules/suppressions/safety.dm
  code/modules/suppressions/training.dm
  lobotomy-corp13.dme
Labels: Feature, Mapping

#586 Wall Clown Fix
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson.dm
Labels: Fix

#580 Ordeal size difference update
  code/modules/mob/living/simple_animal/hostile/ordeal/_ordeal.dm
Labels: Tweak

#587 WAW armor requirements, and Teth armor rebalance
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/clothing/suits/ego_gear/waw.dm
Labels: Balance

#446 Gun Complexity update and Ego fixes
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/ammunition/ego_ammunition/aleph.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/aleph.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
Labels: Tweak

#589 Tutorial Overhaul
  _maps/map_files/generic/CentCom.dmm
  code/datums/holocall.dm
  code/game/machinery/hologram.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/game/objects/structures/tutorial.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/simple_animal/abnormality/!tutorial/bill.dm
  code/modules/mob/living/simple_animal/abnormality/!tutorial/fairies.dm
  code/modules/mob/living/simple_animal/abnormality/!tutorial/shadow.dm
  code/modules/paperwork/records/info/_info.dm
  code/modules/paperwork/records/tutorial/abnormalities.dm
  code/modules/paperwork/records/tutorial/levelling.dm
  icons/mob/animal.dmi
  lobotomy-corp13.dme
Labels: Feature

#591 Duffelbags are now just normal backpacks
  code/game/objects/items/storage/backpack.dm
Labels: Balance

#590 Lowers Volume of really loud ego
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
Labels: Fix

#596 Warden is now faster and has a cap on her speed
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
Labels: Balance

#597 Matriarch AOE now only hits humans
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Fix

#566 Adds road home
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/96x96.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/road_home.dm
  code/modules/mob/living/simple_animal/abnormality/he/scaredy_cat.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/roadhome/Cartoon_Falling_Sound_Effect.ogg
  sound/abnormalities/roadhome/House_HouseBoom.ogg
  sound/abnormalities/roadhome/House_MakeRoad.ogg
  sound/abnormalities/roadhome/House_NormalAtk.ogg
Labels: Feature

#595 Red Buddy is Faster and deals more damage
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
Labels: Balance

#521 Snow Whites Apple Lag reducing changes
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Code improvement, Fix

#507 Possessing Ghosts now always allows Ghosts to possess.
  code/controllers/subsystem/lobotomy_corp.dm
  code/modules/events/wizard/ghost.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Tweak

#577 Remove Barriers, and Revival Pens
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/assistant.dm
Labels: Tweak

#607 Adds in Extraction Cargo Console
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  code/game/machinery/computer/extraction_cargo.dm
  code/game/objects/items/devices/forcefieldprojector.dm
  code/game/objects/items/devices/lightreplacer.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/command.dm
  lobotomy-corp13.dme
Labels: Feature

#610 Crumbling Armor now does Pale Damage
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
  code/modules/paperwork/records/info/teth.dm
Labels: Balance

#588 Ebony Queen's Apple
  ModularTegustation/Teguicons/64x96.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/ebonyqueen/attack.ogg
  sound/abnormalities/ebonyqueen/charge.ogg
  sound/abnormalities/ebonyqueen/strongcharge.ogg
Labels: Feature

#611 Central Command Radio
  code/__DEFINES/radio.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/jobs/job_types/agent.dm
Labels: Tweak

#612 Job Folder Cleanup
  code/modules/jobs/job_types/_outfits.dm
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/jobs/job_types/prisoner.dm
  code/modules/jobs/job_types/psychologist.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  lobotomy-corp13.dme
Labels: Code improvement

#572 Extraction Core Suppression
  ModularTegustation/Teguicons/32x64.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/tegu_procs.dm
  code/__DEFINES/dcs/signals.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/datums/looping_sounds/abnormalities.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/suppressions/extraction.dm
  icons/effects/effects.dmi
  icons/obj/computer.dmi
  lobotomy-corp13.dme
  sound/effects/combat_suppression_end.ogg
  sound/effects/combat_suppression_start.ogg
  sound/magic/arbiter/meltdown.ogg
  sound/magic/arbiter/meltdown_clear.ogg
  sound/magic/arbiter/meltdown_clear_all.ogg
  sound/magic/arbiter/pin.ogg
  sound/magic/arbiter/storm_charge.ogg
  sound/magic/arbiter/storm_create.ogg
  sound/magic/arbiter/storm_fire.ogg
  sound/magic/arbiter/storm_loop.ogg
  sound/magic/arbiter/storm_start.ogg
Labels: Code improvement, Feature, Tweak

#618 Changes Stat Maximums
  code/datums/attributes/_attribute.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/manager.dm
Labels: Feature

#623 Increases Price of Wellcheers soda drastically
  code/game/machinery/computer/extraction_cargo.dm
Labels: Balance

#511 Gammacorp
  _maps/gammacorp.json
  _maps/map_files/Gamma/gammacorp.dmm
  code/game/area/areas/lobotomy_corp.dm
  config/maps.txt
Labels: Feature, Mapping

#615 Respawn tweaks
  code/datums/mind.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/mob.dm
Labels: Tweak

#547 Nest Fixes
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
Labels: Tweak, Fix

#564 Food update
  ModularTegustation/tegufood.dm
  code/game/objects/items/food/meat.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
  icons/obj/food/food.dmi
Labels: Tweak

#627 Solemn Lament armor change
  code/modules/clothing/suits/ego_gear/he.dm
Labels: Balance

#626 Rudolta now ignores players.
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
Labels: Tweak

#601 Updates WAW weapon requirements
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
Labels: Balance

#593 Sephirah (Admin-Enabled, Highpop Role)
  _maps/map_files/generic/CentCom.dmm
  code/_globalvars/lists/names.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/modules/client/preferences.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/jobs.dm
  code/modules/projectiles/guns/ego_gun.dm
  strings/names/sephirah.txt
Labels: Feature

#624 Adds Firebird
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/fire_bird.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  lobotomy-corp13.dme
  sound/abnormalities/firebird/Firebird_Hit.ogg
Labels: Feature

#632 Rudolta can now hurt people
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
Labels: Fix

#622 Records Officer Watches
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_items/records/_records.dm
  ModularTegustation/tegu_items/records/abnoblock.dm
  ModularTegustation/tegu_items/records/ordealcheck.dm
  ModularTegustation/tegu_items/records/timestop.dm
  code/modules/jobs/job_types/command.dm
  lobotomy-corp13.dme
Labels: Feature

#621 Adds Thunderbird
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Teguicons/64x96.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/thunderbird/tbird_beam.ogg
  sound/abnormalities/thunderbird/tbird_bolt.ogg
  sound/abnormalities/thunderbird/tbird_charge.ogg
  sound/abnormalities/thunderbird/tbird_peck.ogg
  sound/abnormalities/thunderbird/tbird_zombieattack.ogg
  sound/abnormalities/thunderbird/tbird_zombify.ogg
Labels: Feature

#636 Dumb Fire Bird Fix
  code/modules/mob/living/simple_animal/abnormality/waw/fire_bird.dm
Labels: Fix

#631 Mini Gammacorp update
  _maps/map_files/Gamma/gammacorp.dmm
Labels: Fix

#629 Alphacorp KOG Fix, 2 Wide Hall removal
  _maps/map_files/Alpha/alphacorp.dmm
Labels: Tweak

#637 Alphacorp hotfix
  _maps/map_files/Alpha/alphacorp.dmm
Labels: Fix

#599 Reworks F.A.N.
  code/modules/mob/living/simple_animal/abnormality/he/fan.dm
  code/modules/paperwork/records/info/he.dm
Labels: Balance

#608 Tools PR 3
  ModularTegustation/Teguicons/tegu_effects32x48.dmi
  ModularTegustation/Teguicons/toolabnormalities.dmi
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/treesap.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/bracelet.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/heart.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/theresia.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/paperwork/records/info/tools.dm
  lobotomy-corp13.dme
Labels: Feature

#633 Mimicry Nerf
  code/game/objects/items/ego_weapons/aleph.dm
Labels: Balance

#639 "Work Forbidden" trait
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/manager.dm
Labels: Tweak

#640 Sanity rework/improvement
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/status_effects/buffs.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/machinery/computer/manager_camera.dm
  code/game/machinery/regenerator.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/heart.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/theresia.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/KHz.dm
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/mob/living/simple_animal/abnormality/he/road_home.dm
  code/modules/mob/living/simple_animal/abnormality/he/silent_girl.dm
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cherry_blossoms.dm
  code/modules/mob/living/simple_animal/abnormality/teth/drowned_sisters.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
  code/modules/mob/living/simple_animal/abnormality/teth/shy_look.dm
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
  code/modules/mob/living/simple_animal/abnormality/waw/express_train.dm
  code/modules/mob/living/simple_animal/abnormality/waw/fire_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yang.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bald.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/spells/ability_types/realized_aimed.dm
Labels: Code improvement, Tweak, Fix

#600 WAW+ Pale Weapon Damage Reduction
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/waw.dm
Labels: Balance, Do Not Merge, Test Merge Candidate

#628 Amber midnight tweaks
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/ordeals/amber_ordeals.dm
Labels: Tweak, Fix

#638 Patrol fix attempts
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Fix

#641 Radial menu for manager bullet selection
  code/game/machinery/computer/manager_camera.dm
  icons/obj/manager_bullets.dmi
Labels: Code improvement, Tweak

#643 Gun Ego Equalization.
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  code/modules/projectiles/projectile/ego_bullets/zayin.dm
Labels: Balance

#644 Updates Ebony Queen
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
Labels: Tweak

#617 Green Midnight
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/224x128.dmi
  code/datums/looping_sounds/abnormalities.dm
  code/game/objects/effects/abnormality.dm
  code/game/objects/structures/ordealmonitor.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/ordeals/green_ordeals.dm
  icons/effects/beam.dmi
  icons/obj/ordeal_monitor.dmi
  sound/effects/ordeals/green/Machine_Midnight_5.ogg
  sound/effects/ordeals/green/Machine_Midnight_5_1.ogg
  sound/effects/ordeals/green/Machine_Midnight_7.ogg
  sound/effects/ordeals/green/midnight_dead.ogg
  sound/effects/ordeals/green/midnight_gears.ogg
  sound/effects/ordeals/green/midnight_gears_fast.ogg
  sound/effects/ordeals/green/midnight_laser_end.ogg
  sound/effects/ordeals/green/midnight_laser_fire.ogg
  sound/effects/ordeals/green/midnight_laser_loop.ogg
  sound/effects/ordeals/green/midnight_laser_new.ogg
  sound/effects/ordeals/green/midnight_laser_prepare.ogg
  sound/effects/ordeals/green/midnight_laser_warning.ogg
Labels: Feature, Fix

#634 Hopefully bug-free E.G.O. dump
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/projectiles/ammunition/ego_ammunition/he.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  sound/weapons/ego/clash1.ogg
  sound/weapons/ego/sword1.ogg
  sound/weapons/ego/sword2.ogg
Labels: Feature

#630 Green Dusks No Longer Spawn On Top Of Each Other
  code/modules/ordeals/green_ordeals.dm
Labels: Fix

#646 WN's good effect calls async instead of normal proc
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
Labels: Fix

#548 Quirk rebalance with new additions affecting gameplay
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/controllers/subsystem/processing/quirks.dm
  code/datums/quirks/good.dm
  code/datums/quirks/negative.dm
  code/datums/quirks/neutral.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Tweak

#649 Magic bullet buff
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
Labels: Balance, Tweak

#652 Hits some awkward HE armor sets
  code/modules/clothing/suits/ego_gear/he.dm
Labels: Balance

#642 Siren That Sings The Past
  ModularTegustation/Teguicons/64x64.dmi
  code/datums/looping_sounds/abnormalities.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/siren.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  lobotomy-corp13.dme
  sound/abnormalities/siren/backtherebenjamin.ogg
  sound/abnormalities/siren/burningmemory.ogg
  sound/abnormalities/siren/driftingtimemisplaced.ogg
  sound/abnormalities/siren/needle1.ogg
  sound/abnormalities/siren/needle2.ogg
Labels: Feature

#605 My Sweet Home Abnormality
  ModularTegustation/Teguicons/96x64.dmi
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/my_sweet_home.dm
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#661 Adds clown smiling at me
  ModularTegustation/Teguicons/tegumobs.dmi
  code/datums/looping_sounds/abnormalities.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
  sound/abnormalities/clownsmiling/announce.ogg
  sound/abnormalities/clownsmiling/announcedead.ogg
  sound/abnormalities/clownsmiling/clownloop.ogg
  sound/abnormalities/clownsmiling/final_stab.ogg
  sound/abnormalities/clownsmiling/throw.ogg
Labels: Feature

#654 road home nerf
  code/modules/mob/living/simple_animal/abnormality/he/road_home.dm
  code/modules/paperwork/records/info/he.dm
Labels: Balance

#664 Updates clown smiling at me
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
Labels: Balance

#665 Thunderbird changes
  ModularTegustation/Teguicons/32x32.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
Labels: Balance, Tweak

#667 Fixes the KHz paper
  code/modules/mob/living/simple_animal/abnormality/he/KHz.dm
Labels: Fix

#650 Overload chance is reset to 0 on meltdown
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Tweak

#670 Fixes well
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
Labels: Fix

#669 Do_After Tweaks
  code/game/machinery/computer/abnormality_work.dm
  code/game/machinery/regenerator.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
Labels: Code improvement

#655 New Yang Animation
  ModularTegustation/Teguicons/64x64.dmi
Labels: Sprites

#656 Random fixer equipment
  code/game/objects/items/fixer_weaponry/swords.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/mob/living/carbon/human/human_say.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  code/modules/projectiles/boxes_magazines/internal/revolver.dm
  code/modules/projectiles/boxes_magazines/internal/rifle.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/rifle_auto.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  icons/mob/clothing/mask.dmi
  icons/obj/clothing/masks.dmi
  lobotomy-corp13.dme
  sound/weapons/fixer/durandal1.ogg
  sound/weapons/fixer/durandal2.ogg
  sound/weapons/fixer/durandal_strong.ogg
  sound/weapons/gun/revolver/shot_atelier.ogg
  sound/weapons/gun/rifle/shot_atelier.ogg
Labels: Tweak

#662 Adds Jangsan Tiger
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/jangsan.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  lobotomy-corp13.dme
  sound/abnormalities/jangsan/tigerbite.ogg
Labels: Feature

#671 Watchman Flavor Update
  code/modules/mob/living/simple_animal/abnormality/he/watchman.dm
Labels: Feature

#668 Adds Sleeping Beauty
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  code/datums/abnormality/_ego_datum/zayin.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/sleeping_beauty.dm
  code/modules/paperwork/records/info/zayin.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#647 Adds Little Prince
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/tegu_effects32x48.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/little_prince.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/littleprince/Prince_Active.ogg
  sound/abnormalities/littleprince/Prince_Attack.ogg
  sound/abnormalities/littleprince/Prince_Death.ogg
Labels: Feature

#678 fixes the brawler and nerd quirks
  code/datums/quirks/neutral.dm
Labels: Fix

#673 RAK Buff
  code/game/machinery/regenerator.dm
Labels: Balance

#679 Funeral Visual and Attacks Tweaks
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/64x96.dmi
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
Labels: Tweak

#672 Reddened Buddy Icon Fix
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
Labels: Fix

#684 Extremely Important Change
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
Labels: Balance, Fix

#685 Removes bolting action from manager's console
  code/game/machinery/computer/manager_camera.dm
  lobotomy-corp13.dme
Labels: Tweak

#395 Auto-Apocalypse
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
  code/_globalvars/lists/mobs.dm
  code/controllers/subsystem/lobotomy_events.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  lobotomy-corp13.dme
Labels: Feature

#689 CRITICAL ALPHACORP FIX
  _maps/map_files/Alpha/alphacorp.dmm
Labels: Fix, Mapping
