Repository vlggms/lobotomy-corp13, pull requests merged in 2023-05, with the labels that each got.

#861 New Abnormality - Clouded Monk
  ModularTegustation/Teguicons/32x48.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/datums/looping_sounds/abnormalities.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clouded_monk.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/clouded_monk/eat.ogg
  sound/abnormalities/clouded_monk/eat_groggy.ogg
  sound/abnormalities/clouded_monk/howl.ogg
  sound/abnormalities/clouded_monk/monk_attack.ogg
  sound/abnormalities/clouded_monk/monk_bite.ogg
  sound/abnormalities/clouded_monk/monk_cast.ogg
  sound/abnormalities/clouded_monk/monk_groggy.ogg
  sound/abnormalities/clouded_monk/run.ogg
  sound/abnormalities/clouded_monk/transform.ogg
Labels: Abnormality

#899 Sphinx hotfix
  code/modules/mob/living/simple_animal/abnormality/waw/sphinx.dm
Labels: Fix

#893 Adds Fallen Amurdād
  ModularTegustation/Teguicons/tegumobs.dmi
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fallen_amurdad.dm
  code/modules/paperwork/records/info/zayin.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/obj/hydroponics/growing_flowers.dmi
  icons/obj/hydroponics/growing_mushrooms.dmi
  icons/obj/hydroponics/harvest.dmi
  lobotomy-corp13.dme
  sound/abnormalities/fallen_amurdad/plant.ogg
Labels: Abnormality

#900 Dirt no longer spawns by zayin records bins
  code/modules/mob/living/simple_animal/abnormality/zayin/fallen_amurdad.dm
Labels: Fix

#906 One character bottle fix
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
Labels: Tweak, Fix

#880 Abno Jam EGO dump
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/mob/clothing/ego_gear/limbus_suit.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/limbus_suits.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
Labels: Feature

#793 Crumbling armor changes
  ModularTegustation/Teguicons/status_sprites.dmi
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
  code/modules/paperwork/records/info/teth.dm
  sound/abnormalities/crumbling/attack.ogg
  sound/abnormalities/crumbling/globalwarning.ogg
  sound/abnormalities/crumbling/warning.ogg
Labels: Balance, Do Not Merge, Tweak, Test Merge Candidate

#916 Better Gamemode Voting
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/vote.dm
  code/game/gamemodes/management/management.dm
Labels: Tweak

#884 Fourth match flame realization
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/spells/ability_types/realized.dm
  icons/mob/actions/actions_ability.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/obj/clothing/ego_gear/realization.dmi
Labels: Tweak

#882 Spreading Structure Type
  ModularTegustation/lc13_machinery.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Feature

#838 Visualize Vitals
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_items/lc13unique_items.dm
  code/game/machinery/computer/extraction_cargo.dm
Labels: Feature

#914 Cleans the only Null in abnormalities files
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
Labels: Fix

#917 Clouded monk weapon update
  code/game/objects/items/ego_weapons/waw.dm
Labels: Balance, Fix

#897 Map Fixes (Eta, Gamma)
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
Labels: Mapping

#924 The one proc gamemode vote fix
  code/controllers/subsystem/vote.dm
Labels: Tweak, Fix

#928 Etacorp Fix
  _maps/map_files/Eta/etacorp.dmm
Labels: Mapping

#941 Fix #859
  code/modules/mob/living/carbon/carbon_update_icons.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
Labels: Fix

#932 Zeta Corp (F Corp/Saltmine)
  _maps/map_files/Zeta/zetacorp.dmm
  _maps/zetacorp.json
Labels: Mapping

#926 Managerial Offices 2.1 soul update + fixes + new plushie
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Mapping, Sprites

#937 Eta Fix
  _maps/map_files/Eta/etacorp.dmm
Labels: Fix, Mapping

#921 Fix invalid initialize hints in LC13 code
  ModularTegustation/lc13_machinery.dm
  ModularTegustation/tegu_items/lc13/refinery/_spawners.dm
  ModularTegustation/tegu_items/lc13/refinery/sales.dm
  ModularTegustation/tegu_items/lc13unique_items.dm
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
  code/game/objects/effects/abnormality.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/zwei.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/treesap.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/staining_rose.dm
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/mob/living/simple_animal/abnormality/he/jangsan.dm
  code/modules/mob/living/simple_animal/abnormality/he/road_home.dm
  code/modules/mob/living/simple_animal/abnormality/teth/old_lady.dm
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/living/simple_animal/abnormality/waw/sphinx.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/misc.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  code/modules/projectiles/projectile/ego_bullets/special.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
Labels: Code improvement

#819 Double Tap PR
  code/game/objects/items/ego_weapons/_ego_weapon.dm
Labels: Tweak

#939 Fix meat subtype recipes
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
Labels: Fix

#919 Big fat E.G.O. dump
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/projectiles/ammunition/ego_ammunition/teth.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  icons/obj/projectiles_impact.dmi
  icons/obj/projectiles_muzzle.dmi
  icons/obj/projectiles_tracer.dmi
  sound/abnormalities/babayaga/attack.ogg
  sound/abnormalities/babayaga/charge.ogg
  sound/abnormalities/blubbering_toad/attack.ogg
  sound/abnormalities/blubbering_toad/blurble1.ogg
  sound/abnormalities/blubbering_toad/blurble2.ogg
  sound/abnormalities/blubbering_toad/blurble3.ogg
  sound/abnormalities/blubbering_toad/blurble4.ogg
  sound/abnormalities/blubbering_toad/tongue.ogg
  sound/abnormalities/blubbering_toad/windup.ogg
  sound/abnormalities/orangetree/ding.ogg
  sound/abnormalities/orangetree/light1.ogg
  sound/abnormalities/orangetree/light2.ogg
  sound/abnormalities/orangetree/light3.ogg
  sound/abnormalities/orangetree/light4.ogg
  sound/abnormalities/orangetree/light5.ogg
  sound/abnormalities/orangetree/light6.ogg
  sound/abnormalities/pagoda/throw.ogg
  sound/abnormalities/pagoda/throw2.ogg
  sound/abnormalities/palehorse/damage.ogg
  sound/abnormalities/palehorse/debuff.ogg
  sound/abnormalities/palehorse/kill.ogg
  sound/abnormalities/someonesportrait/panic.ogg
Labels: Feature, Sprites

#927 Tweaks "!tgs check" and hub status message
  ModularTegustation/tegu_config.dm
  ModularTegustation/tegu_world.dm
  code/game/world.dm
  code/modules/admin/chat_commands.dm
  lobotomy-corp13.dme
Labels: Tweak

#944 Fixes Duplicate Proc Definition from Double Tap PR
  code/game/objects/items/ego_weapons/waw.dm
Labels: Fix

#943 Add config option for qliphoth meltdown percentage
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/lobotomy_corp.dm
  config/config.txt
Labels: Code improvement

#952 Removes Double Tap
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/waw.dm
Labels: Fix, Removal

#925 [MDB IGNORE] E Corp V5
  ModularTegustation/tegu_items/associations/association_beacon.dm
  _maps/map_files/Epsilon/epsiloncommand.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  code/__DEFINES/jobs.dm
  code/controllers/subsystem/maptype.dm
  code/game/area/areas/lobotomy_corp.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/clothing/under/clerksuits.dm
  code/modules/jobs/job_types/trusted_players/association/associate.dm
  code/modules/jobs/job_types/trusted_players/association/director.dm
  code/modules/jobs/job_types/trusted_players/association/veteran.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  icons/mob/clothing/ego_gear/under.dmi
  icons/obj/card.dmi
  lobotomy-corp13.dme
Labels: Feature, Mapping

#956 Eta
  _maps/map_files/Eta/etacorp.dmm
Labels: Tweak

#909 Adds Someone's Portrait
  ModularTegustation/Teguicons/tegumobs.dmi
  code/modules/mob/living/simple_animal/abnormality/teth/someonesportrait.dm
  code/modules/paperwork/records/info/teth.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#913 Adds My Sweet Orange Tree
  ModularTegustation/Teguicons/48x64.dmi
  code/datums/diseases/orange_tree.dm
  code/datums/looping_sounds/abnormalities.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/modules/mob/living/simple_animal/abnormality/waw/orange_tree.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/ammunition/ego_ammunition/special.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/special.dm
  code/modules/projectiles/projectile/ego_bullets/special.dm
  icons/effects/effects.dmi
  icons/obj/projectiles.dmi
  icons/obj/wallmounts.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#886 Adds missing sprites on ego gifts
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/flesh_idol.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
Labels: Sprites

#960 Fixes bug with tutorial abnos
  code/modules/mob/living/simple_animal/abnormality/!tutorial/shadow.dm
Labels: Fix

#959 Spellchecks Limbus EGO
  code/modules/clothing/suits/ego_gear/non_abnormality/limbus_ego.dm
Labels: Fix

#948 Cleans dead vars from dangle
  code/modules/mob/living/simple_animal/abnormality/teth/dingle_dangle.dm
Labels: Code improvement

#947 Homing Instinct's Minimum damage is increased
  code/game/objects/items/ego_weapons/he.dm
Labels: Balance

#946 Ordeals now only take players in game into account
  code/modules/ordeals/amber_ordeals.dm
Labels: Balance

#962 Parasite Tree Ego Gear
  ModularTegustation/Teguicons/32x32.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
Labels: Balance

#968 Dumps a bunch of E.G.O.
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/zayin.dm
  code/game/objects/effects/misc.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles_impact.dmi
  icons/obj/projectiles_tracer.dmi
  sound/abnormalities/kqe/hitsound1.ogg
  sound/abnormalities/kqe/hitsound2.ogg
  sound/abnormalities/kqe/load1.ogg
  sound/abnormalities/kqe/load2.ogg
  sound/abnormalities/kqe/load3.ogg
Labels: Tweak

#966 Zayin as first pick
  code/controllers/subsystem/abnormality_queue.dm
Labels: Tweak

#961 Removes Scorp from Cargo.
  code/game/machinery/computer/extraction_cargo.dm
Labels: Tweak, Removal

#945 Titania properly announces her laws
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
Labels: Fix

#967 Sephirah Console
  code/game/machinery/computer/manager_camera.dm
Labels: Feature

#972 Adds Deepscanners to all info rooms
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
Labels: Tweak

#933 Theta Corp
  _maps/map_files/Theta/thetacorp.dmm
  _maps/thetacorp.json
Labels: Balance, Mapping

#975 Psicorp Added by Skits
  _maps/map_files/Psi/psicorp.dmm
  _maps/psicorp.json
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/trusted_players/representative.dm
  code/modules/jobs/job_types/trusted_players/sephirah.dm
  config/maps.txt
Labels: Mapping

#964 Max understanding counter & PE on yellow roll
  code/controllers/subsystem/lobotomy_corp.dm
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/abnormality_queue.dm
  code/modules/jobs/job_types/agent.dm
Labels: Feature

#885 Adds blubbering toad
  ModularTegustation/Teguicons/64x64.dmi
  code/modules/mob/living/simple_animal/abnormality/zayin/blubbering_toad.dm
  code/modules/paperwork/records/info/zayin.dm
  icons/effects/beam.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#973 Refinery Update, Gadgets moved around
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/Teguicons/refiner.dmi
  ModularTegustation/tegu_items/lc13/admin.dm
  ModularTegustation/tegu_items/lc13/gadgets/detector.dm
  ModularTegustation/tegu_items/lc13/gadgets/manager_bullets.dm
  ModularTegustation/tegu_items/lc13/gadgets/powered.dm
  ModularTegustation/tegu_items/lc13/gadgets/unpowered.dm
  ModularTegustation/tegu_items/lc13/injectors.dm
  ModularTegustation/tegu_items/lc13/refinery/_spawners.dm
  ModularTegustation/tegu_items/lc13/refinery/crates.dm
  ModularTegustation/tegu_items/lc13/refinery/sales.dm
  ModularTegustation/tegu_items/lc13unique_items.dm
  code/game/objects/items/ego_weapons/non_abnormality/_cityweapons.dm
  code/game/objects/items/ego_weapons/non_abnormality/misc.dm
  code/game/objects/items/ego_weapons/non_abnormality/molar.dm
  code/game/objects/items/ego_weapons/non_abnormality/ncorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/pierre.dm
  code/game/objects/items/ego_weapons/non_abnormality/rats.dm
  code/game/objects/items/ego_weapons/non_abnormality/shrimp.dm
  code/game/objects/items/ego_weapons/non_abnormality/syndicate.dm
  code/game/objects/items/ego_weapons/non_abnormality/yun.dm
  code/game/objects/items/ego_weapons/non_abnormality/zwei.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/bladelineage.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/ncorp.dm
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  lobotomy-corp13.dme
Labels: Code improvement, Tweak

#938 Adds Pygmalion
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/pygmalion.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#979 Gadgets 1.1
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_items/lc13/gadgets/powered.dm
  code/datums/status_effects/debuffs.dm
  code/game/machinery/recharger.dm
Labels: Fix

#982 Lance fixes
  code/game/objects/items/ego_weapons/_ego_weapon.dm
Labels: Fix

#896 Nameless Fetus
  ModularTegustation/Teguicons/48x48.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/nameless_fetus.dm
  code/modules/paperwork/records/info/he.dm
  lobotomy-corp13.dme
  sound/abnormalities/fetus/crying.ogg
Labels: Abnormality

#994 Records cabinets no longer croak
  code/modules/mob/living/simple_animal/abnormality/zayin/blubbering_toad.dm
Labels: Fix

#995 Stop pod spawn trait from selecting tutorial areas
  code/controllers/subsystem/job.dm
Labels: Fix

#985 Snow White Apple vine removal and immunity list updates
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
Labels: Fix

#904 Adds All-natural snake oil
  ModularTegustation/Teguicons/toolabnormalities.dmi
  code/modules/mob/living/simple_animal/abnormality/_tools/he/dr_jekyll.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/dr_jekyll.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/snake_oil.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/paperwork/records/info/tools.dm
  icons/effects/effects.dmi
  lobotomy-corp13.dme
Labels: Feature, Tweak

#930 Thunderbird E.G.O rework
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles_impact.dmi
  icons/obj/projectiles_muzzle.dmi
  icons/obj/projectiles_tracer.dmi
Labels: Balance, Tweak

#974 Ecorp V5.1
  _maps/map_files/Epsilon/epsiloncommand.dmm
  code/__DEFINES/jobs.dm
  code/modules/jobs/job_types/gimmick/HHPP.dm
  code/modules/jobs/job_types/gimmick/backstreets_butcher.dm
  code/modules/jobs/job_types/gimmick/doctor.dm
  code/modules/jobs/job_types/gimmick/scavenger.dm
  code/modules/jobs/job_types/trusted_players/association/associate.dm
  code/modules/jobs/job_types/trusted_players/association/director.dm
  code/modules/jobs/job_types/trusted_players/association/veteran.dm
  code/modules/jobs/jobs.dm
  icons/mob/hud.dmi
  icons/obj/card.dmi
  lobotomy-corp13.dme
Labels: Feature, Mapping

#984 Refinery Armor Update and Forging Workshop Weapons
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/Teguicons/refiner.dmi
  ModularTegustation/Teguicons/workshop.dmi
  ModularTegustation/tegu_items/admin.dm
  ModularTegustation/tegu_items/associations/association_beacon.dm
  ModularTegustation/tegu_items/gadgets/detector.dm
  ModularTegustation/tegu_items/gadgets/manager_bullets.dm
  ModularTegustation/tegu_items/gadgets/powered.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_items/injectors.dm
  ModularTegustation/tegu_items/refinery/_spawners.dm
  ModularTegustation/tegu_items/refinery/crates.dm
  ModularTegustation/tegu_items/refinery/pebox.dm
  ModularTegustation/tegu_items/refinery/refinery.dm
  ModularTegustation/tegu_items/refinery/sales.dm
  ModularTegustation/tegu_items/refinery/tools.dm
  ModularTegustation/tegu_items/workshop/_mods.dm
  ModularTegustation/tegu_items/workshop/_templates.dm
  ModularTegustation/tegu_items/workshop/forging.dm
  ModularTegustation/tegu_items/workshop/mods/basic.dm
  ModularTegustation/tegu_items/workshop/mods/healthup.dm
  ModularTegustation/tegu_items/workshop/mods/sapping.dm
  ModularTegustation/tegu_items/workshop/mods/throwforce.dm
  ModularTegustation/tegu_items/workshop/templates/basic.dm
  ModularTegustation/tegu_items/workshop/templates/gauntlet.dm
  ModularTegustation/tegu_items/workshop/templates/scythe.dm
  code/game/objects/items/ego_weapons/non_abnormality/_cityweapons.dm
  code/game/objects/items/ego_weapons/non_abnormality/dawn.dm
  code/game/objects/items/ego_weapons/non_abnormality/fullstop.dm
  code/game/objects/items/ego_weapons/non_abnormality/index.dm
  code/game/objects/items/ego_weapons/non_abnormality/jeong.dm
  code/game/objects/items/ego_weapons/non_abnormality/miscfixer.dm
  code/game/objects/items/ego_weapons/non_abnormality/pierre.dm
  code/game/objects/items/ego_weapons/non_abnormality/streetlight.dm
  code/game/objects/items/ego_weapons/non_abnormality/syndicate.dm
  code/game/objects/items/ego_weapons/non_abnormality/weak_edits/ecorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/zwei.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/dawn.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/fullstop.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/hana.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/misc.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/seven.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/wedge.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/zwei.dm
  code/modules/projectiles/ammunition/ego_ammunition/special.dm
  code/modules/projectiles/guns/ego_gun.dm
  code/modules/projectiles/projectile/ego_bullets/special.dm
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  lobotomy-corp13.dme
Labels: Feature

#1006 Removes the recipe for large cardboard boxes
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Balance, Removal

#1000 Gamemode Vote Redux
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/vote.dm
  data/mode.txt
Labels: Feature

#992 Indigo Dusk White Sweeper now ignores insanity
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Fix

#912 Naked nest fixes part2
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Fix

#1010 Fix patrol_reset messing with target chase AI
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Fix

#853 G corp remenant mob, Steel Ordeal, Ordeal Refactor.
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x48.dmi
  code/datums/status_effects/buffs.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/misc.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
  code/modules/ordeals/_ordealtypes.dm
  code/modules/ordeals/amber_ordeals.dm
  code/modules/ordeals/crimson_ordeals.dm
  code/modules/ordeals/green_ordeals.dm
  code/modules/ordeals/indigo_ordeals.dm
  code/modules/ordeals/misc_ordeals.dm
  code/modules/ordeals/steel_ordeals.dm
  code/modules/ordeals/violet_ordeals.dm
  lobotomy-corp13.dme
  sound/effects/ordeals/steel/gcorp_attack1.ogg
  sound/effects/ordeals/steel/gcorp_attack2.ogg
  sound/effects/ordeals/steel/gcorp_attack3.ogg
  sound/effects/ordeals/steel/gcorp_boom.ogg
  sound/effects/ordeals/steel/gcorp_chitter.ogg
  sound/effects/ordeals/steel/gcorp_hiss.ogg
Labels: Feature

#1009 Quiet Day audiovisual changes
  ModularTegustation/Teguicons/48x48.dmi
  code/datums/looping_sounds/abnormalities.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/quiet_day.dm
  sound/abnormalities/quietday/quietloop.ogg
Labels: Tweak

#1011 Adds a force reset to Jeong Office Sword. Adds ability recharge notice to Blade Lineage.
  code/game/objects/items/ego_weapons/non_abnormality/jeong.dm
  code/game/objects/items/ego_weapons/non_abnormality/syndicate.dm
Labels: Fix

#1012 Raises max PE on blubbering toad
  code/modules/mob/living/simple_animal/abnormality/zayin/blubbering_toad.dm
Labels: Balance

#1014 General Map Fix and Add ons
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/Psi/psicorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
  _maps/map_files/Xi/xicommand.dmm
  _maps/map_files/Xi/xicorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
Labels: Mapping

#976 Sephirah Update
  code/_globalvars/lists/names.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/trusted_players/sephirah.dm
  code/modules/mob/living/carbon/human/species_types/sephirah.dm
  icons/mob/human_parts_greyscale.dmi
  lobotomy-corp13.dme
Labels: Feature, Tweak

#989 Food code dump
  ModularTegustation/tegufood.dm
  code/game/objects/items/food/meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  icons/obj/food/food.dmi
  icons/obj/food/piecake.dmi
Labels: Tweak

#1015 Moved Shy look DMI files to 64by48
  ModularTegustation/Teguicons/64x48.dmi
  code/modules/mob/living/simple_animal/abnormality/teth/shy_look.dm
  icons/mob/shy_look.dmi
Labels: Code improvement
