Repository vlggms/lobotomy-corp13, pull requests merged in 2023-06, with the labels that each got.

#907 Adds KQE-1J-23
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/96x64.dmi
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#993 Worn Ego Sprites
  ModularTegustation/Teguicons/32x32.dmi
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  icons/mob/clothing/belt.dmi
  icons/mob/clothing/belt_mirror.dmi
Labels: Sprites

#1021 Drinks from TG part one: Telepole
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  icons/obj/drinks.dmi
Labels: Tweak, Sprites

#825 Silent Girl Rework
  code/modules/mob/living/carbon/human/physiology.dm
  code/modules/mob/living/simple_animal/abnormality/he/silent_girl.dm
  code/modules/paperwork/records/info/he.dm
Labels: Balance, Tweak

#802 RRRR Corp
  ModularTegustation/Teguicons/head_item.dmi
  ModularTegustation/Teguicons/head_worn.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/tegu_items/refinery/crates.dm
  _maps/map_files/Event/rcorp.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/rcorp_test.json
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/maptype.dm
  code/controllers/subsystem/ticker.dm
  code/datums/map_config.dm
  code/game/gamemodes/management/event/combat.dm
  code/game/objects/items/ego_weapons/non_abnormality/rcorp.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/jobs/job_types/rcorp/command.dm
  code/modules/jobs/job_types/rcorp/rabbit.dm
  code/modules/jobs/job_types/rcorp/raven.dm
  code/modules/jobs/job_types/rcorp/reindeer.dm
  code/modules/jobs/job_types/rcorp/rhino.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/vehicles/mecha/combat/rhino.dm
  config/maps.txt
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/under.dmi
  icons/mob/clothing/neck.dmi
  icons/obj/clothing/cloaks.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/lcuniform.dmi
  icons/obj/clothing/under/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/guns/energy.dmi
  lobotomy-corp13.dme
Labels: Feature

#1023 Frees Hermit from the Prison of Body Bags
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
Labels: Fix

#864 Magical Girl Realized Abilities, Also Hats
  ModularTegustation/Teguicons/status_sprites.dmi
  code/game/objects/effects/abnormality.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/spells/ability_types/_ability.dm
  code/modules/spells/ability_types/realized.dm
  code/modules/spells/ability_types/realized_aimed.dm
  icons/effects/64x64.dmi
  icons/mob/actions/actions_ability.dmi
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/realization.dmi
Labels: Feature, Tweak

#1026 Put Vitals Projector in Crate instead of the status effect
  ModularTegustation/tegu_items/refinery/crates.dm
Labels: Fix

#1027 Updates Config and such for downstreams, and spawn messages
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/manager.dm
  config/admins.txt
  config/config.txt
  config/game_options.txt
  config/maps.txt
Labels: Tweak

#1008 Records Lore
  _maps/map_files/generic/CentCom.dmm
  code/modules/paperwork/records/lore/aleph.dm
  code/modules/paperwork/records/lore/he.dm
  code/modules/paperwork/records/lore/teth.dm
  code/modules/paperwork/records/recordsfiling.dm
  lobotomy-corp13.dme
Labels: Feature

#1013 Rosespanner
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  code/game/objects/items/ego_weapons/non_abnormality/_cityweapons.dm
  code/game/objects/items/ego_weapons/non_abnormality/cane.dm
  code/game/objects/items/ego_weapons/non_abnormality/rosespanner.dm
  code/game/objects/items/ego_weapons/non_abnormality/wcorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/rosespanner.dm
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  lobotomy-corp13.dme
Labels: Tweak

#1029 Ego resprite
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/clothing/ego_gear/under.dmi
  icons/mob/clothing/old_ego.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/lcuniform.dmi
  icons/obj/clothing/ego_gear/suits.dmi
Labels: Sprites

#965 Tip of the Round overhaul
  code/controllers/subsystem/ticker.dm
  strings/abnotips.txt
  strings/jobtips.txt
  strings/sillytips.txt
  strings/tips.txt
Labels: Feature, Tweak

#1034 Adds 2 more templates
  ModularTegustation/Teguicons/workshop.dmi
  ModularTegustation/tegu_items/workshop/templates/basic.dm
Labels: Tweak

#1038 Fixes Piscine Mermaid Realization
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
Labels: Fix

#898 Adds bongy
  ModularTegustation/Teguicons/tegumobs.dmi
  ModularTegustation/tegu_items/refinery/crates.dm
  ModularTegustation/tegu_mobs/lc13_bongy.dm
  code/game/objects/items/plushes.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  icons/mob/clothing/mask.dmi
  icons/obj/plushes.dmi
  lobotomy-corp13.dme
  sound/creatures/lc13/bongy/chatter1.ogg
  sound/creatures/lc13/bongy/chatter2.ogg
  sound/creatures/lc13/bongy/chatter3.ogg
  sound/creatures/lc13/bongy/kweh.ogg
Labels: Feature

#866 Pile of mail - Contest abnormality
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x48.dmi
  code/game/machinery/computer/abnormality_work.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/carbon/human/physiology.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/pile_of_mail.dm
  code/modules/paperwork/records/info/zayin.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/mailpile/gotmail.ogg
Labels: Test Merge Candidate, Abnormality

#1022 Nihil ego dump
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/special.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nihil.dm
  code/modules/projectiles/ammunition/ego_ammunition/aleph.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/guns/ego_gun/special.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/aleph.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  sound/abnormalities/hatredqueen/blast.ogg
  sound/abnormalities/pinocchio/attack.ogg
  sound/abnormalities/seasons/fall_attack.ogg
  sound/abnormalities/seasons/fall_change.ogg
  sound/abnormalities/seasons/spring_change.ogg
  sound/abnormalities/seasons/summer_attack.ogg
  sound/abnormalities/seasons/summer_change.ogg
  sound/abnormalities/seasons/summer_idle.ogg
  sound/abnormalities/seasons/winter_attack.ogg
  sound/abnormalities/seasons/winter_change.ogg
Labels: Feature

#1045 Make Jangsan Make sense
  code/modules/mob/living/simple_animal/abnormality/he/jangsan.dm
Labels: Tweak

#1019 Adds tool E.G.O
  ModularTegustation/Teguicons/lc13_weapons.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/zayin.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  code/modules/projectiles/ammunition/ego_ammunition/he.dm
  code/modules/projectiles/ammunition/ego_ammunition/teth.dm
  code/modules/projectiles/ammunition/ego_ammunition/zayin.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
  code/modules/projectiles/projectile/ego_bullets/zayin.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles_tracer.dmi
Labels: Feature

#1039 Big Iron gets some love
  code/modules/projectiles/guns/ego_gun/waw.dm
Labels: Tweak

#1046 Removes aux console
  _maps/map_files/generic/CentCom.dmm
Labels: Removal

#1030 RCorp 2: Rank Titles, Operations Officers, Requisitions and Lieutenant Commander
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/tegu_items/rcorp/itemspawner.dm
  ModularTegustation/tegu_items/rcorp/landmarks.dm
  ModularTegustation/tegu_items/rcorp/turrets.dm
  _maps/map_files/Event/rcorp.dmm
  _maps/rcorp_test.json
  code/__HELPERS/game.dm
  code/controllers/subsystem/maptype.dm
  code/datums/station_traits/negative_traits.dm
  code/game/gamemodes/management/event/combat.dm
  code/game/objects/items/ego_weapons/non_abnormality/rcorp.dm
  code/game/objects/structures/manned_turret.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/rcorp/command.dm
  code/modules/jobs/job_types/rcorp/officer.dm
  code/modules/jobs/job_types/rcorp/rabbit.dm
  code/modules/jobs/job_types/rcorp/raven.dm
  code/modules/jobs/job_types/rcorp/reindeer.dm
  code/modules/jobs/job_types/rcorp/rhino.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/fire_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/projectiles/guns/misc/medbeam.dm
  code/modules/vehicles/mecha/combat/rhino.dm
  code/modules/vehicles/mecha/combat/tank.dm
  code/modules/vehicles/mecha/equipment/weapons/mecha_melee.dm
  code/modules/vehicles/tank.dm
  icons/mecha/mecha.dmi
  icons/obj/card.dmi
  icons/obj/chronos.dmi
  lobotomy-corp13.dme
Labels: Feature

#1047 Updates timelocks for Agent Captain and Records Officer.
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/command.dm
Labels: Tweak

#448 Robots Improved?
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Psi/psicorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
  _maps/map_files/Xi/xicorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
Labels: Tweak, Fix, Mapping

#1028 Ordeal Refraction Edits
  code/modules/ordeals/_ordealtypes.dm
  code/modules/ordeals/amber_ordeals.dm
  code/modules/ordeals/green_ordeals.dm
  code/modules/ordeals/indigo_ordeals.dm
Labels: Tweak

#1056 Rats get a pipe
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/tegu_items/refinery/crates.dm
  code/game/objects/items/ego_weapons/non_abnormality/rats.dm
  sound/weapons/ego/pipesuffering.ogg
Labels: Tweak

#856 Parasite Tree
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/tegu_effects32x48.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/parasite_tree.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#1069 Fixes a singular pipe on Eta
  _maps/map_files/Eta/etacorp.dmm
Labels: Fix, Mapping

#1071 Gives gcorp some cleanbots
  _maps/map_files/Eta/etacorp.dmm
Labels: Mapping

#1065 Charge Refactor
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/subtype/charge.dm
  code/game/objects/items/ego_weapons/subtype/lance.dm
  code/game/objects/items/ego_weapons/subtype/shield.dm
  lobotomy-corp13.dme
Labels: Code improvement

#1054 Makes the Black Silence weapons not hurt my eyes
  icons/obj/black_silence_weapons.dmi
Labels: Sprites

#1058 Adds cherry blossoms realization
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/spells/ability_types/realized.dm
  icons/effects/effects.dmi
  icons/mob/actions/actions_ability.dmi
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/realization.dmi
Labels: Tweak

#918 Price of silence E.G.O. Rename
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
Labels: Tweak

#1077 Psicorp missing tile fix
  _maps/map_files/Psi/psicorp.dmm
Labels: Fix, Mapping

#1072 Fairy Festival Lore
  code/modules/paperwork/records/lore/zayin.dm
Labels: Writing

#812 Adds Pale Horse
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/pale_horse.dm
  code/modules/paperwork/records/info/teth.dm
  lobotomy-corp13.dme
Labels: Abnormality

#1067 Core Suppression time limit + some tweaks
  _maps/map_files/generic/CentCom.dmm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/ordeals/white_ordeals.dm
  code/modules/suppressions/safety.dm
  code/modules/suppressions/training.dm
  config/config.txt
Labels: Tweak

#1084 Tweaks to range/view procs
  code/__HELPERS/unsorted.dm
Labels: Code improvement, Fix

#863 Adjustable EGO Example
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
Labels: Feature

#1076 LCB13 Backstreets additions
  ModularTegustation/Teguicons/tegumobs.dmi
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
Labels: Tweak

#1086 Gives clerks the ability to make bigger, better and more complex art
  code/__DEFINES/construction.dm
Labels: Tweak

#1085 No More Infinite Dissolve
  code/modules/mob/living/carbon/human/ego_gifts.dm
Labels: Fix

#878 Yin
  ModularTegustation/Teguicons/64x64.dmi
  code/controllers/subsystem/lobotomy_events.dm
  code/datums/abnormality/datum/abnormality.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yang.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yin.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/paperwork/records/info/waw.dm
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  lobotomy-corp13.dme
  sound/abnormalities/yin/dragon_spawn.ogg
Labels: Abnormality

#957 Halves Violet Midnight's damage
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
Labels: Balance

#889 Contract Rework, Waw minor changes
  code/modules/mob/living/simple_animal/abnormality/waw/contract.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dimension_refraction.dm
  code/modules/mob/living/simple_animal/abnormality/waw/flesh_idol.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Balance

#872 Shield Rebalance
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/non_abnormality/kcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_sinner.dm
  code/game/objects/items/ego_weapons/subtype/shield.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
Labels: Balance

#1081 Adds new E.G.O.
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_sinner.dm
  code/game/objects/items/ego_weapons/subtype/shield.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/he/nameless_fetus.dm
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
  code/modules/projectiles/guns/ego_gun/special.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  sound/abnormalities/distortedform/slam.ogg
  sound/weapons/ego/heavy_guard.ogg
Labels: Tweak

#1102 Manager alt titles
  ModularTegustation/altjobtitles/LC13.dm
  code/modules/jobs/job_types/manager.dm
Labels: Tweak

#1104 Parry Fix
  code/game/objects/items/ego_weapons/subtype/shield.dm
Labels: Fix

#1105 Fixes Yin
  code/modules/mob/living/simple_animal/abnormality/waw/yin.dm
Labels: Tweak, Fix
