Repository vlggms/lobotomy-corp13, pull requests merged in 2023-12, with the labels that each got.

#1668 Refinery Tweaks
  ModularTegustation/tegu_items/refinery/boxes.dm
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/refinery/crates/workshop.dm
  ModularTegustation/tegu_items/refinery/sales.dm
  ModularTegustation/tegu_items/representative/console.dm
  ModularTegustation/tegu_items/representative/outfits.dm
  code/modules/clothing/head/_ego_head.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/_cityarmor.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/jcorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/kcorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/ncorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/wcorp.dm
  code/modules/jobs/job_types/wcorp/wcorpl1.dm
  code/modules/jobs/job_types/wcorp/wcorpl2.dm
  code/modules/jobs/job_types/wcorp/wcorprecon.dm
  code/modules/jobs/job_types/wcorp/wcorpshield.dm
  code/modules/jobs/job_types/wcorp/wcorpspear.dm
  code/modules/spells/ability_types/_ability.dm
  icons/mob/actions/actions_ability.dmi
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/mob/clothing/ego_gear/neck.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/neck.dmi
  lobotomy-corp13.dme
Labels: Code improvement, Tweak, Sprites

#1671 Dingle-Dangle Rework.
  code/modules/mob/living/simple_animal/abnormality/teth/dingle_dangle.dm
  code/modules/paperwork/records/info/teth.dm
Labels: Tweak

#1672 Eris Hotfixes
  code/modules/mob/living/simple_animal/abnormality/he/eris.dm
Labels: Balance, Fix

#1630 Teth updates (Basic stuff)
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/mob/living/simple_animal/abnormality/teth/MHz.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cleaner.dm
  code/modules/mob/living/simple_animal/abnormality/teth/forsaken_murderer.dm
  code/modules/mob/living/simple_animal/abnormality/teth/spider_bud.dm
  code/modules/paperwork/records/info/teth.dm
Labels: Tweak

#1561 Edits to Manager Holocommands and Glowing Commands
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/game/machinery/computer/manager_camera.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
Labels: Tweak

#1682 Holy shit I got fucking fished
  code/controllers/subsystem/persistence.dm
Labels: Fix

#1684 Adds proper span's to ever moar things
  ModularTegustation/tegu_items/admin.dm
  ModularTegustation/tegu_items/apostle_items.dm
  ModularTegustation/tegu_items/associations/association_beacon.dm
  ModularTegustation/tegu_items/associations/fixer.dm
  ModularTegustation/tegu_items/associations/fixeroffice.dm
  ModularTegustation/tegu_items/associations/items.dm
  ModularTegustation/tegu_items/associations/machines.dm
  ModularTegustation/tegu_items/associations/syndicateoffice.dm
  ModularTegustation/tegu_items/gadgets/detector.dm
  ModularTegustation/tegu_items/gadgets/manager_bullets.dm
  ModularTegustation/tegu_items/gadgets/powered.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_items/injectors.dm
  ModularTegustation/tegu_items/lc13unique_items.dm
  ModularTegustation/tegu_items/records/_records.dm
  ModularTegustation/tegu_items/records/abnoblock.dm
  ModularTegustation/tegu_items/records/meltdown_extend.dm
  ModularTegustation/tegu_items/records/ordealcheck.dm
  ModularTegustation/tegu_items/refinery/crates/_crate.dm
  ModularTegustation/tegu_items/refinery/sales.dm
  ModularTegustation/tegu_items/representative/console.dm
  ModularTegustation/tegu_items/representative/items/kcorp.dm
  ModularTegustation/tegu_items/representative/items/lcorp.dm
  ModularTegustation/tegu_items/representative/items/ncorp.dm
  ModularTegustation/tegu_items/representative/research/lcorp.dm
  ModularTegustation/tegu_items/representative/spawners.dm
  ModularTegustation/tegu_items/wcorp/enemies.dm
  ModularTegustation/tegu_items/workshop/_materials.dm
  ModularTegustation/tegu_items/workshop/_templates.dm
  ModularTegustation/tegu_items/workshop/forging.dm
  ModularTegustation/tegu_items/workshop/mods/offbeat.dm
  ModularTegustation/tegu_items/workshop/mods/sharp.dm
  ModularTegustation/tegu_items/workshop/ordeal extractor.dm
  ModularTegustation/tegu_items/workshop/templates/chargeblade.dm
  ModularTegustation/tegu_items/workshop/templates/gauntlet.dm
  ModularTegustation/tegu_items/workshop/templates/katana.dm
Labels: Code improvement

#1646 Carbon Claw
  ModularTegustation/Tegusounds/claw/r_prep.ogg
  ModularTegustation/Tegusounds/claw/stab.ogg
  ModularTegustation/Tegusounds/claw/w_fin.ogg
  ModularTegustation/Tegusounds/claw/w_portal.ogg
  ModularTegustation/Tegusounds/claw/w_slashes.ogg
  code/__HELPERS/unsorted.dm
  code/game/objects/items/ego_weapons/non_abnormality/blue_sicko.dm
  code/game/objects/items/ego_weapons/non_abnormality/purple_tear.dm
  code/game/objects/items/ego_weapons/ordeal.dm
  code/modules/antagonists/head/claw.dm
  code/modules/antagonists/wizard/arbiter.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/clothing/suits/ego_gear/ordeal.dm
  code/modules/clothing/under/clerksuits.dm
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Code improvement, Feature

#1687 Dying No Longer Resets Timer While Insane
  code/datums/mind.dm
Labels: Fix

#1689 Fixes Pygmalion having a 20% damage resistance to everything
  code/modules/mob/living/simple_animal/abnormality/waw/pygmalion.dm
Labels: Fix

#1676 White ordeals tweak
  ModularTegustation/tegu_mobs/the_claw.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
Labels: Balance

#1643 Minor Workshop update
  ModularTegustation/Teguicons/workshop.dmi
  ModularTegustation/tegu_items/workshop/_templates.dm
  ModularTegustation/tegu_items/workshop/templates/axe.dm
  ModularTegustation/tegu_items/workshop/templates/basic.dm
  ModularTegustation/tegu_items/workshop/templates/knife.dm
  lobotomy-corp13.dme
Labels: Balance, Side content

#1673 Updates some abnormalities
  _maps/map_files/generic/CentCom.dmm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/shelter.dm
  code/modules/mob/living/simple_animal/abnormality/teth/book.dm
  code/modules/mob/living/simple_animal/abnormality/teth/pale_horse.dm
  code/modules/paperwork/records/info/teth.dm
Labels: Balance

#1690 Swaps Pharaoh Suit Sprites
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
Labels: Sprites

#1693 Updates W-Corp L2A Equipment
  code/modules/jobs/job_types/wcorp/wcorprecon.dm
Labels: Tweak, Side content

#1699 Creates shrimps.dm in ordeals folder and adds shrimp rifleman
  code/modules/mob/living/simple_animal/hostile/ordeal/shrimps.dm
Labels: Side content

#1691 Adds Wcorp round inbetween healing effects
  code/game/gamemodes/management/event/combat.dm
Labels: Tweak, Side content

#1692 Adds third w-corp enemy type
  ModularTegustation/tegu_items/wcorp/enemies.dm
  code/game/gamemodes/management/event/combat.dm
Labels: Expansion

#1695 Representative Update
  ModularTegustation/tegu_items/representative/console.dm
  ModularTegustation/tegu_items/representative/items/kcorp.dm
  ModularTegustation/tegu_items/representative/outfits.dm
  ModularTegustation/tegu_items/representative/research.dm
  ModularTegustation/tegu_items/representative/research/kcorp.dm
  ModularTegustation/tegu_items/representative/research/rcorp.dm
  ModularTegustation/tegu_items/representative/spawners.dm
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
  code/game/objects/items/ego_weapons/non_abnormality/kcorp.dm
  code/modules/jobs/job_types/trusted_players/representative.dm
  sound/weapons/fixer/generic/kcorp1.ogg
Labels: Expansion

#1698 Adds R-corp map "Nest"
  ModularTegustation/tegu_items/rcorp/random_maps.dm
  _maps/RandomRooms/rcorp/facility/nest.dmm
Labels: Mapping, Side content

#1701 Cades are no longer structurally strong enough to support a wall
  code/game/machinery/deployable.dm
Labels: Tweak, Removal

#1694 Shi armor/ Inhands fix
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
Labels: Fix

#1702 Adds buff shrimps
  code/modules/mob/living/simple_animal/hostile/ordeal/shrimps.dm
Labels: Tweak

#1644 Facility upgrades
  ModularTegustation/tegu_items/gadgets/manager_bullets.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/facility_upgrades.dm
  code/__DEFINES/lobotomy_corp.dm
  code/__HELPERS/lobotomy_corp.dm
  code/__HELPERS/priority_announce.dm
  code/controllers/subsystem/abnormality_queue.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/controllers/subsystem/persistence.dm
  code/datums/abnormality/datum/abnormality.dm
  code/datums/facility_upgrade.dm
  code/game/machinery/computer/abnormality_auxilary.dm
  code/game/machinery/computer/abnormality_auxiliary.dm
  code/game/machinery/computer/abnormality_logs.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/machinery/computer/camera_advanced.dm
  code/game/machinery/computer/crew.dm
  code/game/machinery/computer/manager_camera.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/clerks/hypo/hypo.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/crying_children.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/he/galaxy_child.dm
  code/modules/mob/living/simple_animal/abnormality/teth/beauty_beast.dm
  code/modules/mob/living/simple_animal/abnormality/teth/meat_lantern.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
  code/modules/mob/living/simple_animal/abnormality/teth/spider_bud.dm
  code/modules/mob/living/simple_animal/abnormality/waw/fire_bird.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/suppressions/_core_suppression.dm
  code/modules/suppressions/command.dm
  code/modules/suppressions/control.dm
  code/modules/suppressions/extraction.dm
  code/modules/suppressions/information.dm
  code/modules/suppressions/keter.dm
  code/modules/suppressions/records.dm
  code/modules/suppressions/safety.dm
  code/modules/suppressions/training.dm
  code/modules/suppressions/welfare.dm
  code/modules/suppressions/white_ordeals.dm
  lobotomy-corp13.dme
Labels: Code improvement, Feature, Tweak

#1708 New Samjo Plushie
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Feature

#1715 Pygmalion Doesn't Block Humans when Friendly
  code/modules/mob/living/simple_animal/abnormality/waw/pygmalion.dm
Labels: Tweak

#1718 Warpco maps but maybe I dont squish it into someone elses PR this time
  ModularTegustation/tegu_items/wcorp/mapping.dm
  _maps/RandomRooms/wcorp/Templates copy.dmm
  _maps/RandomRooms/wcorp/kitchen.dmm
  _maps/RandomRooms/wcorp/library.dmm
  _maps/RandomRooms/wcorp/lounge.dmm
  _maps/RandomRooms/wcorp/storage1.dmm
Labels: Mapping, Side content

#1714 Experimental Temperance update
  code/__DEFINES/attributes.dm
  code/datums/abnormality/datum/abnormality.dm
Labels: Balance

#1554 AI Targeting Overhaul
  code/__DEFINES/mobs.dm
  code/__HELPERS/_lists.dm
  code/controllers/subsystem/idlenpcpool.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Code improvement, Feature

#1626 EO Text Adventure
  ModularTegustation/lc13_adventuredatum.dm
  ModularTegustation/lc13_machinery.dm
  lobotomy-corp13.dme
Labels: Feature

#1728 Rcorp Assorted Changes (+ Realization engine)
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/tegu_items/rcorp/landmarks.dm
  ModularTegustation/tegu_items/rcorp/objective.dm
  code/game/objects/effects/abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/mob/living/simple_animal/abnormality/he/wayward_passenger.dm
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
  code/modules/mob/living/simple_animal/abnormality/waw/alriune.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/fire_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/luna.dm
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Code improvement, Sprites, Expansion, Side content

#1653 Adds steam transport machine
  ModularTegustation/Teguicons/64x64.dmi
  code/game/objects/items/ego_weapons/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/steam_transport_machine.dm
  code/modules/paperwork/records/info/he.dm
  lobotomy-corp13.dme
  sound/abnormalities/steam/attack.ogg
  sound/abnormalities/steam/exhale.ogg
  sound/abnormalities/steam/steambreak.ogg
  sound/abnormalities/steam/steamfire.ogg
  sound/abnormalities/steam/step.ogg
Labels: Abnormality

#1732 Gamemode Weights
  code/controllers/subsystem/abnormality_queue.dm
  code/controllers/subsystem/persistence.dm
  code/game/gamemodes/management/management.dm
Labels: Tweak

#1721 PE Runoff
  ModularTegustation/tegu_items/refinery/sales.dm
Labels: Tweak

#1720 Adds an option to generate typecaches as zebras, a TG mirror
  code/__HELPERS/_lists.dm
  code/datums/components/chasm.dm
  code/datums/components/fantasy/suffixes.dm
  code/datums/components/storage/concrete/pockets.dm
  code/datums/components/thermite.dm
  code/datums/emotes.dm
  code/datums/helper_datums/teleport.dm
  code/datums/mutations/holy_mutation/honorbound.dm
  code/game/machinery/gulag_teleporter.dm
  code/game/machinery/iv_drip.dm
  code/game/machinery/recharger.dm
  code/game/objects/effects/effect_system/effects_foam.dm
  code/game/objects/effects/glowshroom.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/devices/electroadaptive_pseudocircuit.dm
  code/game/objects/items/weaponry.dm
  code/game/objects/structures/traps.dm
  code/game/turfs/open/dirtystation.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/cult/cult_structures.dm
  code/modules/antagonists/eldritch_cult/eldritch_book.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
  code/modules/antagonists/morph/morph.dm
  code/modules/cargo/bounties/assistant.dm
  code/modules/cargo/bounties/botany.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/cargo/bounties/engineering.dm
  code/modules/cargo/bounties/item.dm
  code/modules/cargo/bounties/mech.dm
  code/modules/cargo/bounties/medical.dm
  code/modules/cargo/bounties/mining.dm
  code/modules/cargo/bounties/science.dm
  code/modules/cargo/bounties/security.dm
  code/modules/cargo/bounties/slime.dm
  code/modules/cargo/bounties/special.dm
  code/modules/cargo/exports.dm
  code/modules/events/anomaly.dm
  code/modules/events/sentience.dm
  code/modules/events/stray_cargo.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/mining/aux_base.dm
  code/modules/power/tesla/energy_ball.dm
Labels: Code improvement

#1722 Cleanup and belt buff
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/_lists.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
Labels: Balance, Code improvement

#1729 Adds ordeal text and fonts
  code/modules/ordeals/_ordeal.dm
  code/modules/ordeals/_ordealtypes.dm
  code/modules/ordeals/amber_ordeals.dm
  code/modules/ordeals/crimson_ordeals.dm
  code/modules/ordeals/gold_ordeals.dm
  code/modules/ordeals/green_ordeals.dm
  code/modules/ordeals/indigo_ordeals.dm
  code/modules/ordeals/misc_ordeals.dm
  code/modules/ordeals/steel_ordeals.dm
  code/modules/ordeals/violet_ordeals.dm
  code/modules/ordeals/white_ordeals.dm
  icons/fonts/BMDOHYEON.ttf
  icons/fonts/baskvl.ttf
  icons/fonts/font.dm
  lobotomy-corp13.dme
Labels: Feature

#1740 NO SKATEBOARDING, NO SCOOTERS, NO PARKING PAST 6PM
  code/datums/components/crafting/recipes.dm
Labels: Fix

#1742 N-Corp Commander armor icon fix
  icons/obj/clothing/ego_gear/lc13_armor.dmi
Labels: Fix, Sprites

#1741 Sloshing Sprite Update
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
Labels: Sprites

#1737 Gift file winter cleanup
  code/modules/mob/living/carbon/human/ego_gifts.dm
Labels: Code improvement

#1739 Naked Nest Math Fix
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
Labels: Fix

#1743 Removes Placeholder Abno from Spawning in Queue, my B.
  code/controllers/subsystem/persistence.dm
Labels: Fix

#1696 Fixes library lighting
  _maps/map_files/Library/floor_art.dmm
  _maps/map_files/Library/floor_history.dmm
  _maps/map_files/Library/floor_language.dmm
  _maps/map_files/Library/floor_literature.dmm
  _maps/map_files/Library/floor_naturalsci.dmm
  _maps/map_files/Library/floor_philosophy.dmm
  _maps/map_files/Library/floor_religion.dmm
  _maps/map_files/Library/floor_socialsci.dmm
  _maps/map_files/Library/floor_techsci.dmm
Labels: Mapping, Side content

#1747 Particle Emitter Fadeout Proc
  code/game/objects/effects/particles/particles.dm
Labels: Code improvement, Tweak

#1749 Rose Sign's roses no longer fit in bodybags
  code/modules/mob/living/simple_animal/abnormality/waw/rose_sign.dm
Labels: Fix

#1746 Small Fragment visual update
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/game/objects/effects/particles/particles.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fragment.dm
Labels: Tweak, Sprites

#1706 Experimental Changes: 2
  ModularTegustation/tegu_items/representative/research/lcorp.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/controllers/subsystem/abnormality_queue.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/game/gamemodes/management/management.dm
  code/game/objects/effects/spawners/abnormality_room.dm
  code/modules/jobs/job_types/command.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  code/modules/ordeals/_ordeal.dm
Labels: Code improvement, Feature, Tweak

#1659 Gives clerks a random item on spawn.
  code/modules/jobs/job_types/assistant.dm
Labels: Tweak

#1738 Health calculation fixes and Red damage spread
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance

#1744 Adds Loos weapon black damage scaling
  code/game/objects/items/ego_weapons/aleph.dm
Labels: Fix

#1751 Fixes Fragment Runtime
  code/modules/mob/living/simple_animal/abnormality/teth/fragment.dm
Labels: Fix

#1750 Gives Error Messages to Vitals Visualizer Gadget
  ModularTegustation/tegu_items/gadgets/powered.dm
Labels: Tweak

#1754 Fixes charge weapons
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/non_abnormality/_charge.dm
  code/game/objects/items/ego_weapons/subtype/charge.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
Labels: Fix

#1752 Fixes book's paper abno health
  code/modules/mob/living/simple_animal/abnormality/teth/book.dm
Labels: Fix

#1745 Drifiting Fox Abnormality; Take 3.
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/96x96.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/drifting_fox.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/drifting_fox/fox_aoe_sound.ogg
  sound/abnormalities/drifting_fox/fox_death_sound.ogg
  sound/abnormalities/drifting_fox/fox_melee_sound.ogg
Labels: Abnormality

#1755 Rebalances Faelantern E.G.O.
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
Labels: Balance

#1759 Updates Guilt sprite
  ModularTegustation/Teguicons/tegu_effects.dmi
Labels: Sprites

#1760 Update Zayin Spans and Sunset Traveler
  code/modules/mob/living/simple_animal/abnormality/zayin/bald.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/blubbering_toad.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fallen_amurdad.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/pile_of_mail.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/sunset_traveller.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
Labels: Tweak, Fix

#1765 Fixes courage E.G.O.
  code/datums/abnormality/_ego_datum/he.dm
  icons/obj/ego_weapons.dmi
Labels: Fix

#1733 Insanity Update
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/ai/sanity/sanityloss_behaviors.dm
  code/modules/projectiles/ammunition/_ammunition.dm
Labels: Tweak

#1763 Clerkbot Change
  ModularTegustation/tegu_items/gadgets/powered.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/representative/console.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/modules/jobs/job_types/assistant.dm
Labels: Tweak

#1650 Adds Faelantern
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/faelantern.dm
  code/modules/paperwork/records/info/teth.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  lobotomy-corp13.dme
  sound/abnormalities/faelantern/faelantern_breach.ogg
  sound/abnormalities/faelantern/faelantern_giggle.ogg
  sound/abnormalities/faelantern/faelantern_uproot.ogg
Labels: Abnormality

#1764 EGO additions remake
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/mob/living/simple_animal/abnormality/he/highway_devotee.dm
  code/modules/mob/living/simple_animal/abnormality/teth/skin_prophet.dm
  icons/mob/inhands/96x96_lefthand.dmi
  icons/mob/inhands/96x96_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
Labels: Sprites, Expansion

#1770 Cleared cores info
  code/_globalvars/misc.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Tweak

#1757 Allows ghosts to drag-click themselfes onto abnormalities to possess them. Ghosting no longer bricks abnormalities -- The PR that all event players needed
  ModularTegustation/misc_procs.dm
  code/modules/mob/dead/observer/observer.dm
  lobotomy-corp13.dme
Labels: Feature

#1710 Wcorp carriage pack
  _maps/RandomRooms/wcorp/stage.dmm
  _maps/RandomRooms/wcorp/zoo.dmm
Labels: Mapping, Side content

#1727 Adds Rats Simplemobs (but not dumb)
  ModularTegustation/Teguicons/tegumobs.dmi
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
  code/game/objects/items/ego_weapons/non_abnormality/rats.dm
  lobotomy-corp13.dme
Labels: Expansion, Side content

#1771 Abnormality Information Scanner
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/modules/jobs/job_types/agent.dm
Labels: Tweak
