Repository vlggms/lobotomy-corp13, pull requests merged in 2023-11, with the labels that each got.

#1593 Fix Unanchored Nets
  ModularTegustation/fishing/code/fishing_items/fishing_net.dm
Labels: Fix

#1594 Lor13 Boss Raids.
  code/controllers/subsystem/city_events.dm
Labels: Expansion, Side content

#1592 EMAIS Radial Menu
  code/game/objects/items/clerks/hypo/hypo.dm
Labels: Tweak

#1596 Fix Out of Stock wording on vendors
  tgui/packages/tgui/interfaces/Vending.js
Labels: Tweak

#1597 Frames and Posters now work on Indestructable Walls
  code/game/turfs/closed/_closed.dm
Labels: Tweak

#1591 RAK Refactor
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/game/machinery/regenerator.dm
  icons/obj/tools.dmi
Labels: Code improvement

#1566 Updates the drowned sisters and penitent girl
  code/modules/mob/living/simple_animal/abnormality/teth/drowned_sisters.dm
  code/modules/mob/living/simple_animal/abnormality/teth/penitent_girl.dm
  code/modules/paperwork/records/info/teth.dm
  icons/effects/effects.dmi
Labels: Tweak

#1588 Deep Scanner Upgrade
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/__HELPERS/mobs.dm
  code/modules/mob/living/simple_animal/dc_changes.dm
Labels: Balance

#1587 Manager Console Examine Update
  code/game/machinery/computer/manager_camera.dm
Labels: Fix

#1411 New Job: Carnival
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/tegu_items/associations/machines.dm
  ModularTegustation/tegu_items/associations/vending.dm
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
  _maps/map_files/Event/city.dmm
  code/datums/components/butchering.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/silkweave.dm
  code/game/objects/items/ego_weapons/non_abnormality/carnival.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/stacks/sheets/silk.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/carnival.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/woven_armor.dm
  code/modules/jobs/job_types/city/carnival.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/library.dmi
  icons/obj/stack_objects.dmi
  lobotomy-corp13.dme
Labels: Feature, Tweak, Mapping, Side content

#1601 De-mystifies Red Queen's records page
  code/modules/paperwork/records/info/he.dm
Labels: Writing

#1590 Vitals Projector and Enkephalin Injector Buff
  ModularTegustation/tegu_items/gadgets/powered.dm
Labels: Balance

#1599 Makes it possible to give plushies unique pet messages - Ayin did nothing wrong
  code/game/objects/items/plushes.dm
Labels: Writing

#1604 It's cold out there. Better hoagie down.
  strings/hallucination.json
Labels: Writing

#1425 New reps
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_items/associations/items.dm
  ModularTegustation/tegu_items/associations/vending.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_items/representative/console.dm
  ModularTegustation/tegu_items/representative/items/kcorp.dm
  ModularTegustation/tegu_items/representative/items/lcorp.dm
  ModularTegustation/tegu_items/representative/items/ncorp.dm
  ModularTegustation/tegu_items/representative/items/pcorp.dm
  ModularTegustation/tegu_items/representative/research.dm
  ModularTegustation/tegu_items/representative/research/kcorp.dm
  ModularTegustation/tegu_items/representative/research/lcorp.dm
  ModularTegustation/tegu_items/representative/research/ncorp.dm
  ModularTegustation/tegu_items/representative/research/pcorp.dm
  ModularTegustation/tegu_items/representative/research/rcorp.dm
  ModularTegustation/tegu_items/representative/research/wcorp.dm
  code/modules/clothing/under/clerksuits.dm
  code/modules/jobs/job_types/trusted_players/representative.dm
  icons/mob/clothing/ego_gear/under.dmi
  icons/obj/clothing/ego_gear/lcuniform.dmi
  lobotomy-corp13.dme
Labels: Expansion

#1605 Understanding Slight Refactor
  ModularTegustation/tegu_items/representative/items/lcorp.dm
  code/datums/abnormality/datum/abnormality.dm
Labels: Code improvement, Fix

#1487 Adds Sign of Roses
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/96x96.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/rose_sign.dm
  code/modules/paperwork/records/info/waw.dm
  icons/effects/64x64.dmi
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/rosesign/rose_summon.ogg
  sound/abnormalities/rosesign/vinegrab.ogg
  sound/abnormalities/rosesign/vinegrab_prep.ogg
Labels: Abnormality

#1607 Red shoes no longer raises your prudence permanently
  code/modules/mob/living/simple_animal/abnormality/he/red_shoes.dm
Labels: Fix

#1608 Artist 1984
  code/datums/quirks/neutral.dm
Labels: Balance, Removal, Side content

#1611 Increases WCCA's attachment and repression work rates
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
Labels: Balance

#1606 RBA buffs
  code/modules/mob/living/simple_animal/abnormality/teth/redblooded.dm
Labels: Balance

#1595 Wellcheers Glowup
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
Labels: Sprites

#1435 Adds distorted form
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/64x96.dmi
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/datum/abnormality.dm
  code/datums/looping_sounds/abnormalities.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/waw/clock.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/misc.dm
  code/modules/paperwork/records/info/aleph.dm
  icons/effects/96x96.dmi
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/obj/computer.dmi
  lobotomy-corp13.dme
  sound/abnormalities/distortedform/DF_soundloop.ogg
  sound/abnormalities/distortedform/metal_impact.ogg
  sound/abnormalities/distortedform/screech1.ogg
  sound/abnormalities/distortedform/screech2.ogg
  sound/abnormalities/distortedform/screech3.ogg
  sound/abnormalities/distortedform/screech4.ogg
Labels: Abnormality

#1613 Joke ego tweak
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/joke.dm
  icons/effects/96x96.dmi
Labels: Feature

#1616 Codes out Duplicate Abno Document Codes
  code/modules/paperwork/records/info/teth.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/abno_code.dm
Labels: Code improvement

#1618 Fixing Linter issue with Message Hallucination
  code/modules/flufftext/Hallucination.dm
Labels: Fix

#1623 Wrist slap to mockery
  code/game/objects/items/ego_weapons/aleph.dm
Labels: Balance

#1622 Adding Type C weapons as well as fixing Quantum pad and L2 Research.
  ModularTegustation/tegu_items/representative/research/wcorp.dm
Labels: Fix

#1621 Updates La Luna, Pinnochio for Rcorp and playables, gives minions NV on Rcorp AND moves CheckCombat to simple_animal.
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/mob/living/simple_animal/abnormality/waw/luna.dm
  code/modules/mob/living/simple_animal/distortion/_distortion.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Tweak, Side content

#1576 adds nobody is
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/64x96.dmi
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/projectiles/projectile/beams.dm
  icons/effects/effects.dmi
  icons/obj/projectiles_impact.dmi
  icons/obj/projectiles_muzzle.dmi
  icons/obj/projectiles_tracer.dmi
  lobotomy-corp13.dme
  sound/abnormalities/nobodyis/strangle.ogg
Labels: Abnormality

#1627 Removes a superfluous and outdated EGO
  code/modules/clothing/suits/ego_gear/waw.dm
Labels: Removal

#1620 [QOL & Roleplay addition] Adds text emphasis and custom say emotes, both on radio and without it
  code/__DEFINES/say.dm
  code/datums/chatmessage.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/say.dm
  code/modules/mob/living/living_say.dm
  code/modules/mob/mob_say.dm
Labels: Feature

#1507 Create Vile Workshop Mod
  ModularTegustation/Teguicons/lc13icons.dmi
  ModularTegustation/Teguicons/workshop.dmi
  ModularTegustation/tegu_items/workshop/_templates.dm
  ModularTegustation/tegu_items/workshop/mods/offbeat.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/components/corruption_balance.dm
  code/modules/spells/ability_types/component_ability.dm
  code/modules/spells/ability_types/misc_ability.dm
  icons/mob/actions/actions_ability.dmi
  lobotomy-corp13.dme
Labels: Feature

#1493 Map Wall Decorations + Door/Step Triggered Mobspawns + 2 New Rooms
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/lc13_structures.dmi
  ModularTegustation/lc13_effects.dm
  ModularTegustation/lc13_machinery.dm
  ModularTegustation/lc13_spawners.dm
  ModularTegustation/lc13_structures.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/west.dm
  _maps/RandomRooms/backstreets/medium_west/lcorp_office.dmm
  lobotomy-corp13.dme
Labels: Feature, Mapping, Side content

#1578 The Great Golden Apple Nerf
  ModularTegustation/Teguicons/96x48.dmi
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/mob/living/simple_animal/abnormality/he/wayward_passenger.dm
  sound/abnormalities/goldenapple/False_Attack3.ogg
Labels: Balance

#1488 !!!!!ඞඞඞ The SUS PR ඞඞඞ!!!!!
  ModularTegustation/tegu_clothes_code/tegu_clothing.dm
  _maps/map_files/Event/skeld.dmm
  _maps/skeld.json
  code/controllers/subsystem/maptype.dm
  code/controllers/subsystem/ticker.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  config/maps.txt
Labels: Feature, Mapping

#1610 Blessings reworked AGAIN
  ModularTegustation/Teguicons/48x48.dmi
  code/modules/mob/living/simple_animal/abnormality/he/puss_in_boots.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Balance, Expansion

#1631 [MDB IGNORE] RNGs the backstreets
  ModularTegustation/Teguicons/refiner.dmi
  ModularTegustation/tegu_items/associations/cityspawners.dm
  ModularTegustation/tegu_items/associations/machines.dm
  ModularTegustation/tegu_items/backstreets/templates.dm
  ModularTegustation/tegu_items/refinery/crates/_crate.dm
  ModularTegustation/tegu_items/refinery/crates/misc.dm
  ModularTegustation/tegu_items/refinery/crates/workshop.dm
  _maps/RandomRooms/backstreetlayout/lcorp.dmm
  _maps/RandomRooms/backstreetlayout/standard.dmm
  _maps/RandomRooms/backstreets/bossroom/gcorp.dmm
  _maps/RandomRooms/backstreets/bossroom/jacques.dmm
  _maps/RandomRooms/backstreets/bossroom/robot.dmm
  _maps/RandomRooms/backstreets/connector/courtyard.dmm
  _maps/RandomRooms/backstreets/connector/jumpscare.dmm
  _maps/RandomRooms/backstreets/large_north/apartment_lna.dmm
  _maps/RandomRooms/backstreets/large_north/robot_lna.dmm
  _maps/RandomRooms/backstreets/large_south/apartment_lsa.dmm
  _maps/RandomRooms/backstreets/large_south/apartment_lsb.dmm
  _maps/RandomRooms/backstreets/large_south/prosthetic_factory.dmm
  _maps/RandomRooms/backstreets/large_south/robot_castle.dmm
  _maps/RandomRooms/backstreets/medium_east/apartment_mea.dmm
  _maps/RandomRooms/backstreets/medium_east/arcade_me.dmm
  _maps/RandomRooms/backstreets/medium_north/office_bloody.dmm
  _maps/RandomRooms/backstreets/medium_north/workshop_mn.dmm
  _maps/RandomRooms/backstreets/medium_south/bedroom_msa.dmm
  _maps/RandomRooms/backstreets/medium_south/eyes_temple.dmm
  _maps/RandomRooms/backstreets/medium_west/butcher_medium.dmm
  _maps/RandomRooms/backstreets/medium_west/lcorp_office.dmm
  _maps/RandomRooms/backstreets/medium_west/office_mwa.dmm
  _maps/RandomRooms/backstreets/medium_west/rat_mess.dmm
  _maps/RandomRooms/backstreets/medium_west/sweeper_pen.dmm
  _maps/RandomRooms/backstreets/small_north/coffee_break.dmm
  _maps/RandomRooms/backstreets/small_north/smallarmory.dmm
  _maps/RandomRooms/backstreets/small_south/jumpscare_closet.dmm
  _maps/map_files/Event/city.dmm
  code/controllers/subsystem/mapping.dm
  code/game/objects/effects/spawners/roomspawners.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/_ordeal.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Expansion, Side content

#1634 Nano-Transen Icon Replacement
  tgui/packages/tgui/assets/bg-nanotrasen.svg
Labels: Tweak

#1632 New Gamemodes
  code/game/gamemodes/management/management.dm
Labels: Tweak

#1641 Makes Ordeal Fixers patrol (not you Pale)
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
Labels: Balance

#1628 Buffs 2 Reps slightly. (W-Corp and P-Corp)
  ModularTegustation/tegu_items/representative/items/pcorp.dm
  ModularTegustation/tegu_items/representative/research/kcorp.dm
  ModularTegustation/tegu_items/representative/research/pcorp.dm
  ModularTegustation/tegu_items/representative/research/wcorp.dm
  ModularTegustation/tegu_items/representative/spawners.dm
  code/game/objects/items/ego_weapons/_lists.dm
  code/game/objects/items/storage/belt.dm
  icons/obj/storage.dmi
  lobotomy-corp13.dme
Labels: Balance, Code improvement, Tweak

#1625 Reworks manager shields, fixes welf reward & changes how info core works
  ModularTegustation/tegu_items/gadgets/manager_bullets.dm
  code/__DEFINES/dcs/signals.dm
  code/__HELPERS/priority_announce.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/suppressions/information.dm
  code/modules/suppressions/welfare.dm
Labels: Code improvement, Tweak

#1564 ReSummons Hammer
  code/modules/mob/living/simple_animal/abnormality/zayin/hammer_light.dm
Labels: Fix

#1635 Adds new backstreets layout map.
  _maps/RandomRooms/backstreetlayout/dungeon_backstreets.dmm
Labels: Tweak

#1637 Alpha & Lambda Fixes
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
Labels: Fix, Mapping

#1520 General Bee and Lady Facing the wall Icon and Reward Tweaks
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/48x96.dmi
  code/modules/mob/living/simple_animal/abnormality/teth/lady_facing_the_wall.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
Labels: Code improvement, Tweak

#1270 Ebony Queen Changes and Improvements
  ModularTegustation/Teguicons/64x96.dmi
  ModularTegustation/Teguicons/tegu_effects32x48.dmi
  code/__HELPERS/mobs.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/actions/actions_abnormality.dmi
Labels: Code improvement, Tweak

#1636 Fixes nameless fetus
  code/modules/mob/living/simple_animal/abnormality/he/nameless_fetus.dm
Labels: Fix

#1633 Adds Ego
  ModularTegustation/Teguicons/32x32.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/eris.dm
  code/modules/mob/living/simple_animal/abnormality/he/highway_devotee.dm
  code/modules/mob/living/simple_animal/abnormality/he/nameless_fetus.dm
  code/modules/mob/living/simple_animal/abnormality/he/will_you_play.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cleaner.dm
  code/modules/mob/living/simple_animal/abnormality/teth/skin_prophet.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/oceanwaves.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/sunset_traveller.dm
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/ego_weapons.dmi
Labels: Sprites, Expansion

#1652 Violet midnight cooldowns are randomized further
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
Labels: Balance

#1655 Makes The Fish Market Indestructable
  ModularTegustation/fishing/code/fish_market.dm
Labels: Tweak

#1654 Fixes some bugs
  code/game/objects/items/ego_weapons/non_abnormality/jcorp.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Writing

#1656 Child of the galaxy overlay and runtime fix
  ModularTegustation/Teguicons/tegu_effects32x48.dmi
  code/modules/mob/living/simple_animal/abnormality/he/galaxy_child.dm
Labels: Fix

#1658 Fixes some Mismatched Items in the Representative Console
  ModularTegustation/tegu_items/representative/console.dm
Labels: Fix

#1657 we do a lil bit of code cleaning on LC13 computers
  code/game/machinery/computer/abnormality_archive.dm
  code/game/machinery/computer/abnormality_auxilary.dm
  code/game/machinery/computer/abnormality_ego.dm
  code/game/machinery/computer/abnormality_logs.dm
  code/game/machinery/computer/abnormality_queue.dm
  code/game/machinery/computer/abnormality_work.dm
Labels: Code improvement, Tweak

#1663 Central Command core suppression
  code/controllers/subsystem/lobotomy_corp.dm
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/manager_camera.dm
  code/modules/suppressions/command.dm
  code/modules/suppressions/control.dm
  lobotomy-corp13.dme
Labels: Expansion

#1664 Fixes DamageEffect
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Fix

#1665 Nothing There stops the disguise soundloop on breach
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
Labels: Fix

#1666 Records core suppression
  code/__DEFINES/dcs/signals.dm
  code/_globalvars/lists/objects.dm
  code/_onclick/click.dm
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/manager_camera.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/city/HHPP.dm
  code/modules/jobs/job_types/city/doctor.dm
  code/modules/jobs/job_types/city/fixer/east.dm
  code/modules/jobs/job_types/city/fixer/north.dm
  code/modules/jobs/job_types/city/workshop.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/manager.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
  code/modules/suppressions/records.dm
  lobotomy-corp13.dme
  sound/effects/hokma_meltdown.ogg
  sound/effects/hokma_meltdown_short.ogg
Labels: Tweak

#1662 Adds Library area types and replaces library rooms with corresponding types
  _maps/map_files/Library/floor_art.dmm
  _maps/map_files/Library/floor_history.dmm
  _maps/map_files/Library/floor_language.dmm
  _maps/map_files/Library/floor_literature.dmm
  _maps/map_files/Library/floor_naturalsci.dmm
  _maps/map_files/Library/floor_philosophy.dmm
  _maps/map_files/Library/floor_religion.dmm
  _maps/map_files/Library/floor_socialsci.dmm
  _maps/map_files/Library/floor_techsci.dmm
  code/game/area/areas/lobotomy_corp.dm
Labels: Tweak

#1660 Buffs(nerfs?) gold noon
  ModularTegustation/Teguicons/32x64.dmi
  code/modules/mob/living/simple_animal/hostile/ordeal/gold.dm
Labels: Balance, Sprites

#1649 Shot glass and drink dispenser sprite fix
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  icons/obj/reagentfillings.dmi
Labels: Fix

#1638 LoR13 Skill Books
  ModularTegustation/tegu_items/associations/vending.dm
  code/game/objects/items/fixerskills/level1.dm
  code/game/objects/items/fixerskills/level2.dm
  code/game/objects/items/fixerskills/level3.dm
  code/game/objects/items/fixerskills/level4.dm
  code/game/objects/items/fixerskills/no_level.dm
  code/modules/jobs/job_types/city/civilian.dm
  code/modules/jobs/job_types/city/scavenger.dm
  icons/hud/screen_skills.dmi
  lobotomy-corp13.dme
Labels: Feature, Side content

#1589 Warning level buffs and debuffs
  ModularTegustation/Teguicons/status_sprites.dmi
  code/controllers/subsystem/lobotomy_events.dm
  code/modules/security_levels/security_levels.dm
Labels: Balance, Expansion
