Repository vlggms/lobotomy-corp13, pull requests merged in 2023-04, with the labels that each got.

#785 Various abnormality fixes
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/mob/living/simple_animal/abnormality/he/jangsan.dm
  code/modules/mob/living/simple_animal/abnormality/teth/beanstalk.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Balance, Code improvement, Tweak, Fix

#620 New Gadgets
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_items/lc13unique_items.dm
  code/game/machinery/computer/extraction_cargo.dm
Labels: Tweak

#796 Fixes head of god ability
  code/modules/spells/ability_types/realized.dm
Labels: Fix

#779 Most abnormalities now share faction
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/he/jangsan.dm
  code/modules/mob/living/simple_animal/abnormality/he/scarecrow.dm
  code/modules/mob/living/simple_animal/abnormality/he/schadenfreude.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
Labels: Balance

#712 Work speed and work chance overrides
  code/game/machinery/computer/abnormality_work.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/he/schadenfreude.dm
Labels: Tweak

#764 Adds 3 new tool abnormalities
  ModularTegustation/Teguicons/toolabnormalities.dmi
  code/__DEFINES/dcs/signals.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/theonite_slab.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/vivavoce.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/dr_jekyll.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/skin.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/paperwork/records/info/tools.dm
  lobotomy-corp13.dme
  sound/abnormalities/vivavoce/doorknock.ogg
Labels: Feature, Test Merge Candidate

#551 Lobotomy Corp UI Theme
  code/_onclick/hud/hud.dm
  icons/hud/screen_lobotomy.dmi
Labels: Feature

#810 Clown meat
  code/game/objects/items/food/meat.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson.dm
  icons/obj/food/food.dmi
Labels: Tweak

#770 [COMMISSION] A Quiet Day
  ModularTegustation/Teguicons/48x48.dmi
  code/datums/abnormality/_ego_datum/zayin.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/quiet_day.dm
  code/modules/paperwork/records/info/zayin.dm
  code/modules/projectiles/ammunition/ego_ammunition/zayin.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  code/modules/projectiles/projectile/ego_bullets/zayin.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#815 road home no longer leaves the status effect after death
  code/modules/mob/living/simple_animal/abnormality/he/road_home.dm
Labels: Fix

#806 Abnormality re-designation
  code/modules/paperwork/records/info/he.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Tweak

#727 Attempts to remove botany exploits
  code/datums/materials/basemats.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/hydroponics/grown/ambrosia.dm
  code/modules/hydroponics/grown/banana.dm
  code/modules/hydroponics/grown/random.dm
  code/modules/hydroponics/grown/tomato.dm
  code/modules/hydroponics/plant_genes.dm
  lobotomy-corp13.dme
Labels: Fix

#784 Adds PE Refining
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/Teguicons/lc13icons.dmi
  ModularTegustation/Teguicons/refiner.dmi
  ModularTegustation/tegu_items/lc13/refinery/_spawners.dm
  ModularTegustation/tegu_items/lc13/refinery/crates.dm
  ModularTegustation/tegu_items/lc13/refinery/pebox.dm
  ModularTegustation/tegu_items/lc13/refinery/refinery.dm
  ModularTegustation/tegu_items/lc13/refinery/sales.dm
  ModularTegustation/tegu_items/lc13/refinery/tools.dm
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  code/game/machinery/computer/extraction_cargo.dm
  code/game/objects/items/ego_weapons/non_abnormality/_cityweapons.dm
  code/game/objects/items/ego_weapons/non_abnormality/kcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_ego.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_sinner.dm
  code/game/objects/items/ego_weapons/non_abnormality/ncorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/rcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/wcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/zwei.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/ego_weapons/tutorial.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/ego_gear/special.dm
  code/modules/clothing/under/clerksuits.dm
  code/modules/clothing/under/limbus_suits.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/clothing/ego_gear/under.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/lcuniform.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/clothing/under/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
Labels: Feature, Mapping

#692 You Must Become Strong
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/96x64.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/human.dmi
  icons/mob/human_parts_greyscale.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Feature

#804 Parry Code Improvement
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/non_abnormality/kcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_sinner.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
Labels: Code improvement

#818 You Strong part fix
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
Labels: Fix

#807 Thunderbird Code Cleanup + New Sprites
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Teguicons/64x64.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
Labels: Code improvement, Tweak

#680 Servant of wrath
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/96x64.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
  sound/abnormalities/wrath_servant/big_smash1.ogg
  sound/abnormalities/wrath_servant/big_smash2.ogg
  sound/abnormalities/wrath_servant/big_smash3.ogg
  sound/abnormalities/wrath_servant/enrage.ogg
  sound/abnormalities/wrath_servant/hermit_attack.ogg
  sound/abnormalities/wrath_servant/hermit_attack_hard.ogg
  sound/abnormalities/wrath_servant/hermit_magic.ogg
  sound/abnormalities/wrath_servant/small_smash1.ogg
  sound/abnormalities/wrath_servant/small_smash2.ogg
Labels: Feature, Test Merge Candidate

#822 Nosferatu Slurp Fix
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
Labels: Fix

#830 Strong EGO Update
  code/game/objects/items/ego_weapons/he.dm
  sound/weapons/ego/strong_charged1.ogg
  sound/weapons/ego/strong_charged2.ogg
  sound/weapons/ego/strong_gauntlet.ogg
  sound/weapons/ego/strong_uncharged.ogg
Labels: Balance, Fix

#805 Abno Lighting Update
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
  code/game/area/areas.dm
  code/game/area/areas/lobotomy_corp.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/security_levels/security_levels.dm
Labels: Feature

#834 Blind Rage fix
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/waw.dm
Labels: Code improvement, Fix

#835 Ppodae Damage Up
  code/modules/mob/living/simple_animal/abnormality/teth/ppodae.dm
Labels: Balance

#824 Cinderella Ego Dump
  code/datums/abnormality/_ego_datum/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
Labels: Feature

#803 Pink Midnight+ Atomization, Base
  code/__DEFINES/abnormalities.dm
  code/_globalvars/lists/mobs.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/_ordeal.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/misc.dm
Labels: Feature

#846 Small description fixes
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
Labels: Fix

#783 Torn Off Wings Update
  code/game/objects/items/ego_weapons/waw.dm
Labels: Balance

#828 Abnormality Archive Fix and Minor Records fixes
  code/game/machinery/computer/abnormality_archive.dm
  code/modules/paperwork/records/info/_info.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Fix

#816 Adds Doomsday Calendar
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/64x64.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/paperwork/records/info/zayin.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/doomsdaycalendar/Doomsday_Attack.ogg
  sound/abnormalities/doomsdaycalendar/Doomsday_Dead.ogg
  sound/abnormalities/doomsdaycalendar/Doomsday_Slash.ogg
  sound/abnormalities/doomsdaycalendar/Doomsday_Universe.ogg
  sound/abnormalities/doomsdaycalendar/Effect_Burn.ogg
  sound/abnormalities/doomsdaycalendar/Impending_Charge.ogg
  sound/abnormalities/doomsdaycalendar/Limbus_Dead_Generic.ogg
  sound/abnormalities/doomsdaycalendar/Lor_Slash_Generic.ogg
Labels: Test Merge Candidate, Abnormality

#831 Adds wall gazer abnormality. Lady facing the wall
  ModularTegustation/Teguicons/96x48.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/modules/mob/living/simple_animal/abnormality/teth/lady_facing_the_wall.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/projectiles/ammunition/ego_ammunition/he.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#837 Rebalances Clown Smiling At Me
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
Labels: Balance, Tweak, Test Merge Candidate

#852 New Magical Girl Plushies
  ModularTegustation/tegu_items/lc13unique_items.dm
  code/game/objects/items/plushes.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  icons/obj/plushes.dmi
Labels: Tweak

#801 Indigo Dusk leadership Update
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
Labels: Tweak

#351 Ordeal Pets
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  ModularTegustation/tegu_items/lc13unique_items.dm
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
  code/datums/components/riding/riding_mob.dm
  lobotomy-corp13.dme
Labels: Feature, Tweak

#848 eta corp
  _maps/etacorp.json
  _maps/map_files/Eta/etacorp.dmm
Labels: Mapping

#800 Eyeball Scooper Rework
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
Labels: Balance, Tweak

#851 Trusted players; Sephirah all the time; Representatives
  ModularTegustation/tegu_global_vars.dm
  ModularTegustation/tegu_items/lc13/refinery/crates.dm
  ModularTegustation/trusted.dm
  ModularTegustation/trusted_players/trusted-players_procs.dm
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/jobs.dm
  code/__HELPERS/global_lists.dm
  code/controllers/subsystem/job.dm
  code/game/machinery/computer/card.dm
  code/modules/client/preferences.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/gimmick/HHPP.dm
  code/modules/jobs/job_types/gimmick/departmentcaptain.dm
  code/modules/jobs/job_types/gimmick/departmenthead.dm
  code/modules/jobs/job_types/manager.dm
  code/modules/jobs/job_types/trusted_players/representative.dm
  code/modules/jobs/job_types/trusted_players/sephirah.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  config/trusted_players.txt
  lobotomy-corp13.dme
Labels: Feature, Mapping, Test Merge Candidate

#832 Refinery Update
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/Teguicons/refiner.dmi
  ModularTegustation/tegu_items/lc13/refinery/_spawners.dm
  ModularTegustation/tegu_items/lc13/refinery/crates.dm
  ModularTegustation/tegu_items/lc13/refinery/sales.dm
  code/game/objects/items/ego_weapons/non_abnormality/_cityweapons.dm
  code/game/objects/items/ego_weapons/non_abnormality/cane.dm
  code/game/objects/items/ego_weapons/non_abnormality/index.dm
  code/game/objects/items/ego_weapons/non_abnormality/kcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/rats.dm
  code/game/objects/items/ego_weapons/non_abnormality/seven.dm
  code/game/objects/items/ego_weapons/non_abnormality/shrimp.dm
  code/game/objects/items/ego_weapons/non_abnormality/zwei.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/city.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/kcorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/limbus_ego.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/limbus_sinner.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/ncorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/rcorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/seven.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/wcorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/zwei.dm
  code/modules/clothing/suits/ego_gear/special.dm
  code/modules/projectiles/ammunition/ego_ammunition/special.dm
  code/modules/projectiles/projectile/ego_bullets/special.dm
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/mob/clothing/ego_gear/limbus_suit.dmi
  icons/obj/card.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/limbus_suits.dmi
  lobotomy-corp13.dme
Labels: Feature

#858 adds book without pictures or dialogue
  ModularTegustation/Teguicons/32x32.dmi
  code/datums/abnormality/_ego_datum/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/book.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/projectiles/ammunition/ego_ammunition/teth.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/book/scribble.ogg
Labels: Abnormality

#862 Adds jester of nihil to the code
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/Teguicons/teguitems.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nihil.dm
  code/modules/paperwork/records/info/aleph.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/nihil/attack.ogg
  sound/abnormalities/nihil/filter.ogg
Labels: Abnormality

#865 Adds fluid sac and sfx
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/ego_weapons.dmi
  sound/abnormalities/icthys/blast.ogg
  sound/abnormalities/icthys/charge.ogg
  sound/abnormalities/icthys/hammer1.ogg
  sound/abnormalities/icthys/hammer2.ogg
  sound/abnormalities/icthys/hammer3.ogg
  sound/abnormalities/icthys/hardslap.ogg
  sound/abnormalities/icthys/jump.ogg
  sound/abnormalities/icthys/land.ogg
  sound/abnormalities/icthys/slap.ogg
Labels: Feature

#842 You Strong Fixes
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
Labels: Fix

#811 EGO Rebalance April
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/waw.dm
Labels: Balance, Test Merge Candidate

#868 Morsel Size Fix
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
Labels: Fix

#749 Gives Sweet Home SFX
  code/modules/mob/living/simple_animal/abnormality/teth/my_sweet_home.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
  sound/abnormalities/ebonyqueen/attack.ogg
  sound/abnormalities/sweethome/smash.ogg
  sound/abnormalities/sweethome/walk.ogg
Labels: Tweak

#809 Adds 2 new realization armor sets
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  icons/mob/clothing/ego_gear/realized.dmi
  icons/obj/clothing/ego_gear/realization.dmi
Labels: Tweak

#703 Adds sphinx
  ModularTegustation/Teguicons/64x48.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/teguitems.dmi
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/sphinx.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  lobotomy-corp13.dme
  sound/abnormalities/sphinx/attack.ogg
  sound/abnormalities/sphinx/petrify.ogg
  sound/abnormalities/sphinx/stone_ready.ogg
Labels: Abnormality

#877 Adds Z Level Checks
  code/modules/mob/living/simple_animal/abnormality/aleph/blue_star.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/silent_orchestra.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
Labels: Fix

#879 Adds Missing Gifts
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nihil.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/space_lady.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/mob/living/simple_animal/abnormality/he/KHz.dm
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/mob/living/simple_animal/abnormality/he/fan.dm
  code/modules/mob/living/simple_animal/abnormality/he/galaxy_child.dm
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/mob/living/simple_animal/abnormality/he/road_home.dm
  code/modules/mob/living/simple_animal/abnormality/he/schadenfreude.dm
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
  code/modules/mob/living/simple_animal/abnormality/he/watchman.dm
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
  code/modules/mob/living/simple_animal/abnormality/teth/MHz.dm
  code/modules/mob/living/simple_animal/abnormality/teth/blood_bath.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cherry_blossoms.dm
  code/modules/mob/living/simple_animal/abnormality/teth/drowned_sisters.dm
  code/modules/mob/living/simple_animal/abnormality/teth/lady_facing_the_wall.dm
  code/modules/mob/living/simple_animal/abnormality/teth/old_lady.dm
  code/modules/mob/living/simple_animal/abnormality/teth/penitent_girl.dm
  code/modules/mob/living/simple_animal/abnormality/teth/simple_smile.dm
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
  code/modules/mob/living/simple_animal/abnormality/waw/alriune.dm
  code/modules/mob/living/simple_animal/abnormality/waw/contract.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dimension_refraction.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dreaming_current.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/living/simple_animal/abnormality/waw/luna.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  code/modules/mob/living/simple_animal/abnormality/waw/silence.dm
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yang.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/quiet_day.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
Labels: Feature

#782 Adds Records library
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/paperwork/records/lore/shrimp.dm
  code/modules/paperwork/records/recordsfiling.dm
  lobotomy-corp13.dme
Labels: Feature, Mapping

#820 Reworks Lady out of Space
  code/modules/mob/living/simple_animal/abnormality/aleph/space_lady.dm
Labels: Balance

#881 Alpha Fix
  _maps/map_files/Alpha/alphacorp.dmm
Labels: Fix, Mapping

#883 Status Effect Cleanup and related PascalCasing
  ModularTegustation/tegu_items/lc13unique_items.dm
  code/datums/status_effects/panic.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
  code/modules/mob/living/simple_animal/abnormality/he/road_home.dm
  code/modules/mob/living/simple_animal/abnormality/he/silent_girl.dm
  code/modules/mob/living/simple_animal/abnormality/waw/fire_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
Labels: Code improvement, Fix

#562 Abnochem Part 1
  ModularTegustation/Teguicons/teguitems.dmi
  code/game/machinery/computer/abnormality_work.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bald.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/quiet_day.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/sleeping_beauty.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
  code/modules/paperwork/paper_premade.dm
  code/modules/reagents/chemistry/reagents/abnormality_reagents.dm
  lobotomy-corp13.dme
Labels: Feature

#890 Cat Checks for Godmode
  code/modules/mob/living/simple_animal/abnormality/he/scaredy_cat.dm
Labels: Fix

#891 Servant of Wrath and console reference retooling
  code/controllers/subsystem/lobotomy_corp.dm
  code/datums/abnormality/datum/abnormality.dm
  code/game/objects/effects/spawners/abnormality_room.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
Labels: Code improvement, Fix

#766 Violet dawn rebalance, noon tweak
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
Labels: Balance, Tweak

#892 Servant of Wrath targetting fix and normal breach on random spawn
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
Labels: Tweak, Fix

#895 Zwei & Seven fix
  code/game/objects/items/ego_weapons/non_abnormality/seven.dm
  code/game/objects/items/ego_weapons/non_abnormality/zwei.dm
Labels: Fix
