Repository vlggms/lobotomy-corp13, pull requests merged in 2024-01, with the labels that each got.

#1772 Adds more abnormality portraits
  code/game/machinery/computer/abnormality_portraits.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nihil.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/staining_rose.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
  code/modules/mob/living/simple_animal/abnormality/he/road_home.dm
  code/modules/mob/living/simple_animal/abnormality/he/scaredy_cat.dm
  code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
  code/modules/mob/living/simple_animal/abnormality/teth/dingle_dangle.dm
  code/modules/mob/living/simple_animal/abnormality/teth/drowned_sisters.dm
  code/modules/mob/living/simple_animal/abnormality/teth/my_sweet_home.dm
  code/modules/mob/living/simple_animal/abnormality/teth/penitent_girl.dm
  code/modules/mob/living/simple_animal/abnormality/waw/pygmalion.dm
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/pile_of_mail.dm
  icons/UI_Icons/abnormality_portraits/blue_shepherd.png
  icons/UI_Icons/abnormality_portraits/bottle.png
  icons/UI_Icons/abnormality_portraits/dingle_dangle.png
  icons/UI_Icons/abnormality_portraits/drowned_sisters.png
  icons/UI_Icons/abnormality_portraits/fall.png
  icons/UI_Icons/abnormality_portraits/fall_deity.png
  icons/UI_Icons/abnormality_portraits/hookah.png
  icons/UI_Icons/abnormality_portraits/my_sweet_home.png
  icons/UI_Icons/abnormality_portraits/nihil.png
  icons/UI_Icons/abnormality_portraits/nobody_is.png
  icons/UI_Icons/abnormality_portraits/ozma.png
  icons/UI_Icons/abnormality_portraits/penitent.png
  icons/UI_Icons/abnormality_portraits/pile_of_mail.png
  icons/UI_Icons/abnormality_portraits/pinocchio.png
  icons/UI_Icons/abnormality_portraits/piscine.png
  icons/UI_Icons/abnormality_portraits/pygmalion.png
  icons/UI_Icons/abnormality_portraits/red_buddy.png
  icons/UI_Icons/abnormality_portraits/road_home.png
  icons/UI_Icons/abnormality_portraits/scaredy_cat.png
  icons/UI_Icons/abnormality_portraits/spring.png
  icons/UI_Icons/abnormality_portraits/spring_deity.png
  icons/UI_Icons/abnormality_portraits/staining_rose.png
  icons/UI_Icons/abnormality_portraits/summer.png
  icons/UI_Icons/abnormality_portraits/summer_deity.png
  icons/UI_Icons/abnormality_portraits/tangle.png
  icons/UI_Icons/abnormality_portraits/titania.png
  icons/UI_Icons/abnormality_portraits/white_lake.png
  icons/UI_Icons/abnormality_portraits/winter.png
  icons/UI_Icons/abnormality_portraits/winter_deity.png
  icons/UI_Icons/abnormality_portraits/wrath_servant.png
Labels: Sprites, Expansion

#1773 Fixed position of Arrow Decal Sprite
  icons/turf/decals.dmi
Labels: Sprites

#1780 New Lakewater tiles
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/fishing/code/turfs.dm
  icons/turf/floors/water.dmi
Labels: Sprites

#1783 Fixing watch cooldown typo
  ModularTegustation/tegu_items/records/_records.dm
Labels: Writing

#1787 Fixes nobody is
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
Labels: Fix

#1782 Adds work damage effects
  ModularTegustation/lc13_effects.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  code/modules/mob/living/simple_animal/abnormality/waw/flesh_idol.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/pile_of_mail.dm
  icons/effects/160x96.dmi
Labels: Sprites, Expansion

#1791 Skittish goes from 4 to 2 points
  code/datums/quirks/good.dm
Labels: Balance

#1793 Fixes EMAIS to now work with Support officers
  code/game/objects/items/clerks/hypo/hypo.dm
Labels: Fix, Side content

#1790 Fixes a bug related to god of the seasons
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
Labels: Fix

#1775 Eta 2.0
  _maps/etacorp.json
  _maps/map_files/Eta/etacorp.dmm
Labels: Mapping

#1797 KoD Update
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/ordeals/_ordeal.dm
Labels: Fix

#1795 Nerfs Nobody Is
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
Labels: Balance

#1777 Thetacorp 2.0
  _maps/map_files/Theta/thetacorp.dmm
  _maps/thetacorp.json
Labels: Mapping

#1799 Adds better radio jamming
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/radio/radio.dm
Labels: Mapping

#1796 Make Piscine Mermaid less needy
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
Labels: Balance

#1779 Kappacorp 2.0
  _maps/kappacorp.json
  _maps/map_files/Kappa/kappacorp.dmm
Labels: Mapping

#1801 Zetacorp 2.0
  _maps/map_files/Zeta/zetacorp.dmm
  _maps/zetacorp.json
Labels: Mapping

#1816 Tool abnorm files are now named
  code/modules/paperwork/records/info/tools.dm
Labels: Writing

#1810 New Rudolta Sprite
  ModularTegustation/Teguicons/64x48.dmi
Labels: Sprites

#1812 Nav Beacon added to Gamma Corp due to CL bot issue
  _maps/map_files/Gamma/gammacorp.dmm
Labels: Mapping

#1811 Alpha Corp Camera Issue Fix
  _maps/map_files/Alpha/alphacorp.dmm
Labels: Mapping

#1809 Brings in LCCB and Dieci Sprites
  ModularTegustation/Teguicons/lc13icons.dmi
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  icons/obj/ego_weapons.dmi
Labels: Sprites

#1814 Rep gets a advanced console
  _maps/map_files/generic/CentCom.dmm
Labels: Tweak, Mapping

#1679 Fishing Boat that can Sail on Water Tiles & Water Tile Tweaks
  ModularTegustation/fishing/code/fishing_items/fishing_boat.dm
  ModularTegustation/fishing/code/turfs.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
  lobotomy-corp13.dme
Labels: Feature, Tweak, Side content

#1766 Ultimate Christmas
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/64x48.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
  code/game/objects/effects/abnormality.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/holiday/holidays.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/rudolta_buff.dm
  icons/effects/beam.dmi
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/rudolta_buff/melee.ogg
  sound/abnormalities/rudolta_buff/onrush1.ogg
  sound/abnormalities/rudolta_buff/onrush2.ogg
  sound/abnormalities/rudolta_buff/onrush3.ogg
Labels: Sprites, Abnormality

#1723 Representative Additions
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/tegu_items/representative/items/kcorp.dm
  ModularTegustation/tegu_items/representative/items/pcorp.dm
  ModularTegustation/tegu_items/representative/research/kcorp.dm
  ModularTegustation/tegu_items/representative/research/pcorp.dm
  ModularTegustation/tegu_items/representative/research/rcorp.dm
  ModularTegustation/tegu_items/representative/research/wcorp.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Expansion

#1822 Adventure Console Major Fix
  ModularTegustation/lc13_adventuredatum.dm
Labels: Fix

#1821 Sphinx is less picky about what constitutes a vessel
  code/modules/mob/living/simple_animal/abnormality/waw/sphinx.dm
Labels: Fix

#1823 meat lantern fix
  code/modules/mob/living/simple_animal/abnormality/teth/meat_lantern.dm
Labels: Fix

#1774 Shuttle templates + Shuttle Code for Maps
  _maps/shuttles/deltamain_elevator.dmm
  _maps/shuttles/iotaextra_elevator.dmm
  _maps/shuttles/iotafinal_elevator.dmm
  _maps/shuttles/iotamain_elevator.dmm
  _maps/shuttles/zetadeparteast_elevator.dmm
  _maps/shuttles/zetadepartwest_elevator.dmm
  code/datums/shuttles.dm
Labels: Mapping

#1826 Fix Vitals Visualizer Runtimes
  ModularTegustation/tegu_items/gadgets/powered.dm
Labels: Fix

#1813 Expands flesh idol's blacklist
  code/modules/mob/living/simple_animal/abnormality/waw/flesh_idol.dm
Labels: Balance

#1776 Iota 2.0
  _maps/iotacorp.json
  _maps/map_files/Iota/iotacorp.dmm
Labels: Mapping

#1829 Fix a number of runtime errors
  ModularTegustation/tegu_items/workshop/forging.dm
  code/datums/chatmessage.dm
  code/modules/client/verbs/ooc.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/mob/living/brain/brain_item.dm
Labels: Code improvement

#1831 Brass Nail band-aid
  code/game/objects/items/ego_weapons/non_abnormality/ncorp.dm
Labels: Fix

#1819 K-Corp Class-1 Clerks
  ModularTegustation/tegu_items/representative/items/kcorp.dm
  ModularTegustation/tegu_items/representative/research/kcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/weak_edits/city.dm
Labels: Tweak

#1832 Love Town CoL Structures
  _maps/RandomRooms/backstreets/large_north/town_lna.dmm
  _maps/RandomRooms/backstreets/medium_south/town_msa.dmm
  _maps/RandomRooms/backstreets/medium_west/town_mwa.dmm
  _maps/RandomRooms/backstreets/medium_west/town_mwb.dmm
  _maps/RandomRooms/backstreets/pointofinterest/love_train.dmm
  _maps/RandomRooms/backstreets/small_east/paper_pushed.dmm
Labels: Mapping

#1778 Lambda 2.0
  _maps/lambdacorp.json
  _maps/map_files/Lambda/lambdacorp.dmm
Labels: Mapping

#1827 Ports hair gradients and portrait printer
  code/__DEFINES/art.dm
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/quirks/neutral.dm
  code/game/objects/items/dyekit.dm
  code/game/objects/structures/artstuff.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/silicon/ai/ai_portrait_picker.dm
  code/modules/modular_computers/computers/machinery/console_presets.dm
  code/modules/modular_computers/file_system/programs/portrait_printer.dm
  code/modules/vending/games.dm
  icons/mob/hair_gradients.dmi
  icons/obj/dyespray.dmi
  lobotomy-corp13.dme
  tgui/packages/tgui/interfaces/NtosPortraitPrinter.js
Labels: Feature

#1836 New Tool Abnormality Sprites
  ModularTegustation/Teguicons/toolabnormalities.dmi
  code/modules/mob/living/simple_animal/abnormality/_tools/he/theonite_slab.dm
Labels: Sprites

#1840 adds limbus company abno portraits
  code/game/machinery/computer/abnormality_portraits.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/mob/living/simple_animal/abnormality/he/drifting_fox.dm
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/mob/living/simple_animal/abnormality/he/headless_ichthys.dm
  code/modules/mob/living/simple_animal/abnormality/he/highway_devotee.dm
  code/modules/mob/living/simple_animal/abnormality/he/steam_transport_machine.dm
  code/modules/mob/living/simple_animal/abnormality/he/wayward_passenger.dm
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cleaner.dm
  code/modules/mob/living/simple_animal/abnormality/teth/faelantern.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_gentleman.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_long_legs.dm
  code/modules/mob/living/simple_animal/abnormality/teth/skin_prophet.dm
  code/modules/mob/living/simple_animal/abnormality/teth/so_that_no_cry.dm
  code/modules/mob/living/simple_animal/abnormality/waw/babayaga.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/rose_sign.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/blubbering_toad.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/oceanwaves.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/sunset_traveller.dm
  icons/UI_Icons/abnormality_portraits/alleyway_watchdog.png
  icons/UI_Icons/abnormality_portraits/ambling_pearl.png
  icons/UI_Icons/abnormality_portraits/baba_yaga.png
  icons/UI_Icons/abnormality_portraits/bailisoup.png
  icons/UI_Icons/abnormality_portraits/blubbering_toad.png
  icons/UI_Icons/abnormality_portraits/brazen_bull.png
  icons/UI_Icons/abnormality_portraits/cleaner.png
  icons/UI_Icons/abnormality_portraits/doomsday.png
  icons/UI_Icons/abnormality_portraits/drifting_fox.png
  icons/UI_Icons/abnormality_portraits/ebony_queen.png
  icons/UI_Icons/abnormality_portraits/faelantern.png
  icons/UI_Icons/abnormality_portraits/fairy_gentleman.png
  icons/UI_Icons/abnormality_portraits/fairy_long_legs.png
  icons/UI_Icons/abnormality_portraits/golden_apple.png
  icons/UI_Icons/abnormality_portraits/grown_strong.png
  icons/UI_Icons/abnormality_portraits/headless_icthys.png
  icons/UI_Icons/abnormality_portraits/highway_devotee.png
  icons/UI_Icons/abnormality_portraits/kqe.png
  icons/UI_Icons/abnormality_portraits/my_form_empties.png
  icons/UI_Icons/abnormality_portraits/oceanicwaves.png
  icons/UI_Icons/abnormality_portraits/pagoda_veneration.png
  icons/UI_Icons/abnormality_portraits/rose_sign.png
  icons/UI_Icons/abnormality_portraits/shock_centipede.png
  icons/UI_Icons/abnormality_portraits/siltcurrent.png
  icons/UI_Icons/abnormality_portraits/skin_prophet.png
  icons/UI_Icons/abnormality_portraits/so_that_no_cry.png
  icons/UI_Icons/abnormality_portraits/steam_transport_machine.png
  icons/UI_Icons/abnormality_portraits/sunset_traveller.png
  icons/UI_Icons/abnormality_portraits/wayward_passenger.png
Labels: Sprites

#1835 WAITER!!! MORE STRUCTURES PLEASE!
  _maps/RandomRooms/backstreets/connector/choke_point.dmm
  _maps/RandomRooms/backstreets/connector/fort_knox.dmm
  _maps/RandomRooms/backstreets/large_north/kcorp_warehouse.dmm
  _maps/RandomRooms/backstreets/large_north/robot_lnb.dmm
  _maps/RandomRooms/backstreets/large_north/town_lna.dmm
  _maps/RandomRooms/backstreets/large_south/gcorp_armory.dmm
  _maps/RandomRooms/backstreets/large_south/supermarket.dmm
  _maps/RandomRooms/backstreets/medium_east/shrimp_office.dmm
  _maps/RandomRooms/backstreets/medium_east/worm_cave.dmm
  _maps/RandomRooms/backstreets/medium_north/buffet.dmm
  _maps/RandomRooms/backstreets/medium_north/fairies.dmm
  _maps/RandomRooms/backstreets/medium_north/gmanager_house.dmm
  _maps/RandomRooms/backstreets/medium_south/apartmentmsa.dmm
  _maps/RandomRooms/backstreets/medium_south/lcorp_ruin.dmm
  _maps/RandomRooms/backstreets/medium_south/mech_bay.dmm
  _maps/RandomRooms/backstreets/medium_west/chicken_coop.dmm
  _maps/RandomRooms/backstreets/medium_west/mini_beach.dmm
  _maps/RandomRooms/backstreets/medium_west/town_mwa.dmm
  _maps/RandomRooms/backstreets/pointofinterest/love_train.dmm
  _maps/RandomRooms/backstreets/small_east/dragon_statue.dmm
  _maps/RandomRooms/backstreets/small_north/bird_box.dmm
  _maps/RandomRooms/backstreets/small_south/candlelit_dinner.dmm
  _maps/RandomRooms/backstreets/small_west/booby_trapped.dmm
  _maps/RandomRooms/backstreets/small_west/fake_pit.dmm
  _maps/RandomRooms/backstreets/small_west/risk_rain_reference_robot.dmm
Labels: Mapping, Side content

#1842 its ok guys i turned on the air conditioning
  _maps/RandomRooms/backstreets/bossroom/jacques.dmm
  _maps/RandomRooms/backstreets/medium_south/eyes_temple.dmm
Labels: Fix, Mapping

#1845 Adds Refactor Label
  .github/workflows/enforce-labels.yml
Labels: Github

#1852 Announcements Tablets (Color Coded!!!!)
  ModularTegustation/tegu_items/rcorp/gadgets.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/wcorp/wcorprecon.dm
Labels: Feature

#1853 Delta
  _maps/deltacorp.json
  _maps/map_files/Delta/deltacorp.dmm
Labels: Mapping

#1856 Fixes holomaps sometimes not having cursors
  code/game/machinery/facility_holomap.dm
Labels: Fix

#1855 Syndicate Offices Template 2.0
  ModularTegustation/tegu_items/associations/syndicateoffice.dm
  _maps/map_files/Eta/etacorp.dmm
  _maps/templates/syndicate_office/blade_lineage.dmm
  _maps/templates/syndicate_office/blade_lineageswordmen.dmm
  _maps/templates/syndicate_office/index.dmm
  _maps/templates/syndicate_office/indexfinger.dmm
  _maps/templates/syndicate_office/kurokumo.dmm
  _maps/templates/syndicate_office/kurokumosake.dmm
  _maps/templates/syndicate_office/nagelcorp.dmm
  _maps/templates/syndicate_office/ncorp.dmm
  _maps/templates/syndicate_office/thumb.dmm
  _maps/templates/syndicate_office/thumbfinger.dmm
Labels: Mapping

#1851 Adds Red Riding Hooded Mercenary 2 : Electric Boogaloo
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Teguicons/96x64.dmi
  ModularTegustation/Teguicons/teguicons.dmi
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/waw/red_riding_mercenary.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#1825 Small RCA tweaks
  code/modules/clothing/suits/ego_gear/non_abnormality/rcorp.dm
  code/modules/jobs/job_types/rcorp/rabbit.dm
  code/modules/jobs/job_types/rcorp/raven.dm
  code/modules/jobs/job_types/rcorp/reindeer.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
Labels: Balance, Fix

#1735 The Great Fishing Chance Rework [DONE?]
  ModularTegustation/fishing/code/fish/LC13_fish/saltwater_fish.dm
  ModularTegustation/fishing/code/fish_market.dm
  ModularTegustation/fishing/code/fishing_items/fish_box.dm
  ModularTegustation/fishing/code/fishing_items/fishing_net.dm
  ModularTegustation/fishing/code/fishing_items/fishing_rod.dm
  ModularTegustation/fishing/code/fishing_skill.dm
  ModularTegustation/fishing/code/rod_components/_fishing_component.dm
  ModularTegustation/fishing/code/rod_components/fishing_hooks.dm
  ModularTegustation/fishing/code/rod_components/fishing_lines.dm
  ModularTegustation/fishing/code/turfs.dm
Labels: Tweak

#1850 Butcher spawns with hook
  _maps/map_files/Event/city.dmm
  code/modules/jobs/job_types/city/backstreets_butcher.dm
Labels: Tweak, Side content

#1804 Fixer Skills update (City of Light 13)
  ModularTegustation/tegu_items/associations/vending.dm
  code/game/objects/items/fixerskills/level1.dm
  code/game/objects/items/fixerskills/level1/defensive.dm
  code/game/objects/items/fixerskills/level1/healing.dm
  code/game/objects/items/fixerskills/level1/movement.dm
  code/game/objects/items/fixerskills/level2.dm
  code/game/objects/items/fixerskills/level2/butcher.dm
  code/game/objects/items/fixerskills/level2/confusion.dm
  code/game/objects/items/fixerskills/level2/flashbang.dm
  code/game/objects/items/fixerskills/level2/shockwave.dm
  code/game/objects/items/fixerskills/level3.dm
  code/game/objects/items/fixerskills/level3/battleready.dm
  code/game/objects/items/fixerskills/level3/bulletproof.dm
  code/game/objects/items/fixerskills/level3/hud.dm
  code/game/objects/items/fixerskills/level4/healing.dm
  code/game/objects/items/fixerskills/level4/status_effects.dm
  code/game/objects/items/fixerskills/no_level.dm
  code/game/objects/items/fixerskills/skills.dm
  icons/hud/screen_skills.dmi
  lobotomy-corp13.dme
Labels: Expansion, Side content

#1859 Zeta Map Bug Fixes
  _maps/map_files/Zeta/zetacorp.dmm
Labels: Fix, Mapping

#1805 Backstreet Layout Enable (City)
  ModularTegustation/tegu_items/backstreets/templates.dm
  _maps/RandomRooms/backstreetlayout/dungeon_backstreets.dmm
  _maps/RandomRooms/backstreetlayout/lcorp.dmm
Labels: Fix, Expansion, Side content

#1862 Kappa and Lambda Map Bug Fixes
  _maps/map_files/Kappa/kappacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
Labels: Mapping

#1868 Hana discovers guns are actually worth money
  ModularTegustation/tegu_items/associations/machines.dm
Labels: Tweak

#1870 Realizer no longer takes away states
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
Labels: Tweak

#1833 dash ability fixes
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clouded_monk.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/spells/ability_types/realized_aimed.dm
Labels: Fix

#1872 Minor grammar mistake, utterly unplayable.
  ModularTegustation/tegu_items/refinery/refinery.dm
Labels: Writing

#1871 adds fetus, philip and child of the galaxy to flesh idol blacklist
  code/modules/mob/living/simple_animal/abnormality/waw/flesh_idol.dm
Labels: Balance

#1863 General Map Fixes Part One (non-crucial)
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Kappa/kappacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
Labels: Mapping

#1864 General Map Fix 2 (Non-Crucial)
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Iota/iotacorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
Labels: Mapping

#1869 BL swords are no longer cardboard!
  _maps/templates/syndicate_office/blade_lineageswordmen.dmm
  code/modules/jobs/job_types/city/syndicate/kurokumo/blade_ronin.dm
Labels: Tweak, Side content

#1874 Updates Skill Icons
  icons/hud/screen_skills.dmi
Labels: Sprites

#1867 Fixes CoL13 crate chances
  ModularTegustation/tegu_items/associations/cityspawners.dm
Labels: Fix, Side content

#1817 Pink Midnight Fix
  code/modules/mob/living/simple_animal/hostile/ordeal/misc.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/ordeals/misc_ordeals.dm
Labels: Fix

#1761 Adds debug items, cleans up a bit of code around debug items and reverts some very poor decisions on debug items
  ModularTegustation/tegu_clothes_code/glasses.dm
  ModularTegustation/tegu_items/admin.dm
  ModularTegustation/tegu_items/debug_items.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/outfits/standard.dm
  lobotomy-corp13.dme
Labels: Tweak

#1788 Understanding Runtime Fix
  code/datums/abnormality/datum/abnormality.dm
Labels: Fix

#1857 N-Corp Representative now gets temporary attribute increasers
  ModularTegustation/tegu_items/representative/items/ncorp.dm
  ModularTegustation/tegu_items/representative/research/kcorp.dm
  ModularTegustation/tegu_items/representative/research/ncorp.dm
Labels: Tweak

#1875 Fixer Office Template 2.0
  ModularTegustation/tegu_items/associations/fixeroffice.dm
  _maps/templates/fixer_office/combat.dmm
  _maps/templates/fixer_office/combatfixers.dmm
  _maps/templates/fixer_office/fishing.dmm
  _maps/templates/fixer_office/fishingfixers.dmm
  _maps/templates/fixer_office/peacekeeping.dmm
  _maps/templates/fixer_office/peacekeepingfixers.dmm
  _maps/templates/fixer_office/protection.dmm
  _maps/templates/fixer_office/protectionfixers.dmm
  _maps/templates/fixer_office/recon.dmm
  _maps/templates/fixer_office/reconfixers.dmm
  _maps/templates/fixer_office/workshop.dmm
  _maps/templates/fixer_office/workshopfixers.dmm
Labels: Mapping

#1786 Epsilon2.0
  _maps/epsiloncorp.json
  _maps/map_files/Epsilon/epsiloncommand.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
Labels: Mapping

#1884 CENSORED and ??? no longer do enhanced obj damage
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
Labels: Fix

#1866 20 Non-GMO, Ethically Harvested, Whole Grain CoL Structures
  ModularTegustation/tegu_items/backstreets/random_rooms/bigrooms/connector.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/east.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/north.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/south.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/east.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/north.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/south.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/west.dm
  _maps/RandomRooms/backstreets/connector/rat_cave.dmm
  _maps/RandomRooms/backstreets/medium_east/church.dmm
  _maps/RandomRooms/backstreets/medium_east/roach_mafia.dmm
  _maps/RandomRooms/backstreets/medium_east/robot_mea.dmm
  _maps/RandomRooms/backstreets/medium_north/rage_cage.dmm
  _maps/RandomRooms/backstreets/medium_north/rat_mna.dmm
  _maps/RandomRooms/backstreets/medium_south/rat_msa.dmm
  _maps/RandomRooms/backstreets/medium_south/theatre.dmm
  _maps/RandomRooms/backstreets/small_east/rat_sea.dmm
  _maps/RandomRooms/backstreets/small_north/ash_exhibit.dmm
  _maps/RandomRooms/backstreets/small_north/pet_store.dmm
  _maps/RandomRooms/backstreets/small_north/snow_forest.dmm
  _maps/RandomRooms/backstreets/small_south/human_experiment.dmm
  _maps/RandomRooms/backstreets/small_south/lcorp_tomb.dmm
  _maps/RandomRooms/backstreets/small_south/rat_ssa.dmm
  _maps/RandomRooms/backstreets/small_south/robot_ssa.dmm
  _maps/RandomRooms/backstreets/small_west/dry_cleaners.dmm
  _maps/RandomRooms/backstreets/small_west/rat_swa.dmm
  _maps/RandomRooms/backstreets/small_west/rat_swb.dmm
  _maps/RandomRooms/backstreets/small_west/robot_swb.dmm
Labels: Mapping, Side content

#1861 Improved work economy with Piscine Mermaid
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
  code/modules/paperwork/records/info/he.dm
Labels: Balance

#1748 The great 9 armor massacre of 2023-2024(And red and black fixer nerfs)
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
Labels: Balance, Merge Date Set

#1891 General Map Fix 3.0
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Kappa/kappacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
Labels: Mapping

#1894 Fixes negative fort and prud bonuses
  code/datums/attributes/_attribute.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#1893 Making shepherd abnormality friendly on r corp map
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
Labels: Balance, Side content

#1892 Some runtime fixes
  code/game/objects/items/ego_weapons/he.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/teth/ppodae.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
Labels: Fix

#1888 improves ghost possession code, and resolves a very minor bug that was in the code for 1+ month and NOBODY except my friend yesterday noticed it
  code/modules/mob/dead/observer/observer.dm
Labels: Code improvement, Fix

#1882 Possible fix to dead followers following
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
Labels: Fix

#1885 hammer rhino improvements
  code/modules/vehicles/mecha/equipment/weapons/mecha_melee.dm
Labels: Tweak

#1901 Control Core Suppression now gives 10 LOB as reward
  code/modules/suppressions/control.dm
Labels: Tweak

#1903 Training Dummy Rabbit no longer breach Red Hood
  code/modules/mob/living/simple_animal/abnormality/waw/red_riding_mercenary.dm
Labels: Fix

#1913 Final General Map Fix PR
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Iota/iotacorp.dmm
  _maps/map_files/Kappa/kappacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
Labels: Mapping

#1907 Jeong Weapon Fix
  code/game/objects/items/ego_weapons/non_abnormality/jeong.dm
Labels: Fix

#1906 WorkChance() Proc Cleanup
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
  code/modules/mob/living/simple_animal/abnormality/waw/contract.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yang.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/sleeping_beauty.dm
Labels: Tweak, Refactor

#1917 Kappa Fix
  _maps/map_files/Kappa/kappacorp.dmm
Labels: Mapping

#1915 Door welding removed
  code/game/machinery/doors/door.dm
Labels: Removal

#1910 Surgery Buffs (the lobotomy is real)
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Event/skeld.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/Iota/iotacorp.dmm
  _maps/map_files/Kappa/kappacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Psi/psicorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
  _maps/map_files/Xi/xicommand.dmm
  _maps/map_files/Xi/xicorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
  code/game/objects/items/storage/backpack.dm
  code/modules/surgery/advanced/bioware/cortex_imprint.dm
  code/modules/surgery/advanced/bioware/ligament_hook.dm
  code/modules/surgery/advanced/bioware/vein_threading.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/surgery/healing.dm
  code/modules/surgery/stomachpump.dm
Labels: Tweak

#1909 Fixes a single character issue in Drifting Foxes attribute check.
  code/modules/mob/living/simple_animal/abnormality/he/drifting_fox.dm
Labels: Fix

#1911 Plasma unfuckery attempt 2
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Removal

#1897 Manager tip update + Immune/Absorb tip
  strings/jobtips.txt
  strings/tips.txt
Labels: Writing

#1900 Liu gloves on City are no longer combo focused
  ModularTegustation/tegu_items/associations/association_beacon.dm
  code/game/objects/items/ego_weapons/non_abnormality/weak_edits/city.dm
Labels: Tweak, Side content

#1898 Cinq Writing update
  code/game/objects/items/ego_weapons/non_abnormality/cinq.dm
Labels: Writing

#1841 Backstreet map code and dump.
  ModularTegustation/tegu_items/backstreets/random_rooms/large/north.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/east.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/north.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/south.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/north.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/south.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/west.dm
  _maps/RandomRooms/backstreets/medium_east/zwei_office_mea.dmm
  _maps/RandomRooms/backstreets/medium_north/cirno_mn.dmm
  _maps/RandomRooms/backstreets/medium_north/hana_office_mn.dmm
  _maps/RandomRooms/backstreets/medium_north/lab_ln.dmm
  _maps/RandomRooms/backstreets/medium_south/bar_msa.dmm
  _maps/RandomRooms/backstreets/medium_south/seven_office_msa.dmm
  _maps/RandomRooms/backstreets/small_north/apartment_sna.dmm
  _maps/RandomRooms/backstreets/small_north/kcorp_stash_sna.dmm
  _maps/RandomRooms/backstreets/small_south/wcorp_base_ssa.dmm
  _maps/RandomRooms/backstreets/small_west/freezer_sw.dmm
Labels: Mapping, Expansion, Side content

#1925 Update limbus_sinner.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_sinner.dm
Labels: Writing

#1927 Fixes General Bee Breach Sprite
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
Labels: Fix

#1928 Arbiter icon fix
  icons/mob/actions/actions_spells.dmi
Labels: Fix, Sprites

#1700 Dream-Devouring Siltcurrent
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/64x32.dmi
  ModularTegustation/Teguicons/96x96.dmi
  ModularTegustation/fishing/code/fish/misc_fish.dm
  ModularTegustation/fishing/code/turfs.dm
  ModularTegustation/fishing/icons/fish_sprites.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dreaming_current.dm
  code/modules/mob/living/simple_animal/abnormality/waw/siltcurrent.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/ego_weapons.dmi
  icons/turf/floors/water.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#1912 Distorted Form Update 1 : ITS TIME TO STOP
  ModularTegustation/Teguicons/48x32.dmi
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  sound/abnormalities/siren/sirenhappy.ogg
Labels: Feature
