Repository vlggms/lobotomy-corp13, pull requests merged in 2024-10, with the labels that each got.

#2330 Records Officer Information Update[DONE AND FIXED]
  ModularTegustation/tegu_items/abnoconsole_upgrades.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/game/machinery/computer/abnormality_work.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/modules/jobs/job_types/command.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/reagents/chemistry/reagents/abnormality_reagents.dm
  lobotomy-corp13.dme
Labels: Feature, Tweak

#2364 Abnormality Helper File[WIP]
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
  code/modules/mob/living/simple_animal/abnormality/abnormality_helpers.dm
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_wolf.dm
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
  lobotomy-corp13.dme
Labels: Code improvement

#2339 change steam machine and puss in boots scaling
  code/modules/mob/living/simple_animal/abnormality/he/puss_in_boots.dm
  code/modules/mob/living/simple_animal/abnormality/he/steam_transport_machine.dm
Labels: Balance, Isolated Code

#2390 ZAYIN updates
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bald.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/hammer_light.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/oceanwaves.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/pile_of_mail.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/quiet_day.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/sleeping_beauty.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
  code/modules/paperwork/records/info/zayin.dm
  icons/obj/bureaucracy.dmi
  icons/obj/drinks.dmi
  icons/obj/grenade.dmi
  icons/obj/storage.dmi
  sound/abnormalities/bald/bald_special.ogg
Labels: Balance, Expansion

#2412 E.G.O. telepads (Extraction officer update)
  ModularTegustation/tegu_items/extraction/egodelivery.dm
  ModularTegustation/tegu_items/extraction/egotelepad.dm
  lobotomy-corp13.dme
Labels: Expansion, Isolated Code

#2441 Miscellaneous Abnormality Changes and Bugfixes
  code/modules/mob/living/simple_animal/abnormality/aleph/last_shot.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/he/KHz.dm
  code/modules/mob/living/simple_animal/abnormality/he/happy_teddy_bear.dm
  code/modules/mob/living/simple_animal/abnormality/he/will_you_play.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_long_legs.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
  code/modules/mob/living/simple_animal/abnormality/waw/orange_tree.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fallen_amurdad.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Tweak, Fix

#2458 Whole bunch of fixes
  code/game/objects/items/ego_weapons/subtype/lance.dm
  code/game/objects/items/ego_weapons/subtype/wielded.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_long_legs.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
Labels: Fix

#2460 Emergency hotfix
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
Labels: Fix

#2457 Adds Forsaken Employee (Fixed PR)
  ModularTegustation/Teguicons/32x32.dmi
  code/datums/abnormality/_ego_datum/teth.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/forsaken_employee.dm
  code/modules/paperwork/records/info/teth.dm
  icons/UI_Icons/abnormality_portraits/forsaken_employee.png
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#2463 Makes Clown Smiling at You Explode into Foam like SS13 clown mobs
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
Labels: Feature, Isolated Code

#2462 Zwei Batons now powered by duracell batteries instead of potato batteries
  code/game/objects/items/ego_weapons/non_abnormality/zwei.dm
Labels: Balance, Tweak, Isolated Code

#2465 Gives Express Train to Hell an EGO gift: Part 2 (plus EGO gift sprite clean-up)
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/express_train.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
Labels: Code improvement, Tweak, Sprites

#2466 Fixes K-corp healing drones runtiming every time they hit someone, and them not healing anyone
  ModularTegustation/tegu_items/representative/items/kcorp.dm
Labels: Fix

#2422 Turns the records core code inside out to hopefully no longer make spiders cuddle with shrimps
  code/datums/abnormality/datum/abnormality.dm
  code/game/objects/effects/spawners/abnormality_room.dm
  code/modules/mob/living/simple_animal/abnormality/he/basilisoup.dm
  code/modules/suppressions/records.dm
Labels: Code improvement, Fix

#2467 City Fixer Bugfixes (And a Torso Fab Cost Change)
  ModularTegustation/lc13_machinery.dm
  code/game/objects/items/fixerskills/skills.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo/dawn.dm
Labels: Balance, Side content

#2469 Adds in a plaque from a legendary round
  _maps/map_files/generic/Tutorial_Zone.dmm
Labels: Tweak

#2449 RCA Rhinobusters
  ModularTegustation/tegu_items/rcorp/!abno_overwrites.dm
  ModularTegustation/tegu_items/rcorp/landmarks.dm
  _maps/RandomRooms/rcorp/caves/elevator.dmm
  _maps/RandomRooms/rcorp/facility/beaches.dmm
  _maps/RandomRooms/rcorp/facility/beaches2.dmm
  _maps/RandomRooms/rcorp/facility/city2.dmm
  _maps/RandomRooms/rcorp/facility/maze.dmm
  _maps/RandomRooms/rcorp/facility/maze2.dmm
  _maps/RandomRooms/rcorp/facility/nest.dmm
  _maps/RandomRooms/rcorp/facility/offices.dmm
  _maps/RandomRooms/rcorp/facility/skeld.dmm
  _maps/RandomRooms/rcorp/facility/standard.dmm
  _maps/RandomRooms/rcorp/facility/standard2.dmm
Labels: Balance, Side content

#2426 Body Preservation Unit
  ModularTegustation/lc13_machinery.dm
  _maps/map_files/Event/city.dmm
  _maps/map_files/Event/city_fixer.dmm
  icons/obj/machines/body_preservation.dmi
Labels: Feature, Mapping, Expansion, Isolated Code

#2414 5th Pack Rooster Buff and Raccoon Sniper
  ModularTegustation/Teguicons/lc13_weapons.dmi
  code/game/objects/items/ego_weapons/non_abnormality/rcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/rcorp_assault.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/rcorp/fifthpack/raccoon.dm
  code/modules/jobs/jobs.dm
  code/modules/projectiles/ammunition/energy/lc_ammo.dm
  code/modules/projectiles/projectile/beams.dm
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/hud.dmi
  icons/obj/card.dmi
Labels: Balance, Feature, Side content

#2389 Mobcommander Subsystem[DONE]
  code/controllers/subsystem/mobcommander.dm
  code/datums/components/ai_leadership.dm
  lobotomy-corp13.dme
Labels: Code improvement, Isolated Code

#2473 Emergency PR
  code/modules/mob/living/carbon/human/life.dm
Labels: Fix

#2475 Nerf Gold Dawn Beanstalk Corrosion Damage
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/dawn.dm
Labels: Balance

#2477 Fixes workshop gautlets not checking if a target is qdeleted before its thrown, making a runtime
  ModularTegustation/tegu_items/workshop/templates/gauntlet.dm
Labels: Code improvement, Fix

#2470 plush update
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Tweak

#2476 Adds burn and tox damage visual indicators
  ModularTegustation/Teguicons/lc13_coloreffect.dmi
  code/game/objects/effects/temporary_visuals/effect_indicators.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Expansion

#2451 Jangsan now 100% scarier towards R-Corp infantry
  code/modules/mob/living/simple_animal/abnormality/he/jangsan.dm
Labels: Balance

#2480 Gives doctors better equipment
  _maps/map_files/Event/city.dmm
  _maps/map_files/Event/city_fixer.dmm
Labels: Balance, Side content

#2471 Organs now rot significantly slower.
  code/modules/mob/living/brain/brain_item.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/stomach.dm
Labels: Balance

#2472 Skill Rebalance
  ModularTegustation/tegu_items/associations/vending.dm
  code/game/objects/items/fixerskills/level1/defensive.dm
  code/game/objects/items/fixerskills/level1/healing.dm
  code/game/objects/items/fixerskills/level1/scavenger.dm
  code/game/objects/items/fixerskills/level2/butcher.dm
  code/game/objects/items/fixerskills/level2/lifesteal.dm
  code/game/objects/items/fixerskills/level3/battleready.dm
  code/game/objects/items/fixerskills/level3/bulletproof.dm
  code/game/objects/items/fixerskills/level4/kys.dm
  code/game/objects/items/fixerskills/level4/status_effects.dm
  code/game/objects/items/fixerskills/level4/team.dm
  code/game/objects/items/fixerskills/skills.dm
  icons/hud/screen_skills.dmi
  lobotomy-corp13.dme
Labels: Balance, Side content

#2489 Fixes Gluttony Peccatulum from One hit gibbing abnormalities, and adds more peccatulum to the spawnpool
  code/modules/jobs/job_types/labs/command/assetprot.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/brown/dawn.dm
Labels: Balance, Fix

#2456 New Community E.G.O.
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/ego_weapons/subtype/charge.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_armor.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_weapons.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_worn.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/_egodatum.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_armor.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_weapons.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/mob/living/simple_animal/abnormality/he/fan.dm
  code/modules/mob/living/turn_book.dm
  code/modules/projectiles/guns/ego_gun/special.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/projectiles.dmi
  sound/abnormalities/doomsdaycalendar/Effect_Burn.ogg
  sound/effects/burn.ogg
Labels: Code improvement, Expansion

#2493 Fixes my mistake with KK template
  _maps/templates/syndicate_office/kurokumosake.dmm
  code/game/objects/items/ego_weapons/non_abnormality/weak_edits/city.dm
Labels: Balance, Fix

#2495 Removes some items from J corp Lootboxes
  ModularTegustation/tegu_items/representative/items/jcorp.dm
Labels: Balance

#2494 Very very minor mapfixes with one typo fix sprinkled in
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Event/laboratory.dmm
  _maps/map_files/Theta/thetacorp.dmm
  _maps/templates/fixer_office/protectionfixers.dmm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
Labels: Fix, Mapping

#2496 Canto 7 Sprite additions
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/mob/clothing/ego_gear/limbus_suit.dmi
  icons/mob/clothing/ego_gear/neck.dmi
  icons/mob/clothing/ego_gear/under.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/lcuniform.dmi
  icons/obj/clothing/ego_gear/neck.dmi
Labels: Sprites

#2474 Moves the brain attributes into the body fabricator file for modularity, saves it on death instead of constantly re-saving it every life tick
  ModularTegustation/lc13_machinery.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Code improvement

#2485 Fixes black swan having no correct observation choices
  code/modules/mob/living/simple_animal/abnormality/waw/black_swan.dm
Labels: Fix

#2502 [Factorio 13] Adds Resource Wells
  ModularTegustation/Teguicons/factory.dmi
  ModularTegustation/tegu_items/rcorp_factory/_resourcewell.dm
  ModularTegustation/tegu_items/rcorp_factory/materials.dm
  ModularTegustation/tegu_items/rcorp_factory/temp_resource.dm
  lobotomy-corp13.dme
Labels: Feature

#2500 Makes the one singular violin in CC light enough to be picked up by the average clerk
  _maps/map_files/Beta/betacorp.dmm
Labels: Fix

#2505 pcorp bread factory
  ModularTegustation/tegu_items/rcorp_factory/lowfactories.dm
Labels: Side content

#2503 Zwei west armor
  ModularTegustation/tegu_items/refinery/crates/association.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/cinq.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/zwei.dm
Labels: Tweak

#2491 Mobwavespawner MK2 [DONE]
  ModularTegustation/lc13_structures.dm
  code/datums/components/monwave_spawners.dm
Labels: Tweak

#2508 Sentience Potion no longer affects Abnormalities
  code/modules/research/xenobiology/xenobiology.dm
Labels: Fix

#2486 Fixes faelantern lowering qliphoth if you are below 2 temperance regardless of the work
  code/modules/mob/living/simple_animal/abnormality/teth/faelantern.dm
Labels: Fix

#2511 fishmael sprite
  ModularTegustation/fishing/icons/fish_sprites.dmi
Labels: Sprites

#2509 Can no longer Mind Transferrance potion into abnormalities
  code/modules/research/xenobiology/xenobiology.dm
Labels: Fix

#2515 Mid-High Factories
  ModularTegustation/Teguicons/factory.dmi
  ModularTegustation/tegu_items/rcorp_factory/_factory.dm
  ModularTegustation/tegu_items/rcorp_factory/_resourcewell.dm
  ModularTegustation/tegu_items/rcorp_factory/lowfactories.dm
  ModularTegustation/tegu_items/rcorp_factory/materials.dm
Labels: Expansion, Side content

#2516 Workshop Weapon Upgrades
  ModularTegustation/tegu_items/workshop/_templates.dm
Labels: Expansion, Side content

#2520 Jill no longer sells you air when buying drones[BUGFIX]
  ModularTegustation/tegu_items/representative/research/kcorp.dm
Labels: Fix

#2522 Makes the bot stop telling people who do `!tgs status` or `!tgs check` that the next ordeal will be dawn during R-corp
  code/modules/admin/chat_commands.dm
Labels: Side content

#2525 Fixes HR only telling people the current core suppression and next ordeal if an ordeal is currently in progress
  code/modules/admin/chat_commands.dm
Labels: Fix

#2461 Reworks how the possession blacklist is handled, Admins can now disable possessing on individual abnormalities.
  ModularTegustation/misc_procs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
Labels: Code improvement

#2487 Cleans up handmaiden's code a little bit
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/noon.dm
Labels: Code improvement

#2524 Removes invisible walls from B-facility
  _maps/map_files/Beta/betacorp.dmm
Labels: Fix, Mapping
