Repository vlggms/lobotomy-corp13, pull requests merged in 2024-03, with the labels that each got.

#1977 Pruning misinformation from Cherry Tree record
  code/modules/paperwork/records/info/teth.dm
Labels: Writing

#1976 Removes Miasma Producing Rot Component
  code/__DEFINES/atmospherics.dm
  code/datums/components/rot.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/dummy.dm
  lobotomy-corp13.dme
Labels: Tweak, Removal

#1978 Removes xenomorph embryos from City of Light.
  code/game/objects/effects/spawners/lootdrop.dm
Labels: Removal

#1921 Mermaid Qliphoth Counter lose due to her crown cannot happen while working her as the lover
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
Labels: Fix

#1933 Radio only job title abbreviations
  code/datums/datacore.dm
  code/game/say.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/manager.dm
  code/modules/jobs/job_types/trusted_players/representative.dm
  code/modules/jobs/job_types/trusted_players/sephirah.dm
  code/modules/mob/living/carbon/human/human_say.dm
  code/modules/mob/say_readme.md
Labels: Feature

#1980 Removes autodrobes from maps with them
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/Iota/iotacorp.dmm
  _maps/map_files/Kappa/kappacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
Labels: Mapping, Removal

#1981 Fixes a bug with K-Corp armor purchase and N-Corp fading ampule purchase.
  ModularTegustation/tegu_items/representative/research/kcorp.dm
  ModularTegustation/tegu_items/representative/research/ncorp.dm
Labels: Fix

#1972 Shield bullet buffs and sp bullet nerf
  code/datums/facility_upgrade.dm
  code/game/machinery/computer/manager_camera.dm
Labels: Balance

#1985 re-names rose sign's ego
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
Labels: Writing

#1983 letters lie fix
  code/modules/paperwork/records/info/zayin.dm
Labels: Writing

#1982 Weapon jump attack bug fix
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/he/happy_teddy_bear.dm
  code/modules/mob/living/simple_animal/abnormality/he/headless_ichthys.dm
  code/modules/mob/living/simple_animal/abnormality/he/missed_reaper.dm
  code/modules/mob/living/simple_animal/abnormality/he/norinori.dm
  code/modules/mob/living/simple_animal/abnormality/teth/beanstalk.dm
  code/modules/mob/living/simple_animal/abnormality/teth/blood_bath.dm
  code/modules/mob/living/simple_animal/abnormality/teth/book.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_long_legs.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/sleeping_beauty.dm
Labels: Fix

#1996 No More Wormfood Vomit
  ModularTegustation/tegufood.dm
Labels: Tweak

#1988 Representative QoL Changes
  _maps/map_files/generic/CentCom.dmm
  code/game/machinery/computer/manager_camera.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/jobs/job_types/trusted_players/representative.dm
Labels: Balance

#1992 uses even more span wrappers on stuff because god why
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/fixer_weaponry/swords.dm
  code/game/objects/items/fixerskills/level2/confusion.dm
  code/game/objects/items/fixerskills/level2/flashbang.dm
  code/game/objects/items/fixerskills/level3.dm
  code/game/objects/items/fixerskills/level3/battleready.dm
  code/game/objects/items/fixerskills/level3/bulletproof.dm
  code/game/objects/items/fixerskills/level3/hud.dm
  code/game/objects/items/fixerskills/level4/healing.dm
  code/game/objects/items/fixerskills/skills.dm
Labels: Code improvement

#1984 More Siltcurrent fixes and changes
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/siltcurrent.dm
Labels: Fix

#1994 Lantern fix
  code/game/objects/items/ego_weapons/teth.dm
Labels: Fix

#1890 changes animalism
  code/game/objects/items/ego_weapons/waw.dm
Labels: Balance

#1986 Big and Will be Bad Wolf hp and work damage nerf
  code/modules/mob/living/simple_animal/abnormality/waw/big_wolf.dm
Labels: Balance

#1998 Makes Bread Smite make Bong Bongs into bongbread
  code/modules/admin/smites/bread.dm
Labels: Tweak

#1962 More abno portraits
  code/game/machinery/computer/abnormality_portraits.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/last_shot.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/space_lady.dm
  code/modules/mob/living/simple_animal/abnormality/he/KHz.dm
  code/modules/mob/living/simple_animal/abnormality/he/eris.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_queen.dm
  code/modules/mob/living/simple_animal/abnormality/he/watchman.dm
  code/modules/mob/living/simple_animal/abnormality/he/will_you_play.dm
  code/modules/mob/living/simple_animal/abnormality/teth/falada.dm
  code/modules/mob/living/simple_animal/abnormality/teth/redblooded.dm
  code/modules/mob/living/simple_animal/abnormality/teth/simple_smile.dm
  code/modules/mob/living/simple_animal/abnormality/waw/apex_predator.dm
  code/modules/mob/living/simple_animal/abnormality/waw/contract.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  icons/UI_Icons/abnormality_portraits/apex.png
  icons/UI_Icons/abnormality_portraits/contract.png
  icons/UI_Icons/abnormality_portraits/eris.png
  icons/UI_Icons/abnormality_portraits/falada.png
  icons/UI_Icons/abnormality_portraits/khz.png
  icons/UI_Icons/abnormality_portraits/last_shot.png
  icons/UI_Icons/abnormality_portraits/red_blooded_american.png
  icons/UI_Icons/abnormality_portraits/red_queen.png
  icons/UI_Icons/abnormality_portraits/shrimp_executive.png
  icons/UI_Icons/abnormality_portraits/simple_smile.png
  icons/UI_Icons/abnormality_portraits/space.png
  icons/UI_Icons/abnormality_portraits/watchman.png
  icons/UI_Icons/abnormality_portraits/will_you_play.png
Labels: Sprites

#2010 Jangsan Tigger Playable Button 2nd try
  code/modules/mob/living/simple_animal/abnormality/he/jangsan.dm
  icons/mob/actions/actions_abnormality.dmi
Labels: Feature, Side content

#2000 Returns Adventure Console Defines to Numbers
  ModularTegustation/_adventure_console/adventure_layout.dm
  code/__DEFINES/~lobotomy_defines/adventure.dm
Labels: Fix

#2005 Adds Profile Selection and Password Lock to Adventure Console
  ModularTegustation/_adventure_console/console.dm
Labels: Expansion

#1954 Amber ordeal changes and balancing
  ModularTegustation/Teguicons/224x128.dmi
  code/__DEFINES/traits.dm
  code/datums/elements/climbable.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/ordeals/amber_ordeals.dm
  code/modules/ordeals/crimson_ordeals.dm
  code/modules/ordeals/green_ordeals.dm
  code/modules/ordeals/indigo_ordeals.dm
  code/modules/ordeals/violet_ordeals.dm
  code/modules/ordeals/white_ordeals.dm
  sound/effects/ordeals/amber/dawn_attack.ogg
  sound/effects/ordeals/amber/dawn_dead.ogg
  sound/effects/ordeals/amber/dawn_dig_in.ogg
  sound/effects/ordeals/amber/dawn_dig_out.ogg
  sound/effects/ordeals/amber/dusk_create.ogg
Labels: Balance, Tweak, Merge Date Set

#2012 Removes an N-Word in our code that violated Github TOS.
  code/game/objects/items/grenades/smokebomb.dm
Labels: Writing

#1958 Tweaks Naked Nest Cure Sources
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
Labels: Tweak

#1989 Reworks u-turn and voodoo
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
Labels: Balance

#1947 KQE Damage Coeff Fix
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
Labels: Fix

#2002 Flame and Metal Fixers
  ModularTegustation/Teguicons/tegumobs.dmi
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  icons/obj/projectiles.dmi
Labels: Feature

#1881 Abnormality abilities can now hit rhinos
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
  code/modules/mob/living/simple_animal/abnormality/he/headless_ichthys.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/he/wayward_passenger.dm
  code/modules/mob/living/simple_animal/abnormality/waw/apex_predator.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_wolf.dm
  code/modules/mob/living/simple_animal/abnormality/waw/black_swan.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yin.dm
Labels: Tweak, Fix

#2013 Makes knockback a variable on all EGO weapons, attack_speed variable clean up and correcting bad descriptions
  code/__DEFINES/~lobotomy_defines/weapon.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/ego_weapons/teth.dm
  lobotomy-corp13.dme
Labels: Code improvement, Refactor

#1838 Optional Abnormality Boss Summon Items [DONE]
  ModularTegustation/tegu_items/lc13boss_summon.dm
  icons/obj/bureaucracy.dmi
  lobotomy-corp13.dme
Labels: Feature

#1975 Fort Insanity fixes and improvements
  code/__DEFINES/ai.dm
  code/__HELPERS/AStar.dm
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/ai/sanity/sanityloss_behaviors.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/structures/railings.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/projectiles/guns/ego_gun.dm
Labels: Tweak, Fix

#1734 Money for Torsos
  ModularTegustation/lc13_machinery.dm
  icons/mob/hivebot.dmi
Labels: Feature

#1769 Adds Memories from a Better Time [DONE?]
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/tegu_effects10x10.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/game/machinery/computer/abnormality_portraits.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/better_memories.dm
  code/modules/paperwork/records/info/he.dm
  icons/UI_Icons/abnormality_portraits/better_memories.png
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Abnormality
