Repository vlggms/lobotomy-corp13, pull requests merged in 2024-05, with the labels that each got.

#1949 Bug Fixes and Monitoring
  code/__HELPERS/game.dm
  code/__HELPERS/icon_smoothing.dm
  code/_onclick/hud/alien.dm
  code/_onclick/hud/generic_dextrous.dm
  code/_onclick/hud/guardian.dm
  code/_onclick/hud/hud.dm
  code/datums/components/_component.dm
  code/datums/quirks/negative.dm
  code/game/atoms_movable.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/game/turfs/change_turf.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/projectiles/projectile.dm
  code/modules/shuttle/arrivals.dm
Labels: Code improvement, Fix

#2044 Extraction Shipments
  code/game/machinery/computer/abnormality_ego.dm
Labels: Balance

#2096 fixes some abnos not returning an initialize() hint
  ModularTegustation/tegu_items/refinery/crates/_crate.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/mob/living/simple_animal/abnormality/waw/red_riding_mercenary.dm
Labels: Fix

#2105 Vermillion no longer gains damage and healing from corpses and friendly naked nest serpents
  code/game/objects/items/ego_weapons/non_abnormality/color_fixer.dm
Labels: Fix

#2059 Minor U-Corp content additions
  ModularTegustation/fishing/code/fish/LC13_fish/saltwater_fish.dm
  ModularTegustation/fishing/icons/fish_sprites.dmi
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/ucorp.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  lobotomy-corp13.dme
Labels: Tweak

#2064 Ports Compost Bin and Rake for more cost effective farming
  ModularTegustation/Teguicons/farming_structures.dmi
  ModularTegustation/primitive_farming/farming_structures.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  lobotomy-corp13.dme
Labels: Feature

#2100 Lattice Change
  code/game/objects/structures/lattice.dm
Labels: Balance, Fix

#2082 Minor Contract buffs
  code/modules/mob/living/simple_animal/abnormality/waw/contract.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Balance

#2090 Harvestable Bushes
  ModularTegustation/fishing/code/turfs.dm
  ModularTegustation/harvestable_gardens.dm
  code/modules/mining/lavaland/ash_flora.dm
  icons/obj/hydroponics/harvest.dmi
  icons/obj/lavaland/ash_flora.dmi
  lobotomy-corp13.dme
Labels: Feature, Tweak

#2101 HurtInTurf improvements
  code/__HELPERS/mobs.dm
  code/game/objects/structures/lattice.dm
Labels: Code improvement

#2077 Wounded Courage lets you dual wield Blind Rage
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/realized.dm
Labels: Tweak

#2086 FISHING 4.0
  ModularTegustation/fishing/code/fish/LC13_fish/freshwater_fish.dm
  ModularTegustation/fishing/code/fish/LC13_fish/saltwater_fish.dm
  ModularTegustation/fishing/code/fish/freshwater_fish.dm
  ModularTegustation/fishing/code/fish/misc_fish.dm
  ModularTegustation/fishing/code/fish/saltwater_fish.dm
  ModularTegustation/fishing/code/fish_market.dm
  ModularTegustation/fishing/code/fishcooking/fishfood.dm
  ModularTegustation/fishing/code/fishcooking/fishmachines/_fishmachines.dm
  ModularTegustation/fishing/code/fishcooking/fishmachines/fish_cookers.dm
  ModularTegustation/fishing/code/fishcooking/fishmachines/sushi.dm
  ModularTegustation/fishing/code/fishcooking/fishmeat.dm
  ModularTegustation/fishing/code/fishing_items/fishing_net.dm
  ModularTegustation/fishing/code/fishing_items/fishing_rod.dm
  ModularTegustation/fishing/code/rod_components/fishing_lines.dm
  ModularTegustation/fishing/code/turfs.dm
  ModularTegustation/fishing/icons/fish_sprites.dmi
  ModularTegustation/fishing/icons/fishing.dmi
  ModularTegustation/fishing/icons/fishmachines.dmi
  _maps/map_files/Zeta/zetacorp.dmm
  code/game/objects/items/food/meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm
  icons/obj/food/fish.dmi
  icons/obj/food/food.dmi
  icons/obj/food/seafood.dmi
  lobotomy-corp13.dme
Labels: Expansion, Side content

#2103 Imports Fish from Shiptest
  ModularTegustation/fishing/code/fish/freshwater_fish.dm
  ModularTegustation/fishing/code/turfs.dm
  ModularTegustation/fishing/icons/fish_sprites.dmi
Labels: Expansion

#2047 Limbus Labs Additions
  ModularTegustation/tegu_items/limbus_labs/!abno_overwrites.dm
  ModularTegustation/tegu_items/limbus_labs/!other_overwrites.dm
  ModularTegustation/tegu_items/limbus_labs/spawners.dm
  _maps/map_files/Event/laboratory.dmm
  code/modules/jobs/job_types/labs/research/paperwork.dm
  code/modules/jobs/job_types/labs/security/highsec.dm
  code/modules/jobs/job_types/labs/security/lowsec.dm
  code/modules/jobs/job_types/labs/support/janitor.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/abnormality/he/eris.dm
  code/modules/mob/living/simple_animal/abnormality/he/galaxy_child.dm
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
  code/modules/mob/living/simple_animal/abnormality/teth/forsaken_murderer.dm
  code/modules/mob/living/simple_animal/abnormality/teth/scorched_girl.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clouded_monk.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/paperwork/barriertape.dm
Labels: Expansion, Side content

#1736 Jester of Nihil Part 2 (of 3)
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Teguicons/64x64.dmi
  code/controllers/subsystem/lobotomy_events.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nihil.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yin.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/misc.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
Labels: Expansion

#2108 Jar Icon fix
  code/modules/reagents/reagent_containers/glass.dm
Labels: Fix

#2049 You should AFK yourself... NOW -- Ports soft-ping fixes from TG, AKF players kicked from lobby, SSD indicators
  ModularTegustation/ssd_indicator/code/mob.dm
  ModularTegustation/ssd_indicator/icons/ssd_indicator.dmi
  ModularTegustation/ssd_indicator/readme.md
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/ping.dm
  code/game/machinery/cryopod.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/death.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui/tgui_window.dm
  lobotomy-corp13.dme
  tgui/packages/tgui-panel/game/constants.js
  tgui/packages/tgui-panel/game/middleware.js
  tgui/packages/tgui-panel/ping/actions.js
  tgui/packages/tgui-panel/ping/constants.js
  tgui/packages/tgui-panel/ping/middleware.js
  tgui/packages/tgui-panel/ping/reducer.js
  tgui/packages/tgui/backend.js
Labels: Feature

#2112 You can now call KQE-1j-23 a dumbass
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
Labels: Tweak

#2113 Ports ghost runechat
  code/modules/mob/mob_say.dm
Labels: Tweak

#2119 Lantern Weapon Fix
  code/game/objects/items/ego_weapons/teth.dm
Labels: Fix

#2114 All-around Helper is now all-around weaker
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
Labels: Balance

#2116 Fish Slime is now properly labelled
  ModularTegustation/fishing/code/fishcooking/fishmeat.dm
Labels: Writing

#2066 Don't forget... the button incident
  ModularTegustation/Teguicons/button_counter.dmi
  ModularTegustation/lc13_structures.dm
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Event/skeld.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/Iota/iotacorp.dmm
  _maps/map_files/Kappa/kappacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  code/__DEFINES/directional.dm
  code/controllers/subsystem/persistence.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/touch.dm
  lobotomy-corp13.dme
Labels: Feature, Sprites

#2068 Pino ai fix
  code/datums/ai/sanity/sanityloss_behaviors.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
Labels: Code improvement, Fix

#2126 Fixes Jangsan
  code/modules/mob/living/simple_animal/abnormality/he/jangsan.dm
Labels: Fix

#2125 Finally Fixes Letters
  code/modules/mob/living/simple_animal/abnormality/zayin/pile_of_mail.dm
  code/modules/paperwork/records/info/zayin.dm
Labels: Fix

#2123 Aoe Weapon Fix
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
Labels: Fix

#2110 Makes QoH Compatible for LCL (And Some Bugfixes+Balancing)
  ModularTegustation/tegu_items/limbus_labs/!abno_overwrites.dm
  ModularTegustation/tegu_items/limbus_labs/!other_overwrites.dm
  ModularTegustation/tegu_items/limbus_labs/spawners.dm
  code/modules/mob/living/simple_animal/abnormality/he/steam_transport_machine.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
Labels: Tweak, Side content

#2124 KQE work adjustments
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/paperwork/records/info/he.dm
  lobotomy-corp13.dme
Labels: Balance

#2127 Adds Fishhook Fixers to LAKES Facility
  _maps/epsiloncorp.json
  _maps/map_files/Epsilon/epsiloncorp.dmm
Labels: Tweak, Mapping

#2038 Green & Indigo Dawn Overhaul
  ModularTegustation/Teguicons/32x48.dmi
  code/__DEFINES/lobotomy_corp.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo/dawn.dm
  code/modules/ordeals/_ordealtypes.dm
  code/modules/ordeals/green_ordeals.dm
  code/modules/ordeals/indigo_ordeals.dm
  lobotomy-corp13.dme
Labels: Feature

#2107 Updates Lady out of Space
  code/modules/mob/living/simple_animal/abnormality/aleph/space_lady.dm
  code/modules/paperwork/records/info/aleph.dm
Labels: Tweak

#2136 Facility Minor Tweaks
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/Iota/iotacorp.dmm
  _maps/map_files/Kappa/kappacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Psi/psicorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
Labels: Fix, Mapping

#2120 RCorp Escort the Payload Objective
  ModularTegustation/tegu_items/rcorp/objective.dm
  _maps/RandomRooms/rcorp/caves/pit.dmm
  _maps/map_files/Event/rcorp.dmm
  code/controllers/subsystem/maptype.dm
  code/datums/reusable_visual_pool.dm
  code/game/gamemodes/management/event/combat.dm
  code/game/objects/effects/reusable_visual.dm
  code/modules/mob/payload/payload.dm
  lobotomy-corp13.dme
Labels: Feature, Side content

#2137 Events now have Custom Battle Coin Rewards
  ModularTegustation/_adventure_console/adventure_events/_event.dm
  ModularTegustation/_adventure_console/adventure_events/general/quiz.dm
  code/__DEFINES/~lobotomy_defines/adventure.dm
  lobotomy-corp13.dme
Labels: Tweak

#2144 Fixes the button counter not properly updating its overlays
  ModularTegustation/lc13_structures.dm
Labels: Fix

#2142 Advancements in K-Corp technology allows city citizens to heal OTHERS more at the 9 PM news segment.
  ModularTegustation/tegu_items/representative/items/kcorp.dm
Labels: Fix

#2145 makes pallid fish actually optainable
  ModularTegustation/fishing/code/turfs.dm
Labels: Tweak

#2133 Gives Cinq a hat
  code/modules/clothing/suits/ego_gear/non_abnormality/cinq.dm
  icons/mob/clothing/ego_gear/head.dmi
Labels: Tweak

#2143 S Corp Gacha Changes
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/refinery/sales.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/pill.dm
Labels: Tweak

#2132 Melting Love display status effect and tweaks [DONE]
  ModularTegustation/Teguicons/tegu_effects10x10.dmi
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
  code/modules/mob/living/simple_animal/abnormality/waw/parasite_tree.dm
Labels: Code improvement

#2109 Adds new tool E.G.O.
  code/datums/abnormality/_ego_datum/tools.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/modules/clothing/suits/ego_gear/tools.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/shelter.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/waw/clock.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/touch.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/you_happy.dm
  icons/mob/clothing/ego_gear/abnormality/tools.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/tools.dmi
  icons/obj/ego_weapons.dmi
Labels: Sprites, Expansion

#2146 S-Corp Fishing Rod
  ModularTegustation/fishing/code/fishing_items/fishing_rod.dm
  ModularTegustation/fishing/icons/fishing.dmi
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
Labels: Tweak

#2091 Mob Speed Improvements
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
  code/__DEFINES/movespeed_modification.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/army_in_black.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/crying_children.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
  code/modules/mob/living/simple_animal/abnormality/teth/so_that_no_cry.dm
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
  code/modules/mob/living/simple_animal/distortion/plague/bunnyman.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/movespeed/_movespeed_modifier.dm
  code/modules/movespeed/modifiers/mobs.dm
  code/modules/spells/ability_types/realized.dm
  code/modules/spells/ability_types/realized_aimed.dm
Labels: Code improvement

#2148 LOB points research for Main Office Representative
  ModularTegustation/tegu_items/representative/research/lcorp.dm
Labels: Expansion

#2140 EGO Gift Extractor
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/representative/research/lcorp.dm
Labels: Feature

#2150 Fish Refinery
  ModularTegustation/fishing/code/fishing_items/fishing_refinery.dm
  ModularTegustation/fishing/icons/fishmachines.dmi
  lobotomy-corp13.dme
Labels: Expansion

#2151 Fix Memories 0 Qliphoth
  code/modules/mob/living/simple_animal/abnormality/he/better_memories.dm
Labels: Fix

#2149 Fire damage runtime fix
  code/modules/mob/living/simple_animal/_damage_coeff.dm
  code/modules/mob/living/simple_animal/damage_coeff_helper.dm
  code/modules/mob/living/simple_animal/damage_procs.dm
Labels: Fix

#2152 Add Visual Flash to Better Memories
  code/modules/mob/living/simple_animal/abnormality/he/better_memories.dm
Labels: Tweak

#2154 No skip crimson ordeal
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson.dm
Labels: Balance

#2153 K Corp Drones Flash
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
Labels: Tweak

#2155 FIX : Main office rep lob points research
  ModularTegustation/tegu_items/representative/research/lcorp.dm
Labels: Fix

#2161 Smoothing and fullauto runtime fixes
  code/datums/components/fullauto.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed/_closed.dm
Labels: Fix

#2051 Changes charge to be a variable on the base EGO weapon instead of its own subtype
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/refinery/crates/workshop.dm
  ModularTegustation/tegu_items/representative/console.dm
  ModularTegustation/tegu_items/representative/outfits.dm
  ModularTegustation/tegu_items/representative/research/wcorp.dm
  ModularTegustation/tegu_items/workshop/templates/chargeblade.dm
  code/__DEFINES/~lobotomy_defines/weapon.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/_lists.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/joke.dm
  code/game/objects/items/ego_weapons/non_abnormality/_charge.dm
  code/game/objects/items/ego_weapons/non_abnormality/cane.dm
  code/game/objects/items/ego_weapons/non_abnormality/rosespanner.dm
  code/game/objects/items/ego_weapons/non_abnormality/wcorp.dm
  code/game/objects/items/ego_weapons/subtype/charge.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/jobs/job_types/wcorp/wcorpl1.dm
  code/modules/jobs/job_types/wcorp/wcorpl2.dm
  code/modules/jobs/job_types/wcorp/wcorpl3.dm
  code/modules/jobs/job_types/wcorp/wcorprecon.dm
  code/modules/jobs/job_types/wcorp/wcorpshield.dm
  code/modules/jobs/job_types/wcorp/wcorpspear.dm
  lobotomy-corp13.dme
Labels: Code improvement, Fix

#1528 Adds Cinderella's Pumpkin Carraige
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/96x96.dmi
  code/game/objects/effects/abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cinderella.dm
  code/modules/paperwork/records/info/teth.dm
  lobotomy-corp13.dme
  sound/abnormalities/cinderella/bell.ogg
  sound/abnormalities/cinderella/carriage_loop.ogg
  sound/abnormalities/cinderella/horse1.ogg
  sound/abnormalities/cinderella/horse2.ogg
Labels: Abnormality

#2163 Nerfs Double Spear Doubts
  code/modules/mob/living/simple_animal/hostile/ordeal/green/dawn.dm
Labels: Balance

#2162 Rhino tweak
  code/__DEFINES/mecha.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/rhino.dm
  code/modules/vehicles/mecha/mech_melee_attack.dm
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Tweak

#2159 Gives solemn eulogy an ability
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
Labels: Tweak

#2094 They can hear you breathe, you can no longer hide forever. -- Makes lockers/crates hide you from abnormalities on a % chance instead of guaranteed
  ModularTegustation/hiding/abnormality.dm
  ModularTegustation/hiding/closet.dm
  ModularTegustation/hiding/turf.dm
  lobotomy-corp13.dme
Labels: Balance

#2135 Adds new EO text adventure events
  ModularTegustation/_adventure_console/adventure_events/abnormality/aleph/giant.dm
  ModularTegustation/_adventure_console/adventure_events/abnormality/he/tsa_woods.dm
  ModularTegustation/_adventure_console/adventure_events/abnormality/waw/thunder_bird.dm
  lobotomy-corp13.dme
Labels: Writing, Expansion

#2165 Apex predator can recloak
  code/modules/mob/living/simple_animal/abnormality/waw/apex_predator.dm
Labels: Balance

#2157 Abnormality Plushie Exctractor
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/representative/research/lcorp.dm
  icons/obj/device.dmi
Labels: Feature

#2168 Returns Braincake to the Hungry Masses
  code/game/objects/items/granters.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
Labels: Tweak

#2048 City Fixers - A Dungeon Crawling PVE gamemode
  ModularTegustation/tegu_items/associations/!overwrites.dm
  ModularTegustation/tegu_items/associations/items.dm
  _maps/RandomRooms/backstreetlayout/lcorp.dmm
  _maps/cityfixers.json
  _maps/map_files/Event/city_fixer.dmm
  code/controllers/subsystem/city_events.dm
  code/controllers/subsystem/maptype.dm
  code/game/gamemodes/management/event/combat.dm
  code/game/objects/items/crayons.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/shi.dm
  code/modules/jobs/job_types/city/HHPP.dm
  code/modules/jobs/job_types/city/civilian.dm
  code/modules/jobs/job_types/city/doctor.dm
  code/modules/jobs/job_types/city/workshop.dm
  code/modules/jobs/job_types/trusted_players/association/roaming.dm
  code/modules/jobs/job_types/trusted_players/hana.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/_ordeal.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/power/lighting.dm
  code/modules/unit_tests/combat.dm
  config/maps.txt
  lobotomy-corp13.dme
Labels: Side content

#2175 New Lobotomite Wood Walls
  icons/turf/walls/wood_wall.dmi
Labels: Sprites

#2167 Minor Sprite fixes
  code/modules/mob/living/simple_animal/hostile/ordeal/gold.dm
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
Labels: Fix, Sprites

#2176 Fishmaxxing 2 DDS edition
  ModularTegustation/fishing/code/turfs.dm
Labels: Expansion

#2065 Adds the abnormality core system
  ModularTegustation/Teguicons/abno_cores/aleph.dmi
  ModularTegustation/Teguicons/abno_cores/he.dmi
  ModularTegustation/Teguicons/abno_cores/template.dmi
  ModularTegustation/Teguicons/abno_cores/teth.dmi
  ModularTegustation/Teguicons/abno_cores/tool.dmi
  ModularTegustation/Teguicons/abno_cores/waw.dmi
  ModularTegustation/Teguicons/abno_cores/zayin.dmi
  ModularTegustation/Tegusounds/abno_extract.ogg
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/abno_cores.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/better_memories.dm
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/mob/living/simple_animal/abnormality/he/drifting_fox.dm
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/mob/living/simple_animal/abnormality/he/headless_ichthys.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/mob/living/simple_animal/abnormality/teth/book.dm
  code/modules/mob/living/simple_animal/abnormality/teth/faelantern.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_long_legs.dm
  code/modules/mob/living/simple_animal/abnormality/teth/scorched_girl.dm
  code/modules/mob/living/simple_animal/abnormality/teth/skin_prophet.dm
  code/modules/mob/living/simple_animal/abnormality/waw/contract.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/luna.dm
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
  code/modules/mob/living/simple_animal/abnormality/waw/rose_sign.dm
  code/modules/mob/living/simple_animal/abnormality/waw/siltcurrent.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/paperwork/records/info/_info.dm
  lobotomy-corp13.dme
Labels: Feature

#2177 Fixes oversight in non-standard weapon charging and wayward having a useless attack_speed variable
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/subtype/charge.dm
Labels: Fix

#2160 The Very Popular Jar Update
  code/datums/components/crafting/recipes/tools.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
Labels: Feature, Fix

#2111 Allows for randomized gamemodes in the future
  code/controllers/subsystem/ticker.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/army_in_black.dm
Labels: Feature

#2092 New Spawners
  ModularTegustation/lc13_spawners.dm
Labels: Feature

#2022 Makes secret abnormality skins into variables and a proc on the base abnormality
  ModularTegustation/tegu_items/debug_items.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
  code/modules/mob/living/simple_animal/abnormality/teth/pale_horse.dm
  code/modules/mob/living/simple_animal/abnormality/teth/training_rabbit.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dreaming_current.dm
  code/modules/mob/living/simple_animal/abnormality/waw/sphinx.dm
Labels: Code improvement, Refactor

#2172 Training Officer, our Equivalent of SEA
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/trusted.dm
  code/__DEFINES/jobs.dm
  code/__HELPERS/global_lists.dm
  code/controllers/subsystem/job.dm
  code/game/machinery/computer/card.dm
  code/modules/client/preferences.dm
  code/modules/clothing/suits/armor.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/mentor/trainingofficer.dm
  code/modules/jobs/job_types/suppression.dm
  code/modules/jobs/job_types/trusted_players/representative.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  icons/mob/clothing/suit.dmi
  icons/mob/hud.dmi
  icons/obj/card.dmi
  icons/obj/clothing/suits.dmi
  lobotomy-corp13.dme
Labels: Feature

#2171 Fixes broken crown
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/spells/ability_types/realized.dm
Labels: Balance

#2156 Misc Ego changes
  code/datums/abnormality/_ego_datum/tools.dm
  code/datums/abnormality/_ego_datum/zayin.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/modules/clothing/suits/ego_gear/special.dm
  code/modules/clothing/suits/ego_gear/tools.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/blubbering_toad.dm
  icons/mob/clothing/ego_gear/abnormality/zayin.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/zayin.dmi
  icons/obj/ego_weapons.dmi
Labels: Tweak, Sprites

#2180 Puts Community and Joke abnormalities into their own folders.
  code/__DEFINES/abnormalities.dm
  code/datums/abnormality/_ego_datum/aleph.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/_info.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_armor.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_weapons.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_worn.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/_egodatum.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/aleph/crying_children.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_armor.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_weapons.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_armor.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_weapons.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_worn.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/_egodatum.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/aleph/barkley.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/aleph/rudolta_buff.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_armor.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_guns.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_weapons.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/zayin/riblin.dm
  code/modules/projectiles/ammunition/ego_ammunition/zayin.dm
  code/modules/projectiles/projectile/ego_bullets/zayin.dm
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/mob/clothing/ego_gear/abnormality/zayin.dmi
  icons/obj/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/clothing/ego_gear/abnormality/zayin.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Code improvement
