Repository vlggms/lobotomy-corp13, pull requests merged in 2024-04, with the labels that each got.

#2020 Adventure console exchange shop and tweaks
  ModularTegustation/_adventure_console/adventure_layout.dm
  ModularTegustation/_adventure_console/console.dm
  code/__DEFINES/~lobotomy_defines/adventure.dm
Labels: Expansion

#2021 Gacha is now always worth it + better odds on some crates + rcorp addition
  ModularTegustation/tegu_items/refinery/crates/_crate.dm
  ModularTegustation/tegu_items/refinery/crates/association.dm
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/refinery/crates/misc.dm
  ModularTegustation/tegu_items/refinery/crates/workshop.dm
  ModularTegustation/tegu_items/refinery/sales.dm
Labels: Balance

#2018 Der Freischutz stops skipping leg day and can now walk (and gun) (with knuckles)
  ModularTegustation/Teguicons/32x64.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/96x64.dmi
  ModularTegustation/tegu_items/rcorp/landmarks.dm
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
  icons/effects/beam.dmi
  icons/mob/actions/actions_abnormality.dmi
Labels: Expansion, Side content

#2024 Makes Porccubus able to dash on any tile, adds it to Rcorp
  ModularTegustation/tegu_items/rcorp/!abno_overwrites.dm
  ModularTegustation/tegu_items/rcorp/landmarks.dm
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
Labels: Expansion, Side content

#2023 Adventure Console Content Update 1
  ModularTegustation/_adventure_console/adventure_events/abnormality/teth/forsaken_murderer.dm
  ModularTegustation/_adventure_console/adventure_events/abnormality/teth/old_lady.dm
  ModularTegustation/_adventure_console/adventure_events/abnormality/teth/scorched_girl.dm
  ModularTegustation/_adventure_console/adventure_events/general/jazz_end.dm
  ModularTegustation/_adventure_console/adventure_events/general/legacy.dm
  ModularTegustation/_adventure_console/adventure_events/general/quiz.dm
  ModularTegustation/_adventure_console/adventure_events/general/sinking_bell.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/allaround_cleaner.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/ambling_pearl.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/ardor_blossom.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/blubbering_toad.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/chicken_strife.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/coffin_return.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/fourthfront_smokewar.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/golden_grip.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/kqe.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/lost_mind.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/monkey_tree.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/nymph.dm
  ModularTegustation/_adventure_console/adventure_events/limbus_company/poultry_passion_tango.dm
  code/__DEFINES/~lobotomy_defines/adventure.dm
  lobotomy-corp13.dme
Labels: Expansion

#2015 Fixer Sound Fixed
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
Labels: Tweak

#2007 Bong Bread Smite Fix
  code/modules/admin/verbs/randomverbs.dm
Labels: Fix

#2029 Fix crate not breaking if they roll cosmetic
  ModularTegustation/tegu_items/refinery/crates/_crate.dm
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
Labels: Fix

#2027 Abnormality weights now count for half of chance
  code/game/gamemodes/management/management.dm
Labels: Tweak

#1997 Extra Shrimp Lines
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
Labels: Tweak, Writing

#2016 Adds Charles Barkley and Riblin joke abnormalities
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/tegufood.dm
  code/datums/abnormality/_ego_datum/joke.dm
  code/game/machinery/computer/abnormality_portraits.dm
  code/game/objects/items/ego_weapons/joke.dm
  code/modules/clothing/suits/ego_gear/joke.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/barkley.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/riblin.dm
  code/modules/projectiles/ammunition/ego_ammunition/zayin.dm
  code/modules/projectiles/guns/ego_gun/joke.dm
  code/modules/projectiles/projectile/ego_bullets/zayin.dm
  icons/UI_Icons/abnormality_portraits/barkley.png
  icons/UI_Icons/abnormality_portraits/mcrib.png
  icons/mob/clothing/ego_gear/abnormality/zayin.dmi
  icons/obj/clothing/ego_gear/abnormality/zayin.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/food/food.dmi
  lobotomy-corp13.dme
  sound/abnormalities/mcrib/enjoy.ogg
  sound/abnormalities/mcrib/evillaugh.ogg
  sound/abnormalities/mcrib/mcrib.ogg
Labels: Abnormality, Expansion

#1639 Realization armor value rework
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
Labels: Balance

#2028 Adds fishhook fixers back
  _maps/map_files/Zeta/zetacorp.dmm
  _maps/zetacorp.json
Labels: Tweak

#1899 L-Corp Rep buff
  ModularTegustation/tegu_items/representative/research/lcorp.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/assistant.dm
Labels: Expansion

#2026 Will You Play Rework
  code/modules/mob/living/simple_animal/abnormality/he/will_you_play.dm
  code/modules/paperwork/records/info/he.dm
Labels: Tweak

#2014 Steel Ordeal III
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
  code/modules/ordeals/steel_ordeals.dm
Labels: Expansion

#1837 RCA minor changes
  ModularTegustation/tegu_items/rcorp/itemspawner.dm
  _maps/map_files/Event/rcorp.dmm
Labels: Balance, Side content

#2037 Adds a TGUI version of the sephirah panel as a button
  ModularTegustation/tegu_items/debug_items.dm
  code/modules/jobs/job_types/trusted_players/sephirah.dm
  tgui/packages/tgui/interfaces/SephirahPanel.js
Labels: Expansion

#1968 City of Light 3.0 Core
  ModularTegustation/Teguicons/refiner.dmi
  ModularTegustation/tegu_items/associations/items.dm
  ModularTegustation/tegu_items/associations/machines.dm
  ModularTegustation/tegu_items/associations/vending.dm
  _maps/RandomRooms/backstreetlayout/dungeon_backstreets.dmm
  _maps/city.json
  _maps/map_files/Event/city.dmm
  code/controllers/subsystem/city_events.dm
  code/game/objects/items/ego_weapons/non_abnormality/weak_edits/city.dm
  code/game/objects/items/ego_weapons/non_abnormality/zwei.dm
  code/game/objects/items/fixerskills/level1/defensive.dm
  code/game/objects/items/fixerskills/level1/scavenger.dm
  code/game/objects/items/fixerskills/level2/lifesteal.dm
  code/game/objects/items/fixerskills/level2/lockpick.dm
  code/game/objects/items/fixerskills/level4/dismember.dm
  code/game/objects/items/fixerskills/level4/status_effects.dm
  code/game/objects/items/fixerskills/level4/team.dm
  code/game/objects/items/food/meat.dm
  code/modules/jobs/job_types/city/backstreets_butcher.dm
  code/modules/jobs/job_types/city/carnival.dm
  code/modules/jobs/job_types/city/syndicate/blade_lineage/cutthroat.dm
  code/modules/jobs/job_types/trusted_players/hana.dm
  icons/hud/screen_skills.dmi
  lobotomy-corp13.dme
Labels: Expansion

#2041 Adventure Console Infinite Stats hotfix
  ModularTegustation/_adventure_console/adventure_events/_event.dm
Labels: Fix

#2042 Reduces the size of Stone Brick Floor's description.
  code/game/turfs/open/floor/misc_floor.dm
Labels: Writing

#2008 Limbus company Labs
  ModularTegustation/Teguicons/head_item.dmi
  ModularTegustation/Teguicons/head_worn.dmi
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/tegu_clothes_code/head.dm
  ModularTegustation/tegu_items/limbus_labs/!abno_overwrites.dm
  ModularTegustation/tegu_items/limbus_labs/!other_overwrites.dm
  ModularTegustation/tegu_items/limbus_labs/spawners.dm
  _maps/lclabs.json
  _maps/map_files/Event/laboratory.dmm
  code/controllers/subsystem/maptype.dm
  code/game/gamemodes/management/event/combat.dm
  code/game/objects/items/ego_weapons/non_abnormality/_ammoguns.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_labs.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/limbus_labs.dm
  code/modules/clothing/under/limbus_suits.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/labs/_information.dm
  code/modules/jobs/job_types/labs/command/assetprot.dm
  code/modules/jobs/job_types/labs/command/command.dm
  code/modules/jobs/job_types/labs/command/commandsec.dm
  code/modules/jobs/job_types/labs/command/infotech.dm
  code/modules/jobs/job_types/labs/medical/chemist.dm
  code/modules/jobs/job_types/labs/medical/cmo.dm
  code/modules/jobs/job_types/labs/medical/nurse.dm
  code/modules/jobs/job_types/labs/medical/paramedic.dm
  code/modules/jobs/job_types/labs/medical/surgeon.dm
  code/modules/jobs/job_types/labs/research/clerk.dm
  code/modules/jobs/job_types/labs/research/lead.dm
  code/modules/jobs/job_types/labs/research/paperwork.dm
  code/modules/jobs/job_types/labs/research/researcher.dm
  code/modules/jobs/job_types/labs/research/senior.dm
  code/modules/jobs/job_types/labs/security/highsec.dm
  code/modules/jobs/job_types/labs/security/lowsec.dm
  code/modules/jobs/job_types/labs/support/chef.dm
  code/modules/jobs/job_types/labs/support/engineer.dm
  code/modules/jobs/job_types/labs/support/janitor.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold.dm
  code/modules/paperwork/barriertape.dm
  config/maps.txt
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/mob/clothing/ego_gear/limbus_labs.dmi
  icons/mob/clothing/ego_gear/under.dmi
  icons/mob/clothing/head.dmi
  icons/mob/hud.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/barriertape.dmi
  icons/obj/card.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/limbus_labs.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/limbus_weapons.dmi
  lobotomy-corp13.dme
Labels: Side content

#2036 Replaces unused internals button with a stats button
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  icons/hud/screen_gen.dmi
Labels: Feature

#2045 Moves most duplicate alt refinery checks to the parent and some cleanup
  ModularTegustation/tegu_items/refinery/alt_refinery/_refiner.dm
  ModularTegustation/tegu_items/refinery/alt_refinery/blood.dm
  ModularTegustation/tegu_items/refinery/alt_refinery/chance.dm
  ModularTegustation/tegu_items/refinery/alt_refinery/quickrefine.dm
  ModularTegustation/tegu_items/refinery/alt_refinery/timed.dm
  ModularTegustation/tegu_items/refinery/alt_refinery/weapon.dm
Labels: Code improvement

#2034 Makes the mask of the black silence completelly block examine attempts and make your footsteps silent
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/human_say.dm
Labels: Tweak

#2052 5 Plastic for one Flap? I THINK NOT!
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Removal

#2040 Adds 8 new goobers to Rcorp, plus some misceclaneous playables/rcorp changes.
  ModularTegustation/tegu_items/rcorp/!abno_overwrites.dm
  ModularTegustation/tegu_items/rcorp/landmarks.dm
  code/datums/looping_sounds/abnormalities.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/abnormality/he/better_memories.dm
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/mob/living/simple_animal/abnormality/he/puss_in_boots.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/living/simple_animal/abnormality/waw/red_riding_mercenary.dm
  icons/mob/actions/actions_abnormality.dmi
  sound/abnormalities/woodsman/woodsman_loop.ogg
Labels: Balance, Expansion, Side content

#1876 KK replace their cardboard swords with steel and kill off a Ronin.
  _maps/templates/syndicate_office/kurokumosake.dmm
  code/modules/jobs/job_types/city/syndicate/kurokumo/captain.dm
Labels: Balance, Side content

#2003 BL learn the blade once more (bug fix)
  _maps/templates/syndicate_office/blade_lineageswordmen.dmm
Labels: Fix

#1181 Wave Nests, Wave Based Monster Spawning [DONE]
  code/datums/components/monwave_spawners.dm
  lobotomy-corp13.dme
Labels: Feature

#2057 Fixes DME jank
  lobotomy-corp13.dme
Labels: Fix

#1325 Attempting to make AI Leadership Component [Done but unapproved]
  code/datums/components/ai_leadership.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
  lobotomy-corp13.dme
Labels: Feature, Tweak

#2001 Suppression Agents
  ModularTegustation/Teguicons/head_item.dmi
  ModularTegustation/Teguicons/head_worn.dmi
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/jobs.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/non_abnormality/_cityweapons.dm
  code/modules/clothing/head/departmentberet.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/_cityarmor.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/suppression.dm
  code/modules/jobs/jobs.dm
  code/modules/projectiles/guns/ego_gun.dm
  icons/mob/hud.dmi
  icons/obj/card.dmi
  lobotomy-corp13.dme
Labels: Feature

#2067 reworks heart of aspiration
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/heart.dm
  code/modules/paperwork/records/info/tools.dm
Labels: Tweak

#2060 [Do not merge until #2056 is merged] Improves job outfit code
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/manager.dm
  code/modules/jobs/job_types/suppression.dm
  code/modules/jobs/job_types/trusted_players/association/associate.dm
  code/modules/jobs/job_types/trusted_players/association/director.dm
  code/modules/jobs/job_types/trusted_players/association/veteran.dm
  code/modules/jobs/job_types/trusted_players/hana.dm
  code/modules/jobs/job_types/trusted_players/representative.dm
  code/modules/jobs/job_types/trusted_players/sephirah.dm
  code/modules/jobs/job_types/wcorp/wcorpl1.dm
  code/modules/jobs/job_types/wcorp/wcorpl2.dm
  code/modules/jobs/job_types/wcorp/wcorpl3.dm
  code/modules/jobs/job_types/wcorp/wcorprecon.dm
  code/modules/jobs/job_types/wcorp/wcorprep.dm
  code/modules/jobs/job_types/wcorp/wcorpshield.dm
  code/modules/jobs/job_types/wcorp/wcorpspear.dm
Labels: Code improvement

#1680 Adds gasharpoon
  code/datums/abnormality/_ego_datum/aleph.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  icons/mob/clothing/ego_gear/realized.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/obj/clothing/ego_gear/realization.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  sound/weapons/ego/gasharpoon_bullet_impact.ogg
  sound/weapons/ego/gasharpoon_fire.ogg
  sound/weapons/ego/gasharpoon_hit.ogg
  sound/weapons/ego/gasharpoon_piphit.ogg
  sound/weapons/ego/gasharpoon_queeblock.ogg
  sound/weapons/ego/gasharpoon_queehit.ogg
  sound/weapons/ego/gasharpoon_starbuckhit.ogg
  sound/weapons/ego/gasharpoon_transform.ogg
Labels: Expansion

#2035 Widespread Attribute Chems Reagent Update [DONE?]
  ModularTegustation/Teguicons/tegu_effects10x10.dmi
  ModularTegustation/fishing/code/fish/LC13_fish/freshwater_fish.dm
  ModularTegustation/fishing/code/fish/LC13_fish/saltwater_fish.dm
  ModularTegustation/tegu_chemistry/recipes.dm
  ModularTegustation/tegufood.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/simple_animal/abnormality/teth/MHz.dm
  code/modules/mob/living/simple_animal/abnormality/teth/beauty_beast.dm
  code/modules/mob/living/simple_animal/abnormality/teth/blood_bath.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cleaner.dm
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
  code/modules/mob/living/simple_animal/abnormality/teth/drowned_sisters.dm
  code/modules/mob/living/simple_animal/abnormality/teth/forsaken_murderer.dm
  code/modules/mob/living/simple_animal/abnormality/teth/lady_facing_the_wall.dm
  code/modules/mob/living/simple_animal/abnormality/teth/old_lady.dm
  code/modules/mob/living/simple_animal/abnormality/teth/penitent_girl.dm
  code/modules/mob/living/simple_animal/abnormality/teth/scorched_girl.dm
  code/modules/mob/living/simple_animal/abnormality/teth/training_rabbit.dm
  code/modules/reagents/chemistry/reagents/abnormality_reagents.dm
Labels: Feature

#2039 Adds a new sillytip
  strings/sillytips.txt
Labels: Tweak

#2071 Adds in Alt-refiners to every map.
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
Labels: Mapping

#2058 Minor Bullet Changes
  ModularTegustation/tegu_items/gadgets/manager_bullets.dm
  code/datums/facility_upgrade.dm
  code/datums/status_effects/debuffs.dm
Labels: Balance

#2072 New Chem Lesser Sange Rau
  ModularTegustation/tegu_chemistry/recipes.dm
  code/modules/reagents/chemistry/reagents/abnormality_reagents.dm
Labels: Feature

#1995 Adds TGUI to the auxiliary console
  code/game/machinery/computer/abnormality_auxiliary.dm
  code/modules/tgui/external.dm
  tgui/packages/tgui/interfaces/AuxiliaryManagerConsole.js
Labels: Expansion

#2074 Adds curtains to laboratory gamemode
  _maps/map_files/Event/laboratory.dmm
Labels: Fix, Mapping

#2080 STOP STEALING MY ANVIL YOU LOBOTOMIZED DWAFES, I DO NOT CARE THAT YOU HAVE A WRENCH OR A SCREWDRIVER. JUST STOP STEALING IT YOU GREEDY BASTARD. YOU CANT EVEN DECONSTRUCT IT PROPERLY AND YET YOU STILL TRY. WHAT IS THE METAL AND METAL RODS GONNA DO FOR YOU HUH?
  ModularTegustation/tegu_items/workshop/forging.dm
Labels: Fix

#2085 Add Together Forever's head piece
  code/modules/clothing/suits/ego_gear/realized.dm
  icons/mob/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/head.dmi
Labels: Tweak

#2073 Backstreet Rooms fix
  _maps/RandomRooms/backstreetlayout/dungeon_backstreets.dmm
Labels: Fix, Mapping

#2087 Broken Crown Nerf
  code/modules/spells/ability_types/realized.dm
Labels: Balance

#2070 Last Shot small update, new Flesh is willing sprite
  code/modules/mob/living/simple_animal/abnormality/aleph/last_shot.dm
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/clothing/ego_gear/abnormality/aleph.dmi
Labels: Balance

#2084 Manager and Abnormality Z-Levels
  _maps/map_files/generic/Abnormality_Z.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/generic/Manager.dmm
  _maps/map_files/generic/Tutorial_Zone.dmm
  code/controllers/subsystem/mapping.dm
Labels: Code improvement, Fix, Mapping

#1713 Tileset PR
  code/game/machinery/doors/airlock.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed/_closed.dm
  icons/obj/smooth_structures/plastitanium_window.dmi
  icons/obj/smooth_structures/reinforced_window.dmi
  icons/obj/smooth_structures/window.dmi
  icons/turf/walls/facility.dmi
Labels: Feature, Sprites

#2081 Fixes Amber Ordeal Runtime on Dungeon Map
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
Labels: Fix

#2075 Agent attribute bugfix
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/suppression.dm
Labels: Fix

#2069 Fixed blind obsession yet again
  code/game/objects/items/ego_weapons/waw.dm
Labels: Fix

#2104 renames Combusting Courage to Waxen Pinion
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/crying_children.dm
Labels: Writing

#2106 Removes a duplicate line from realizer code
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
Labels: Code improvement
