Repository vlggms/lobotomy-corp13, pull requests merged in 2024-02, with the labels that each got.

#1935 Adds a debug test dummy
  ModularTegustation/tegu_items/debug_items.dm
Labels: Feature

#1934 Batong update
  code/game/objects/items/melee/misc.dm
Labels: Tweak

#1929 Improved arbiter (Adminsbus)
  ModularTegustation/tegu_items/rcorp/objective.dm
  code/modules/antagonists/wizard/arbiter.dm
  code/modules/spells/spell_types/aimed.dm
  icons/mob/actions/actions_spells.dmi
Labels: Tweak

#1941 Update my_sweet_home.dm
  code/modules/mob/living/simple_animal/abnormality/teth/my_sweet_home.dm
Labels: Fix

#1918 Fixes attributes counting as 1
  code/datums/attributes/_attribute.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#1930 Changes more <span>'s into span_defines, fixes more lists, de-hardcodes a lil bit of code and removes useless defines
  ModularTegustation/tegu_cloning/machine.dm
  ModularTegustation/tegu_security_code/detective_vendor.dm
  code/__DEFINES/~lobotomy_defines/adventure.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/_lists.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/joke.dm
  code/game/objects/items/ego_weapons/non_abnormality/_charge.dm
  code/game/objects/items/ego_weapons/non_abnormality/black_silence.dm
  code/game/objects/items/ego_weapons/non_abnormality/blue_sicko.dm
  code/game/objects/items/ego_weapons/non_abnormality/cane.dm
  code/game/objects/items/ego_weapons/non_abnormality/carnival.dm
  code/game/objects/items/ego_weapons/non_abnormality/cinq.dm
  code/game/objects/items/ego_weapons/non_abnormality/color_fixer.dm
  code/game/objects/items/ego_weapons/non_abnormality/dawn.dm
  code/game/objects/items/ego_weapons/non_abnormality/fullstop.dm
  code/game/objects/items/ego_weapons/non_abnormality/gradeone.dm
  code/game/objects/items/ego_weapons/non_abnormality/hana.dm
  code/game/objects/items/ego_weapons/non_abnormality/index.dm
  code/game/objects/items/ego_weapons/non_abnormality/jcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/jeong.dm
  code/game/objects/items/ego_weapons/non_abnormality/leaflet.dm
  code/game/objects/items/ego_weapons/non_abnormality/liu.dm
  code/game/objects/items/ego_weapons/non_abnormality/mirae.dm
  code/game/objects/items/ego_weapons/non_abnormality/miscbackstreet.dm
  code/game/objects/items/ego_weapons/non_abnormality/miscfixer.dm
  code/game/objects/items/ego_weapons/non_abnormality/molar.dm
  code/game/objects/items/ego_weapons/non_abnormality/ncorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/purple_tear.dm
  code/game/objects/items/ego_weapons/non_abnormality/rats.dm
  code/game/objects/items/ego_weapons/non_abnormality/rcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/rcorp_assault.dm
  code/game/objects/items/ego_weapons/non_abnormality/rosespanner.dm
  code/game/objects/items/ego_weapons/non_abnormality/seven.dm
  code/game/objects/items/ego_weapons/non_abnormality/shi.dm
  code/game/objects/items/ego_weapons/non_abnormality/sweeper.dm
  code/game/objects/items/ego_weapons/non_abnormality/syndicate.dm
  code/game/objects/items/ego_weapons/non_abnormality/thumb.dm
  code/game/objects/items/ego_weapons/non_abnormality/wcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/weak_edits/city.dm
  code/game/objects/items/ego_weapons/non_abnormality/zwei.dm
  code/game/objects/items/ego_weapons/ordeal.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/ego_weapons/subtype/charge.dm
  code/game/objects/items/ego_weapons/subtype/lance.dm
  code/game/objects/items/ego_weapons/subtype/shield.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/game/objects/items/ego_weapons/zayin.dm
Labels: Code improvement

#1940 various fixes to c corp
  _maps/map_files/Gamma/gammacorp.dmm
Labels: Fix, Mapping

#1936 Small edit to the special text of hypocrisy
  code/modules/projectiles/guns/ego_gun/waw.dm
Labels: Tweak, Writing

#1951 Updates Dependencies to 515
  dependencies.sh
Labels: dependencies

#1945 Reworks some endgame armors
  code/modules/clothing/suits/ego_gear/aleph.dm
Labels: Balance

#1943 Wishing well rework
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
Labels: Balance

#1955 Another Gbee fix for Pink Midnight
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
Labels: Code improvement, Fix

#1798 Oberon 2
  ModularTegustation/Teguicons/64x64.dmi
  code/game/objects/effects/abnormality.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/projectiles/projectile/beams.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/obj/ego_weapons.dmi
Labels: Feature

#1957 A little 515 fix
  code/controllers/subsystem/timer.dm
  code/modules/admin/verbs/debug.dm
Labels: Fix

#1959 Adds the station charter to the manager, allowing them to change the facility's name less than 5 minutes into the game
  code/modules/jobs/job_types/manager.dm
Labels: Tweak

#1926 Melting Love Update
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/paperwork/records/info/aleph.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
Labels: Balance, Sprites, Expansion

#1960 Includes new M and C abnormality barcode designation
  code/modules/paperwork/records/info/_info.dm
Labels: Tweak, Writing

#1290 Sleeper and Chems Changes
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/__DEFINES/span.dm
  code/datums/wounds/loss.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/computer/Operating.dm
  code/game/machinery/medical_kiosk.dm
  code/game/machinery/regenerator.dm
  code/game/objects/items/clerks/hypo/hypo.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/reagents/chemistry/reagents/cat2_medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  html/browser/scannernew.css
  icons/mob/hud.dmi
  icons/obj/tools.dmi
  interface/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui/interfaces/Cryo.js
  tgui/packages/tgui/interfaces/MedicalKiosk.js
  tgui/packages/tgui/interfaces/OperatingComputer.js
  tgui/packages/tgui/interfaces/Sleeper.js
Labels: Balance, Code improvement

#1964 sephirah roll fix
  code/modules/jobs/job_types/trusted_players/sephirah.dm
Labels: Fix

#1966 Abno queue null entry fix
  code/__HELPERS/_lists.dm
  code/controllers/subsystem/abnormality_queue.dm
Labels: Code improvement, Fix

#1923 Lantern and Cobalt scar buffs
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  icons/effects/effects.dmi
Labels: Tweak

#1971 Removes an unused EGO
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
Labels: Fix

#1965 Giant Tree Sap E.G.O gear
  code/datums/abnormality/_ego_datum/tools.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/tools.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/treesap.dm
  icons/mob/clothing/ego_gear/abnormality/tools.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/tools.dmi
  icons/obj/ego_weapons.dmi
Labels: Expansion

#1854 Clouded Monk: Bubblegum Edition
  code/datums/looping_sounds/abnormalities.dm
  code/modules/antagonists/slaughter/slaughter.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clouded_monk.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/mob/living/simple_animal/hostile/regalrat.dm
  code/modules/mob/living/simple_animal/hostile/skeleton.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/actions/actions_abnormality.dmi
Labels: Tweak
