Repository vlggms/lobotomy-corp13, pull requests merged in 2024-12, with the labels that each got.

#2580 Fixes Two Friendly Shrimps having the same code path
  ModularTegustation/ego_weapons/ranged/zayin.dm
Labels: Fix

#2583 Mobwave Spawner Fix
  ModularTegustation/lc13_structures.dm
  code/datums/components/monwave_spawners.dm
Labels: Fix

#2582 Fixes Will You Play's Last Worker check
  code/modules/mob/living/simple_animal/abnormality/he/will_you_play.dm
Labels: Fix

#2581 unshittifies whatever the hell is the loop in the shrimp pistol
  ModularTegustation/ego_weapons/_ego_weapon.dm
  ModularTegustation/ego_weapons/ranged/zayin.dm
Labels: Code improvement

#2528 Carnival Update
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  ModularTegustation/ego_weapons/melee/non_abnormality/carnival.dm
  ModularTegustation/tegu_items/associations/vending.dm
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
  _maps/RandomRooms/backstreets/bossroom/clan_stronghold.dmm
  _maps/RandomRooms/backstreets/bossroom/gcorp.dmm
  _maps/RandomRooms/backstreets/bossroom/jacques.dmm
  _maps/RandomRooms/backstreets/bossroom/robot.dmm
  _maps/RandomRooms/backstreets/pointofinterest/love_train.dmm
  _maps/RandomRooms/backstreets/pointofinterest/robot_city.dmm
  _maps/RandomRooms/backstreets/pointofinterest/scorp_vault.dmm
  _maps/RandomRooms/backstreets/small_north/bird_box.dmm
  _maps/map_files/Event/city.dmm
  _maps/map_files/Event/city_fixer.dmm
  _maps/templates/fixer_office/workshopfixers.dmm
  code/__DEFINES/construction.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_blade_lineage.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_boatworks.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_custom_armor.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_index.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_j_corp_gangs.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_kurokumo.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_liu.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_n_corp.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_ordeal_armor.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_rosepanner.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_seven.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_shi.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_wedge.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_zwei.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_zwei_west.dm
  code/datums/components/crafting/recipes/carnival_silk/silk_tailoring/carnival_converted.dm
  code/datums/components/crafting/recipes/carnival_silk/silk_tailoring/carnival_meat_tailoring.dm
  code/datums/components/crafting/recipes/carnival_silk/silk_tailoring/carnival_transfer.dm
  code/datums/components/crafting/recipes/carnival_silkcrafting.dm
  code/game/objects/effects/spawners/vending.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/stacks/sheets/silk.dm
  code/game/objects/items/storage/bags.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/rosespanner.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/woven_armor.dm
  code/modules/jobs/job_types/city/carnival.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
  code/modules/paperwork/paper_premade.dm
  icons/obj/bureaucracy.dmi
  icons/obj/carnival_silk.dmi
  icons/obj/library.dmi
  icons/obj/mining.dmi
  icons/obj/stack_objects.dmi
  lobotomy-corp13.dme
Labels: Balance, Expansion, Side content

#2561 Adds Supporter plaque, as according to patreon
  _maps/map_files/generic/Manager.dmm
Labels: Tweak, Isolated Code

#2574 Newer Sprites Addition (Plus a new alt Sprite for an Abnormality)
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/96x64.dmi
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
Labels: Tweak, Sprites

#2554 Fix Lobotomy Corp Achivement Icons [testmerge whenever]
  code/__DEFINES/achievements.dm
  code/__HELPERS/roundend.dm
  code/datums/achievements/LC13_achievements.dm
  code/datums/achievements/_achievement_data.dm
  code/datums/achievements/boss_achievements.dm
  code/datums/achievements/misc_achievements.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/ordeals/amber_ordeals.dm
  code/modules/ordeals/green_ordeals.dm
  code/modules/ordeals/violet_ordeals.dm
  code/modules/ordeals/white_ordeals.dm
  icons/UI_Icons/Achievements/lobotomycorp13/amber.png
  icons/UI_Icons/Achievements/lobotomycorp13/claw.png
  icons/UI_Icons/Achievements/lobotomycorp13/green.png
  icons/UI_Icons/Achievements/lobotomycorp13/lcorp.png
  icons/UI_Icons/Achievements/lobotomycorp13/shrimp.png
  icons/UI_Icons/Achievements/lobotomycorp13/twlight.png
  icons/UI_Icons/Achievements/lobotomycorp13/violet.png
  icons/UI_Icons/Achievements/lobotomycorp13/whitenight.png
  lobotomy-corp13.dme
Labels: Fix

#2586 Fix: Upload Limit raised to 16 MB
  code/modules/client/client_procs.dm
Labels: Tweak

#2481 [CF/COL] Prosthetics Clinic, and 5 new Prosthetics
  ModularTegustation/ego_weapons/melee/non_abnormality/rats.dm
  ModularTegustation/tegu_items/associations/vending.dm
  ModularTegustation/tegu_items/prosthetics/chainsword.dm
  ModularTegustation/tegu_items/prosthetics/explosivearm.dm
  ModularTegustation/tegu_items/prosthetics/extra_arm_implant.dm
  ModularTegustation/tegu_items/prosthetics/extrarm.dm
  ModularTegustation/tegu_items/prosthetics/icons/explosivearm.dmi
  ModularTegustation/tegu_items/prosthetics/icons/generic.dmi
  ModularTegustation/tegu_items/prosthetics/icons/speedleg.dmi
  ModularTegustation/tegu_items/prosthetics/mantis.dm
  ModularTegustation/tegu_items/prosthetics/zippyarm.dm
  _maps/map_files/Event/city.dmm
  _maps/map_files/Event/city_fixer.dmm
  code/modules/jobs/job_types/city/prosthetic.dm
  code/modules/jobs/jobs.dm
  code/modules/surgery/bodyparts/parts.dm
  lobotomy-corp13.dme
Labels: Expansion, Side content

#2596 Imperfect Morsel Hotfix [DONE]
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
Labels: Fix, Isolated Code

#2598 Perfect Shield and Manager Shield Damage Rework
  ModularTegustation/tegu_items/gadgets/manager_bullets.dm
Labels: Tweak

#2597 City Addition: Shrimp/Rat Drops, Fishing for Shrimp
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/fishing/code/fish_market.dm
  ModularTegustation/fishing/code/fishing_items/fishing_net.dm
  ModularTegustation/fishing/icons/fishing.dmi
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/shrimps.dm
Labels: Feature, Tweak

#2592 Add: Conveyor Splitter
  code/__HELPERS/bitflag_helpers.dm
  code/modules/recycling/special_conveyor.dm
  icons/obj/recycling.dmi
  lobotomy-corp13.dme
Labels: Balance, Expansion

#2595 City Silk Fix
  ModularTegustation/fishing/code/fishing_items/fishing_net.dm
  _maps/map_files/Event/city_fixer.dmm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_seven.dm
  code/modules/paperwork/paper_premade.dm
  icons/obj/bureaucracy.dmi
Labels: Feature, Fix, Mapping

#2607 Fix: Changelogs Workflow Secrets Update
  .github/workflows/compile_changelogs.yml
Labels: Github, Fix

#2604 SoW Hermit Fix
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
Labels: Fix, Isolated Code

#2613 Fix Thunderbird Ego Bug
  ModularTegustation/ego_weapons/ranged/waw.dm
Labels: Fix

#2609 Fix Mermaid Water Tiles
  ModularTegustation/fishing/code/turfs.dm
  lobotomy-corp13.dme
Labels: Fix

#2445 Echo Office Gear
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/ego_weapons/melee/non_abnormality/echo_office.dm
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/echo_office.dm
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  lobotomy-corp13.dme
Labels: Tweak, Expansion

#2606 Fixes the runtime of civilians spawning with a tier 0 skill book + optimizations and cleanup
  code/game/objects/items/fixerskills/fishing/_fishing.dm
  code/game/objects/items/fixerskills/fishing/level1/arcane.dm
  code/game/objects/items/fixerskills/fishing/level1/healing.dm
  code/game/objects/items/fixerskills/fishing/level1/joke.dm
  code/game/objects/items/fixerskills/fishing/level1/motion.dm
  code/game/objects/items/fixerskills/fishing/level2.dm
  code/game/objects/items/fixerskills/fishing/level4.dm
  code/game/objects/items/fixerskills/level1/healing.dm
  code/game/objects/items/fixerskills/level4/dismember.dm
  code/game/objects/items/fixerskills/skills.dm
  code/modules/jobs/job_types/city/civilian.dm
Labels: Code improvement, Fix

#2603 Wcorp Shieldweapons now block all damage types.
  ModularTegustation/ego_weapons/melee/non_abnormality/wcorp.dm
Labels: Fix

#2591 Moves some LC13 essential structures to their own files [DONE]
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/_event.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/aleph/giant.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/he/tsa_woods.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/teth/forsaken_murderer.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/teth/old_lady.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/teth/scorched_girl.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/waw/thunder_bird.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/jazz_end.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/legacy.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/quiz.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/sinking_bell.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/allaround_cleaner.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/ambling_pearl.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/ardor_blossom.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/blubbering_toad.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/chicken_strife.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/coffin_return.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/fourthfront_smokewar.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/golden_grip.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/kqe.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/lost_mind.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/monkey_tree.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/nymph.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/poultry_passion_tango.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/readme.md
  ModularTegustation/lc13_obj/_adventure_console/adventure_layout.dm
  ModularTegustation/lc13_obj/_adventure_console/console.dm
  ModularTegustation/lc13_obj/lc13_computers/abnormality_archive.dm
  ModularTegustation/lc13_obj/lc13_computers/abnormality_auxiliary.dm
  ModularTegustation/lc13_obj/lc13_computers/abnormality_ego.dm
  ModularTegustation/lc13_obj/lc13_computers/abnormality_logs.dm
  ModularTegustation/lc13_obj/lc13_computers/abnormality_queue.dm
  ModularTegustation/lc13_obj/lc13_computers/abnormality_work.dm
  ModularTegustation/lc13_obj/regenerator.dm
  lobotomy-corp13.dme
Labels: Code improvement, Refactor

#2614 Fix Warbanner and Warcry
  code/game/objects/items/fixerskills/level4/team.dm
Labels: Fix

#2600 More Lockpick maps
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/east.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/north.dm
  _maps/RandomRooms/backstreets/connector/fort_knox.dmm
  _maps/RandomRooms/backstreets/medium_east/prosthetics_me.dmm
  _maps/RandomRooms/backstreets/medium_north/casino_mn.dmm
Labels: Mapping, Side content

#2616 W-Corp Map Update
  ModularTegustation/tegu_items/wcorp/mapping.dm
  _maps/RandomRooms/wcorp/carriage1.dmm
  _maps/RandomRooms/wcorp/kitchen.dmm
  _maps/RandomRooms/wcorp/library.dmm
  _maps/RandomRooms/wcorp/passenger2.dmm
  _maps/RandomRooms/wcorp/stage.dmm
  _maps/map_files/Event/wcorp.dmm
Labels: Fix, Side content

#2618 Adds Adventure Console to the Rep's Equipment
  ModularTegustation/lc13_obj/_adventure_console/adventure_layout.dm
  _maps/map_files/generic/Manager.dmm
Labels: Tweak, Mapping

#2619 Adds Holopads to 6 Different maps
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
  _maps/map_files/generic/Manager.dmm
Labels: Feature, Mapping

#2621 Roundtime fix
  code/game/world.dm
Labels: Fix

#2620 Holopads now use ACCESS_COMMAND and not ACCESS_KEYCARD_AUTH
  code/game/machinery/hologram.dm
Labels: Fix

#2513 Updates index
  _maps/templates/syndicate_office/indexfinger.dmm
  code/modules/jobs/job_types/city/syndicate/index/messenger.dm
Labels: Balance, Side content

#2623 Fixing the love town train
  _maps/RandomRooms/backstreets/pointofinterest/love_train.dmm
Labels: Fix

#2624 Ghost breach notifications
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Feature

#2587 Add: Patreon Rank system, bump Schema
  SQL/lc13_schema.sql
  code/__DEFINES/subsystems.dm
  code/__DEFINES/~lobotomy_defines/_patreon.dm
  code/datums/patreon_data.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/patreon_ranks.dm
  code/modules/mob/login.dm
  lobotomy-corp13.dme
Labels: Feature, Tweak

#2626 Adds icons to City of lag/City fishers backstreets map spawners
  ModularTegustation/Teguicons/room_spawners/10x10.dmi
  ModularTegustation/Teguicons/room_spawners/13x15.dmi
  ModularTegustation/Teguicons/room_spawners/16x8.dmi
  ModularTegustation/Teguicons/room_spawners/20x20.dmi
  ModularTegustation/Teguicons/room_spawners/30x30.dmi
  ModularTegustation/Teguicons/room_spawners/7x7.dmi
  ModularTegustation/tegu_items/backstreets/random_rooms/bigrooms/bossroom.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/bigrooms/connector.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/bigrooms/pointofinterest.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/large/north.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/large/south.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/east.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/north.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/south.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/west.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/east.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/north.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/south.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/west.dm
  ModularTegustation/tegu_items/backstreets/templates.dm
  code/modules/mapping/random_rooms.dm
  lobotomy-corp13.dme
Labels: Code improvement, Fix, Mapping

#2634 Fishupload
  ModularTegustation/fishing/code/fish/LC13_fish/freshwater_fish.dm
  ModularTegustation/fishing/code/turfs.dm
  ModularTegustation/fishing/icons/fish_sprites.dmi
Labels: Fix, Sprites

#2638 Button changes -- Buttoning now takes 60 seconds instead of 45, vendors unmoveable, SOME doors unhackable
  ModularTegustation/lc13_machinery.dm
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/Kappa/kappacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Psi/psicorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
  _maps/map_files/Xi/xicorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/touch.dm
Labels: Balance

#2629 CoL Map Update: Fixing Old/Adding New Backstreets Layouts (also 2 new rooms)
  ModularTegustation/tegu_items/backstreets/random_rooms/bigrooms/bossroom.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/north.dm
  ModularTegustation/tegu_items/backstreets/templates.dm
  _maps/RandomRooms/backstreetlayout/dungeon_backstreets.dmm
  _maps/RandomRooms/backstreetlayout/lcorp.dmm
  _maps/RandomRooms/backstreetlayout/lcorp_backstreets.dmm
  _maps/RandomRooms/backstreetlayout/ruinned_la_mancha_land.dmm
  _maps/RandomRooms/backstreetlayout/standard.dmm
  _maps/RandomRooms/backstreets/bossroom/slime_office.dmm
  _maps/RandomRooms/backstreets/medium_north/slime_hut.dmm
  code/modules/ruins/objects_and_mobs/necropolis_gate.dm
Labels: Mapping

#2647 N-Corp Armor slowdown
  code/modules/clothing/suits/ego_gear/non_abnormality/ncorp.dm
Labels: Balance, Side content

#2648 Adds Spyglass kit to the Representative
  code/modules/jobs/job_types/trusted_players/representative.dm
Labels: Tweak

#2544 Endermage Rcorp Updates: Reworking Maps
  ModularTegustation/tegu_items/rcorp/landmarks.dm
  ModularTegustation/tegu_items/rcorp/random_caves.dm
  ModularTegustation/tegu_items/rcorp/random_maps.dm
  _maps/RandomRooms/rcorp/caves/caves.dmm
  _maps/RandomRooms/rcorp/caves/choke.dmm
  _maps/RandomRooms/rcorp/caves/elevator.dmm
  _maps/RandomRooms/rcorp/caves/hallway.dmm
  _maps/RandomRooms/rcorp/caves/open.dmm
  _maps/RandomRooms/rcorp/caves/pit.dmm
  _maps/RandomRooms/rcorp/caves/river.dmm
  _maps/RandomRooms/rcorp/caves/winding.dmm
  _maps/RandomRooms/rcorp/facility/beaches.dmm
  _maps/RandomRooms/rcorp/facility/beaches2.dmm
  _maps/RandomRooms/rcorp/facility/city.dmm
  _maps/RandomRooms/rcorp/facility/city2.dmm
  _maps/RandomRooms/rcorp/facility/maze.dmm
  _maps/RandomRooms/rcorp/facility/maze2.dmm
  _maps/RandomRooms/rcorp/facility/nest.dmm
  _maps/RandomRooms/rcorp/facility/offices.dmm
  _maps/RandomRooms/rcorp/facility/raidboss.dmm
  _maps/RandomRooms/rcorp/facility/skeld.dmm
  _maps/RandomRooms/rcorp/facility/standard.dmm
  _maps/RandomRooms/rcorp/facility/standard2.dmm
  _maps/RandomRooms/rcorp/facility/xenos.dmm
  _maps/map_files/Event/rcorp.dmm
  code/__DEFINES/flags.dm
  code/_globalvars/bitfields.dm
  code/game/gamemodes/management/event/combat.dm
  code/modules/mob/mob_movement.dm
Labels: Mapping

#2651 [RCA] 5th Pack Rat Buff
  code/modules/jobs/job_types/rcorp/fifthpack/rat.dm
Labels: Balance, Side content

#2649 Prevents Indestructable Vending Machines from Crushing People [DONE]
  code/modules/vending/_vending.dm
Labels: Tweak, Isolated Code

#2601 Prosthetics Additions 2
  ModularTegustation/tegu_items/associations/vending.dm
  ModularTegustation/tegu_items/prosthetics/extrarm.dm
  ModularTegustation/tegu_items/prosthetics/fixertools.dm
  ModularTegustation/tegu_items/prosthetics/icons/generic.dmi
  ModularTegustation/tegu_items/prosthetics/icons/observation_head.dmi
  ModularTegustation/tegu_items/prosthetics/icons/timestoparm.dmi
  ModularTegustation/tegu_items/prosthetics/mantis.dm
  ModularTegustation/tegu_items/prosthetics/overdrive.dm
  ModularTegustation/tegu_items/prosthetics/scrying.dm
  ModularTegustation/tegu_items/prosthetics/storage.dm
  ModularTegustation/tegu_items/prosthetics/timestop.dm
  lobotomy-corp13.dme
Labels: Expansion, Side content

#2652 Pcorp Icecream Spritepath fix
  ModularTegustation/tegu_items/representative/items/pcorp.dm
Labels: Fix

#2655 Makes the cherry tree in the blade lineage hideout no longer alive
  _maps/templates/syndicate_office/blade_lineageswordmen.dmm
Labels: Fix

#2654 Fixes the moon expanding infinitelly, eventually consuming the entire sky and all the stars
  ModularTegustation/fishing/code/fish_market.dm
  ModularTegustation/fishing/code/fishing_items/fishing_rod.dm
  code/controllers/subsystem/fishing.dm
Labels: Fix
