Repository vlggms/lobotomy-corp13, pull requests merged in 2024-06, with the labels that each got.

#2118 Adds more safeguards against subsystems crashing, and a ton of other subsystem related changes
  code/__DEFINES/MC.dm
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/flags.dm
  code/__DEFINES/spaceman_dmm.dm
  code/__DEFINES/speech_controller.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/hearted.dm
  code/_debugger.dm
  code/_globalvars/bitfields.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/failsafe.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/assets.dm
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/city_events.dm
  code/controllers/subsystem/economy.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/nightshift.dm
  code/controllers/subsystem/profiler.dm
  code/controllers/subsystem/shuttle.dm
  code/controllers/subsystem/speech_controller.dm
  code/controllers/subsystem/sun.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/time_track.dm
  code/controllers/subsystem/timer.dm
  code/datums/brain_damage/brain_trauma.dm
  code/datums/weather/weather.dm
  code/game/world.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/view_variables/reference_tracking.dm
  code/modules/atmospherics/Atmospherics.md
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
  code/modules/atmospherics/machinery/portable/pump.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/ooc.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob_say.dm
  code/modules/tgchat/to_chat.dm
  config/game_options.txt
  lobotomy-corp13.dme
  tgui/packages/tgui-panel/game/constants.js
Labels: Fix

#2187 Additional Abnocores Part 1
  ModularTegustation/Teguicons/abno_cores/he.dmi
  ModularTegustation/Teguicons/abno_cores/teth.dmi
  ModularTegustation/Teguicons/abno_cores/waw.dmi
  code/modules/mob/living/simple_animal/abnormality/he/better_memories.dm
  code/modules/mob/living/simple_animal/abnormality/he/eris.dm
  code/modules/mob/living/simple_animal/abnormality/he/steam_transport_machine.dm
  code/modules/mob/living/simple_animal/abnormality/he/wayward_passenger.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_gentleman.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
Labels: Sprites

#2186 Removes the corpses inside of lockers and crates breathing
  ModularTegustation/hiding/closet.dm
Labels: Balance

#2182 You are my special
  ModularTegustation/Teguicons/tegumobs.dmi
  code/game/machinery/computer/abnormality_portraits.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/_egodatum.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/aleph/sukuna.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_armor.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_weapons.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/waw/clock.dm
  icons/UI_Icons/abnormality_portraits/sukuna.png
  icons/effects/effects.dmi
  icons/mob/actions/actions_abnormality.dmi
  icons/obj/clothing/masks.dmi
  lobotomy-corp13.dme
  sound/abnormalities/cleave.ogg
  sound/abnormalities/fastcleave.ogg
  sound/abnormalities/maloventkitchen.ogg
  sound/abnormalities/strongcleave.mp3
Labels: Abnormality

#2184 ID Sprite fixes, TO coat sprite fix
  icons/mob/clothing/suit.dmi
  icons/obj/card.dmi
Labels: Fix, Sprites

#2130 Fixes, qdel failure fixes and effect optimisations
  code/__HELPERS/mobs.dm
  code/datums/abnormality/datum/abnormality.dm
  code/datums/reusable_visual_pool.dm
  code/game/objects/effects/spawners/abnormality_room.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/non_abnormality/black_silence.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_sinner.dm
  code/game/objects/items/ego_weapons/non_abnormality/sweeper.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_weapons.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/army_in_black.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/blue_star.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/mob/living/simple_animal/abnormality/he/jangsan.dm
  code/modules/mob/living/simple_animal/abnormality/he/norinori.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_shoes.dm
  code/modules/mob/living/simple_animal/abnormality/he/road_home.dm
  code/modules/mob/living/simple_animal/abnormality/he/wayward_passenger.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dreaming_current.dm
  code/modules/mob/living/simple_animal/abnormality/waw/orange_tree.dm
  code/modules/mob/living/simple_animal/abnormality/waw/parasite_tree.dm
  code/modules/mob/living/simple_animal/abnormality/waw/queen_bee.dm
  code/modules/mob/living/simple_animal/abnormality/waw/rose_sign.dm
  code/modules/mob/living/simple_animal/abnormality/waw/silence.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/pile_of_mail.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/quiet_day.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/_ordeal.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/shrimps.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white.dm
  code/modules/mob/mob.dm
  code/modules/spells/ability_types/realized.dm
Labels: Fix

#2194 Minor sukuna nerf, weapon bugfix
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/aleph/sukuna.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_weapons.dm
Labels: Fix

#2178 Adjustments and Balancing to Realizations
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/dc_changes.dm
  code/modules/spells/ability_types/realized.dm
  code/modules/spells/ability_types/realized_aimed.dm
Labels: Code improvement

#2195 Implements a missing portrait
  code/game/machinery/computer/abnormality_portraits.dm
Labels: Fix

#2017 [READY] Adds Reloading to pretty much all guns
  code/game/objects/items/ego_weapons/non_abnormality/_ammoguns.dm
  code/game/objects/items/ego_weapons/non_abnormality/fullstop.dm
  code/game/objects/items/ego_weapons/non_abnormality/kcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_labs.dm
  code/game/objects/items/ego_weapons/non_abnormality/thumb.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ego_gun.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  lobotomy-corp13.dme
Labels: Feature

#2185 Timelock updates
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/manager.dm
Labels: Tweak

#2166 [DNM] Experimental changes 3
  code/__DEFINES/combat.dm
  code/controllers/subsystem/abnormality_queue.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Balance

#2197 Bottle of tears change
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
Labels: Code improvement, Fix

#2191 Fixes Schad Solo Bug
  code/modules/mob/living/simple_animal/abnormality/he/schadenfreude.dm
Labels: Balance

#2193 Some action and hint fixes
  ModularTegustation/tegu_items/limbus_labs/!abno_overwrites.dm
  code/datums/reusable_visual_pool.dm
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/mob.dm
Labels: Code improvement, Fix

#2158 4 new custom dishes.
  code/game/objects/items/food/frozen.dm
  code/game/objects/items/food/meat.dm
  code/game/objects/items/food/salad.dm
  code/game/objects/items/food/soup.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  icons/obj/food/food.dmi
  icons/obj/food/frozen_treats.dmi
  icons/obj/food/soupsalad.dmi
Labels: Feature

#2181 Adds a secret abnormality and fixes cinderella
  ModularTegustation/Teguicons/128x128.dmi
  code/game/machinery/computer/abnormality_portraits.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_armor.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_worn.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/_egodatum.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/aleph/wild_ride.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_armor.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_weapons.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cinderella.dm
  icons/UI_Icons/abnormality_portraits/wild_ride.png
  icons/mob/clothing/under/costume.dmi
  icons/obj/clothing/under/costume.dmi
  lobotomy-corp13.dme
Labels: Fix, Abnormality

#2200 Rhino pilots unequip armor on entry
  code/modules/vehicles/mecha/_mecha.dm
Labels: Balance

#2201 Removes clothes igniting
  code/modules/mob/living/carbon/human/species.dm
Labels: Removal

#2139 Tool Rebalance Project
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/tegu_effects10x10.dmi
  ModularTegustation/Teguicons/toolabnormalities.dmi
  code/modules/mob/living/simple_animal/abnormality/_tools/he/dr_jekyll.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/fateloom.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/researcher.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/shelter.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/theonite_slab.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/treesap.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/vivavoce.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/behavior.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/bracelet.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/heart.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/skin.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/snake_oil.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/waw/dr_jekyll.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/you_happy.dm
  code/modules/paperwork/records/info/tools.dm
  lobotomy-corp13.dme
Labels: Balance, Fix

#2205 Fixes Repentance
  code/modules/spells/ability_types/realized.dm
Labels: Fix

#2209 stat equalizer fix
  code/modules/jobs/job_types/suppression.dm
Labels: Fix

#2216 Prevents Welling the Corpse your Welling
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
Labels: Fix

#2218 Crit health fixes and adjustment
  code/__DEFINES/combat.dm
  code/datums/attributes/fortitude.dm
  code/game/data_huds.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/computer/Operating.dm
  code/game/objects/items/defib.dm
  code/modules/mob/living/brain/brain.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_say.dm
Labels: Fix

#1756 Adds a Christmas ordeal and event ordeal code
  ModularTegustation/Teguicons/tegumobs.dmi
  code/controllers/subsystem/lobotomy_corp.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/event.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/ordeals/event_ordeals.dm
  lobotomy-corp13.dme
  sound/effects/ordeals/holiday/xmas_end.ogg
  sound/effects/ordeals/holiday/xmas_start.ogg
Labels: Feature

#2219 Fairy and Steel Runtime Fixes
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
Labels: Fix

#2217 Slightly more accurate Shi Asso knoife translation
  code/game/objects/items/ego_weapons/non_abnormality/shi.dm
Labels: Writing

#2164 Experimental Global Weapon Changes PR
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/ego_weapons/subtype/lance.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
  icons/effects/effects.dmi
Labels: Balance

#2226 Removes sloth from LCL asset protection spawns
  code/modules/jobs/job_types/labs/command/assetprot.dm
Labels: Removal, Side content

#2227 rewrites the TSA in the woods adventure
  ModularTegustation/_adventure_console/adventure_events/abnormality/he/tsa_woods.dm
Labels: Writing

#2215 Apple Vines now can Grow On Floor Vents
  ModularTegustation/lc13_structures.dm
Labels: Fix

#2223 Adds ordeal end text
  code/modules/ordeals/crimson_ordeals.dm
  code/modules/ordeals/event_ordeals.dm
  code/modules/ordeals/gold_ordeals.dm
  code/modules/ordeals/indigo_ordeals.dm
  code/modules/ordeals/misc_ordeals.dm
  code/modules/ordeals/steel_ordeals.dm
  sound/effects/ordeals/steel_end.ogg
  sound/effects/ordeals/steel_start.ogg
Labels: Expansion

#1834 Adds execution bullets
  code/__DEFINES/facility_upgrades.dm
  code/datums/facility_upgrade.dm
  code/game/machinery/computer/manager_camera.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/smites/an_execution_bullet.dm
  code/modules/admin/verbs/randomverbs.dm
  icons/obj/manager_bullets.dmi
  lobotomy-corp13.dme
Labels: Expansion

#2233 Fluffy Tongue Removal
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/quirks/good.dm
Labels: Removal

#2198 Sukuna Bugfix part 2 trillion
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/aleph/sukuna.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_armor.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/obj/clothing/masks.dmi
Labels: Fix

#2235 Adds the arbiter punch
  code/modules/antagonists/wizard/arbiter.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/touch_attacks.dm
Labels: Expansion

#2213 Adds basilisoup
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/96x48.dmi
  code/game/machinery/computer/abnormality_portraits.dm
  code/modules/mob/living/simple_animal/abnormality/he/basilisoup.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/UI_Icons/abnormality_portraits/bailisoup.png
  icons/UI_Icons/abnormality_portraits/basilisoup.png
  icons/mob/actions/actions_abnormality.dmi
  icons/obj/fireplace.dmi
  icons/obj/food/soupsalad.dmi
  icons/obj/janitor.dmi
  lobotomy-corp13.dme
  sound/abnormalities/basilisoup/spit1.ogg
  sound/abnormalities/basilisoup/spit2.ogg
Labels: Abnormality

#2239 adds rope and cord gift
  code/modules/mob/living/carbon/human/ego_gifts.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
Labels: Sprites

#2240 Cord Ego Armor
  code/datums/abnormality/_ego_datum/zayin.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  icons/mob/clothing/ego_gear/abnormality/zayin.dmi
  icons/obj/clothing/ego_gear/abnormality/zayin.dmi
Labels: Feature

#2232 Lets admins turn people into distortions
  code/modules/admin/admin_verbs.dm
  code/modules/admin/smites/distort.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/living/simple_animal/distortion/_distortion.dm
  lobotomy-corp13.dme
  sound/distortions/distortion_bell.ogg
Labels: Feature, Expansion

#2243 Updates Yin EGO sprites and Fixes sprite misalignments V2
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/ego_weapons.dmi
Labels: Fix, Sprites

#2179 Extraction Officer Expansion
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/lc13_effects.dm
  ModularTegustation/tegu_items/extraction/_extraction.dm
  ModularTegustation/tegu_items/extraction/egodelivery.dm
  ModularTegustation/tegu_items/extraction/egosurgery.dm
  ModularTegustation/tegu_items/extraction/key.dm
  ModularTegustation/tegu_items/extraction/lock.dm
  ModularTegustation/tegu_items/extraction/toolextractor.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  code/__DEFINES/extraction.dm
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/abnormality_ego.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/jobs/job_types/command.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  icons/effects/160x96.dmi
  lobotomy-corp13.dme
Labels: Feature

#2236 Re-sprites thunderbird zombies and thunder warriors
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x48.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold.dm
Labels: Sprites

#2244 Wild ride fixes
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/_egodatum.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/aleph/wild_ride.dm
Labels: Fix

#2230 Makes All Food Recipes Available
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_unusual.dm
Labels: Tweak

#2222 Dosage Estimator
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/modules/clothing/outfits/standard.dm
Labels: Feature

#2097 Fort insane people can now use mechas
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/ai/sanity/sanityloss_behaviors.dm
Labels: Code improvement, Feature

#2247 Fixes bottle status effect
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
Labels: Fix

#2250 Fixes a bug with player-controlled Faelantern
  code/modules/mob/living/simple_animal/abnormality/teth/faelantern.dm
Labels: Fix

#2255 Fixes hurtinturf hitting objects twice
  code/__HELPERS/mobs.dm
Labels: Fix, Isolated Code

#2206 Last Shot Rework and apex gift
  ModularTegustation/Teguicons/32x48.dmi
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/last_shot.dm
  code/modules/mob/living/simple_animal/abnormality/waw/apex_predator.dm
  code/modules/projectiles/ammunition/ego_ammunition/special.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/obj/projectiles.dmi
  icons/obj/smooth_structures/sandbags.dmi
Labels: Expansion

#2257 makes the minigun good
  code/game/objects/items/ego_weapons/non_abnormality/shrimp.dm
  code/modules/mob/living/simple_animal/distortion/star/shrimp.dm
Labels: Balance

#2259 Revert "makes the minigun good"
  code/game/objects/items/ego_weapons/non_abnormality/shrimp.dm
  code/modules/mob/living/simple_animal/distortion/star/shrimp.dm
Labels: Red Label, Removal

#2251 I got pissed at inconsistent tool behavior, so i decided to make the warnings more visible -- A salt PR
  code/modules/mob/living/simple_animal/abnormality/_tools/he/researcher.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/bracelet.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/heart.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/waw/clock.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/waw/dr_jekyll.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
Labels: Balance, Code improvement, Isolated Code

#2260 Fixes my silly little accident
  code/game/objects/items/ego_weapons/non_abnormality/shrimp.dm
  code/modules/mob/living/simple_animal/distortion/star/shrimp.dm
Labels: Fix

#2252 Records core suppression no longer forces agents to cancel works if they were unlucky
  code/modules/suppressions/records.dm
Labels: Fix, Isolated Code

#2264 Re-shades Cinderella's Pumpkin Carraige
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/96x96.dmi
Labels: Sprites

#2261 Adds logging to E.G.O. extraction
  ModularTegustation/tegu_items/extraction/egodelivery.dm
  code/game/machinery/computer/abnormality_ego.dm
Labels: Expansion, Isolated Code

#2242 Once again fixes broken crown
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/spells/ability_types/realized.dm
Labels: Balance, Isolated Code

#2246 Adds final observations Part 1
  code/datums/abnormality/datum/abnormality.dm
  code/game/machinery/computer/abnormality_work.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/last_shot.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/silent_orchestra.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/galaxy_child.dm
  code/modules/mob/living/simple_animal/abnormality/he/happy_teddy_bear.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/he/nameless_fetus.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_shoes.dm
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
  code/modules/mob/living/simple_animal/abnormality/teth/beauty_beast.dm
  code/modules/mob/living/simple_animal/abnormality/teth/blood_bath.dm
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
  code/modules/mob/living/simple_animal/abnormality/teth/forsaken_murderer.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fragment.dm
  code/modules/mob/living/simple_animal/abnormality/teth/lady_facing_the_wall.dm
  code/modules/mob/living/simple_animal/abnormality/teth/old_lady.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
  code/modules/mob/living/simple_animal/abnormality/teth/redblooded.dm
  code/modules/mob/living/simple_animal/abnormality/teth/scorched_girl.dm
  code/modules/mob/living/simple_animal/abnormality/teth/spider_bud.dm
  code/modules/mob/living/simple_animal/abnormality/waw/alriune.dm
  code/modules/mob/living/simple_animal/abnormality/waw/apex_predator.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_wolf.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/little_prince.dm
  code/modules/mob/living/simple_animal/abnormality/waw/queen_bee.dm
  code/modules/mob/living/simple_animal/abnormality/waw/screenwriter.dm
  code/modules/mob/living/simple_animal/abnormality/waw/silence.dm
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bald.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/hammer_light.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/quiet_day.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
Labels: Feature

#2210 Multi tile mobs
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
  code/__DEFINES/combat.dm
  code/_onclick/adjacent.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/blue_star.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/projectile_blocker.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/projectile.dm
  code/modules/suppressions/extraction.dm
  lobotomy-corp13.dme
Labels: Balance, Feature

#2245 simple fix to realization engine
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
Labels: Balance, Fix, Isolated Code
