Repository vlggms/lobotomy-corp13, pull requests merged in 2024-11, with the labels that each got.

#2523 Fixes Bugs of Distorted Form
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
Labels: Balance, Fix

#2518 Bari Sprites
  ModularTegustation/Teguicons/lc13_weapons.dmi
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
Labels: Sprites

#2526 Pcorp Canned Foods
  ModularTegustation/tegu_items/representative/console.dm
  ModularTegustation/tegu_items/representative/items/pcorp.dm
  icons/obj/food/food.dmi
Labels: Tweak

#2529 removes the not in the abnocheck for sentience potions
  code/modules/research/xenobiology/xenobiology.dm
Labels: Balance, Fix

#2527 Skill cleanup and quite a lot of fixes
  code/game/objects/items/fixerskills/level1/defensive.dm
  code/game/objects/items/fixerskills/level1/healing.dm
  code/game/objects/items/fixerskills/level1/movement.dm
  code/game/objects/items/fixerskills/level1/scavenger.dm
  code/game/objects/items/fixerskills/level2/butcher.dm
  code/game/objects/items/fixerskills/level2/confusion.dm
  code/game/objects/items/fixerskills/level2/flashbang.dm
  code/game/objects/items/fixerskills/level2/lifesteal.dm
  code/game/objects/items/fixerskills/level2/lockpick.dm
  code/game/objects/items/fixerskills/level2/shockwave.dm
  code/game/objects/items/fixerskills/level3/bulletproof.dm
  code/game/objects/items/fixerskills/level4/dismember.dm
  code/game/objects/items/fixerskills/level4/healing.dm
  code/game/objects/items/fixerskills/level4/kys.dm
  code/game/objects/items/fixerskills/level4/status_effects.dm
  code/game/objects/items/fixerskills/level4/team.dm
Labels: Balance, Code improvement, Fix, Side content

#2488 FISHING 5.0 (I say morning, cause it's not a good morning unless my chakra is aligned)
  ModularTegustation/Teguicons/workshop.dmi
  ModularTegustation/fishing/code/fish_market.dm
  ModularTegustation/fishing/code/fishing_items/fishing_net.dm
  ModularTegustation/fishing/code/fishing_items/fishing_rod.dm
  ModularTegustation/fishing/code/fishing_items/fishing_shrine.dm
  ModularTegustation/fishing/icons/fishing.dmi
  ModularTegustation/tegu_items/associations/machines.dm
  ModularTegustation/tegu_items/associations/vending.dm
  ModularTegustation/tegu_items/rcorp/mobs.dm
  ModularTegustation/tegu_items/workshop/_templates.dm
  ModularTegustation/tegu_items/workshop/mods/fishing/basic.dm
  ModularTegustation/tegu_items/workshop/templates/fishing/fishingweapons.dm
  _maps/map_files/Event/city.dmm
  _maps/map_files/Event/city_fixer.dmm
  code/__DEFINES/fishing.dm
  code/controllers/subsystem/fishing.dm
  code/game/objects/items/fixerskills/fishing/_fishing.dm
  code/game/objects/items/fixerskills/fishing/level1/arcane.dm
  code/game/objects/items/fixerskills/fishing/level1/healing.dm
  code/game/objects/items/fixerskills/fishing/level1/joke.dm
  code/game/objects/items/fixerskills/fishing/level1/motion.dm
  code/game/objects/items/fixerskills/fishing/level2.dm
  code/game/objects/items/fixerskills/fishing/level4.dm
  code/game/objects/items/fixerskills/level1/scavenger.dm
  code/game/objects/items/fixerskills/level3.dm
  code/game/objects/items/fixerskills/skills.dm
  code/modules/admin/smites/lightning.dm
  code/modules/fishing/aquarium/aquarium.dm
  code/modules/mob/living/living_defines.dm
  icons/hud/screen_fishing.dmi
  lobotomy-corp13.dme
Labels: Expansion, Side content

#2534 fishufo
  ModularTegustation/fishing/icons/fish_sprites.dmi
Labels: Sprites

#2464 Domain Expansion: Sephirah Griefing
  code/modules/jobs/job_types/trusted_players/sephirah.dm
  tgui/packages/tgui/interfaces/SephirahPanel.js
Labels: Expansion

#2532 Reworks how force is handled in workshop weapons, fixes katana's and gauntlets
  ModularTegustation/tegu_items/workshop/_templates.dm
  ModularTegustation/tegu_items/workshop/mods/aoe.dm
  ModularTegustation/tegu_items/workshop/mods/split.dm
  ModularTegustation/tegu_items/workshop/templates/axe.dm
  ModularTegustation/tegu_items/workshop/templates/chargeblade.dm
  ModularTegustation/tegu_items/workshop/templates/dice.dm
  ModularTegustation/tegu_items/workshop/templates/gauntlet.dm
  ModularTegustation/tegu_items/workshop/templates/katana.dm
  ModularTegustation/tegu_items/workshop/templates/scythe.dm
Labels: Code improvement, Fix

#2512 Training Officer Fix
  ModularTegustation/trusted.dm
Labels: Fix

#2537 Fixes some initialize hints
  ModularTegustation/tegu_items/associations/!overwrites.dm
  code/modules/mob/living/simple_animal/distortion/myth/another_day_work.dm
Labels: Code improvement

#2539 Arcadia deals more damage
  ModularTegustation/ego_weapons/melee/zayin.dm
  ModularTegustation/ego_weapons/ranged/ego_bullets/aleph.dm
Labels: Balance

#2551 fix typo in spawners.dm [DONE]
  ModularTegustation/tegu_items/representative/spawners.dm
Labels: Writing

#2546 REDUCE LAG AND DESTROY AUTO PATROL CLEANBOTS [DONE]
  code/__DEFINES/robots.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Tweak, Performance Improvement?

#2549 Makes Phobias trigger from some LC13 stuff
  code/controllers/subsystem/traumas.dm
Labels: Tweak

#2548 Makes the SSlobotomy and SSlobotomy_queue subsystems sleep on combat mode, reworks the automatic round-end notification for everyone dying and adds it to R-corp
  ModularTegustation/tegu_items/wcorp/enemies.dm
  code/controllers/subsystem/abnormality_queue.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/management/event/combat.dm
Labels: Code improvement, Fix, Performance Improvement?

#2538 Cleans up titania's fairy spawning code a tiny bit
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
Labels: Code improvement

#2552 Salbutamol Addition
  code/modules/vending/medical.dm
Labels: Balance, Side content

#2535 Converts hard-coded variables to datums in the fishing subsystem + minor fishing skills cleanup
  ModularTegustation/fishing/code/fish_market.dm
  ModularTegustation/fishing/code/fishing_items/fishing_net.dm
  ModularTegustation/fishing/code/fishing_items/fishing_rod.dm
  ModularTegustation/fishing/code/fishing_items/fishing_shrine.dm
  ModularTegustation/tegu_items/workshop/templates/fishing/fishingweapons.dm
  code/controllers/subsystem/fishing.dm
  code/game/objects/items/fixerskills/fishing/_fishing.dm
  code/game/objects/items/fixerskills/fishing/level1/motion.dm
  code/game/objects/items/fixerskills/fishing/level2.dm
  code/game/objects/items/fixerskills/fishing/level4.dm
Labels: Code improvement, Side content

#2557 Changes the Manager Bullet Suicide so you can Execution Bullet Yourself
  ModularTegustation/tegu_items/gadgets/manager_bullets.dm
Labels: Feature, Isolated Code

#2482 Desert eagle bullets now stun humans.
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
Labels: Balance, Side content

#2483 R corp Defensive Buff
  ModularTegustation/tegu_items/rcorp/turrets.dm
  code/game/machinery/deployable.dm
  code/game/objects/items/stacks/sheets/mineral.dm
Labels: Balance, Side content

#2479 RCA Officer Skills and Payload Changes
  code/modules/jobs/job_types/rcorp/command.dm
  code/modules/jobs/job_types/rcorp/fifthpack/officer.dm
  code/modules/jobs/job_types/rcorp/officer.dm
  code/modules/mob/payload/payload.dm
Labels: Side content

#2368 abno month E.G.O PR 2: Electric Boogaloo
  ModularTegustation/ego_weapons/melee/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_armor.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_lefthand.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_righthand.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_weapons.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_worn.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/_egodatum.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_armor.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_weapons.dm
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/ego_weapons.dmi
  sound/abnormalities/alleywaywatchdog/telepole_1.ogg
  sound/abnormalities/alleywaywatchdog/telepole_2.ogg
  sound/abnormalities/alleywaywatchdog/telepole_3.ogg
Labels: Sprites

#2558 Fix Janky Bugs from putting ego armors on other people
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/mob/living/living.dm
Labels: Fix

#2555 Fixes some init hints and amber bugs hard deleting themselfes saving a LOT of hard-delete time
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/controllers/subsystem/fishing.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/brown/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/dusk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
  code/modules/ordeals/_ordeal.dm
Labels: Code improvement, Performance Improvement?

#2562 Obliterates metastation for real this time
  code/datums/map_config.dm
Labels: Fix

#2556 Endermage Rcorp Updates: Abnormality Nerfs/R-Corp Buffs
  ModularTegustation/ego_weapons/melee/non_abnormality/rcorp.dm
  ModularTegustation/tegu_items/rcorp/!abno_overwrites.dm
  _maps/map_files/Event/rcorp.dmm
  code/game/objects/items/grenades/r_corp.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/he/eris.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
  icons/obj/grenade.dmi
  lobotomy-corp13.dme
Labels: Balance

#2453 Reworks job spawning in City of Light
  code/controllers/subsystem/city_events.dm
  code/modules/jobs/job_types/city/misc/blade_lineage_misc.dm
  code/modules/jobs/job_types/city/rat.dm
  code/modules/jobs/job_types/trusted_players/association/roaming.dm
  code/modules/jobs/job_types/trusted_players/hana.dm
  code/modules/jobs/jobs.dm
  config/maps.txt
  lobotomy-corp13.dme
Labels: Feature, Side content

#2519 Adds our last two Wonderlab Abnormalities
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x64.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/64x96.dmi
  ModularTegustation/ego_weapons/melee/teth.dm
  ModularTegustation/ego_weapons/ranged/aleph.dm
  ModularTegustation/ego_weapons/ranged/ego_bullets/aleph.dm
  ModularTegustation/ego_weapons/ranged/ego_bullets/waw.dm
  ModularTegustation/ego_weapons/ranged/waw.dm
  ModularTegustation/lc13_structures.dm
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/teth/tangle.dm
  code/modules/mob/living/simple_animal/abnormality/waw/caterpillar.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/paperwork/records/info/waw.dm
  icons/effects/96x96.dmi
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#2573 Melting Love fix
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
Labels: Fix

#2468 Revives Skeld
  ModularTegustation/tegu_traitor_code/objectives_tegu.dm
  _maps/map_files/Event/skeld.dmm
  code/controllers/subsystem/lobotomy_corp.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/objective.dm
  code/game/gamemodes/objective_items.dm
  code/game/machinery/computer/manager_camera.dm
  code/game/objects/items/clerks/hypo/hypo.dm
  code/game/objects/structures/test_range.dm
  code/modules/antagonists/highlander/highlander.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/jobs/job_types/trusted_players/sephirah.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/aleph/sukuna.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  code/modules/uplink/uplink_items.dm
Labels: Side content

#2531 Expanded Rhino Captain arsenal
  ModularTegustation/tegu_items/_belt.dm
  ModularTegustation/tegu_items/rcorp/itemspawner.dm
  _maps/map_files/Event/rcorp.dmm
  code/modules/jobs/job_types/rcorp/rhino.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/durand.dm
  code/modules/vehicles/mecha/combat/rhino.dm
  code/modules/vehicles/mecha/combat/tank.dm
  code/modules/vehicles/mecha/equipment/tools/other_tools.dm
  code/modules/vehicles/mecha/equipment/weapons/mecha_melee.dm
  code/modules/vehicles/mecha/mecha_actions.dm
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Balance, Side content

#2517 Multiple Armor Slowdown
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
Labels: Balance

#2568 [MIRROR] Removed proc overhead from the Input subsystem (#59339)
  code/controllers/subsystem/input.dm
  code/modules/keybindings/bindings_client.dm
Labels: Code improvement, Isolated Code, Performance Improvement?

#2576 Some Bugfixes
  ModularTegustation/ego_weapons/ranged/waw.dm
  code/modules/jobs/job_types/labs/medical/chemist.dm
  code/modules/mob/living/simple_animal/abnormality/waw/caterpillar.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
Labels: Fix
