Repository vlggms/lobotomy-corp13, pull requests merged in 2024-09, with the labels that each got.

#2228 Manniquins for EO Display [DONE]
  code/datums/components/crafting/recipes/structures.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/game/objects/structures/mannequin.dm
  icons/obj/mannequin.dmi
  lobotomy-corp13.dme
Labels: Feature

#2392 Gold Rush Minor Rebalance
  code/game/objects/items/ego_weapons/aleph.dm
Labels: Balance, Isolated Code

#1579 Shock Centipede PR
  ModularTegustation/Teguicons/96x64.dmi
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/shock_centipede.dm
  code/modules/paperwork/records/info/he.dm
  lobotomy-corp13.dme
Labels: Abnormality

#2405 Shock Work Fix
  code/modules/mob/living/simple_animal/abnormality/he/shock_centipede.dm
Labels: Fix, Isolated Code

#2253 Adds My Form Empties
  ModularTegustation/Teguicons/32x96.dmi
  ModularTegustation/Teguicons/64x96.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/__DEFINES/sound.dm
  code/__HELPERS/unsorted.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/datums/looping_sounds/abnormalities.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/waw/my_form_empties.dm
  code/modules/mob/living/simple_animal/dc_changes.dm
  code/modules/paperwork/records/info/waw.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
  sound/abnormalities/myformempties/MFE_theme.ogg
  sound/abnormalities/myformempties/MFEattack.ogg
Labels: Abnormality

#2408 Makes the shrimp tongue no longer change "krill" into "kreel"
  code/modules/mob/living/carbon/human/species_types/shrimp.dm
Labels: Fix

#2406 A shocking PR
  ModularTegustation/Teguicons/lc13_coloreffect.dmi
  ModularTegustation/tegu_items/associations/fixer.dm
  code/game/objects/effects/temporary_visuals/effect_indicators.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/non_abnormality/weak_edits/ecorp.dm
  code/game/objects/items/ego_weapons/subtype/charge.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/dusk.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  icons/effects/effects.dmi
  lobotomy-corp13.dme
Labels: Code improvement, Fix, Sprites, Expansion

#2407 Shock centipede adjustments
  code/modules/mob/living/simple_animal/abnormality/he/shock_centipede.dm
  code/modules/paperwork/records/info/he.dm
Labels: Balance, Tweak, Isolated Code

#2404 Density, bullet, and other miscellaneous fixes
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/mob/living/simple_animal/abnormality/he/drifting_fox.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
  code/modules/mob/living/simple_animal/abnormality/waw/red_riding_mercenary.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/dusk.dm
  code/modules/paperwork/records/info/aleph.dm
Labels: Tweak, Fix

#2418 LCL Airlocks Fix
  _maps/map_files/Event/laboratory.dmm
Labels: Fix, Mapping

#2416 Spider bud now slaps you for destroying its cocoons, cocoons are more naturally spread across the cell.
  code/modules/mob/living/simple_animal/abnormality/teth/spider_bud.dm
  code/modules/paperwork/records/info/teth.dm
Labels: Code improvement, Tweak, Isolated Code

#2417 Small Mannequin Fix
  code/game/objects/structures/mannequin.dm
Labels: Fix, Isolated Code

#2421 summer hotspot fix
  code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
Labels: Fix, Isolated Code

#2420 Adventure Console shop expansion
  ModularTegustation/_adventure_console/adventure_layout.dm
Labels: Tweak, Isolated Code

#2424 Update actions
  .github/workflows/ci_suite.yml
Labels: Github, Fix

#2382 Adds melee damage to guns
  ModularTegustation/tegu_items/extraction/egosurgery.dm
  code/_onclick/item_attack.dm
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/components/fullauto.dm
  code/game/objects/items.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/non_abnormality/fullstop.dm
  code/game/objects/items/ego_weapons/non_abnormality/kcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/lcorp_melee.dm
  code/game/objects/items/ego_weapons/non_abnormality/lcorp_ranged.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_labs.dm
  code/game/objects/items/ego_weapons/non_abnormality/rats.dm
  code/game/objects/items/ego_weapons/non_abnormality/shrimp.dm
  code/game/objects/items/ego_weapons/non_abnormality/thumb.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_guns.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/promise.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ego_gun.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/special.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  code/modules/spells/ability_types/realized.dm
Labels: Balance, Tweak, Freeze, Merge Date Set

#2411 Abnormality Portrait Refactor
  code/__HELPERS/abnormalities.dm
  code/game/gamemodes/management/management.dm
  code/game/machinery/computer/abnormality_portraits.dm
  code/game/machinery/computer/abnormality_work.dm
  lobotomy-corp13.dme
Labels: Code improvement, Refactor

#2428 Adds ERA Stat Req Buff to Other Applicable Armors
  code/game/objects/items/ego_weapons/non_abnormality/black_silence.dm
  code/game/objects/items/ego_weapons/non_abnormality/kcorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/index.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/ucorp.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/wcorp.dm
Labels: Tweak

#2443 Associate Fixer is no longer trusted.
  code/modules/jobs/job_types/trusted_players/association/associate.dm
Labels: Tweak, Side content

#2279 Adds monoliths
  ModularTegustation/Teguicons/48x48.dmi
  code/modules/mob/living/simple_animal/distortion/_distortion.dm
  code/modules/mob/living/simple_animal/distortion/legend/papa_bongy.dm
  code/modules/mob/living/simple_animal/distortion/monolith.dm
  code/modules/mob/living/simple_animal/distortion/myth/another_day_work.dm
  code/modules/mob/living/simple_animal/distortion/plague/bunnyman.dm
  code/modules/mob/living/simple_animal/distortion/plague/lantern.dm
  code/modules/mob/living/simple_animal/distortion/star/shrimp.dm
  lobotomy-corp13.dme
Labels: Feature

#2442 Makes the EO's weapon buffing tool always give you the chance to get a weapon to 10% additional damage
  ModularTegustation/tegu_items/extraction/egosurgery.dm
Labels: Code improvement, Fix

#2419 Sunset Traveller Overhaul
  ModularTegustation/Teguicons/32x32.dmi
  code/modules/mob/living/simple_animal/abnormality/zayin/sunset_traveller.dm
Labels: Balance

#2413 Reindeers no longer kill everyone when crossing beams
  code/modules/projectiles/guns/misc/medbeam.dm
  code/modules/projectiles/guns/misc/reindeer.dm
Labels: Balance, Side content, Isolated Code

#2410 Ambling Pearl EGO/Icon Dump
  ModularTegustation/Teguicons/64x64.dmi
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  sound/abnormalities/ambling pearl/goo effect.ogg
  sound/abnormalities/ambling pearl/walking_3_1-1.ogg
  sound/weapons/ego/effervescent.ogg
Labels: Feature

#2446 Scraps duds, fixes Dealer description and adds final observation
  code/modules/mob/living/simple_animal/abnormality/teth/dealerdamned.dm
  code/modules/projectiles/ammunition/ego_ammunition/zayin.dm
  code/modules/projectiles/projectile/ego_bullets/zayin.dm
Labels: Writing, Expansion

#1991 Distorted form can now transform into You're Bald...
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
Labels: Feature

#2440 Replaced W-Corp wall phasing morgue trays with normal morgue trays
  _maps/map_files/Event/laboratory.dmm
Labels: Mapping

#2437 Der Freischutz has replaced his rubber bullets with magic bullets for rca
  ModularTegustation/tegu_items/rcorp/!abno_overwrites.dm
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
Labels: Balance, Side content

#2438 R-Corp Backup Now 100% More Suicidal
  ModularTegustation/tegu_items/representative/spawners.dm
  code/modules/clothing/outfits/ert.dm
Labels: Tweak, Fix

#2439 Priority City vendors now made of X-Corp Indestructonium alloy
  ModularTegustation/tegu_items/associations/vending.dm
Labels: Tweak, Fix, Isolated Code

#2450 Fixes old lady's and forsaken murderer's document being melded together
  code/modules/paperwork/records/lore/teth.dm
Labels: Fix
