Repository vlggms/lobotomy-corp13, pull requests merged in 2024-07, with the labels that each got.

#2196 fixes some stuff relating to ego weapons
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/special.dm
  code/game/objects/items/ego_weapons/waw.dm
Labels: Balance

#2266 Metal pipe if it was actually good
  code/game/objects/items/ego_weapons/non_abnormality/pipebutgood.dm
  lobotomy-corp13.dme
Labels: Feature, Isolated Code

#2225 Click tile to hit mobs
  code/_onclick/click.dm
  code/_onclick/other_mobs.dm
Labels: Feature

#2272 Brute is not a real type of armor, looks like. Public is shocked!
  ModularTegustation/living/damage_procs.dm
Labels: Fix

#2270 Fixes thunderbird's E.G.O weapon
  code/game/objects/items/ego_weapons/waw.dm
Labels: Fix

#2275 IsContained() Sanity check
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Fix, Isolated Code

#2258 Lowers the damage dealt by the saw bones surgery step
  code/modules/surgery/organic_steps.dm
Labels: Balance, Isolated Code

#2278 Makes more abnormalities ignore other Z levels for checks
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/aleph/crying_children.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/norinori.dm
  code/modules/mob/living/simple_animal/abnormality/teth/pale_horse.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/hammer_light.dm
Labels: Tweak, Fix, Isolated Code

#2271 Weapon Maintenance PR
  code/game/objects/items/ego_weapons/_lists.dm
  code/modules/projectiles/guns/ego_gun.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/guns/ego_gun/waw.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
Labels: Balance

#2192 Snow Queen's Winter Arrives [DONE]
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/64x96.dmi
  ModularTegustation/Teguicons/lc13_effects64x64.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  _maps/map_files/generic/Abnormality_Z.dmm
  code/datums/abnormality/_ego_datum/he.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/effects/abnormality.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/game/objects/structures/flora.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/flora/ausflora.dmi
Labels: Mapping, Abnormality

#2169 Ardor Blossom Moth
  ModularTegustation/Teguicons/48x48.dmi
  code/datums/abnormality/_ego_datum/he.dm
  code/game/machinery/regenerator.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/ardor_blossom_moth.dm
  code/modules/paperwork/records/info/he.dm
  code/modules/projectiles/ammunition/ego_ammunition/he.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/projectile/ego_bullets/he.dm
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#2289 Frost Splinter Hotfix
  code/game/objects/items/ego_weapons/he.dm
  lobotomy-corp13.dme
Labels: Fix, Isolated Code

#2282 Fix Hypocrisy Ego Gift
  code/modules/mob/living/carbon/human/ego_gifts.dm
Labels: Fix, Isolated Code

#2292 Timestop no longer affects godmodded mobs
  code/modules/fields/timestop.dm
Labels: Fix

#2290 Lets you sit on quiet day's bench, also you can now stop his talking by pushing him instead of leaving the containment repeatedly (you monster)
  code/modules/mob/living/simple_animal/abnormality/zayin/quiet_day.dm
Labels: Fix, Isolated Code

#2262 Makes a parent for Snake oil/Skin prophecy/Viva la voce/Theonite slab. They can always and only be used 10 times now
  code/modules/mob/living/simple_animal/abnormality/_tools/basic_attribute_giver.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/theonite_slab.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/vivavoce.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/bracelet.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/skin.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/snake_oil.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/tool_abnormality.dm
  code/modules/paperwork/records/info/tools.dm
  lobotomy-corp13.dme
Labels: Code improvement

#2293 Halves the Refresh Rates of Crew Monitors from 10 seconds to 5 seconds
  code/game/machinery/computer/crew.dm
Labels: Tweak, Isolated Code

#2208 Golden Apple RCA adjustments
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
Labels: Balance, Isolated Code

#2267 Adds a Test Range Ghost Role Spawner, and makes Lore Cabinets actually spawn in the Records Library
  _maps/map_files/generic/Test_Range.dmm
  _maps/map_files/generic/Tutorial_Zone.dmm
  code/controllers/subsystem/mapping.dm
  code/game/area/areas/lobotomy_corp.dm
  code/game/machinery/quantum_pad.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/game/objects/structures/test_range.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/aleph/sukuna.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  lobotomy-corp13.dme
Labels: Feature, Mapping

#2297 Drifting fox rework and bugfixes
  code/game/objects/items/ego_weapons/he.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/space_lady.dm
  code/modules/mob/living/simple_animal/abnormality/he/drifting_fox.dm
  code/modules/paperwork/records/info/he.dm
  sound/abnormalities/drifting_fox/fox_umbrella.ogg
  sound/weapons/ego/sunshower1.ogg
  sound/weapons/ego/sunshower2.ogg
  sound/weapons/ego/sunshower3.ogg
Labels: Balance, Fix

#2284 Color Damage Effects
  ModularTegustation/Teguicons/lc13_coloreffect.dmi
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Tweak

#2285 Pushes back the closet hiding variables to just open turfs
  ModularTegustation/hiding/abnormality.dm
  ModularTegustation/hiding/closet.dm
  ModularTegustation/hiding/turf.dm
Labels: Fix, Isolated Code

#2298 Buffs Bucket
  code/modules/projectiles/guns/ego_gun/zayin.dm
Labels: Tweak, Isolated Code

#2302 Adds some custom suicides to some LC13 items.
  ModularTegustation/tegu_items/gadgets/manager_bullets.dm
  ModularTegustation/tegu_items/gadgets/powered.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
Labels: Feature, Isolated Code

#2304 Thetacorp Map Fix
  _maps/map_files/Theta/thetacorp.dmm
Labels: Mapping

#2307 Zeta kitchen redone + fish fridge
  _maps/map_files/Zeta/zetacorp.dmm
Labels: Mapping, Expansion

#2309 Some LCL Bugfixes
  ModularTegustation/lc13_machinery.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_labs.dm
  code/modules/jobs/job_types/labs/support/chef.dm
Labels: Fix

#2303 Adds abnormalities in a seperate tab on the orbit menu
  code/modules/mob/dead/observer/orbit.dm
  tgui/packages/tgui/interfaces/Orbit.js
Labels: Feature, Isolated Code

#2305 Un-Lava-ing Kappa Corp Map and Theta Map Fix 2.0
  _maps/map_files/Kappa/kappacorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
Labels: Mapping

#2313 Minor change to ERA buff description
  code/game/objects/items/ego_weapons/non_abnormality/_cityweapons.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/_cityarmor.dm
Labels: Writing

#2314 ERA Work Bugfix
  code/__HELPERS/lobotomy_corp.dm
  code/controllers/subsystem/lobotomy_corp.dm
Labels: Fix, Isolated Code

#2317 Updates bleeding heart description
  code/game/objects/items/ego_weapons/waw.dm
Labels: Writing

#2269 Wielded Weapon Subtype
  code/game/objects/items/ego_weapons/subtype/wielded.dm
  lobotomy-corp13.dme
Labels: Feature, Isolated Code

#2202 Red hood Vs Big Bad Wolf and other fixes
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/mob/living/simple_animal/abnormality/waw/big_wolf.dm
  code/modules/mob/living/simple_animal/abnormality/waw/red_riding_mercenary.dm
  code/modules/paperwork/records/info/waw.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
Labels: Code improvement, Feature, Fix, Expansion

#2316 Theta Corp map fix 3
  _maps/map_files/Theta/thetacorp.dmm
Labels: Fix, Mapping

#2318 Fixes incorrect variable override on chairs, chairs now shift your position if they are themselfes pixel shifted
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Iota/iotacorp.dmm
  _maps/map_files/Kappa/kappacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Theta/thetacorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
  code/game/objects/structures/beds_chairs/chair.dm
Labels: Code improvement, Fix, Mapping

#1963 Resurgence Clan, Mobs
  ModularTegustation/Teguicons/resurgence_32x48.dmi
  ModularTegustation/Teguicons/resurgence_48x48.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/tegu_items/associations/machines.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/north.dm
  ModularTegustation/tegu_mobs/lc13_resurgence_clan_mobs.dm
  ModularTegustation/tegu_mobs/lc13_resurgence_tapes.dm
  _maps/RandomRooms/backstreets/small_north/small_clan_hideout.dmm
  code/datums/components/crafting/recipes/carnival_silkcrafting.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/stacks/sheets/silk.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/woven_armor.dm
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/obj/clothing/ego_gear/lc13_armor.dmi
  icons/obj/stack_objects.dmi
  icons/turf/floors.dmi
  lobotomy-corp13.dme
Labels: Feature

#2220 Experimental Job Overhaul
  ModularTegustation/Teguicons/refiner.dmi
  ModularTegustation/tegu_items/_belt.dm
  ModularTegustation/tegu_items/gadgets/powered.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  _maps/map_files/Alpha/alphacorp.dmm
  _maps/map_files/Beta/betacorp.dmm
  _maps/map_files/Delta/deltacorp.dmm
  _maps/map_files/Epsilon/epsiloncorp.dmm
  _maps/map_files/Eta/etacorp.dmm
  _maps/map_files/Gamma/gammacorp.dmm
  _maps/map_files/Kappa/kappacorp.dmm
  _maps/map_files/Lambda/lambdacorp.dmm
  _maps/map_files/Psi/psicorp.dmm
  _maps/map_files/Zeta/zetacorp.dmm
  code/game/machinery/computer/abnormality_ego.dm
  code/game/objects/items/clerks/hypo/hypo.dm
  code/game/objects/items/fixerskills/level4/team.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/ego_gear/special.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/suppression.dm
  code/modules/jobs/jobs.dm
  icons/mob/clothing/ego_gear/suit.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/crates.dmi
  lobotomy-corp13.dme
Labels: Balance, Expansion

#2320 Pushes our midi2piano tool to its latest version, monke's of course because TG's is broke as shit
  tools/midi2piano/README.txt
  tools/midi2piano/easygui/__init__.py
  tools/midi2piano/midi/midi.py
  tools/midi2piano/midi2piano.py
Labels: Code improvement

#2312 Tweaks Green Stem Ego and New Move_Resist Proc[DONE]
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/waw.dm
Labels: Tweak

#1686 Ordeal armor
  code/datums/abnormality/_ego_datum/ordeal.dm
  code/game/objects/items/stacks/sheets/silk.dm
  code/modules/clothing/suits/ego_gear/ordeal.dm
  icons/mob/clothing/ego_gear/ordeal.dmi
  icons/obj/clothing/ego_gear/ordeal.dmi
  icons/obj/library.dmi
  lobotomy-corp13.dme
Labels: Tweak, Sprites

#2321 Fixes equipment issues with LCL
  _maps/map_files/Event/laboratory.dmm
Labels: Balance, Mapping

#2249 Delays Ordeal Minimum Times
  code/controllers/subsystem/lobotomy_corp.dm
Labels: Balance, Isolated Code

#2273 Removes Attack Speed Variable = 1 Runtime[DONE]
  code/game/objects/items/ego_weapons/_ego_weapon.dm
Labels: Tweak, Fix, Isolated Code

#1950 listclearnulls is faster now
  code/__HELPERS/_lists.dm
Labels: Code improvement, Stale, Isolated Code

#2229 Item middle click actions
  code/__DEFINES/dcs/signals.dm
  code/_onclick/click.dm
  code/game/objects/items.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
Labels: Feature

#2295 A beginning for customizable TGUI: Auxiliary console preference
  code/game/machinery/computer/abnormality_auxiliary.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  tgui/packages/tgui/interfaces/AuxiliaryManagerConsole.js
Labels: Code improvement

#2268 Turns Off Atmos Subsystem[DONE?]
  code/controllers/subsystem/air.dm
  code/game/turfs/open/lobotomy.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/gasmixtures/immutable_mixtures.dm
  code/modules/mob/living/carbon/life.dm
Labels: Fix, Do Not Merge - Maintainer Discussion

#1468 Crow's Eye View
  ModularTegustation/tegu_items/refinery/crates/misc.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_ego.dm
  icons/obj/limbus_weapons.dmi
Labels: Feature, Stale

#2277 New Achivements[DONE][NEEDS TESTMERGE]
  code/__DEFINES/achievements.dm
  code/__HELPERS/roundend.dm
  code/datums/achievements/boss_achievements.dm
  code/datums/achievements/misc_achievements.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/ordeals/amber_ordeals.dm
  code/modules/ordeals/green_ordeals.dm
  code/modules/ordeals/violet_ordeals.dm
  code/modules/ordeals/white_ordeals.dm
  icons/UI_Icons/Achievements/Boss/amber.png
  icons/UI_Icons/Achievements/Boss/claw.png
  icons/UI_Icons/Achievements/Boss/green.png
  icons/UI_Icons/Achievements/Boss/violet.png
  icons/UI_Icons/Achievements/Boss/whitenight.png
  icons/UI_Icons/Achievements/Misc/lcorp.png
  icons/UI_Icons/Achievements/Misc/shrimp.png
  icons/UI_Icons/Achievements/Misc/twlight.png
Labels: Feature

#2256 Adds the ordeals of brown and revamped gold ordeals
  ModularTegustation/Teguicons/128x64.dmi
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/32x64.dmi
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/64x48.dmi
  ModularTegustation/Teguicons/96x96.dmi
  ModularTegustation/tegu_mobs/lc13_corrosions.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/aleph/sukuna.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/mob/living/simple_animal/abnormality/he/headless_ichthys.dm
  code/modules/mob/living/simple_animal/abnormality/he/puss_in_boots.dm
  code/modules/mob/living/simple_animal/abnormality/teth/faelantern.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/blubbering_toad.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/brown/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/dusk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/midnight.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/noon.dm
  code/modules/ordeals/brown_ordeals.dm
  code/modules/ordeals/gold_ordeals.dm
  lobotomy-corp13.dme
  sound/abnormalities/doomsdaycalendar/Limbus_Dead_Generic.ogg
  sound/effects/limbus_death.ogg
  sound/effects/ordeals/brown/cromer_slam.ogg
  sound/effects/ordeals/brown/cromer_stab.ogg
  sound/effects/ordeals/brown/dead_generic.ogg
  sound/effects/ordeals/brown/flea_attack.ogg
  sound/effects/ordeals/brown/flea_dead.ogg
  sound/effects/ordeals/brown/flea_kill.ogg
  sound/effects/ordeals/brown/flower_attack.ogg
  sound/effects/ordeals/brown/flower_kill.ogg
  sound/effects/ordeals/brown/pridespin.ogg
  sound/effects/ordeals/brown/rock_attack.ogg
  sound/effects/ordeals/brown/rock_dead.ogg
  sound/effects/ordeals/brown/rock_kill.ogg
  sound/effects/ordeals/brown/rock_runover.ogg
  sound/effects/ordeals/brown/tentacle_attack.ogg
  sound/effects/ordeals/brown/tentacle_before_explode.ogg
  sound/effects/ordeals/brown/tentacle_death.ogg
  sound/effects/ordeals/brown/tentacle_explode.ogg
  sound/effects/ordeals/brown_end.ogg
  sound/effects/ordeals/brown_start.ogg
  sound/effects/ordeals/gold/radiostatic.ogg
Labels: Feature

#1895 Throwing Animation, Audio, and Verbs
  code/__HELPERS/pronouns.dm
  code/game/objects/items.dm
  code/game/objects/items/cigs_lighters.dm
  code/modules/mob/living/carbon/carbon.dm
  sound/attributions.txt
  sound/weapons/throw.ogg
  sound/weapons/throwhard.ogg
  sound/weapons/throwsoft.ogg
Labels: Feature, Tweak

#1730 More Wrathful Servant
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
Labels: Balance, Stale

#2238 Rcorp rep additions
  ModularTegustation/tegu_items/representative/research/rcorp.dm
  ModularTegustation/tegu_items/representative/spawners.dm
Labels: Balance, Isolated Code

#2122 Tip updates to include more Jobs
  strings/abnotips.txt
  strings/jobtips.txt
Labels: Writing

#2286 Reusable visual optimisation
  code/datums/reusable_visual_pool.dm
  code/game/objects/effects/reusable_visual.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet.dm
Labels: Tweak, Isolated Code, Performance Improvement?

#2062 Playable Laetitia!
  ModularTegustation/tegu_items/limbus_labs/spawners.dm
  code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
Labels: Feature

#2308 Snow Queen New Gift[DONE]
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
  icons/mob/clothing/ego_gear/ego_gifts.dmi
Labels: Tweak

#2324 Removes White Pixel From Vermillion Cross Sprite
  ModularTegustation/Teguicons/lc13_left_64x64.dmi
Labels: Sprites

#2323 Disabling Atmospherics Subsystem Hotfix
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/surgery/organs/lungs.dm
Labels: Fix

#1499 Adds Weapon Sweeping and Thrusting
  ModularTegustation/Teguicons/64x32.dmi
  ModularTegustation/Teguicons/96x96.dmi
  code/__DEFINES/~lobotomy_defines/weapon.dm
  code/__HELPERS/icons.dm
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
  code/game/objects/items/ego_weapons/_ego_weapon.dm
  code/game/objects/items/ego_weapons/non_abnormality/cinq.dm
  code/game/objects/items/ego_weapons/non_abnormality/purple_tear.dm
  code/game/objects/items/ego_weapons/non_abnormality/seven.dm
  code/game/objects/items/ego_weapons/subtype/lance.dm
  code/game/objects/items/ego_weapons/subtype/shield.dm
  code/game/objects/items/ego_weapons/waw.dm
Labels: Feature

#2326 TGUI Attributes
  code/modules/mob/living/carbon/human/human.dm
  tgui/packages/tgui/interfaces/ShowAttributes.js
Labels: Refactor, Isolated Code

#2329 Quiet day fixes and improvements
  code/modules/mob/living/simple_animal/abnormality/zayin/quiet_day.dm
Labels: Code improvement, Fix, Isolated Code

#2280 Fort insanity update
  code/__DEFINES/dcs/signals.dm
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/datums/ai/sanity/sanityloss_behaviors.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/mob/living/simple_animal/distortion/legend/papa_bongy.dm
  code/modules/vehicles/mecha/_mecha.dm
Labels: Tweak, Fix, Refactor

#2327 Laetitia Cooldown bugfix
  code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
Labels: Fix, Isolated Code

#2299 Final observations part 3
  code/modules/clothing/suits/ego_gear/special.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/space_lady.dm
  code/modules/mob/living/simple_animal/abnormality/he/KHz.dm
  code/modules/mob/living/simple_animal/abnormality/he/eris.dm
  code/modules/mob/living/simple_animal/abnormality/he/fan.dm
  code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
  code/modules/mob/living/simple_animal/abnormality/he/missed_reaper.dm
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
  code/modules/mob/living/simple_animal/abnormality/teth/faelantern.dm
  code/modules/mob/living/simple_animal/abnormality/teth/falada.dm
  code/modules/mob/living/simple_animal/abnormality/teth/training_rabbit.dm
  code/modules/mob/living/simple_animal/abnormality/waw/alriune.dm
  code/modules/mob/living/simple_animal/abnormality/waw/black_swan.dm
  code/modules/mob/living/simple_animal/abnormality/waw/contract.dm
  code/modules/mob/living/simple_animal/abnormality/waw/fire_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/living/simple_animal/abnormality/waw/parasite_tree.dm
  code/modules/mob/living/simple_animal/abnormality/waw/queen_bee.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bald.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/pile_of_mail.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
Labels: Expansion, Isolated Code

#2332 Makes Quota Calculated From Only Alive People
  code/controllers/subsystem/lobotomy_corp.dm
Labels: Balance

#2334 Swaps the snow queens and morii's armor and weapon locations around
  code/modules/mob/living/simple_animal/abnormality/he/better_memories.dm
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
Labels: Fix

#2340 Invisible nobody is finally(?) fixed
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
Labels: Fix

#2338 Shrimply a miracle -- Shrimp changes (buffs?) and injector cleanup
  ModularTegustation/tegu_items/injectors.dm
  code/modules/mob/living/carbon/human/species_types/shrimp.dm
Labels: Balance, Code improvement

#2342 So i casually broke every injector except the Agent one on the shrimp PR, casual [insert day here]
  ModularTegustation/tegu_items/injectors.dm
Labels: Fix

#2343 Reduces Blood Refinery PE Cost
  ModularTegustation/tegu_items/refinery/alt_refinery/blood.dm
Labels: Balance

#2141 J Corp Representative
  ModularTegustation/tegu_items/refinery/crates/_crate.dm
  ModularTegustation/tegu_items/refinery/crates/workshop.dm
  ModularTegustation/tegu_items/refinery/sales.dm
  ModularTegustation/tegu_items/representative/console.dm
  ModularTegustation/tegu_items/representative/items/jcorp.dm
  ModularTegustation/tegu_items/representative/research/jcorp.dm
  code/modules/clothing/under/clerksuits.dm
  code/modules/jobs/job_types/trusted_players/representative.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/storage.dmi
  lobotomy-corp13.dme
Labels: Expansion

#2345 View Gift Button in Attribute Window
  code/modules/mob/living/carbon/human/human.dm
  tgui/packages/tgui/interfaces/ShowAttributes.js
Labels: Tweak

#2346 [KAR] Fixes Quirk Runtime
  code/datums/quirks/_quirk.dm
Labels: Fix, Isolated Code

#2341 Adds more phrases for shrimp language to change
  code/modules/mob/living/carbon/human/species_types/shrimp.dm
Labels: Expansion, Isolated Code
