Repository vlggms/lobotomy-corp13, pull requests merged in 2024-08, with the labels that each got.

#2344 Optimizes most LC13 uses of Range to incorporate urange and livinginrange
  code/datums/ai/sanity/_sanityloss_controller.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/non_abnormality/blue_sicko.dm
  code/game/objects/items/ego_weapons/non_abnormality/purple_tear.dm
  code/game/objects/items/ego_weapons/ordeal.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_weapons.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/treesap.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/army_in_black.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nihil.dm
  code/modules/mob/living/simple_animal/abnormality/he/nameless_fetus.dm
  code/modules/mob/living/simple_animal/abnormality/teth/pale_horse.dm
  code/modules/mob/living/simple_animal/abnormality/teth/void_dream.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/orange_tree.dm
  code/modules/mob/living/simple_animal/abnormality/waw/red_riding_mercenary.dm
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/wrath_servant.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/event.dm
  code/modules/spells/ability_types/realized.dm
Labels: Code improvement, Performance Improvement?

#2347 Adds Stupor, a Sloshing Realization (And a Fallen Colors Bugfix)
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
  code/modules/spells/ability_types/realized_aimed.dm
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/realized.dmi
  icons/obj/clothing/ego_gear/head.dmi
  icons/obj/clothing/ego_gear/realization.dmi
Labels: Tweak, Fix

#2352 Improves Bottle of Tears' Workrates
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
Labels: Balance

#2350 August 2024 Sprite Dump and small pbird change[DONE]
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/48x64.dmi
  ModularTegustation/Teguicons/64x48.dmi
  ModularTegustation/Teguicons/96x64.dmi
  ModularTegustation/Teguicons/abno_cores/waw.dmi
  ModularTegustation/Teguicons/lc13_structures.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/toolabnormalities.dmi
  ModularTegustation/fishing/code/fish_market.dm
  code/modules/mob/living/simple_animal/abnormality/teth/punishing_bird.dm
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/ego_weapons.dmi
Labels: Tweak, Sprites

#2337 Small Fishing Update 1.3[DONE]
  ModularTegustation/fishing/code/fish/LC13_fish/freshwater_fish.dm
  ModularTegustation/fishing/code/fish/LC13_fish/saltwater_fish.dm
  ModularTegustation/fishing/code/turfs.dm
  ModularTegustation/fishing/icons/fish_sprites.dmi
Labels: Expansion

#2356 Black Sun Aux PR
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x64.dmi
  code/datums/abnormality/_ego_datum/aleph.dm
  code/game/objects/items/ego_weapons/_lists.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/projectiles/ammunition/ego_ammunition/aleph.dm
  code/modules/projectiles/guns/ego_gun/aleph.dm
  code/modules/projectiles/projectile/ego_bullets/aleph.dm
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/ego_weapons.dmi
Labels: Tweak, Sprites

#2357 Changes meat lantern to a temp 3 check
  code/modules/mob/living/simple_animal/abnormality/teth/meat_lantern.dm
  code/modules/paperwork/records/info/teth.dm
Labels: Balance, Code improvement

#2355 Qbee Balance Update
  code/datums/diseases/bee_spawn.dm
  code/modules/mob/living/simple_animal/abnormality/waw/queen_bee.dm
Labels: Balance

#2359 Fixes runtime when someone finishes off a mob that qdeletes on death with a knockback weapon
  code/game/objects/items/ego_weapons/_ego_weapon.dm
Labels: Code improvement, Isolated Code

#2319 Fallen Amurdad Crops Changes
  code/modules/hydroponics/grown/ambrosia.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fallen_amurdad.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Tweak, Isolated Code

#2360 Makes the spoon and Mail satchel show its true damage on examine, instead of hiding it
  code/game/objects/items/ego_weapons/special.dm
Labels: Code improvement, Isolated Code

#2325 Weapon rebalance 07 24
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/non_abnormality/dawn.dm
  code/game/objects/items/ego_weapons/non_abnormality/gradeone.dm
  code/game/objects/items/ego_weapons/non_abnormality/index.dm
  code/game/objects/items/ego_weapons/non_abnormality/jcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/jeong.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_ego.dm
  code/game/objects/items/ego_weapons/non_abnormality/limbus_sinner.dm
  code/game/objects/items/ego_weapons/non_abnormality/liu.dm
  code/game/objects/items/ego_weapons/non_abnormality/miscfixer.dm
  code/game/objects/items/ego_weapons/non_abnormality/molar.dm
  code/game/objects/items/ego_weapons/non_abnormality/pierre.dm
  code/game/objects/items/ego_weapons/non_abnormality/rats.dm
  code/game/objects/items/ego_weapons/non_abnormality/seven.dm
  code/game/objects/items/ego_weapons/non_abnormality/shi.dm
  code/game/objects/items/ego_weapons/non_abnormality/streetlight.dm
  code/game/objects/items/ego_weapons/non_abnormality/syndicate.dm
  code/game/objects/items/ego_weapons/non_abnormality/wcorp.dm
  code/game/objects/items/ego_weapons/non_abnormality/yun.dm
  code/game/objects/items/ego_weapons/non_abnormality/zwei.dm
  code/game/objects/items/ego_weapons/teth.dm
  code/game/objects/items/ego_weapons/waw.dm
Labels: Balance

#2361 abno month E.G.O PR
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/game/objects/items/ego_weapons/he.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/obj/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/ego_weapons.dmi
Labels: Sprites, Expansion

#2362 Makes the cherry tree no longer stop you from working or hold your gained attributes hostage for 10 seconds upon breaching
  code/modules/mob/living/simple_animal/abnormality/teth/cherry_blossoms.dm
Labels: Fix

#2349 New ego dump
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/tools.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/game/objects/items/ego_weapons/aleph.dm
  code/game/objects/items/ego_weapons/he.dm
  code/game/objects/items/ego_weapons/waw.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/ego_weapons.dmi
  sound/abnormalities/clownsmiling/egoslash.ogg
  sound/abnormalities/clownsmiling/egostab.ogg
  sound/abnormalities/clownsmiling/jumpscare.ogg
Labels: Sprites, Expansion

#2365 Fixes constant runtimes when sweeper equipment is used
  code/game/objects/items/ego_weapons/non_abnormality/sweeper.dm
Labels: Fix

#2366 Fixes runtime with metal fixer's projectiles calling the wrong arguments in a proc + cleanup
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
Labels: Fix, Isolated Code

#2354 Turns eta-corp wastefull var-edited turfs into actual coded ones
  ModularTegustation/turfs.dm
  _maps/map_files/Eta/etacorp.dmm
  lobotomy-corp13.dme
Labels: Code improvement, Mapping

#2369 Fixes Child Proc Oversights
  ModularTegustation/tegu_items/limbus_labs/!other_overwrites.dm
  ModularTegustation/tegu_items/rcorp/!abno_overwrites.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
Labels: Fix

#2376 Fixes the training officer having a "Newbie Agent" alt-title
  code/modules/jobs/job_types/mentor/trainingofficer.dm
Labels: Fix

#2374 Fixes even more metal fixer runtimes
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
Labels: Fix

#2371 Fix Naked Nest 0 Breach[DONE]
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
Labels: Fix

#2375 Removes stat equalizers from ERA's/DO's, stats automatically get assigned when available instead
  code/controllers/subsystem/abnormality_queue.dm
  code/datums/facility_upgrade.dm
  code/modules/jobs/job_types/mentor/trainingofficer.dm
  code/modules/jobs/job_types/suppression.dm
  code/modules/ordeals/_ordeal.dm
Labels: Feature

#2379 Fixes training officers tool not working
  ModularTegustation/Teguicons/teguitems.dmi
  code/modules/jobs/job_types/mentor/trainingofficer.dm
Labels: Fix

#2378 Fixes memories temperance check
  code/modules/mob/living/simple_animal/abnormality/he/better_memories.dm
Labels: Fix, Isolated Code

#2381 Soup code deshittification
  code/modules/mob/living/simple_animal/abnormality/he/basilisoup.dm
Labels: Balance, Code improvement, Fix

#2380 Improves Simple Smile's Work Rates
  code/modules/mob/living/simple_animal/abnormality/teth/simple_smile.dm
Labels: Balance, Isolated Code

#2372 Returns inhand Sprites to Rabbit Gun[DONE]
  code/game/objects/items/ego_weapons/non_abnormality/rcorp.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
Labels: Sprites

#2300 Makes Rose Sign's breach more manageable
  code/modules/mob/living/simple_animal/abnormality/waw/rose_sign.dm
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
Labels: Tweak, Isolated Code

#2370 Adds Oracle Ego[DONE with ORACLE]
  ModularTegustation/Teguicons/tegu_effects10x10.dmi
  code/datums/abnormality/_ego_datum/zayin.dm
  code/datums/status_effects/buffs.dm
  code/game/objects/items/ego_weapons/zayin.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  icons/mob/clothing/ego_gear/abnormality/zayin.dmi
  icons/mob/clothing/ego_gear/lc13_armor.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/zayin.dmi
  icons/obj/ego_weapons.dmi
Labels: Feature

#2377 Makes abnormalities where you avoid goods give more understanding on Neutrals
  code/datums/abnormality/datum/abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/silent_orchestra.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cherry_blossoms.dm
  code/modules/mob/living/simple_animal/abnormality/teth/spider_bud.dm
  code/modules/mob/living/simple_animal/abnormality/waw/alriune.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
  code/modules/mob/living/simple_animal/abnormality/waw/fire_bird.dm
Labels: Balance

#2358 Minor Abnormality Tweaks
  code/game/objects/items/ego_weapons/teth.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cherry_blossoms.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/little_prince.dm
  code/modules/mob/living/simple_animal/abnormality/waw/luna.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/projectiles/guns/ego_gun/he.dm
Labels: Balance

#2367 Fetus Tweaks
  code/modules/mob/living/simple_animal/abnormality/he/nameless_fetus.dm
  code/modules/paperwork/records/info/he.dm
Labels: Balance, Isolated Code

#2387 Makes bottle of tears no longer consider your temperance buff, when taking away your justice
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
Labels: Code improvement, Fix, Isolated Code

#2335 Snow Queen Lag Reduction[DONE]
  code/game/objects/effects/abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
Labels: Tweak

#2385 Reversion of Qbee buff
  code/datums/diseases/bee_spawn.dm
Labels: Balance

#2276 Epsiloncorp Fixes and Emulsijack Pollution Removed [DONE]
  ModularTegustation/fishing/code/turfs.dm
  _maps/map_files/Epsilon/epsiloncorp.dmm
Labels: Tweak, Fix, Mapping

#2263 L-corp gacha and ERA gear
  ModularTegustation/Teguicons/lcorp_left.dmi
  ModularTegustation/Teguicons/lcorp_right.dmi
  ModularTegustation/Teguicons/lcorp_weapons.dmi
  ModularTegustation/Teguicons/teguitems.dmi
  ModularTegustation/tegu_items/disciplinary/_disciplinary.dm
  ModularTegustation/tegu_items/disciplinary/egoshards.dm
  code/game/objects/items/ego_weapons/non_abnormality/lcorp_melee.dm
  code/game/objects/items/ego_weapons/non_abnormality/lcorp_ranged.dm
  code/game/objects/items/melee/misc.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/lcorp.dm
  code/modules/clothing/suits/ego_gear/special.dm
  code/modules/projectiles/guns/ego_gun/zayin.dm
  icons/mob/clothing/ego_gear/lcorp.dmi
  icons/mob/clothing/ego_gear/suit.dmi
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/ego_gear/lcorp.dmi
  icons/obj/clothing/ego_gear/suits.dmi
  icons/obj/clothing/suits.dmi
  lobotomy-corp13.dme
Labels: Feature, Sprites

#2322 Oracle Of No Future
  ModularTegustation/Teguicons/tegumobs.dmi
  code/modules/mob/living/simple_animal/abnormality/zayin/oracle.dm
  code/modules/paperwork/records/info/zayin.dm
  lobotomy-corp13.dme
Labels: Abnormality

#2391 Gold midnight disable and new ordeal SFX
  code/modules/ordeals/gold_ordeals.dm
  sound/effects/ordeals/gold_end.ogg
  sound/effects/ordeals/gold_end_special.ogg
  sound/effects/ordeals/gold_start.ogg
Labels: Tweak

#2331 Dealer of the Damned (Formerly-ish Six-Shot Sharper)
  ModularTegustation/Teguicons/64x64.dmi
  code/datums/abnormality/_ego_datum/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/teth/dealerdamned.dm
  code/modules/paperwork/records/info/teth.dm
  code/modules/projectiles/ammunition/ego_ammunition/teth.dm
  code/modules/projectiles/ammunition/ego_ammunition/waw.dm
  code/modules/projectiles/ammunition/ego_ammunition/zayin.dm
  code/modules/projectiles/guns/ego_gun/he.dm
  code/modules/projectiles/guns/ego_gun/teth.dm
  code/modules/projectiles/projectile/ego_bullets/teth.dm
  code/modules/projectiles/projectile/ego_bullets/waw.dm
  code/modules/projectiles/projectile/ego_bullets/zayin.dm
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#2199 Second coming of the Black Sun
  code/modules/mob/living/simple_animal/abnormality/aleph/black_sun.dm
  code/modules/paperwork/records/info/aleph.dm
  icons/effects/weather_effects.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#2383 Snow Queen Arena Tweaks and Fixes[DONE]
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
Labels: Balance, Tweak, Fix, Isolated Code

#2395 Removes Box of L corp Debug tools from J Corp Lootbox pool
  ModularTegustation/tegu_items/representative/items/jcorp.dm
Labels: Fix

#2397 Allow Wcorp Vest to be Removed from Armor Fridges
  code/modules/clothing/suits/ego_gear/non_abnormality/wcorp.dm
Labels: Fix

#2398 Snow queen and crumbling armor final observation adjustments
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
  code/modules/mob/living/simple_animal/abnormality/teth/crumbling_armor.dm
Labels: Tweak, Fix

#2401 Distorted form bug fix
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
Labels: Fix

#2399 Sphinx fixes and adjustments(?)
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
Labels: Fix, Sprites

#2400 Sweeping Refactor
  code/__DEFINES/~lobotomy_defines/weapon.dm
  code/_onclick/item_attack.dm
Labels: Refactor

#2402 Minor grammatical improvements
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
Labels: Writing

#2384 Updates oz abnos to be less punishing.
  code/modules/mob/living/simple_animal/abnormality/he/road_home.dm
  code/modules/mob/living/simple_animal/abnormality/he/scarecrow.dm
  code/modules/mob/living/simple_animal/abnormality/he/scaredy_cat.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/paperwork/records/info/he.dm
Labels: Balance, Isolated Code
