Repository vlggms/lobotomy-corp13, pull requests merged in 2025-03, with the labels that each got.

#2738 Pulsar's cooking update 2 (cakes)
  code/game/objects/items/food/cake.dm
  code/game/objects/items/food/pastries.dm
  code/game/objects/items/food/pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  icons/obj/food/piecake.dmi
Labels: Sprites, Expansion

#2590 Danteh Clock Head
  ModularTegustation/danteh_head.dm
  code/__DEFINES/language.dm
  code/modules/surgery/organs/tongue.dm
  icons/hud/screen_skills.dmi
  icons/misc/language.dmi
  icons/mob/clothing/head.dmi
  icons/obj/clothing/hats.dmi
  lobotomy-corp13.dme
Labels: Feature

#2695 BPU Fixes Part 2
  ModularTegustation/lc13_machinery.dm
Labels: Fix

#2628 Hostile AI fixes
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/aleph/crying_children.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/aleph/rudolta_buff.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/aleph/sukuna.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/mountain.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/space_lady.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/titania.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/basilisoup.dm
  code/modules/mob/living/simple_animal/abnormality/he/better_memories.dm
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
  code/modules/mob/living/simple_animal/abnormality/he/drifting_fox.dm
  code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_buddy.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_shoes.dm
  code/modules/mob/living/simple_animal/abnormality/he/scarecrow.dm
  code/modules/mob/living/simple_animal/abnormality/teth/faelantern.dm
  code/modules/mob/living/simple_animal/abnormality/teth/ppodae.dm
  code/modules/mob/living/simple_animal/abnormality/teth/redblooded.dm
  code/modules/mob/living/simple_animal/abnormality/teth/scorched_girl.dm
  code/modules/mob/living/simple_animal/abnormality/waw/apex_predator.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clouded_monk.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
  code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dreaming_current.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/my_form_empties.dm
  code/modules/mob/living/simple_animal/abnormality/waw/naked_nest.dm
  code/modules/mob/living/simple_animal/abnormality/waw/parasite_tree.dm
  code/modules/mob/living/simple_animal/abnormality/waw/pygmalion.dm
  code/modules/mob/living/simple_animal/abnormality/waw/rose_sign.dm
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
  code/modules/mob/living/simple_animal/abnormality/waw/sphinx.dm
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/blubbering_toad.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
Labels: Code improvement, Fix

#2510 col ncorp nerf
  ModularTegustation/ego_weapons/melee/non_abnormality/ncorp.dm
Labels: Balance, Side content

#2725 Ego fixes
  ModularTegustation/ego_weapons/melee/aleph.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/black_silence.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/carnival.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/hana.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/index.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/kcorp.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/limbus_ego.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/limbus_sinner.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/liu.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/miscfixer.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/rosespanner.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/wcorp.dm
  ModularTegustation/ego_weapons/melee/special.dm
  ModularTegustation/ego_weapons/melee/waw.dm
  ModularTegustation/tegu_items/disciplinary/egoshards.dm
  ModularTegustation/tegu_items/workshop/templates/basic.dm
Labels: Balance, Fix

#2751 Work Console Meltdown Indicator Upgrade
  ModularTegustation/lc13_machinery.dm
  ModularTegustation/lc13_obj/lc13_computers/abnormality_work.dm
  ModularTegustation/tegu_items/abnoconsole_upgrades.dm
  code/game/machinery/computer/extraction_cargo.dm
  lobotomy-corp13.dme
Labels: Expansion

#2734 Para's Devious Trap Update
  ModularTegustation/Teguicons/lc13_structures.dmi
  ModularTegustation/lc13_traps.dm
  ModularTegustation/signal_system.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/large/south.dm
  _maps/RandomRooms/backstreets/large_south/shotgun_exam.dmm
  code/controllers/subsystem/minor_mapping.dm
  code/game/objects/items/devices/pressureplates.dm
  code/modules/assembly/signaler.dm
  icons/turf/floors.dmi
  lobotomy-corp13.dme
Labels: Feature

#2214 Replaces General Mob Spawns in Rooms with Spawners [DONE]
  ModularTegustation/lc13_spawners.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/bigrooms/pointofinterest.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/east.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/west.dm
  _maps/RandomRooms/backstreets/connector/sweeper_ca.dmm
  _maps/RandomRooms/backstreets/large_north/apartment_lna.dmm
  _maps/RandomRooms/backstreets/large_north/scorp.dmm
  _maps/RandomRooms/backstreets/large_north/scorp_warehouse.dmm
  _maps/RandomRooms/backstreets/large_south/apartment_lsa.dmm
  _maps/RandomRooms/backstreets/large_south/gcorp_armory.dmm
  _maps/RandomRooms/backstreets/large_south/supermarket.dmm
  _maps/RandomRooms/backstreets/medium_north/gmanager_house.dmm
  _maps/RandomRooms/backstreets/medium_south/eyes_temple.dmm
  _maps/RandomRooms/backstreets/medium_south/theatre.dmm
  _maps/RandomRooms/backstreets/medium_west/butcher_medium.dmm
  _maps/RandomRooms/backstreets/medium_west/lcorp_office.dmm
  _maps/RandomRooms/backstreets/medium_west/office_kcorp.dmm
  _maps/RandomRooms/backstreets/pointofinterest/love_train.dmm
  _maps/RandomRooms/backstreets/pointofinterest/robot_city.dmm
  _maps/RandomRooms/backstreets/pointofinterest/scorp_vaultb.dmm
  _maps/RandomRooms/backstreets/small_north/pet_store.dmm
  _maps/RandomRooms/backstreets/small_south/rat_ssa.dmm
  _maps/RandomRooms/backstreets/small_south/wcorp_base_ssa.dmm
  _maps/RandomRooms/backstreets/small_west/dry_cleaners.dmm
  _maps/RandomRooms/backstreets/small_west/freezer_sw.dmm
  _maps/RandomRooms/backstreets/small_west/gcorp_swa.dmm
  code/game/objects/effects/spawners/scatter.dm
Labels: Mapping

#2730 Branch 12 Weapon Changes [PART 1]
  ModularTegustation/!extra_abnos/branch12/!equipment/branch12_datum.dm
  ModularTegustation/!extra_abnos/branch12/!equipment/branch12_weapon.dm
  ModularTegustation/!extra_abnos/branch12/he/dearest_friends.dm
  ModularTegustation/Teguicons/branch12/branch12_weapon.dmi
  code/datums/status_effects/debuffs.dm
Labels: Expansion

#2715 Office Fixers Renovation [DONE]
  ModularTegustation/tegu_items/associations/tutorial_tapes.dm
  ModularTegustation/tegu_items/workshop/_templates.dm
  _maps/map_files/Event/fixer_office.dmm
  code/game/objects/effects/spawners/village_spawner.dm
  code/game/objects/items/granters.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/surgery/organs/organ_internal.dm
  lobotomy-corp13.dme
Labels: Mapping

#2755 Fix Snow Queen Sword being Stuck in Belts and Doorstuck
  code/game/machinery/doors/airlock_types.dm
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/hammer_light.dm
Labels: Fix

#2754 City Spawner Hotfix
  ModularTegustation/lc13_spawners.dm
Labels: Tweak, Fix, Isolated Code

#2752 Balance changes to 2 gacha outlets
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/refinery/sales.dm
Labels: Balance

#2745 Balances Quirk Points
  code/datums/quirks/good.dm
  code/datums/quirks/negative.dm
  code/datums/quirks/neutral.dm
Labels: Balance, Isolated Code

#2762 PE Filter Resprites
  ModularTegustation/Teguicons/refiner.dmi
Labels: Sprites

#2763 Quirk Bugfix
  code/datums/quirks/neutral.dm
Labels: Fix, Isolated Code

#2767 Branch 12 Weapon Update: Mental Decay
  ModularTegustation/!extra_abnos/branch12/!equipment/branch12_datum.dm
  ModularTegustation/!extra_abnos/branch12/!equipment/branch12_weapon.dm
  ModularTegustation/!extra_abnos/branch12/aleph/black_hole.dm
  ModularTegustation/!extra_abnos/branch12/aleph/selene.dm
  ModularTegustation/!extra_abnos/branch12/records.dm
  ModularTegustation/!extra_abnos/branch12/waw/babel.dm
  ModularTegustation/!extra_abnos/branch12/waw/pentacles_genie.dm
  ModularTegustation/Teguicons/branch12/branch12_weapon.dmi
  _maps/map_files/Branch12/Branch12.dmm
  code/datums/status_effects/debuffs.dm
  sound/weapons/ego/shattering_window.ogg
Labels: Expansion

#2765 Tuning up Thumb firearms
  ModularTegustation/ego_weapons/melee/non_abnormality/thumb.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/weak_edits/city.dm
Labels: Balance

#2759 Nosferatu captured by Limbus Company Labs
  ModularTegustation/tegu_items/limbus_labs/!abno_overwrites.dm
  ModularTegustation/tegu_items/limbus_labs/spawners.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
Labels: Feature, Side content

#2691 Adds the noon of brown
  ModularTegustation/Teguicons/128x64.dmi
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/Teguicons/64x32.dmi
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/96x64.dmi
  ModularTegustation/Teguicons/96x96.dmi
  ModularTegustation/Teguicons/lc13_coloreffect.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  code/datums/status_effects/debuffs.dm
  code/game/objects/effects/temporary_visuals/effect_indicators.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/brown/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/brown/envy.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/brown/noon.dm
  code/modules/ordeals/brown_ordeals.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  lobotomy-corp13.dme
  sound/effects/ordeals/brown/envy1.ogg
  sound/effects/ordeals/brown/envy2.ogg
  sound/effects/ordeals/brown/envy3.ogg
  sound/effects/ordeals/brown_start.ogg
  sound/effects/tremorburst.ogg
Labels: Expansion

#2769 Add prosthetic electronic tool
  code/modules/jobs/job_types/city/prosthetic.dm
  code/modules/jobs/jobs.dm
  code/modules/surgery/mechanic_steps.dm
  code/modules/surgery/tools.dm
  code/modules/vending/medical.dm
Labels: Feature

#2739 Minor Cargo Update
  ModularTegustation/tegu_items/refinery/refinery.dm
  code/game/machinery/computer/extraction_cargo.dm
Labels: Balance, Isolated Code

#2777 Hana Newscasters, Prosthetician Screwdriver
  _maps/map_files/Event/city.dmm
  _maps/map_files/Event/city_fixer.dmm
Labels: Tweak, Mapping

#2776 Pinocchio is now immune to glass shards
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
Labels: Balance, Isolated Code

#2784 Thumb Grenades replaced with less destructive ones to avoid destroying their businesses.
  _maps/templates/syndicate_office/thumbfinger.dmm
  code/game/objects/items/grenades/r_corp.dm
Labels: Balance

#2786 It is no longer taboo for doctors to have access to their anesthetic lockers
  _maps/map_files/Event/city.dmm
  _maps/map_files/Event/city_fixer.dmm
  _maps/shuttles/emergency_asteroid.dmm
  code/game/objects/structures/crates_lockers/closets/secure/lc13.dm
Labels: Code improvement, Fix

#2785 Containment Engineers have found and closed up the tunnel Blue Shepherd was using to escape into the maintenance shaft.
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
Labels: Fix, Mapping

#2792 Joke abnos are forced on April 1st
  code/controllers/subsystem/ticker.dm
Labels: Tweak

#2790 K-Corp drones have been reprogrammed to avoid flashing K-Corp staff.
  ModularTegustation/tegu_items/representative/outfits.dm
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
  code/modules/clothing/outfits/ert.dm
Labels: Balance

#2788 LCL HQ has removed specimen safety suppression allowing for higher abnormality aggression between each othe
  ModularTegustation/tegu_items/limbus_labs/!abno_overwrites.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
  code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
  code/modules/mob/living/simple_animal/abnormality/waw/nosferatu.dm
Labels: Balance

#2761 Skub
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_armor.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_weapons.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_worn.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/_egodatum.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_armor.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_guns.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_weapons.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/waw/skub.dm
  code/modules/paperwork/records/info/auxillary_modes/joke.dm
  icons/UI_Icons/abnormality_portraits/skub.png
  lobotomy-corp13.dme
Labels: Abnormality

#2794 2 new Holidays to bring festive Cheer!
  code/modules/holiday/holidays.dm
Labels: Feature

#2795 Adds trait for brute white/black and brute pale.
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
Labels: Feature, Isolated Code

#2778 Limbus Company Labs now captures a wider variety of Peccatula
  code/modules/jobs/job_types/labs/command/assetprot.dm
Labels: Expansion

#2797 Adds Idle Bounce to Snow Queens Head [DONE]
  ModularTegustation/Teguicons/64x96.dmi
Labels: Sprites

#2781 A pull request
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_armor.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_lefthand.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_righthand.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_weapons.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/!icons/ego_worn.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/_egodatum.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_armor.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/ego_weapons.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/joke/teth/an_abnormality.dm
  lobotomy-corp13.dme
Labels: Abnormality

#2728 Adds a new abnormality
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/abno_cores/teth.dmi
  ModularTegustation/ego_weapons/melee/he.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_armor.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_lefthand.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_righthand.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_weapons.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_worn.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/_egodatum.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_armor.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_weapons.dm
  code/modules/mob/living/simple_animal/abnormality/teth/sirocco.dm
  code/modules/paperwork/records/info/teth.dm
  icons/UI_Icons/abnormality_portraits/sirocco.png
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#2789 More Ordeals
  ModularTegustation/ego_weapons/ranged/ego_bullets/casings.dm
  ModularTegustation/ego_weapons/ranged/ego_bullets/special.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/salmon.dm
  code/modules/ordeals/salmon_ordeals.dm
  lobotomy-corp13.dme
  sound/effects/ordeals/salmon_end.ogg
  sound/effects/ordeals/salmon_start.ogg
Labels: Feature

#2799 Due to complaints filed by the Chief Medical Officer engineering staff have given them chemistry access and repositioned medical records console for more comfortable use.
  _maps/map_files/Event/laboratory.dmm
  code/modules/jobs/job_types/labs/medical/cmo.dm
Labels: Fix, Mapping

#2798 Sphinx, Jbird, Fairy Gentleman and GWSS added to LCL
  ModularTegustation/tegu_items/limbus_labs/!abno_overwrites.dm
  ModularTegustation/tegu_items/limbus_labs/!other_overwrites.dm
  ModularTegustation/tegu_items/limbus_labs/spawners.dm
  code/game/objects/structures/petrified_statue.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_gentleman.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
Labels: Expansion, Side content

#2801 Slightly alters Red Blooded American's work rates
  code/modules/mob/living/simple_animal/abnormality/teth/redblooded.dm
Labels: Balance

#2802 Improved event ordeals
  ModularTegustation/ego_weapons/ranged/zayin.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/salmon.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/shrimps.dm
  code/modules/ordeals/event_ordeals.dm
  code/modules/ordeals/salmon_ordeals.dm
  lobotomy-corp13.dme
Labels: Code improvement, Writing

#2780 Adds new computer screen sprites
  ModularTegustation/lc13_obj/lc13_computers/abnormality_archive.dm
  ModularTegustation/lc13_obj/lc13_computers/abnormality_auxiliary.dm
  ModularTegustation/lc13_obj/lc13_computers/abnormality_ego.dm
  ModularTegustation/lc13_obj/lc13_computers/abnormality_logs.dm
  ModularTegustation/lc13_obj/lc13_computers/abnormality_queue.dm
  ModularTegustation/lc13_obj/lc13_computers/abnormality_work.dm
  code/game/machinery/computer/extraction_cargo.dm
  code/game/machinery/computer/manager_camera.dm
  icons/obj/computer.dmi
Labels: Sprites

#2771 Peccatulum Update
  ModularTegustation/Teguicons/32x32.dmi
  code/modules/mob/living/simple_animal/hostile/ordeal/brown/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/brown/envy.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/brown/noon.dm
Labels: Tweak

#2783 WCC Update: Fixes the "Wild Hunt" Spawners and updates some waves.
  ModularTegustation/tegu_items/wcorp/enemies.dm
  ModularTegustation/tegu_mobs/lc13_blood_fiend.dm
  _maps/map_files/Event/wcorp.dmm
  code/game/gamemodes/management/event/combat.dm
Labels: Fix, Side content

#2803 Extremely minor bugfixes+adjustments
  code/modules/mob/living/carbon/human/species_types/shrimp.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/noon.dm
Labels: Fix

#2805 Ordeal microadjustments
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/dusk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green/dusk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green/midnight.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green/noon.dm
  lobotomy-corp13.dme
Labels: Code improvement
