Repository vlggms/lobotomy-corp13, pull requests merged in 2025-06, with the labels that each got.

#2938 Ego extraction tool 1 line fix
  ModularTegustation/tegu_items/extraction/egodelivery.dm
Labels: Fix

#2936 Indigo Noon Rework 2025/06
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo/noon.dm
  code/modules/ordeals/indigo_ordeals.dm
  lobotomy-corp13.dme
Labels: Balance

#2940 Discord EGO wielded DPS "rebalancing", minor fixes
  ModularTegustation/ego_weapons/melee/waw.dm
  ModularTegustation/ego_weapons/ranged/ego_bullets/waw.dm
  code/datums/abnormality/_ego_datum/waw.dm
Labels: Fix

#2941 Updates wield subtype to allow forced dual-wielding
  ModularTegustation/ego_weapons/melee/subtype/wielded.dm
Labels: Tweak

#2946 Transfervar fix
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
  code/modules/mob/living/simple_animal/abnormality/teth/beauty_beast.dm
Labels: Code improvement

#2895 Adds Fell Bullet
  ModularTegustation/ego_weapons/ranged/ego_bullets/waw.dm
  ModularTegustation/ego_weapons/ranged/waw.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/he.dm
  icons/effects/effects.dmi
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/ego_weapons.dmi
  icons/obj/projectiles.dmi
  sound/abnormalities/fluchschutze/fell_aim.ogg
  sound/abnormalities/fluchschutze/fell_bullet.ogg
  sound/abnormalities/fluchschutze/fell_bullet2.ogg
  sound/abnormalities/fluchschutze/fell_magic.ogg
  sound/abnormalities/fluchschutze/fell_portal.ogg
  sound/abnormalities/fluchschutze/fell_scatter.ogg
  sound/abnormalities/fluchschutze/fell_scatter2.ogg
Labels: Expansion

#2950 Adds ego assimilation
  code/_globalvars/abnormalities.dm
  code/modules/clothing/suits/ego_gear/realized.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  code/modules/spells/ability_types/realized.dm
  lobotomy-corp13.dme
Labels: Feature

#2951 Simple Mob Fix
  code/modules/mob/living/simple_animal/animal_defense.dm
Labels: Fix

#2887 E.G.O. Improvements, Resprites, and Additions.
  ModularTegustation/ego_weapons/melee/teth.dm
  ModularTegustation/ego_weapons/melee/waw.dm
  ModularTegustation/ego_weapons/melee/zayin.dm
  ModularTegustation/ego_weapons/ranged/ego_bullets/teth.dm
  ModularTegustation/ego_weapons/ranged/teth.dm
  code/datums/abnormality/_ego_datum/aleph.dm
  code/datums/abnormality/_ego_datum/tools.dm
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/tools.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/behavior.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/bracelet.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/skin.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/teth/theresia.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/mirror.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/promise.dm
  icons/mob/clothing/ego_gear/abnormality/aleph.dmi
  icons/mob/clothing/ego_gear/abnormality/tools.dmi
  icons/mob/clothing/ego_gear/abnormality/waw.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/aleph.dmi
  icons/obj/clothing/ego_gear/abnormality/tools.dmi
  icons/obj/clothing/ego_gear/abnormality/waw.dmi
  icons/obj/ego_weapons.dmi
Labels: Code improvement, Sprites, Expansion

#2956 Facility A-bandoned
  _maps/templates/admin_fuckery/alphabandoned.dmm
Labels: Feature

#2959 Adds Wedge Office Spear inhand sprites
  ModularTegustation/Teguicons/lc13_left.dmi
  ModularTegustation/Teguicons/lc13_right.dmi
Labels: Sprites
