Repository vlggms/lobotomy-corp13, pull requests merged in 2025-02, with the labels that each got.

#2697 La Mancha Land map fix
  _maps/RandomRooms/backstreetlayout/ruinned_la_mancha_land.dmm
Labels: Fix

#2686 New events
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/aleph/army_in_black.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/waw/big_wolf.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/waw/red_riding_hood_mercenary.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/zayin/fairy_festival.dm
Labels: Expansion, Isolated Code

#2599 Fixer Office Gamemode (Lowpop Fixers for local play)
  ModularTegustation/tegu_items/associations/items.dm
  _maps/map_files/Event/fixer_office.dmm
  _maps/office.json
  code/__DEFINES/~lobotomy_defines/jobs.dm
  code/controllers/subsystem/maptype.dm
  code/game/objects/items/fixerskills/skills.dm
  code/modules/jobs/job_types/city/fixer/minifixers.dm
  code/modules/jobs/jobs.dm
  lobotomy-corp13.dme
Labels: Feature, Side content

#2689 New ego sprite stuff
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_lefthand.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_righthand.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/!icons/ego_weapons.dmi
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_armor.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_weapons.dm
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/mob/inhands/96x96_lefthand.dmi
  icons/mob/inhands/96x96_righthand.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
Labels: Balance, Sprites

#2688 In the name of Love and Hate healing is now a flat number
  ModularTegustation/ego_weapons/ranged/ego_bullets/waw.dm
Labels: Balance

#2633 Sephirah Alternate Room
  _maps/map_files/generic/Manager.dmm
Labels: Tweak, Mapping, Isolated Code

#2703 Removes noise pollution from ordeals
  code/modules/ordeals/_ordeal.dm
Labels: Fix, Isolated Code

#2704 COL Directors Cryoing can no longer create infinite antagonists
  code/modules/jobs/job_types/trusted_players/association/director.dm
Labels: Fix

#2705 [Branch 12] Full Wave M'aider
  ModularTegustation/!extra_abnos/branch12/records.dm
  ModularTegustation/!extra_abnos/branch12/zayin/wave.dm
  ModularTegustation/Teguicons/branch12/32x32.dmi
  code/__DEFINES/abnormalities.dm
  lobotomy-corp13.dme
Labels: Abnormality

#2706 [Branch 12] The Remnant of the forest
  ModularTegustation/!extra_abnos/branch12/records.dm
  ModularTegustation/!extra_abnos/branch12/teth/rock.dm
  ModularTegustation/Teguicons/branch12/32x32.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#2707 Show goes on
  ModularTegustation/!extra_abnos/branch12/he/show_goes_on.dm
  ModularTegustation/!extra_abnos/branch12/records.dm
  ModularTegustation/Teguicons/branch12/48x64.dmi
  ModularTegustation/lc13_obj/lc13_computers/abnormality_work.dm
  lobotomy-corp13.dme
Labels: Abnormality

#2711 [Branch 12] First Two Tool Abnormalities.
  ModularTegustation/!extra_abnos/branch12/!tools/eye.dm
  ModularTegustation/!extra_abnos/branch12/!tools/midnight.dm
  ModularTegustation/!extra_abnos/branch12/records.dm
  ModularTegustation/!extra_abnos/branch12/teth/rock.dm
  ModularTegustation/Teguicons/branch12/32x32.dmi
  lobotomy-corp13.dme
Labels: Feature

#2712 Queen keres
  ModularTegustation/!extra_abnos/branch12/records.dm
  ModularTegustation/!extra_abnos/branch12/teth/remnant_rock.dm
  ModularTegustation/!extra_abnos/branch12/waw/queen_keres.dm
  ModularTegustation/!extra_abnos/branch12/zayin/full_wave.dm
  ModularTegustation/Teguicons/branch12/48x64.dmi
  code/datums/ai/sanity/_sanityloss_controller.dm
  lobotomy-corp13.dme
Labels: Abnormality

#2714 Branch 12 tools 2
  ModularTegustation/!extra_abnos/branch12/!tools/compass.dm
  ModularTegustation/!extra_abnos/branch12/!tools/mislocation.dm
  ModularTegustation/!extra_abnos/branch12/records.dm
  ModularTegustation/Teguicons/branch12/32x32.dmi
  ModularTegustation/Teguicons/branch12/48x64.dmi
  ModularTegustation/Teguicons/tegu_effects10x10.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#2716 [Branch 12] Old Man Pale
  ModularTegustation/!extra_abnos/branch12/aleph/oldman_pale.dm
  ModularTegustation/!extra_abnos/branch12/waw/joe_shmoe.dm
  ModularTegustation/Teguicons/branch12/32x32.dmi
  ModularTegustation/Teguicons/branch12/joe.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#2717 Branch 12 Map
  _maps/branch12.json
  _maps/map_files/Branch12/Branch12.dmm
Labels: Mapping

#2719 Fixes getting infinite damage with the workshop axes
  ModularTegustation/tegu_items/workshop/templates/axe.dm
Labels: Fix, Isolated Code

#2701 Station Traits
  ModularTegustation/ego_weapons/_ego_weapon.dm
  ModularTegustation/ego_weapons/melee/aleph.dm
  ModularTegustation/ego_weapons/melee/he.dm
  ModularTegustation/ego_weapons/melee/teth.dm
  ModularTegustation/ego_weapons/melee/waw.dm
  ModularTegustation/ego_weapons/ranged/_ranged_projectile.dm
  ModularTegustation/moba_skills/artificer/charge.dm
  ModularTegustation/moba_skills/defensive/hunker_down.dm
  ModularTegustation/moba_skills/defensive/parry.dm
  ModularTegustation/moba_skills/healing/healing.dm
  ModularTegustation/moba_skills/healing/soothing.dm
  ModularTegustation/moba_skills/ranged/autoloader.dm
  ModularTegustation/moba_skills/ranged/grenade.dm
  ModularTegustation/moba_skills/ranged/grenade_launcher.dm
  ModularTegustation/moba_skills/ranged/smokedash.dm
  ModularTegustation/moba_skills/skill_chooser.dm
  ModularTegustation/moba_skills/skirmisher/assault.dm
  ModularTegustation/moba_skills/skirmisher/blitz.dm
  ModularTegustation/moba_skills/skirmisher/dash.dm
  code/__DEFINES/facility_traits.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/abnormality_queue.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/controllers/subsystem/maptype.dm
  code/controllers/subsystem/ticker.dm
  code/datums/wounds/_wounds.dm
  code/game/gamemodes/management/management.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/fixerskills/level1/movement.dm
  code/game/objects/objs.dm
  code/modules/admin/chat_commands.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/suppression.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/ordeals/_ordeal.dm
  icons/effects/effects.dmi
  icons/hud/screen_skills.dmi
  lobotomy-corp13.dme
Labels: Feature

#2727 fix ego icons
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/ego_weapons.dmi
Labels: Fix, Sprites

#2731 Fishing fix
  ModularTegustation/fishing/code/fishcooking/fishmachines/fish_cookers.dm
  ModularTegustation/fishing/code/fishcooking/fishmachines/sushi.dm
  ModularTegustation/fishing/code/turfs.dm
Labels: Expansion

#2666 Combat Pages Revived
  ModularTegustation/tegu_items/!combat_page/combat_page.dm
  ModularTegustation/tegu_items/!combat_page/console.dm
  ModularTegustation/tegu_items/!combat_page/level1.dm
  ModularTegustation/tegu_items/!combat_page/level2.dm
  ModularTegustation/tegu_items/!combat_page/level3.dm
  _maps/map_files/generic/Manager.dmm
  code/game/objects/structures/crates_lockers/closets/secure/lc13.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/lcorp.dm
  code/modules/jobs/job_types/suppression.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/aleph/crying_children.dm
  icons/obj/closet.dmi
  lobotomy-corp13.dme
Labels: Feature

#2694 Some Projectile Dummy Fixes
  code/_onclick/other_mobs.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
Labels: Fix, Isolated Code

#2668 Recodes a good chunk of galaxy child's code to be cleaner and more efficient
  code/modules/mob/living/simple_animal/abnormality/he/galaxy_child.dm
Labels: Code improvement, Fix, Isolated Code

#2732 Croissant and Pain au chocolat
  code/game/objects/items/food/pastries.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  icons/obj/food/food.dmi
Labels: Feature

#2733 Chemistry Additions
  ModularTegustation/tegu_chemistry/reagents.dm
  ModularTegustation/tegu_chemistry/recipes.dm
  code/datums/quirks/negative.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  lobotomy-corp13.dme
Labels: Feature, Fix, Side content

#2735 Pulsar's cooking update 1 (Pies)
  code/game/objects/items/food/pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  icons/obj/food/piecake.dmi
Labels: Tweak

#2736 adjustments to the LCL Qliphoth Suppression Fields [BUGFIX]
  ModularTegustation/tegu_items/limbus_labs/!abno_overwrites.dm
Labels: Fix, Side content
