Repository vlggms/lobotomy-corp13, pull requests merged in 2025-08, with the labels that each got.

#3003 Damage Type Shuffle Pale Adjustment
  ModularTegustation/ego_weapons/_ego_weapon.dm
  ModularTegustation/ego_weapons/ranged/_ranged.dm
  code/datums/abnormality/_ego_datum/_ego_datum.dm
  code/modules/mob/living/damage_procs.dm
Labels: Tweak

#2995 makes chance refinary less op
  ModularTegustation/tegu_items/refinery/alt_refinery/chance.dm
Labels: Balance

#2998 RCA Update: Making windows breakable
  _maps/RandomRooms/rcorp/caves/river.dmm
  _maps/RandomRooms/rcorp/facility/city2.dmm
  _maps/RandomRooms/rcorp/facility/offices.dmm
  _maps/RandomRooms/rcorp/facility/standard.dmm
  _maps/RandomRooms/rcorp/facility/standard2.dmm
Labels: Tweak

#2997 CoL Update: Killing Multitools/Door Hacking
  _maps/map_files/Event/city.dmm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/devices/multitool.dm
Labels: Balance

#2541 Endermage Rcorp Updates: Removal of Friendly Fire from Abnormalities [Done]
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/melting_love.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Balance, Tweak

#2631 Representative Stock Market [Should be OKAY]
  code/modules/stock_market/stonk_company.dm
  code/modules/stock_market/stonk_computer.dm
  code/modules/stock_market/stonk_market.dm
  lobotomy-corp13.dme
Labels: Feature

#2958 XP Mod and MOBA Adjustment
  ModularTegustation/moba_skills/healing/healing.dm
  ModularTegustation/moba_skills/healing/soothing.dm
  ModularTegustation/moba_skills/skill_chooser.dm
  code/__DEFINES/facility_traits.dm
  code/controllers/subsystem/maptype.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Balance, Feature

#3004 Expedition Machinery
  ModularTegustation/Teguicons/expedition_32x32.dmi
  ModularTegustation/Teguicons/lc13_structures_32x48.dmi
  ModularTegustation/expedition/items.dm
  ModularTegustation/expedition/machinery.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  lobotomy-corp13.dme
Labels: Expansion

#2991 Expands Central Command in District4
  ModularTegustation/tegu_items/enkephalin_rush/enkr_mobs.dm
  _maps/map_files/Enkephalin_Rush/district_4.dmm
Labels: Mapping

#3009 King of Greed is Greedier (especially on D-069)
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
Labels: Balance

#2990 RCE Features: Mobs
  ModularTegustation/Teguicons/resurgence_32x48.dmi
  ModularTegustation/Teguicons/resurgence_actions.dmi
  ModularTegustation/Teguicons/resurgence_greed_32x48.dmi
  ModularTegustation/Teguicons/resurgence_greed_48x48.dmi
  ModularTegustation/tegu_mobs/lc13_resurgence_clan_greed_touched.dm
  ModularTegustation/tegu_mobs/lc13_resurgence_clan_mobs.dm
  ModularTegustation/tegu_mobs/lc13_resurgence_clan_rce.dm
  ModularTegustation/tegu_mobs/lc13_resurgence_clan_rce_ranged.dm
  ModularTegustation/tegu_mobs/lc13_resurgence_clan_tinkerer.dm
  ModularTegustation/tegu_mobs/rce_mobs.md
  icons/effects/96x96.dmi
  icons/effects/cult_effects.dmi
  icons/mob/drone.dmi
  lobotomy-corp13.dme
Labels: Feature, Expansion

#2968 Experimental PR: Bindable Actions
  code/__DEFINES/dcs/signals.dm
  code/_onclick/hud/action_button.dm
  code/datums/action.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/tgui/tgui_keybind_modal.dm
  lobotomy-corp13.dme
  tgui/packages/tgui/interfaces/KeyComboModal.js
Labels: Feature

#3015 Love and Justice Realization Buff
  code/modules/spells/ability_types/realized_aimed.dm
Labels: Balance

#3019 RCE Fix: Re-added teleport away to Clan Mobs
  ModularTegustation/tegu_mobs/lc13_resurgence_clan_mobs.dm
Labels: Tweak, Fix

#3020 Replaces blurb font
  code/__HELPERS/unsorted.dm
  code/modules/suppressions/extraction.dm
  code/modules/suppressions/keter.dm
  icons/fonts/bettervcr.ttf
  icons/fonts/font.dm
  lobotomy-corp13.dme
Labels: Tweak, Fix

#3010 Slight adjustments to the game's pace
  ModularTegustation/lc13_obj/lc13_computers/abnormality_work.dm
  code/__HELPERS/lobotomy_corp.dm
  code/controllers/subsystem/abnormality_queue.dm
  code/controllers/subsystem/lobotomy_corp.dm
Labels: Balance, Test Merge Candidate

#3022 Ego Surgery Fix
  ModularTegustation/tegu_items/extraction/egosurgery.dm
Labels: Fix

#3023 TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/LICENSE
  code/modules/tgs/core/README.md
  code/modules/tgs/core/_definitions.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/includes.dm
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v3210/commands.dm
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v4/commands.dm
  code/modules/tgs/v5/README.md
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/bridge.dm
  code/modules/tgs/v5/chunking.dm
  code/modules/tgs/v5/commands.dm
  code/modules/tgs/v5/serializers.dm
  code/modules/tgs/v5/topic.dm
  code/modules/tgs/v5/undefs.dm
Labels: Code improvement

#3024 Another TGS DMAPI update
  code/__DEFINES/tgs.dm
Labels: Fix

#2682 Fixes golden apple trying to check a non-existant status effect's stacks
  code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
Labels: Fix, Isolated Code

#3013 Oracle Sprite Replacement (DONE)
  ModularTegustation/Teguicons/tegumobs.dmi
Labels: Sprites, Isolated Code

#3026 disables station traits and the message
  ModularTegustation/!extra_abnos/joke_abnormalities/!equipment/weapons.dm
  ModularTegustation/ego_weapons/_ego_weapon.dm
  ModularTegustation/ego_weapons/melee/aleph.dm
  ModularTegustation/ego_weapons/melee/he.dm
  ModularTegustation/ego_weapons/melee/teth.dm
  ModularTegustation/ego_weapons/melee/waw.dm
  ModularTegustation/ego_weapons/ranged/_ranged.dm
  ModularTegustation/ego_weapons/ranged/_ranged_projectile.dm
  ModularTegustation/misc_procs.dm
  ModularTegustation/tegu_items/representative/research/lcorp.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/abnormality_queue.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/controllers/subsystem/maptype.dm
  code/controllers/subsystem/ticker.dm
  code/datums/wounds/_wounds.dm
  code/game/objects/objs.dm
  code/modules/admin/chat_commands.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/command.dm
  code/modules/jobs/job_types/suppression.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
  code/modules/ordeals/_ordeal.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  lobotomy-corp13.dme
Labels: Balance, Removal

#3029 LC Armor Values
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
Labels: Tweak

#3027 Disables unfinished/badly implemented ordeals
  code/modules/ordeals/indigo_ordeals.dm
  lobotomy-corp13.dme
Labels: Removal

#2128 Adds Pink Shoes
  ModularTegustation/Teguicons/128x128.dmi
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/Teguicons/32x96.dmi
  ModularTegustation/Teguicons/status_sprites.dmi
  ModularTegustation/Teguicons/tegu_effects.dmi
  ModularTegustation/Teguicons/tegu_effects10x10.dmi
  code/modules/mob/living/simple_animal/abnormality/he/pink_shoes.dm
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
  code/modules/paperwork/records/info/he.dm
  icons/UI_Icons/abnormality_portraits/pink_shoes.png
  icons/effects/effects.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#3036 Damage Effects
  ModularTegustation/Teguicons/lc13_coloreffect.dmi
  code/game/objects/effects/temporary_visuals/effect_indicators.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_weapons.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Tweak

#3039 Replaces game icon
  icons/tg_32.png
Labels: Tweak

#3041 Reduced telecomms volume
  code/datums/looping_sounds/machinery_sounds.dm
Labels: Tweak

#3044 Ordeal Folder reorganization
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber/dusk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber/midnight.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson/dusk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson/midnight.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/crimson/noon.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/event/april_fools/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/event/april_fools/dusk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/event/april_fools/midnight.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/event/april_fools/noon.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/event/christmas/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green/dusk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green/midnight.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green/noon.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo/dusk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/indigo/midnight.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/pink/midnight.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/shrimps.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel/dusk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel/noon.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet/midnight.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/violet/noon.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white/the_claw.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/white/white.dm
  lobotomy-corp13.dme
Labels: Code improvement

#3016 Minor City Update: Migo buff/Ruined Town nerf
  _maps/Quests/ruined_town.dmm
  code/modules/mob/living/simple_animal/hostile/netherworld.dm
Labels: Balance

#3054 Ego Armor Slowdown Removal but take twice as long to equip
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
Labels: Balance, Removal

#3052 Enkephalin Rush + Community E.G.O HP rebalance
  ModularTegustation/tegu_items/enkephalin_rush/enkr_mobs.dm
  ModularTegustation/tegu_items/enkephalin_rush/ore_turfs.dm
  ModularTegustation/tegu_mobs/lc13_corrosions.dm
  _maps/map_files/Enkephalin_Rush/district_4.dmm
  code/modules/mining/equipment/mining_tools.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_weapons.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/blubbering_toad.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/oceanwaves.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/oracle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/pile_of_mail.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/we_can_change_anything.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/midnight.dm
  code/modules/reagents/chemistry/reagents/lc13_reagents.dm
Labels: Balance, Mapping, Side content

#3061 Adjustable EGO Refactor
  ModularTegustation/tegu_items/refinery/crates/syndicate.dm
  _maps/templates/syndicate_office/indexfinger.dmm
  code/datums/components/adjustable_clothes.dm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_index.dm
  code/modules/antagonists/head/claw.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/index.dm
  code/modules/clothing/suits/ego_gear/ordeal.dm
  lobotomy-corp13.dme
Labels: Refactor

#3053 Delusionist's end and Painful purpose Changes
  code/modules/clothing/suits/ego_gear/ordeal.dm
  icons/mob/clothing/ego_gear/head.dmi
  icons/mob/clothing/ego_gear/neck.dmi
  icons/mob/clothing/ego_gear/ordeal.dmi
  icons/obj/clothing/ego_gear/ordeal.dmi
  lobotomy-corp13.dme
Labels: Balance, Removal
