Repository vlggms/lobotomy-corp13, pull requests merged in 2025-05, with the labels that each got.

#2886 Damage Type Shuffle Uniform RNG + abno resistances in abno docs
  ModularTegustation/lc13_damage_type_shuffler.dm
  code/modules/paperwork/records/info/_info.dm
Labels: Tweak

#2835 Better gold dusk and noon
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/64x64.dmi
  code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/dusk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/noon.dm
  code/modules/ordeals/gold_ordeals.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/effects/64x64.dmi
  sound/effects/ordeals/gold/weather_thunder_0.ogg
  sound/effects/ordeals/gold/weather_thunder_1.ogg
  sound/effects/ordeals/gold/weather_thunder_2.ogg
  sound/effects/ordeals/gold/weather_thunder_3.ogg
Labels: Expansion

#2896 after a months long lawsuit P-Corp now promises to sell REAL P-Corp Storage Gloves
  ModularTegustation/tegu_items/representative/items/pcorp.dm
Labels: Fix

#2897 Hurting Teddy Bear PR #3 - Jack fucked up
  ModularTegustation/Teguicons/64x64.dmi
  ModularTegustation/Teguicons/abno_cores/teth.dmi
  code/modules/mob/living/simple_animal/abnormality/he/happy_teddy_bear.dm
  code/modules/mob/living/simple_animal/abnormality/teth/hurting_teddy.dm
  code/modules/paperwork/records/info/teth.dm
  icons/UI_Icons/abnormality_portraits/hurting_teddy.png
  lobotomy-corp13.dme
Labels: Abnormality

#2900 Fix Warm Hearted Woodsman Attacking Corpses
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  lobotomy-corp13.dme
Labels: Fix

#2898 Adds chems to some original abnormalities
  code/modules/mob/living/simple_animal/abnormality/aleph/last_shot.dm
  code/modules/mob/living/simple_animal/abnormality/teth/redblooded.dm
  code/modules/mob/living/simple_animal/abnormality/teth/sirocco.dm
  code/modules/mob/living/simple_animal/abnormality/waw/apex_predator.dm
Labels: Feature

#2908 Provides a user agent when downloading Byond
  tools/ci/install_byond.sh
Labels: Code improvement, Github, Red Label, Fix

#2907 Ghosts are now capable of spotting midround job openings (CoL)
  code/controllers/subsystem/city_events.dm
Labels: Tweak

#2909 Fixes faelantern
  code/modules/mob/living/simple_animal/abnormality/teth/faelantern.dm
Labels: Fix

#2906 Carnival Fix
  ModularTegustation/ego_weapons/melee/non_abnormality/carnival.dm
Labels: Balance

#2911 Out of the good in the heart of the corporations and zero self-interest they will now give out care packages.
  ModularTegustation/tegu_items/representative/console.dm
  ModularTegustation/tegu_items/representative/items/kcorp.dm
Labels: Expansion

#2916 Mini Col Update: Backstreets Templates Fixes
  _maps/RandomRooms/backstreetlayout/lcorp.dmm
  _maps/RandomRooms/backstreetlayout/lcorp_backstreets.dmm
  _maps/RandomRooms/backstreets/bossroom/slime_office.dmm
  _maps/RandomRooms/backstreets/small_north/snow_forest.dmm
Labels: Fix

#2912 Adventure Console Update V2.2 [DONE]
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/_event.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/zayin/we_can_change_anything.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/sinking_bell.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_layout.dm
Labels: Expansion

#2918 Damage Type Shuffle Adjustments
  ModularTegustation/lc13_damage_type_shuffler.dm
  code/controllers/subsystem/maptype.dm
Labels: Balance

#2921 Removes one line that made blockheal not work
  ModularTegustation/lc13_obj/_adventure_console/adventure_layout.dm
Labels: Fix

#2922 Updates TO with some QoL Features
  code/modules/jobs/job_types/mentor/trainingofficer.dm
Labels: Fix, Isolated Code

#2914 Makes Felinids take sanity damage from getting wet.
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Feature, Isolated Code

#2875 Cargo Console fix
  code/game/machinery/computer/extraction_cargo.dm
Labels: Fix

#2899 L-Corp City Update: Mapping Errors
  _maps/RandomRooms/backstreetlayout/lcorp.dmm
  _maps/map_files/LcorpCity/mixcommand.dmm
Labels: Fix, Mapping

#2927 SpitePR | Cleanbot Shush
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
Labels: Tweak

#2924 Fixes blind obsession runtimes and "sticky" slowdown
  ModularTegustation/ego_weapons/melee/waw.dm
Labels: Fix, Isolated Code

#2910 Adds Drenched Gossypium EGO, Gift and Core - Unfucked Linters edition
  ModularTegustation/Teguicons/abno_cores/teth.dmi
  ModularTegustation/ego_weapons/melee/teth.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/mob/living/carbon/human/ego_gifts.dm
  icons/mob/clothing/ego_gear/abnormality/teth.dmi
  icons/mob/clothing/ego_gear/ego_gifts.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/clothing/ego_gear/abnormality/teth.dmi
  icons/obj/ego_weapons.dmi
Labels: Abnormality

#2891 CoL Update: Removing Simple Stuns
  code/game/objects/structures/beds_chairs/chair.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance

#2894 City Update: Ruined Town Adjustments
  _maps/Quests/ruined_town.dmm
  code/modules/mob/living/simple_animal/friendly/eric_t.dm
  code/modules/mob/living/simple_animal/friendly/nuke_leader.dm
Labels: Balance, Mapping

#2808 City of Light association skills
  ModularTegustation/tegu_items/associations/association_beacon.dm
  ModularTegustation/tegu_items/associations/skills/liu/associate.dm
  ModularTegustation/tegu_items/associations/skills/liu/director.dm
  ModularTegustation/tegu_items/associations/skills/liu/skillgranter .dm
  ModularTegustation/tegu_items/associations/skills/liu/veteran.dm
  ModularTegustation/tegu_items/associations/skills/seven/associate.dm
  ModularTegustation/tegu_items/associations/skills/seven/director.dm
  ModularTegustation/tegu_items/associations/skills/seven/skillgranter.dm
  ModularTegustation/tegu_items/associations/skills/seven/veteran.dm
  ModularTegustation/tegu_items/associations/skills/skillgranter.dm
  ModularTegustation/tegu_items/associations/skills/zwei/associate.dm
  ModularTegustation/tegu_items/associations/skills/zwei/director.dm
  ModularTegustation/tegu_items/associations/skills/zwei/skillgranter.dm
  ModularTegustation/tegu_items/associations/skills/zwei/veteran.dm
  code/modules/mob/living/simple_animal/dc_changes.dm
  lobotomy-corp13.dme
Labels: Balance, Side content

#2782 City Update: Justice Nerf/BL Buff
  ModularTegustation/ego_weapons/melee/non_abnormality/syndicate.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/weak_edits/city.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance

#2811 Add: Proof-of-Concept Adminbus Custom Mines
  code/game/objects/effects/adminbus/adminbus.dm
  code/game/objects/effects/adminbus/custom_mines.dm
  code/game/objects/effects/adminbus/gravity.dm
  code/game/objects/effects/adminbus/meme_effects.dm
  code/game/objects/effects/adminbus/triggers.dm
  lobotomy-corp13.dme
Labels: Feature

#2933 Fixes Drifting Fox works
  code/modules/mob/living/simple_animal/abnormality/he/drifting_fox.dm
Labels: Fix

#2932 adds abno sutures
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/storage/firstaid.dm
Labels: Feature, Side content
