Repository vlggms/lobotomy-corp13, pull requests merged in 2025-01, with the labels that each got.

#2661 Made Tough weapon Teth
  ModularTegustation/ego_weapons/ranged/ego_bullets/teth.dm
  ModularTegustation/ego_weapons/ranged/ego_bullets/zayin.dm
  ModularTegustation/ego_weapons/ranged/teth.dm
  ModularTegustation/ego_weapons/ranged/zayin.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/datums/abnormality/_ego_datum/zayin.dm
Labels: Balance

#2660 Make the porta copier and portable prediction device smaller
  ModularTegustation/tegu_items/gadgets/unpowered.dm
Labels: Balance

#2659 Cleanbots no longer disarm employees of their EGO
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
Labels: Code improvement

#2664 Adventure Console Combat Dice Update [DONE]
  ModularTegustation/lc13_obj/_adventure_console/adventure_layout.dm
  ModularTegustation/lc13_obj/_adventure_console/console.dm
Labels: Expansion

#2656 Fix: CentCom Search Runtime
  code/modules/admin/topic.dm
Labels: Fix

#2665 Adds 4 new adventure console events
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/waw/general_bee.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/zayin/oceanic.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/zayin/we_can_change_anything.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/vending machine.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/limbus_company/ambling_pearl.dm
  lobotomy-corp13.dme
Labels: Expansion

#2579 Craftable christmas hats, I love being jolly!
  code/datums/components/crafting/recipes/clothing.dm
Labels: Expansion, Isolated Code

#2672 Barefoot no longer heals
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Balance

#2673 Fixes bone hooks giving endless fishing points
  ModularTegustation/fishing/code/fish_market.dm
Labels: Fix

#2674 Fixes the "Violet/Crimson Silk to Azure Silk" conversion making amber silk instead
  code/datums/components/crafting/recipes/carnival_silk/silk_tailoring/carnival_transfer.dm
Labels: Fix

#2667 Fixes round-end not auto-triggering when a player dies on combat maps because of pinocchio + R-corp round-end improvements
  ModularTegustation/tegu_items/rcorp/objective.dm
  code/game/gamemodes/management/event/combat.dm
Labels: Fix

#2675 Removing Debug Text from Metal Fixer
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
Labels: Fix

#2676 Mirror Dungeon Events Added
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/he/singing_machine.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/teth/ppodae.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/teth/void_dream.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/zayin/fairy_festival.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/Man_Sand.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/fun_contract.dm
  lobotomy-corp13.dme
Labels: Expansion

#2679 LC13 Bleed Statues effect
  ModularTegustation/Teguicons/status_sprites.dmi
  code/datums/status_effects/debuffs.dm
Labels: Feature

#2622 Damage effects and big mob improvement.
  ModularTegustation/tegu_mobs/apocalypse_bird.dm
  code/__HELPERS/game.dm
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/_onclick/other_mobs.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/mob/living/simple_animal/projectile_blocker.dm
Labels: Tweak

#2572 Kikimora Ego [DONE]
  ModularTegustation/ego_weapons/melee/teth.dm
  code/datums/abnormality/_ego_datum/teth.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
Labels: Abnormality

#2588 Fix: Move default to config/example, ignore config
  .gitignore
  config/example/admin_nicknames.json
  config/example/admin_ranks.txt
  config/example/admins.txt
  config/example/antag_rep.txt
  config/example/arenas/README.md
  config/example/awaymissionconfig.txt
  config/example/badges.json
  config/example/comms.txt
  config/example/config.txt
  config/example/dbconfig.txt
  config/example/dynamic.json
  config/example/game_options.txt
  config/example/iceruinblacklist.txt
  config/example/in_character_filter.txt
  config/example/interviews.txt
  config/example/jobs.txt
  config/example/jukebox_music/LICENSE.txt
  config/example/jukebox_music/README.txt
  config/example/jukebox_music/sounds/exclude
  config/example/lavaruinblacklist.txt
  config/example/maps.txt
  config/example/motd.txt
  config/example/policy.json
  config/example/resources.txt
  config/example/silicon_laws.txt
  config/example/spaceruinblacklist.txt
  config/example/title_music/LICENSE.txt
  config/example/title_music/README.txt
  config/example/title_music/sounds/exclude
  config/example/title_screens/LICENSE.txt
  config/example/title_screens/README.txt
  config/example/title_screens/images/exclude
  config/example/trusted_players.txt
  config/example/unbuyableshuttles.txt
  config/example/whitelist.txt
Labels: Tweak

#2336 Makes Some Abnormalities Not Bleed[DONE]
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/he/ardor_blossom_moth.dm
  code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
  code/modules/mob/living/simple_animal/abnormality/he/steam_transport_machine.dm
  code/modules/mob/living/simple_animal/abnormality/teth/MHz.dm
  code/modules/mob/living/simple_animal/abnormality/teth/book.dm
  code/modules/mob/living/simple_animal/abnormality/teth/faelantern.dm
  code/modules/mob/living/simple_animal/abnormality/waw/dimension_refraction.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/screenwriter.dm
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/quiet_day.dm
Labels: Tweak

#2653 Adds hana paperwork forms into the photocopier for City Fishers
  _maps/map_files/Event/city.dmm
  _maps/map_files/Event/city_fixer.dmm
  code/modules/paperwork/photocopier.dm
  config/blanks.json
  config/blanks_city.json
  tgui/packages/tgui/interfaces/Photocopier.js
Labels: Feature, Side content, Isolated Code

#2663 Makes sphinx less terrible
  code/modules/mob/living/simple_animal/abnormality/waw/sphinx.dm
  code/modules/paperwork/records/info/waw.dm
  icons/effects/effects.dmi
Labels: Balance, Tweak

#2678 Better brown dawn
  code/modules/mob/living/simple_animal/hostile/ordeal/brown/dawn.dm
Labels: Balance, Tweak

#2550 Endermage Rcorp Updates: Auto Shutters [DONE]
  ModularTegustation/tegu_items/rcorp/button.dm
  ModularTegustation/tegu_items/rcorp/landmarks.dm
  _maps/RandomRooms/rcorp/facility/beaches.dmm
  _maps/RandomRooms/rcorp/facility/beaches2.dmm
  _maps/RandomRooms/rcorp/facility/city.dmm
  _maps/RandomRooms/rcorp/facility/city2.dmm
  _maps/RandomRooms/rcorp/facility/maze.dmm
  _maps/RandomRooms/rcorp/facility/maze2.dmm
  _maps/RandomRooms/rcorp/facility/nest.dmm
  _maps/RandomRooms/rcorp/facility/offices.dmm
  _maps/RandomRooms/rcorp/facility/raidboss.dmm
  _maps/RandomRooms/rcorp/facility/skeld.dmm
  _maps/RandomRooms/rcorp/facility/standard.dmm
  _maps/RandomRooms/rcorp/facility/standard2.dmm
  _maps/RandomRooms/rcorp/facility/xenos.dmm
  _maps/map_files/Event/rcorp.dmm
  code/game/gamemodes/management/event/combat.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  lobotomy-corp13.dme
Labels: Balance, Tweak, Mapping, Freeze

#2683 Mirror Dungeon Event Bugfixes
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/teth/ppodae.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/zayin/fairy_festival.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/Man_Sand.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/fun_contract.dm
Labels: Fix

#2547 Endermage Rcorp Updates: Buffing/Reworking R-Corp Abnormalities [DONE]
  ModularTegustation/Teguicons/48x48.dmi
  ModularTegustation/tegu_items/rcorp/!abno_overwrites.dm
  _maps/RandomRooms/rcorp/facility/nest.dmm
  code/game/objects/items/grenades/grenade.dm
  code/game/objects/items/grenades/r_corp.dm
  code/modules/mob/living/simple_animal/abnormality/he/eris.dm
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/mob/living/simple_animal/abnormality/he/scarecrow.dm
  code/modules/mob/living/simple_animal/abnormality/teth/ppodae.dm
  code/modules/mob/living/simple_animal/abnormality/teth/redblooded.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clouded_monk.dm
  code/modules/mob/living/simple_animal/abnormality/waw/greed_king.dm
  code/modules/mob/living/simple_animal/abnormality/waw/warden.dm
  code/modules/projectiles/projectile/beams.dm
  icons/mob/actions/actions_abnormality.dmi
  icons/mob/actions/actions_rcorp.dmi
Labels: Balance

#2542 Endermage Rcorp Updates: Shrimp VIP Buff [DONE]
  ModularTegustation/tegu_items/rcorp/objective.dm
  icons/mob/actions/actions_shrimp.dmi
Labels: Balance

#2685 Update fairy_festival.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/zayin/fairy_festival.dm
Labels: Fix

#2681 Adds more ordeal meat
  ModularTegustation/tegu_items/associations/machines.dm
  code/game/objects/items/food/meat.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/brown/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/dawn.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/dusk.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/midnight.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/gold/noon.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/steel.dm
  icons/obj/food/food.dmi
Labels: Fix, Sprites, Isolated Code

#2687 Makes Lances Hit Multi-Tile Mobs
  ModularTegustation/ego_weapons/melee/subtype/lance.dm
Labels: Fix

#2690 Visuals for Statues Effects
  ModularTegustation/Teguicons/lc13_coloreffect.dmi
  code/datums/status_effects/debuffs.dm
  code/game/objects/effects/temporary_visuals/effect_indicators.dm
Labels: Sprites

#2615 Adds the mining breach type
  ModularTegustation/Teguicons/96x48.dmi
  ModularTegustation/Teguicons/tegumobs.dmi
  ModularTegustation/tegu_items/debug_items.dm
  code/__DEFINES/abnormalities.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/army_in_black.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/blue_star.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/distortedform.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/last_shot.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/silent_orchestra.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/space_lady.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/white_night.dm
  code/modules/mob/living/simple_animal/abnormality/he/doomsday_calendar.dm
  code/modules/mob/living/simple_animal/abnormality/he/highway_devotee.dm
  code/modules/mob/living/simple_animal/abnormality/he/jangsan.dm
  code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
  code/modules/mob/living/simple_animal/abnormality/he/porccubus.dm
  code/modules/mob/living/simple_animal/abnormality/he/red_shoes.dm
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
  code/modules/mob/living/simple_animal/abnormality/teth/blood_bath.dm
  code/modules/mob/living/simple_animal/abnormality/teth/book.dm
  code/modules/mob/living/simple_animal/abnormality/teth/faelantern.dm
  code/modules/mob/living/simple_animal/abnormality/teth/falada.dm
  code/modules/mob/living/simple_animal/abnormality/teth/meat_lantern.dm
  code/modules/mob/living/simple_animal/abnormality/waw/alriune.dm
  code/modules/mob/living/simple_animal/abnormality/waw/black_swan.dm
  code/modules/mob/living/simple_animal/abnormality/waw/contract.dm
  code/modules/mob/living/simple_animal/abnormality/waw/ebony_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/luna.dm
  code/modules/mob/living/simple_animal/abnormality/waw/my_form_empties.dm
  code/modules/mob/living/simple_animal/abnormality/waw/pygmalion.dm
  code/modules/mob/living/simple_animal/abnormality/waw/rose_sign.dm
  code/modules/mob/living/simple_animal/abnormality/waw/screenwriter.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  code/modules/mob/living/simple_animal/abnormality/waw/snow_whites_apple.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/blubbering_toad.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/bottle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/one_sin.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/oracle.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/quiet_day.dm
  code/modules/mob/living/simple_animal/distortion/monolith.dm
  sound/abnormalities/fairyfestival/fairyqueen_eat.ogg
  sound/abnormalities/fairyfestival/fairyqueen_growl.ogg
  sound/abnormalities/fairyfestival/fairyqueen_hit.ogg
  sound/abnormalities/onesin/onesin_attack.ogg
Labels: Feature

#2692 Removes sukuna from the test range's computer
  code/game/objects/structures/test_range.dm
Labels: Removal

#2693 BPU Fix
  ModularTegustation/lc13_machinery.dm
Labels: Fix

#2635 Delivery Quest Door BASIC CODE [DONE but UNIMPLIMENTED]
  ModularTegustation/delivery_doors.dm
  lobotomy-corp13.dme
Labels: Feature

#2650 Resurgence Clan Update: Villages [DONE]
  ModularTegustation/Teguicons/resurgence_32x48.dmi
  ModularTegustation/Teguicons/resurgence_48x48.dmi
  ModularTegustation/Teguicons/room_spawners/29x22.dmi
  ModularTegustation/fishing/code/fishing_items/fishing_net.dm
  ModularTegustation/fishing/code/rod_components/fishing_lines.dm
  ModularTegustation/fishing/icons/fishing.dmi
  ModularTegustation/fishing/icons/fishing_lines.dmi
  ModularTegustation/tegu_items/associations/!overwrites.dm
  ModularTegustation/tegu_items/associations/cityspawners.dm
  ModularTegustation/tegu_items/associations/machines.dm
  ModularTegustation/tegu_items/associations/vending.dm
  ModularTegustation/tegu_items/backstreets/templates.dm
  ModularTegustation/tegu_items/prosthetics/resurgence_core.dm
  ModularTegustation/tegu_items/refinery/crates/_crate.dm
  ModularTegustation/tegu_mobs/lc13_corrosions.dm
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
  ModularTegustation/tegu_mobs/lc13_resurgence_clan_mobs.dm
  ModularTegustation/tegu_mobs/lc13_resurgence_clan_npcs.dm
  ModularTegustation/tegu_mobs/lc13_resurgence_tapes.dm
  _maps/RandomRooms/backstreetlayout/dungeon_backstreets.dmm
  _maps/RandomRooms/backstreetlayout/lcorp.dmm
  _maps/RandomRooms/backstreetlayout/lcorp_backstreets.dmm
  _maps/RandomRooms/backstreetlayout/outskirts.dmm
  _maps/RandomRooms/backstreetlayout/ruinned_la_mancha_land.dmm
  _maps/RandomRooms/backstreetlayout/standard.dmm
  _maps/RandomRooms/backstreetlayout/tunnels_backstreets.dmm
  _maps/RandomRooms/backstreets/bossroom/clan_stronghold.dmm
  _maps/RandomRooms/backstreets/bossroom/flame_fixer.dmm
  _maps/RandomRooms/backstreets/bossroom/gcorp.dmm
  _maps/RandomRooms/backstreets/bossroom/jacques.dmm
  _maps/RandomRooms/backstreets/bossroom/metal_fixer.dmm
  _maps/RandomRooms/backstreets/bossroom/robot.dmm
  _maps/RandomRooms/backstreets/bossroom/slime_office.dmm
  _maps/RandomRooms/backstreets/pointofinterest/lcorp.dmm
  _maps/RandomRooms/backstreets/pointofinterest/love_train.dmm
  _maps/RandomRooms/backstreets/pointofinterest/n_corp.dmm
  _maps/RandomRooms/backstreets/pointofinterest/robot_city.dmm
  _maps/RandomRooms/backstreets/pointofinterest/scorp_vault.dmm
  _maps/RandomRooms/backstreets/resurgence_village.dmm
  code/__DEFINES/dcs/signals.dm
  code/datums/components/return_to_origin.dm
  code/game/area/areas/lobotomy_corp.dm
  code/game/gamemodes/management/event/combat.dm
  code/game/objects/effects/spawners/roomspawners.dm
  code/game/objects/effects/spawners/village_spawner.dm
  code/game/objects/items/devices/gps.dm
  code/game/objects/items/fixerskills/skills.dm
  code/modules/mob/living/simple_animal/abnormality/waw/shrimp.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/shrimps.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/paperwork/paper_premade.dm
  code/modules/projectiles/projectile/bullets/smg.dm
  icons/obj/library.dmi
  icons/obj/surgery.dmi
  lobotomy-corp13.dme
  sound/ambience/resurgence_village1.ogg
Labels: Feature, Side content

#2677 adds contempt, awe
  ModularTegustation/ego_weapons/melee/waw.dm
  code/game/objects/effects/misc.dm
  icons/effects/effects.dmi
  icons/mob/inhands/weapons/ego_lefthand.dmi
  icons/mob/inhands/weapons/ego_righthand.dmi
  icons/obj/ego_weapons.dmi
  sound/abnormalities/spiral_contempt/spiral_bleed.ogg
  sound/abnormalities/spiral_contempt/spiral_grow.ogg
  sound/abnormalities/spiral_contempt/spiral_hit.ogg
  sound/abnormalities/spiral_contempt/spiral_mark.ogg
  sound/abnormalities/spiral_contempt/spiral_whine.ogg
Labels: Tweak

#2658 City Gamemodes Update: Bloodfiends [DONE]
  ModularTegustation/Teguicons/blood_fiend_gear.dmi
  ModularTegustation/Teguicons/blood_fiend_gear_worn.dmi
  ModularTegustation/Teguicons/blood_fiends_32x32.dmi
  ModularTegustation/tegu_items/associations/machines.dm
  ModularTegustation/tegu_items/associations/vending.dm
  ModularTegustation/tegu_mobs/lc13_blood_fiend.dm
  ModularTegustation/tegu_mobs/lc13_corrosions.dm
  _maps/RandomRooms/backstreetlayout/ruinned_la_mancha_land.dmm
  code/datums/components/crafting/recipes/carnival_silk/armor_weaving/carnival_bloodfiend.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/granters.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/bloodfiend.dm
  code/modules/movespeed/modifiers/mobs.dm
  icons/effects/eldritch.dmi
  icons/obj/library.dmi
  lobotomy-corp13.dme
Labels: Feature
