Repository vlggms/lobotomy-corp13, pull requests merged in 2025-04, with the labels that each got.

#2800 EGO Description Update
  ModularTegustation/ego_weapons/_ego_weapon.dm
  ModularTegustation/ego_weapons/ranged/_ranged.dm
  ModularTegustation/ego_weapons/ranged/he.dm
  ModularTegustation/ego_weapons/ranged/special.dm
  ModularTegustation/ego_weapons/ranged/teth.dm
  ModularTegustation/ego_weapons/ranged/waw.dm
  code/modules/clothing/suits/ego_gear/_ego_gear.dm
Labels: Code improvement, Tweak

#2770 Distorted Bamboo Hatted Kim
  ModularTegustation/Teguicons/DistortedKim.dmi
  code/modules/mob/living/simple_animal/distortion/nightmare/DistortedKim.dm
  lobotomy-corp13.dme
  sound/distortions/KimBasicSlash.ogg
  sound/distortions/KimPrep.ogg
  sound/distortions/kim_bone_claim.ogg
Labels: Feature, Side content

#2807 Makes Runaway Crows Able to be Shot
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
Labels: Balance

#2812 Adventure Console Combat Update
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/zayin/oceanic.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/fun_contract.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_layout.dm
  code/game/objects/items/grenades/r_corp.dm
Labels: Expansion

#2753 New Adventure Console Events for Teth Abnormalities
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/aleph/army_in_black.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/he/singing_machine.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/teth/MHz.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/teth/beauty_beast.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/teth/cherry_blossoms.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/teth/meat_lantern.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/waw/big_wolf.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/waw/red_riding_hood_mercenary.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/zayin/fairy_festival.dm
  code/modules/mob/living/simple_animal/distortion/nightmare/DistortedKim.dm
  lobotomy-corp13.dme
Labels: Expansion, Isolated Code

#2814 uncaps your TypePath
  ModularTegustation/Teguicons/distorted_kim.dmi
  ModularTegustation/tegu_mobs/lc13_outskirtdwellers.dm
  _maps/RandomRooms/backstreets/medium_south/eyes_temple.dmm
  _maps/RandomRooms/backstreets/medium_west/lcorp_office.dmm
  code/controllers/subsystem/city_events.dm
  code/modules/mob/living/simple_animal/distortion/nightmare/distorted_kim.dm
  lobotomy-corp13.dme
Labels: Tweak

#2819 gives box seph languages other sephs have
  code/modules/mob/living/carbon/human/species_types/sephirah.dm
Labels: Fix

#2817 Nerfs Salmon Noon
  code/modules/ordeals/event_ordeals.dm
Labels: Balance

#2825 a machine themed abnormality should act like a machine
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/fan.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/he/shock_centipede.dm
  code/modules/mob/living/simple_animal/abnormality/he/singing_machine.dm
  code/modules/mob/living/simple_animal/abnormality/he/siren.dm
  code/modules/mob/living/simple_animal/abnormality/he/steam_transport_machine.dm
  code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
  code/modules/mob/living/simple_animal/abnormality/teth/cleaner.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/oceanwaves.dm
Labels: Tweak

#2823 Frees the jukebox at manager z level from the tyrany of access locking.
  _maps/map_files/generic/Manager.dmm
Labels: Fix, Mapping, Isolated Code

#2824 Claw and arbiter given brutepale trait
  code/modules/antagonists/head/claw.dm
  code/modules/antagonists/wizard/arbiter.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/lcorp.dm
Labels: Balance, Side content

#2822 K-Corp drones now capable of differentiating flesh from steel
  ModularTegustation/tegu_items/representative/items/kcorp.dm
Labels: Balance, Tweak, Isolated Code

#2820 Zwei West Weapons
  ModularTegustation/ego_weapons/melee/non_abnormality/zwei.dm
  ModularTegustation/tegu_items/refinery/crates/association.dm
Labels: Feature, Isolated Code

#2571 Kikimora Language Curse [Testmergable]
  ModularTegustation/Teguicons/32x48.dmi
  ModularTegustation/Teguicons/wall_markings.dmi
  ModularTegustation/lc13_effects.dm
  code/datums/components/cognitohazard_visual.dm
  code/modules/mob/living/simple_animal/abnormality/teth/kikimora.dm
  code/modules/paperwork/records/info/teth.dm
  lobotomy-corp13.dme
Labels: Abnormality

#2821 Adventure Console 2.0 [DONE]
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/_event.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/legacy.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/man_sands.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/quiz.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_layout.dm
  ModularTegustation/lc13_obj/_adventure_console/console.dm
  lobotomy-corp13.dme
Labels: Expansion, Isolated Code

#2828 Oracle EGO spelling check
  code/modules/clothing/suits/ego_gear/zayin.dm
Labels: Writing

#2829 Very miscellaneous LCL changes (its mostly mapping)
  ModularTegustation/tegu_items/limbus_labs/!abno_overwrites.dm
  ModularTegustation/tegu_items/limbus_labs/!other_overwrites.dm
  _maps/map_files/Event/laboratory.dmm
Labels: Mapping, Side content

#2827 Fixes faction issues with specific abnos
  ModularTegustation/tegu_items/limbus_labs/!abno_overwrites.dm
Labels: Fix

#2830 Insane People are no longer possessable by Evil Gamer Ghosts
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#2831 Fixes a issue with Zwei West, adds it to roaming fixers.
  ModularTegustation/ego_weapons/melee/non_abnormality/zwei.dm
  code/modules/jobs/job_types/trusted_players/association/roaming.dm
Labels: Fix

#2833 Adds a small set of Nagel themed adventure console events.
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/waw/general_bee.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/abnormality/zayin/oceanic.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/ncorp/_bread.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/ncorp/canteen.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/ncorp/lineup.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/ncorp/lone_prosthetics.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/ncorp/read_scripture.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/ncorp/tragedy.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/ncorp_start.dm
  lobotomy-corp13.dme
Labels: Writing, Expansion

#2840 R-Corp arbiters will no longer lower themselves to the level of filthy animals
  ModularTegustation/ego_weapons/melee/non_abnormality/rcorp.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/rcorp_assault.dm
  ModularTegustation/tegu_items/rcorp/turrets.dm
  code/game/objects/items/grenades/r_corp.dm
  code/modules/antagonists/head/claw.dm
  code/modules/antagonists/wizard/arbiter.dm
  code/modules/projectiles/guns/misc/medbeam.dm
  code/modules/projectiles/guns/misc/reindeer.dm
Labels: Balance, Side content

#2841 Branch 12 Weapon Changes [PART 4]
  ModularTegustation/!extra_abnos/branch12/!equipment/branch12_datum.dm
  ModularTegustation/!extra_abnos/branch12/!equipment/ego_weapons/teth.dm
  ModularTegustation/!extra_abnos/branch12/!equipment/ego_weapons/waw.dm
  ModularTegustation/!extra_abnos/branch12/training_boar.dm
  ModularTegustation/!extra_abnos/branch12/waw/babel.dm
  ModularTegustation/Teguicons/lc13_coloreffect.dmi
  _maps/map_files/Branch12/Branch12.dmm
  code/datums/status_effects/debuffs.dm
  code/game/objects/effects/temporary_visuals/effect_indicators.dm
Labels: Expansion

#2816 LCL abnormalities that couldnt breach can now breach
  ModularTegustation/tegu_items/limbus_labs/!abno_overwrites.dm
  code/modules/mob/living/simple_animal/abnormality/he/KQE.dm
  code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
  code/modules/mob/living/simple_animal/abnormality/teth/scorched_girl.dm
  code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
Labels: Fix, Side content, Isolated Code

#2743 Station traits Rework/Rebalance
  code/__DEFINES/facility_traits.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/lobotomy_corp.dm
  code/controllers/subsystem/maptype.dm
  code/datums/abnormality/datum/abnormality.dm
  code/modules/jobs/job_types/agent.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/wellcheers.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/parts.dm
Labels: Balance

#2710 Fire damage Overhaul
  code/datums/status_effects/debuffs.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/dawn.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/liu.dm
  code/modules/clothing/suits/ego_gear/teth.dm
  code/modules/clothing/suits/ego_gear/waw.dm
  code/modules/clothing/suits/ego_gear/zayin.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_armor.dm
  code/modules/mob/living/simple_animal/abnormality/_auxiliary_modes/community/ego_weapons.dm
  code/modules/mob/living/simple_animal/abnormality/he/ardor_blossom_moth.dm
  code/modules/mob/living/simple_animal/abnormality/he/basilisoup.dm
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
  code/modules/mob/living/simple_animal/abnormality/he/rudolta.dm
  code/modules/mob/living/simple_animal/abnormality/he/snow_queen.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Balance, Code improvement, Fix, Expansion

#2849 Chat Save fix
  tgui/global.d.ts
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/packages/tgui/links.js
  tgui/public/tgui.html
Labels: Fix

#2848 Replaces observation implant in dispenser with thermal+wall eyes
  ModularTegustation/tegu_items/associations/vending.dm
  code/modules/surgery/organs/eyes.dm
Labels: Balance, Side content

#2851 Add a new Adventure Console Event
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/todd_damn_it.dm
Labels: Tweak

#2853 Bugfixes my past R-Corp PRs
  ModularTegustation/ego_weapons/melee/non_abnormality/rcorp.dm
  ModularTegustation/tegu_items/rcorp/turrets.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/game/objects/items/grenades/r_corp.dm
  code/modules/antagonists/head/claw.dm
  code/modules/antagonists/wizard/arbiter.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/simple_animal/abnormality/he/pinocchio.dm
Labels: Fix

#2856 Hotfix
  ModularTegustation/tegu_items/enkephalin_rush/objective.dm
Labels: Red Label, Fix

#2722 J-Corp Rep Expansion - Part 1
  ModularTegustation/tegu_items/representative/console.dm
  ModularTegustation/tegu_items/representative/items/jcorp.dm
  ModularTegustation/tegu_items/representative/research/jcorp.dm
  ModularTegustation/tegu_items/representative/spawners.dm
  code/game/objects/items/cards_ids.dm
  code/modules/mining/ores_coins.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/he/treesap.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/mirror.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/promise.dm
  code/modules/mob/living/simple_animal/abnormality/_tools/zayin/wishwell.dm
  code/modules/mob/living/simple_animal/abnormality/he/will_you_play.dm
  code/modules/mob/living/simple_animal/abnormality/teth/dealerdamned.dm
  code/modules/mob/living/simple_animal/abnormality/zayin/oceanwaves.dm
  code/modules/surgery/revival.dm
Labels: Feature, Expansion

#2854 Another Adventure Console Event!
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/hamham_hunger.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/tempting_treats.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/todd_damn_it.dm
  lobotomy-corp13.dme
Labels: Tweak

#2852 Adventure Console 2.1
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/_event.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/legacy.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/ncorp_start.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_layout.dm
Labels: Expansion

#2855 Update ci_suite.yml
  .github/workflows/ci_suite.yml
  .github/workflows/compile_changelogs.yml
  .github/workflows/docker_publish.yml
  .github/workflows/generate_documentation.yml
  .github/workflows/has_515_compatibility.yml
  .github/workflows/round_id_linker.yml
  .github/workflows/stale.yml
  .github/workflows/update_tgs_dmapi.yml
  dependencies.sh
Labels: Github, Fix

#2860 Fixes eye prosthetic cost
  code/modules/surgery/organs/eyes.dm
Labels: Fix

#2862 secure safe fix
  code/game/objects/items/storage/secure.dm
Labels: Fix

#2864 Reverts required Python back to 3.7.9
  dependencies.sh
Labels: python

#2863 Adventure Console Events: Skinwoman
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/_statinfo.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/ncorp/dance.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/ncorp/lady.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/skinwoman/_sighting.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/skinwoman/bedroom_blues.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_events/general/skinwoman_start.dm
  ModularTegustation/lc13_obj/_adventure_console/adventure_layout.dm
  lobotomy-corp13.dme
Labels: Tweak, Writing, Expansion

#2720 Delivery System/UI NPCs [DONE]
  ModularTegustation/delivery_doors.dm
  ModularTegustation/tegu_items/associations/machines.dm
  ModularTegustation/tegu_items/associations/vending.dm
  ModularTegustation/tegu_mobs/lc13_humanoids.dm
  ModularTegustation/tegu_mobs/lc13_nuke_clowns.dm
  ModularTegustation/tegu_mobs/lc13_resurgence_clan_mobs.dm
  ModularTegustation/tegu_mobs/lc13_resurgence_clan_npcs.dm
  _maps/Quests/ruined_town.dmm
  _maps/RandomRooms/backstreetlayout/dungeon_backstreets.dmm
  _maps/RandomRooms/backstreetlayout/lcorp.dmm
  _maps/RandomRooms/backstreetlayout/lcorp_backstreets.dmm
  _maps/RandomRooms/backstreetlayout/outskirts.dmm
  _maps/RandomRooms/backstreetlayout/standard.dmm
  _maps/RandomRooms/backstreetlayout/tunnels_backstreets.dmm
  _maps/map_files/Event/city.dmm
  _maps/map_files/Event/city_fixer.dmm
  _maps/map_files/Event/fixer_office.dmm
  _maps/map_files/LcorpCity/mixcommand.dmm
  _maps/map_files/LcorpCity/mixcorp.dmm
  _maps/shuttles/quest_coolbus.dmm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/sound.dm
  code/_globalvars/lists/mapping.dm
  code/datums/components/return_to_origin.dm
  code/datums/shuttles.dm
  code/datums/ui_npc/expression_parser_test.dm
  code/datums/ui_npc/expresssion_parser.dm
  code/datums/ui_npc/scene.dm
  code/datums/ui_npc/scene_manager.dm
  code/datums/ui_npc/test_verb.dm
  code/datums/ui_npc/var_resolver.dm
  code/game/objects/items/fixerskills/level2/lockpick.dm
  code/game/turfs/closed/_closed.dm
  code/modules/mob/living/simple_animal/friendly/eric_t.dm
  code/modules/mob/living/simple_animal/friendly/nuke_leader.dm
  code/modules/mob/living/simple_animal/friendly/nuked_npc.dm
  code/modules/mob/living/simple_animal/friendly/shopkeeper.dm
  code/modules/mob/living/simple_animal/friendly/ui_npc.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/netherworld.dm
  code/modules/mob/living/simple_animal/hostile/regalrat.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  icons/UI_Icons/NPC_Portraits/bill.png
  icons/UI_Icons/NPC_Portraits/erik_bloodfiend.PNG
  icons/UI_Icons/NPC_Portraits/erik_bloodfiend_zoom.PNG
  icons/UI_Icons/NPC_Portraits/rat_guide.png
  icons/UI_Icons/NPC_Portraits/rat_leader.png
  icons/UI_Icons/NPC_Portraits/the-goat.png
  icons/mob/clown_mobs.dmi
  icons/mob/cult.dmi
  icons/obj/bus.dmi
  lobotomy-corp13.dme
  sound/creatures/lc13/goat_bleating.ogg
  sound/creatures/lc13/mailman.ogg
  sound/creatures/lc13/talking.ogg
  tgui/packages/tgui/components/TypingScroller.js
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/SpeakingNpc.js
Labels: Feature, Side content

#2746 Nobody Is Improvements/Nothing there fixes
  code/modules/mob/living/simple_animal/abnormality/aleph/nobody_is.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/nothing_there.dm
Labels: Code improvement, Fix, Isolated Code

#2865 Armor datum cleanup + silk upgrading improvement.
  code/datums/armor.dm
  code/datums/components/silkweave.dm
  code/game/objects/items/stacks/sheets/silk.dm
  code/modules/clothing/suits/ego_gear/aleph.dm
  code/modules/clothing/suits/ego_gear/ordeal.dm
Labels: Fix

#2726 MOBA rebalance
  ModularTegustation/moba_skills/artificer/charge.dm
  ModularTegustation/moba_skills/defensive/hunker_down.dm
  ModularTegustation/moba_skills/defensive/parry.dm
  ModularTegustation/moba_skills/healing/healing.dm
  ModularTegustation/moba_skills/healing/soothing.dm
  ModularTegustation/moba_skills/ranged/autoloader.dm
  ModularTegustation/moba_skills/ranged/smokedash.dm
  ModularTegustation/moba_skills/skirmisher/assault.dm
  ModularTegustation/moba_skills/skirmisher/blitz.dm
Labels: Balance

#2625 Patreon Doublevote
  code/controllers/subsystem/vote.dm
Labels: Tweak

#2872 City L-Corp Update: Amber Fix
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
Labels: Fix

#2775 The British Update (Time Ripper)
  ModularTegustation/Teguicons/Ripper32x64.dmi
  ModularTegustation/Teguicons/Ripper64x64.dmi
  code/modules/mob/living/simple_animal/distortion/nightmare/TimeRipper.dm
  lobotomy-corp13.dme
Labels: Feature

#2871 CoL Update: Carnival Buff
  ModularTegustation/ego_weapons/melee/non_abnormality/carnival.dm
  code/game/objects/items/stacks/sheets/silk.dm
  code/modules/jobs/job_types/city/carnival.dm
Labels: Balance

#2721 Backstreets Balance Update [DONE]
  ModularTegustation/tegu_items/associations/!overwrites.dm
  ModularTegustation/tegu_items/associations/items.dm
  ModularTegustation/tegu_items/workshop/_mods.dm
  ModularTegustation/tegu_items/workshop/_templates.dm
  ModularTegustation/tegu_items/workshop/mods/aoe.dm
  lobotomy-corp13.dme
Labels: Balance

#2837 City Gear Addition: Devyat
  ModularTegustation/Teguicons/devyat_left.dmi
  ModularTegustation/Teguicons/devyat_right.dmi
  ModularTegustation/ego_weapons/melee/non_abnormality/devyat.dm
  ModularTegustation/tegu_items/refinery/crates/association.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/devyat.dm
  icons/obj/clothing/ego_gear/devyat_armor.dmi
  icons/obj/clothing/ego_gear/devyat_icon.dmi
  lobotomy-corp13.dme
  sound/weapons/ego/devyat_alarm.ogg
  sound/weapons/ego/devyat_combat_start.ogg
  sound/weapons/ego/devyat_overclock.ogg
  sound/weapons/ego/devyat_overclock_death.ogg
  sound/weapons/ego/devyat_slam.ogg
  sound/weapons/ego/devyat_slice.ogg
  sound/weapons/ego/devyat_stage_1.ogg
  sound/weapons/ego/devyat_stage_2.ogg
  sound/weapons/ego/devyat_stage_2_idle.ogg
  sound/weapons/ego/devyat_stage_3.ogg
  sound/weapons/ego/devyat_stage_up.ogg
Labels: Feature

#2815 Adds Barber as a mob for B12 ordeal.
  ModularTegustation/Teguicons/TheTrioBloodfiend.dmi
  ModularTegustation/Teguicons/WildHuntBoss.dmi
  ModularTegustation/Teguicons/WildhuntDullahan.dmi
  ModularTegustation/Tegusounds/Erlking/CathyScreaming.ogg
  ModularTegustation/Tegusounds/Erlking/DullahanMount.ogg
  ModularTegustation/Tegusounds/Erlking/ErlkingBoss.ogg
  ModularTegustation/Tegusounds/Erlking/ErlkingCoffin.ogg
  ModularTegustation/Tegusounds/Erlking/ErlkingDullahan.ogg
  ModularTegustation/Tegusounds/Erlking/Erlkinghit.ogg
  ModularTegustation/Tegusounds/Erlking/NoRepose.ogg
  ModularTegustation/Tegusounds/Erlking/desktop.ini
  ModularTegustation/tegu_mobs/Barber.dm
  ModularTegustation/tegu_mobs/Wildhunt.dm
  code/game/objects/effects/abnormality.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  lobotomy-corp13.dme
  sound/creatures/lc13/bloodfiend/BarberGatheredMaterials.ogg
  sound/creatures/lc13/bloodfiend/BarberGoodEnough.ogg
  sound/creatures/lc13/bloodfiend/BarberNoUglyThings.ogg
Labels: Feature

#2869 CoL Update: Office Update
  ModularTegustation/tegu_items/associations/fixeroffice.dm
  ModularTegustation/tegu_items/associations/office_upgrades.dm
  ModularTegustation/tegu_items/associations/vending.dm
  _maps/templates/fixer_office/contractfixers.dmm
  _maps/templates/fixer_office/deliveryfixers.dmm
  _maps/templates/fixer_office/peacekeepingfixers.dmm
  _maps/templates/fixer_office/reconfixers.dmm
  lobotomy-corp13.dme
Labels: Expansion

#2874 Fixes awkward wording with Daredevil empowered parry flavour text (and adds a bit more of it)
  ModularTegustation/ego_weapons/melee/he.dm
Labels: Writing

#2878 Revert "Adds Barber as a mob for B12 ordeal."
  ModularTegustation/Teguicons/TheTrioBloodfiend.dmi
  ModularTegustation/Teguicons/WildHuntBoss.dmi
  ModularTegustation/Teguicons/WildhuntDullahan.dmi
  ModularTegustation/Tegusounds/Erlking/CathyScreaming.ogg
  ModularTegustation/Tegusounds/Erlking/DullahanMount.ogg
  ModularTegustation/Tegusounds/Erlking/ErlkingBoss.ogg
  ModularTegustation/Tegusounds/Erlking/ErlkingCoffin.ogg
  ModularTegustation/Tegusounds/Erlking/ErlkingDullahan.ogg
  ModularTegustation/Tegusounds/Erlking/Erlkinghit.ogg
  ModularTegustation/Tegusounds/Erlking/NoRepose.ogg
  ModularTegustation/Tegusounds/Erlking/desktop.ini
  ModularTegustation/tegu_mobs/Barber.dm
  ModularTegustation/tegu_mobs/Wildhunt.dm
  code/game/objects/effects/abnormality.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  lobotomy-corp13.dme
  sound/creatures/lc13/bloodfiend/BarberGatheredMaterials.ogg
  sound/creatures/lc13/bloodfiend/BarberGoodEnough.ogg
  sound/creatures/lc13/bloodfiend/BarberNoUglyThings.ogg
Labels: Removal

#2879 Revert "The British Update (Time Ripper)"
  ModularTegustation/Teguicons/Ripper32x64.dmi
  ModularTegustation/Teguicons/Ripper64x64.dmi
  code/modules/mob/living/simple_animal/distortion/nightmare/TimeRipper.dm
  lobotomy-corp13.dme
Labels: Removal

#2877 Pai fix and change of font for secure briefcase
  code/game/objects/items/devices/paicard.dm
  code/game/objects/items/storage/secure.dm
Labels: Fix

#2577 Endermage Rcorp Updates: Buffing/Reworking R-Corp Abnormalities Part 2 [DONE]
  ModularTegustation/ego_weapons/ranged/ego_bullets/waw.dm
  ModularTegustation/tegu_items/rcorp/!abno_overwrites.dm
  ModularTegustation/tegu_items/rcorp/random_maps.dm
  _maps/map_files/Event/rcorp.dmm
  code/__DEFINES/keybinding.dm
  code/datums/keybinding/_defines.dm
  code/datums/keybinding/abnos.dm
  code/game/area/areas/lobotomy_corp.dm
  code/game/gamemodes/management/event/combat.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/abnormality/aleph/censored.dm
  code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
  code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
  code/modules/mob/living/simple_animal/abnormality/he/drifting_fox.dm
  code/modules/mob/living/simple_animal/abnormality/he/helper.dm
  code/modules/mob/living/simple_animal/abnormality/he/scarecrow.dm
  code/modules/mob/living/simple_animal/abnormality/he/woodsman.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fairy_gentleman.dm
  code/modules/mob/living/simple_animal/abnormality/teth/fragment.dm
  code/modules/mob/living/simple_animal/abnormality/teth/ppodae.dm
  code/modules/mob/living/simple_animal/abnormality/waw/clown_smiling.dm
  code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
  code/modules/mob/living/simple_animal/abnormality/waw/yin.dm
  code/modules/projectiles/projectile/magic/abnormality.dm
  icons/mob/actions/actions_abnormality.dmi
  icons/obj/projectiles.dmi
  lobotomy-corp13.dme
Labels: Balance, Feature, Side content

#2839 Official Offices [DONE]
  ModularTegustation/tegu_items/associations/machines.dm
  ModularTegustation/tegu_items/associations/official_office.dm
  ModularTegustation/tegu_items/associations/vending.dm
  code/modules/jobs/job_types/city/syndicate/blade_lineage/cutthroat.dm
  code/modules/jobs/job_types/city/syndicate/index/messenger.dm
  code/modules/jobs/job_types/city/syndicate/kurokumo/captain.dm
  code/modules/jobs/job_types/city/syndicate/ncorp/grandinquis.dm
  code/modules/jobs/job_types/city/syndicate/thumb/sottocapo.dm
  code/modules/jobs/job_types/trusted_players/hana.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  lobotomy-corp13.dme
Labels: Balance

#2882 Actually enables Sirocco
  code/modules/mob/living/simple_animal/abnormality/teth/sirocco.dm
Labels: Fix

#2883 Adds Burrowing Heaven's EGO to the Wishing Well
  code/datums/abnormality/_ego_datum/waw.dm
  code/modules/clothing/suits/ego_gear/waw.dm
Labels: Tweak

#2881 CoL Update: Wandering Devyat
  code/modules/jobs/job_types/trusted_players/association/roaming.dm
Labels: Expansion

#2885 Flesh Idol Buff
  code/modules/mob/living/simple_animal/abnormality/waw/flesh_idol.dm
  code/modules/paperwork/records/info/waw.dm
Labels: Balance

#2884 Fixes fake shuttle call announcement on shuttle purchase
  code/controllers/subsystem/shuttle.dm
Labels: Fix

#2744 Damage Type Shuffle Station Trait
  ModularTegustation/ego_weapons/_ego_weapon.dm
  ModularTegustation/ego_weapons/ranged/_ranged.dm
  ModularTegustation/lc13_damage_type_shuffler.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  code/__DEFINES/facility_traits.dm
  code/controllers/subsystem/maptype.dm
  code/datums/abnormality/_ego_datum/_ego_datum.dm
  code/game/machinery/computer/manager_camera.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
  code/modules/mob/living/simple_animal/damage_coeff_helper.dm
  code/modules/mob/living/simple_animal/damage_procs.dm
  code/modules/paperwork/records/info/_info.dm
  lobotomy-corp13.dme
Labels: Feature
