Repository vlggms/lobotomy-corp13, pull requests merged in 2025-09, with the labels that each got.

#3073 Better debug dummy
  ModularTegustation/tegu_items/debug_items.dm
Labels: Tweak

#3014 Ego QOL Updates
  ModularTegustation/Teguicons/lc13_left_64x64.dmi
  ModularTegustation/Teguicons/lc13_right_64x64.dmi
  ModularTegustation/Teguicons/lc13_weapons.dmi
  ModularTegustation/ego_weapons/melee/aleph.dm
  ModularTegustation/ego_weapons/melee/special.dm
  ModularTegustation/ego_weapons/melee/teth.dm
  ModularTegustation/ego_weapons/melee/waw.dm
  ModularTegustation/tegu_items/refinery/crates/workshop.dm
  _maps/map_files/Library/floor_language.dmm
  _maps/map_files/Library/floor_philosophy.dmm
  code/datums/abnormality/_ego_datum/aleph.dm
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/obj/ego_weapons.dmi
  sound/weapons/ego/mimicry_stab.ogg
Labels: Balance, Tweak, Removal

#3075 Mermaids no longer invade the rest of the city
  _maps/alphacorp.json
  _maps/betacorp.json
  _maps/city.json
  _maps/cityfixers.json
  _maps/deltacorp.json
  _maps/epsiloncorp.json
  _maps/etacorp.json
  _maps/gammacorp.json
  _maps/iotacorp.json
  _maps/kappacorp.json
  _maps/lambdacorp.json
  _maps/lclabs.json
  _maps/lcorpcity.json
  _maps/office.json
  _maps/psicorp.json
  _maps/rcorp_test.json
  _maps/skeld.json
  _maps/thetacorp.json
  _maps/wcorp.json
  _maps/xicorp.json
  _maps/zetacorp.json
Labels: Fix, Mapping

#3059 Content Cull & Miscellaneous Updates
  ModularTegustation/tegu_items/_belt.dm
  ModularTegustation/tegu_items/gadgets/powered.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/representative/research/lcorp.dm
  code/__DEFINES/preferences.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/simple_animal/distortion/nightmare/black_hole_sun.dm
Labels: Removal
