Repository vlggms/lobotomy-corp13, pull requests merged in 2025-07, with the labels that each got.

#2960 Fixes Plushie Extractor
  ModularTegustation/tegu_items/_belt.dm
  ModularTegustation/tegu_items/gadgets/unpowered.dm
  ModularTegustation/tegu_items/refinery/crates/corporation.dm
  ModularTegustation/tegu_items/representative/research/lcorp.dm
Labels: Fix

#2766 Para's Devious Trap Update: Tile Remake [DONE]
  ModularTegustation/Teguicons/sigsystem_icons.dmi
  ModularTegustation/lc13_traps.dm
  ModularTegustation/signal_system.dm
  ModularTegustation/sigsystem/activators.dm
  ModularTegustation/sigsystem/parts.dm
  ModularTegustation/sigsystem/towers.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/bigrooms/connector.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/large/north.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/large/south.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/medium/west.dm
  ModularTegustation/tegu_items/backstreets/random_rooms/small/south.dm
  _maps/RandomRooms/backstreets/connector/old_checkpoint.dmm
  _maps/RandomRooms/backstreets/connector/rat_cave.dmm
  _maps/RandomRooms/backstreets/large_north/containment_lna.dmm
  _maps/RandomRooms/backstreets/large_south/shotgun_exam.dmm
  _maps/RandomRooms/backstreets/large_south/sweeper_nestsmall.dmm
  _maps/RandomRooms/backstreets/medium_north/rat_mna.dmm
  _maps/RandomRooms/backstreets/medium_west/cryo_lab.dmm
  _maps/RandomRooms/backstreets/pointofinterest/robot_city.dmm
  _maps/RandomRooms/backstreets/small_south/locked_crate.dmm
  lobotomy-corp13.dme
Labels: Feature, Mapping

#2971 Adv Console Health Overflow Removal Bug
  ModularTegustation/lc13_obj/_adventure_console/adventure_layout.dm
Labels: Fix

#2903 Fix: Audio Player works again
  tgui/packages/tgui-panel/audio/player.js
Labels: javascript, Fix, Isolated Code

#2942 Amber Dawn Infestation
  code/game/objects/items/food/meat.dm
  code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
  code/modules/reagents/chemistry/reagents/lc13_reagents.dm
Labels: Feature, Expansion

#2952 City Update: Achievements+
  ModularTegustation/tegu_mobs/lc13_nuke_clowns.dm
  ModularTegustation/tegu_mobs/lc13_resurgence_clan_npcs.dm
  code/__DEFINES/achievements.dm
  code/_globalvars/lists/mobs.dm
  code/datums/achievements/LC13_achievements.dm
  code/datums/achievements/_achievement_data.dm
  code/game/area/areas/lobotomy_corp.dm
  code/game/objects/items/devices/taperecorder.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mob/living/simple_animal/friendly/eric_t.dm
  code/modules/mob/living/simple_animal/friendly/npc.dm
  code/modules/mob/living/simple_animal/friendly/nuke_leader.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  icons/UI_Icons/Achievements/lobotomycorp13/briefcase.png
  icons/UI_Icons/Achievements/lobotomycorp13/briefcase_gold.png
  icons/UI_Icons/Achievements/lobotomycorp13/clan_genocide.png
  icons/UI_Icons/Achievements/lobotomycorp13/clown_boss.png
  icons/UI_Icons/Achievements/lobotomycorp13/parcel.png
  icons/UI_Icons/Achievements/lobotomycorp13/rat_quest.png
  icons/UI_Icons/Achievements/lobotomycorp13/rats_genocide.png
  icons/UI_Icons/Achievements/lobotomycorp13/tape.png
  icons/UI_Icons/Achievements/lobotomycorp13/tinkerer.png
  icons/UI_Icons/Achievements/lobotomycorp13/village.png
Labels: Expansion

#2702 Interdimensional Rubber Duck
  ModularTegustation/Teguicons/32x32.dmi
  ModularTegustation/ego_weapons/ranged/ego_bullets/he.dm
  ModularTegustation/ego_weapons/ranged/he.dm
  code/datums/abnormality/_ego_datum/he.dm
  code/modules/clothing/suits/ego_gear/he.dm
  code/modules/mob/living/simple_animal/abnormality/he/rubber_duck.dm
  code/modules/paperwork/records/info/he.dm
  icons/mob/clothing/ego_gear/abnormality/he.dmi
  icons/obj/clothing/ego_gear/abnormality/he.dmi
  icons/obj/ego_weapons.dmi
  lobotomy-corp13.dme
Labels: Abnormality

#2890 Disciplinary Update: Combat Research
  ModularTegustation/ego_weapons/melee/non_abnormality/_cityweapons.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/black_silence.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/kcorp.dm
  ModularTegustation/ego_weapons/melee/non_abnormality/lcorp_ranged.dm
  ModularTegustation/tegu_items/disciplinary/_disciplinary.dm
  ModularTegustation/tegu_items/disciplinary/combat_page/_combatpage.dm
  ModularTegustation/tegu_items/disciplinary/combat_page/level1.dm
  ModularTegustation/tegu_items/disciplinary/combat_page/level2.dm
  ModularTegustation/tegu_items/disciplinary/combat_page/level3.dm
  ModularTegustation/tegu_items/disciplinary/discipline_cargo.dm
  ModularTegustation/tegu_items/disciplinary/egoshards.dm
  ModularTegustation/tegu_items/disciplinary/research.dm
  code/__HELPERS/lobotomy_corp.dm
  code/game/objects/structures/crates_lockers/closets/secure/lc13.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/_cityarmor.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/index.dm
  code/modules/clothing/suits/ego_gear/non_abnormality/wcorp.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/suppression.dm
  code/modules/jobs/jobs.dm
  icons/mob/hud.dmi
  lobotomy-corp13.dme
Labels: Feature, Removal

#2969 LCL Hostile Faction fix
  ModularTegustation/tegu_items/limbus_labs/!other_overwrites.dm
  code/game/gamemodes/management/event/combat.dm
Labels: Tweak, Fix

#2980 Fixes Courage (sword)
  ModularTegustation/ego_weapons/melee/he.dm
Labels: Fix

#2982 Update activators.dm
  ModularTegustation/sigsystem/activators.dm
Labels: Fix

#2993 Fixes the Researcher generating infinite PE
  ModularTegustation/tegu_items/disciplinary/research.dm
Labels: Fix
